import { CVExample } from '../../types';

export const communicatieAdviseur: CVExample = {
    slug: 'communicatie-adviseur',
    categorySlug: 'marketing-en-communicatie',
    name: 'Communicatieadviseur',
    description: 'CV voorbeeld voor een corporate communicatieadviseur met ervaring in interne communicatie, change communicatie en stakeholder management.',
    templateId: 'modern',
    colorThemeId: 'forest-green',

    metaTitle: 'CV Voorbeeld Communicatieadviseur | WerkCV.nl',
    metaDesc: 'Professioneel CV voorbeeld voor communicatieadviseurs. Met voorbeeldteksten voor interne communicatie, verandercommunicatie en stakeholder management. Maak direct je CV.',
    keywords: ['cv voorbeeld communicatieadviseur', 'cv interne communicatie', 'cv corporate communicatie', 'communicatieadviseur cv', 'cv verandercommunicatie'],
    heroTitle: 'CV Voorbeeld Communicatieadviseur',
    heroText: 'Als communicatieadviseur verbind je strategie met uitvoering en zorg je dat de juiste boodschap de juiste doelgroep bereikt. Dit CV voorbeeld toont hoe je je ervaring met interne communicatie, verandermanagement en stakeholder management overtuigend presenteert aan werkgevers in zowel de publieke als private sector.',
    tips: [
        'Benadruk je ervaring met verschillende communicatiedisciplines: intern, extern, corporate, verandercommunicatie',
        'Toon meetbare impact: medewerkersbetrokkenheid, bereik van interne campagnes, stakeholder tevredenheid',
        'Vermeld je adviesvaardigheden en ervaring met het adviseren van directie of management',
        'Benoem tools en kanalen die je beheerst: intranet, SharePoint, interne nieuwsbrieven, townhalls',
        'Laat zien dat je complexe boodschappen helder en begrijpelijk kunt vertalen voor diverse doelgroepen',
    ],
    relatedSlugs: ['marketing-en-communicatie/pr-adviseur', 'marketing-en-communicatie/marketing-manager'],

    sampleCV: {
        personal: {
            name: 'Martijn Visser',
            title: 'Senior Communicatieadviseur',
            email: 'martijn.visser@email.nl',
            phone: '06-67890123',
            location: 'Utrecht',
            address: 'Maliebaan 32',
            postalCode: '3581 CR',
            summary: 'Ervaren communicatieadviseur met meer dan 7 jaar ervaring in corporate en interne communicatie bij grote Nederlandse organisaties. Gespecialiseerd in verandercommunicatie, medewerkersbetrokkenheid en strategisch communicatieadvies. Sterk in het vertalen van complexe organisatieveranderingen naar heldere en inspirerende boodschappen voor diverse doelgroepen.',
            birthDate: '27 augustus 1989',
            birthPlace: 'Arnhem',
            nationality: 'Nederlands',
            driversLicense: 'B',
            gender: '',
            maritalStatus: '',
            linkedIn: 'linkedin.com/in/martijnvisser',
            github: '',
            website: '',
            photo: '',
        },
        experience: [
            {
                role: 'Senior Communicatieadviseur',
                company: 'Rabobank',
                location: 'Utrecht',
                start: 'januari 2021',
                end: 'heden',
                description: 'Strategisch communicatieadviseur binnen de afdeling Corporate Communicatie, verantwoordelijk voor interne communicatie en verandercommunicatie bij grootschalige organisatietransformaties.',
                highlights: [
                    'Communicatiestrategie ontwikkeld voor een reorganisatie die 3.000 medewerkers betrof, met een medewerkerstevredenheidsscore van 7,8 op communicatie',
                    'Nieuw intranetplatform (SharePoint) gelanceerd met een adoptiegraad van 85% binnen de eerste drie maanden',
                    'Kwartaalmagazine en maandelijkse townhalls opgezet die de interne betrokkenheid volgens het MTO met 15% verhoogden',
                ],
            },
            {
                role: 'Communicatieadviseur',
                company: 'NS (Nederlandse Spoorwegen)',
                location: 'Utrecht',
                start: 'april 2018',
                end: 'december 2020',
                description: 'Adviseerde het management over interne en externe communicatie rondom operationele veranderingen, duurzaamheidsinitiatieven en medewerkersbeleid.',
                highlights: [
                    'Communicatieplan opgesteld en uitgevoerd voor de introductie van nieuw dienstrooster, bereik van 18.000 medewerkers',
                    'Contentredactie gevoerd voor het interne nieuwskanaal met wekelijks 12.000 lezers',
                    'Crisiscommunicatieprotocol bijgewerkt en communicatietrainingen verzorgd voor 25 leidinggevenden',
                ],
            },
            {
                role: 'Junior Communicatiemedewerker',
                company: 'Gemeente Utrecht',
                location: 'Utrecht',
                start: 'september 2016',
                end: 'maart 2018',
                description: 'Ondersteunde het communicatieteam bij burgerparticipatie, persberichten en interne communicatie over gemeentelijk beleid.',
                highlights: [
                    'Communicatiecampagnes opgezet voor burgerparticipatieprojecten die meer dan 5.000 inwoners bereikten',
                    'Webteksten en nieuwsbrieven geschreven voor de gemeentelijke website en sociale media kanalen',
                ],
            },
        ],
        education: [
            {
                degree: 'Master Communicatiewetenschappen',
                school: 'Universiteit Utrecht',
                location: 'Utrecht',
                start: 'september 2014',
                end: 'juli 2016',
                description: 'Specialisatie Organisatiecommunicatie. Scriptie over de rol van interne communicatie bij succesvolle verandertrajecten in de financiele sector.',
            },
            {
                degree: 'Bachelor Communicatiewetenschap',
                school: 'Radboud Universiteit',
                location: 'Nijmegen',
                start: 'september 2010',
                end: 'juli 2014',
                description: 'Minor Bestuurskunde. Afstudeeronderzoek naar effectieve overheidscommunicatie bij beleidsveranderingen.',
            },
        ],
        skills: [
            { name: 'Interne communicatie', level: 5 },
            { name: 'Verandercommunicatie', level: 5 },
            { name: 'Redactie & contentcreatie', level: 4 },
            { name: 'Stakeholder Management', level: 4 },
            { name: 'SharePoint / Intranet', level: 4 },
            { name: 'Communicatiestrategie & advies', level: 4 },
        ],
        languages: [
            { name: 'Nederlands', level: 'Moedertaal' },
            { name: 'Engels', level: 'Vloeiend' },
            { name: 'Duits', level: 'Goed' },
        ],
        interests: ['Schrijven', 'Fietsen', 'Vrijwilligerswerk', 'Architectuur'],
        courses: [
            { name: 'Leergang Verandercommunicatie', institution: 'Logeion', year: '2022' },
            { name: 'Strategisch Communicatiemanagement', institution: 'Nyenrode Business Universiteit', year: '2020' },
            { name: 'NIMA C Communicatie', institution: 'NIMA', year: '2019' },
        ],
        internships: [],
        awards: [],
    },
};
