import { CVExample } from '../../types';

export const contentSchrijver: CVExample = {
    slug: 'content-schrijver',
    categorySlug: 'marketing-en-communicatie',
    name: 'Content Schrijver',
    description: 'CV voorbeeld voor een content schrijver en copywriter met ervaring in SEO-content, storytelling en redactioneel werk voor diverse platformen.',
    templateId: 'sepia',
    colorThemeId: 'warm-earth',

    metaTitle: 'CV Voorbeeld Content Schrijver | WerkCV.nl',
    metaDesc: 'Professioneel CV voorbeeld voor content schrijvers en copywriters. Met voorbeeldteksten voor SEO-content, blogs en redactie. Maak direct je eigen CV.',
    keywords: ['cv voorbeeld content schrijver', 'cv copywriter', 'cv redacteur', 'content schrijver cv', 'cv tekstschrijver'],
    heroTitle: 'CV Voorbeeld Content Schrijver',
    heroText: 'Als content schrijver is taal je belangrijkste instrument. Dit CV voorbeeld laat zien hoe je je schrijfvaardigheden, SEO-kennis en redactionele ervaring overtuigend presenteert. Perfect voor copywriters, webredacteuren en content creators die op zoek zijn naar hun volgende uitdaging.',
    tips: [
        'Voeg een link toe naar je portfolio of gepubliceerde artikelen als bewijs van je schrijfkwaliteit',
        'Vermeld je kennis van SEO-tools zoals Ahrefs, SEMrush of Yoast en laat resultaten zien',
        'Benoem de verschillende contenttypes waarin je ervaring hebt: blogs, whitepapers, social media, e-mail',
        'Toon meetbare resultaten: organisch verkeer, positie in zoekresultaten, leestijd of conversie',
        'Laat zien dat je kunt schrijven voor verschillende doelgroepen en tone-of-voice stijlen',
    ],
    relatedSlugs: ['marketing-en-communicatie/pr-adviseur', 'marketing-en-communicatie/social-media-specialist'],

    sampleCV: {
        personal: {
            name: 'Thomas Bakker',
            title: 'Content Schrijver & Copywriter',
            email: 'thomas.bakker@email.nl',
            phone: '06-34567890',
            location: 'Leiden',
            address: 'Rapenburg 42',
            postalCode: '2311 EW',
            summary: 'Veelzijdige content schrijver en copywriter met meer dan 5 jaar ervaring in het creeren van doeltreffende webcontent, blogs, whitepapers en marketingteksten. Gespecialiseerd in SEO-schrijven en storytelling met een bewezen track record in het verhogen van organisch verkeer. Combineert journalistieke nauwkeurigheid met commerciele slagkracht.',
            birthDate: '8 september 1993',
            birthPlace: 'Leiden',
            nationality: 'Nederlands',
            driversLicense: 'B',
            gender: '',
            maritalStatus: '',
            linkedIn: 'linkedin.com/in/thomasbakker',
            github: '',
            website: 'thomasbakker.nl',
            photo: '',
        },
        experience: [
            {
                role: 'Senior Content Schrijver',
                company: 'Travix (CheapTickets / BudgetAir)',
                location: 'Amsterdam',
                start: 'mei 2021',
                end: 'heden',
                description: 'Verantwoordelijk voor de gehele contentstrategie en het schrijven van SEO-geoptimaliseerde webcontent, blogs en landingspagina\'s voor de Nederlandstalige markten.',
                highlights: [
                    'Contentstrategie ontwikkeld die het organisch verkeer binnen 12 maanden met 65% verhoogde',
                    'Meer dan 200 SEO-artikelen geschreven die structureel in de top 3 van Google ranken',
                    'Redactionele richtlijnen en tone-of-voice document opgesteld voor het gehele contentteam',
                ],
            },
            {
                role: 'Copywriter',
                company: 'Greenhouse Group',
                location: 'Eindhoven',
                start: 'september 2019',
                end: 'april 2021',
                description: 'Schreef commerciele en redactionele content voor diverse klanten waaronder Philips, Bavaria en Jumbo, in nauwe samenwerking met het strategy- en designteam.',
                highlights: [
                    'Conversiegerichte landingspagina\'s geschreven die de gemiddelde conversieratio van klanten met 23% verbeterden',
                    'Wekelijkse blogs en nieuwsbrieven verzorgd voor 4 klantaccounts met consistente kwaliteit en planning',
                    'Content audits uitgevoerd en verbeterplannen opgesteld op basis van Ahrefs- en Google Analytics-data',
                ],
            },
            {
                role: 'Webredacteur',
                company: 'RTL Nederland',
                location: 'Hilversum',
                start: 'februari 2018',
                end: 'augustus 2019',
                description: 'Schreef en redigeerde dagelijks nieuwsartikelen, achtergrondverhalen en entertainmentcontent voor RTL Nieuws en RTL Boulevard online.',
                highlights: [
                    'Gemiddeld 5 artikelen per dag geschreven met een hoge journalistieke standaard en SEO-optimalisatie',
                    'Breaking news coverage opgepakt met snelle en accurate berichtgeving',
                ],
            },
        ],
        education: [
            {
                degree: 'Master Journalistiek en Media',
                school: 'Universiteit Leiden',
                location: 'Leiden',
                start: 'september 2016',
                end: 'juli 2018',
                description: 'Specialisatie Digitale Journalistiek. Scriptie over de rol van SEO in de hedendaagse journalistiek.',
            },
            {
                degree: 'Bachelor Communicatiewetenschappen',
                school: 'Universiteit van Amsterdam',
                location: 'Amsterdam',
                start: 'september 2012',
                end: 'juli 2016',
                description: 'Minor Creatief Schrijven. Afstudeeronderzoek naar storytelling in contentmarketing.',
            },
        ],
        skills: [
            { name: 'SEO-schrijven', level: 5 },
            { name: 'Storytelling & copywriting', level: 5 },
            { name: 'WordPress / CMS-beheer', level: 4 },
            { name: 'Ahrefs / SEMrush', level: 4 },
            { name: 'Redactie & eindredactie', level: 4 },
            { name: 'E-mailmarketing (Mailchimp)', level: 3 },
        ],
        languages: [
            { name: 'Nederlands', level: 'Moedertaal' },
            { name: 'Engels', level: 'Vloeiend' },
            { name: 'Frans', level: 'Basis' },
        ],
        interests: ['Schrijven', 'Lezen', 'Podcasts produceren', 'Wielrennen'],
        courses: [
            { name: 'SEO Certification', institution: 'HubSpot Academy', year: '2022' },
            { name: 'Content Marketing Strategie', institution: 'Beeckestijn Business School', year: '2021' },
        ],
        internships: [],
        awards: [],
    },
};
