import { CVExample } from '../../types';

export const grafischOntwerper: CVExample = {
    slug: 'grafisch-ontwerper',
    categorySlug: 'marketing-en-communicatie',
    name: 'Grafisch Ontwerper',
    description: 'CV voorbeeld voor een grafisch ontwerper met ervaring in branding, visuele identiteit en digitaal ontwerp bij creatieve bureaus en bedrijven.',
    templateId: 'dynamic',
    colorThemeId: 'purple-royal',

    metaTitle: 'CV Voorbeeld Grafisch Ontwerper | WerkCV.nl',
    metaDesc: 'Professioneel CV voorbeeld voor grafisch ontwerpers. Met voorbeeldteksten voor branding, UX/UI design en visuele communicatie. Maak direct je eigen CV.',
    keywords: ['cv voorbeeld grafisch ontwerper', 'cv designer', 'cv grafisch vormgever', 'grafisch ontwerper cv', 'cv visual designer'],
    heroTitle: 'CV Voorbeeld Grafisch Ontwerper',
    heroText: 'Als grafisch ontwerper is je CV een reflectie van je ontwerpvaardigheden. Dit voorbeeld laat zien hoe je je creatieve expertise, technische kennis en projectresultaten overtuigend presenteert. Combineer een opvallend ontwerp met sterke inhoud om werkgevers te overtuigen van je talent.',
    tips: [
        'Voeg altijd een link toe naar je online portfolio met je beste projecten en casestudies',
        'Vermeld je expertise in specifieke tools: Adobe Creative Suite, Figma, Sketch of InDesign',
        'Toon de diversiteit van je werk: branding, webdesign, drukwerk, motion graphics',
        'Benoem klanten of merken waarvoor je hebt gewerkt om je ervaring te onderbouwen',
        'Gebruik een creatief CV-template dat je ontwerpstijl laat zien zonder de leesbaarheid te compromitteren',
    ],
    relatedSlugs: ['marketing-en-communicatie/marketing-manager', 'marketing-en-communicatie/content-schrijver'],

    sampleCV: {
        personal: {
            name: 'Noor el Amrani',
            title: 'Senior Grafisch Ontwerper',
            email: 'noor.elamrani@email.nl',
            phone: '06-56789012',
            location: 'Eindhoven',
            address: 'Strijp-S 74',
            postalCode: '5616 GM',
            summary: 'Creatieve en veelzijdige grafisch ontwerper met meer dan 6 jaar ervaring in branding, visuele identiteit en digitaal ontwerp. Gespecialiseerd in het vertalen van merkstrategieen naar visueel impactvolle ontwerpen voor zowel print als digitale media. Sterk in conceptontwikkeling, typografie en het aansturen van designtrajecten van briefing tot oplevering.',
            birthDate: '19 januari 1994',
            birthPlace: 'Eindhoven',
            nationality: 'Nederlands',
            driversLicense: 'B',
            gender: '',
            maritalStatus: '',
            linkedIn: 'linkedin.com/in/noorelamrani',
            github: '',
            website: 'noorelamrani.design',
            photo: '',
        },
        experience: [
            {
                role: 'Senior Grafisch Ontwerper',
                company: 'Philips',
                location: 'Eindhoven',
                start: 'maart 2022',
                end: 'heden',
                description: 'Verantwoordelijk voor het visuele ontwerp van campagnemateriaal, productverpakkingen en digitale assets voor de divisie Personal Health, in samenwerking met internationale marketingteams.',
                highlights: [
                    'Visuele identiteit ontwikkeld voor een nieuwe productlijn die internationaal werd uitgerold in 15 markten',
                    'Brand guidelines bijgewerkt en een design system opgezet in Figma voor consistentie across alle kanalen',
                    'Campagnemateriaal ontworpen dat bijdroeg aan een stijging van 18% in merkherkenning volgens onderzoek',
                ],
            },
            {
                role: 'Grafisch Ontwerper',
                company: 'Studio Dumbar (onderdeel van Dept)',
                location: 'Rotterdam',
                start: 'juni 2019',
                end: 'februari 2022',
                description: 'Werkte aan branding- en identiteitsprojecten voor uiteenlopende klanten waaronder de Rijksoverheid, NS en Randstad.',
                highlights: [
                    'Complete visuele identiteit ontworpen voor twee middelgrote bedrijven inclusief logo, huisstijl en webdesign',
                    'Motion graphics en animaties gecreeerd voor social media campagnes met in totaal meer dan 5 miljoen views',
                    'UX/UI designs opgeleverd voor klantwebsites en apps in nauwe samenwerking met development teams',
                ],
            },
            {
                role: 'Junior Grafisch Vormgever',
                company: 'MediaMarkt Nederland',
                location: 'Rotterdam',
                start: 'september 2017',
                end: 'mei 2019',
                description: 'Ontwierp campagnemateriaal voor online en offline kanalen, waaronder flyers, webbanners, e-mail templates en social media visuals.',
                highlights: [
                    'Wekelijks promotiemateriaal ontworpen voor de webshop en fysieke winkels met strakke deadlines',
                    'E-mail templates herontworpen wat resulteerde in een 25% hogere click-through rate',
                ],
            },
        ],
        education: [
            {
                degree: 'Bachelor Grafisch Ontwerp',
                school: 'Design Academy Eindhoven',
                location: 'Eindhoven',
                start: 'september 2013',
                end: 'juli 2017',
                description: 'Afstudeerproject over de invloed van typografie op merkbeleving. Eindwerk genomineerd voor de Dutch Design Awards.',
            },
        ],
        skills: [
            { name: 'Adobe Creative Suite (Photoshop, Illustrator, InDesign)', level: 5 },
            { name: 'Figma / Sketch', level: 5 },
            { name: 'Branding & visuele identiteit', level: 5 },
            { name: 'Typografie & layout', level: 4 },
            { name: 'UX/UI Design', level: 4 },
            { name: 'Motion Graphics (After Effects)', level: 3 },
        ],
        languages: [
            { name: 'Nederlands', level: 'Moedertaal' },
            { name: 'Engels', level: 'Vloeiend' },
            { name: 'Arabisch', level: 'Goed' },
        ],
        interests: ['Typografie', 'Museumbezoek', 'Illustreren', 'Streetart'],
        courses: [
            { name: 'UX Design Professional Certificate', institution: 'Google (Coursera)', year: '2023' },
            { name: 'Advanced Motion Design', institution: 'School of Motion', year: '2021' },
        ],
        internships: [],
        awards: [],
    },
};
