import { CVExample } from '../../types';

export const marketingManager: CVExample = {
    slug: 'marketing-manager',
    categorySlug: 'marketing-en-communicatie',
    name: 'Marketing Manager',
    description: 'CV voorbeeld voor een marketing manager met ruime ervaring in campagnestrategie, teamleiderschap en datagedreven marketing bij grote Nederlandse bedrijven.',
    templateId: 'remarkable',
    colorThemeId: 'rose-gold',

    metaTitle: 'CV Voorbeeld Marketing Manager | WerkCV.nl',
    metaDesc: 'Professioneel CV voorbeeld voor marketing managers. Met voorbeeldteksten voor campagnestrategie, teamleiderschap en meetbare resultaten. Maak direct je eigen CV.',
    keywords: ['cv voorbeeld marketing manager', 'cv marketing', 'cv campagnestrategie', 'marketing manager cv', 'hoofd marketing cv'],
    heroTitle: 'CV Voorbeeld Marketing Manager',
    heroText: 'Als marketing manager laat je zien dat je zowel strategisch kunt denken als operationeel kunt aansturen. Dit CV voorbeeld toont hoe je campagneresultaten, teamleiderschap en datagedreven beslissingen overtuigend presenteert aan potentiele werkgevers.',
    tips: [
        'Benadruk meetbare resultaten: conversieratio\'s, ROI, omzetgroei en bereik van campagnes',
        'Vermeld je ervaring met marketing automation tools zoals HubSpot, Salesforce of Marketo',
        'Toon je leiderschapskwaliteiten: teamomvang, budgetverantwoordelijkheid en cross-functionele samenwerking',
        'Benoem je kennis van zowel online als offline marketingkanalen',
        'Laat zien hoe je data en analytics inzet om marketingstrategieen te optimaliseren',
    ],
    relatedSlugs: ['marketing-en-communicatie/social-media-specialist', 'marketing-en-communicatie/content-schrijver'],

    sampleCV: {
        personal: {
            name: 'Lisa van den Berg',
            title: 'Senior Marketing Manager',
            email: 'lisa.vandenberg@email.nl',
            phone: '06-12345678',
            location: 'Amsterdam',
            address: 'Herengracht 256',
            postalCode: '1016 BV',
            summary: 'Resultaatgerichte marketing manager met meer dan 8 jaar ervaring in het ontwikkelen en uitvoeren van omnichannel marketingstrategieen. Bewezen track record in het aansturen van teams, het vergroten van merkbekendheid en het realiseren van significante omzetgroei. Sterk in datagedreven besluitvorming, A/B testing en marketing automation.',
            birthDate: '15 juni 1990',
            birthPlace: 'Den Haag',
            nationality: 'Nederlands',
            driversLicense: 'B',
            gender: '',
            maritalStatus: '',
            linkedIn: 'linkedin.com/in/lisavandenberg',
            github: '',
            website: '',
            photo: '',
        },
        experience: [
            {
                role: 'Senior Marketing Manager',
                company: 'Coolblue',
                location: 'Rotterdam',
                start: 'januari 2021',
                end: 'heden',
                description: 'Verantwoordelijk voor de gehele marketingstrategie van de categorie consumer electronics, met aansturing van een team van 6 marketeers en een jaarlijks budget van 2,5 miljoen euro.',
                highlights: [
                    'Omnichannel campagnestrategie ontwikkeld die de online conversie met 28% verhoogde en de omzet met 3,2 miljoen euro deed groeien',
                    'Marketing automation flows opgezet in HubSpot waardoor de lead-to-customer ratio met 35% verbeterde',
                    'A/B testing framework geimplementeerd voor e-mailcampagnes, resulterend in 22% hogere open rates',
                ],
            },
            {
                role: 'Marketing Manager',
                company: 'VodafoneZiggo',
                location: 'Utrecht',
                start: 'maart 2018',
                end: 'december 2020',
                description: 'Leidde het marketingteam voor de zakelijke divisie en was verantwoordelijk voor campagneontwikkeling, brand management en digitale marketing.',
                highlights: [
                    'Go-to-market strategie ontwikkeld voor drie nieuwe zakelijke producten, met een gezamenlijke omzet van 1,8 miljoen euro in het eerste jaar',
                    'Google Ads en social media campagnes geoptimaliseerd waardoor de cost-per-acquisition met 40% daalde',
                    'Cross-functionele samenwerking met sales en productteams opgezet voor geintegreerde campagneplanning',
                ],
            },
            {
                role: 'Online Marketing Specialist',
                company: 'Booking.com',
                location: 'Amsterdam',
                start: 'september 2015',
                end: 'februari 2018',
                description: 'Verantwoordelijk voor performance marketing campagnes gericht op de Benelux-markt, met focus op SEA, display advertising en retargeting.',
                highlights: [
                    'Performance marketing campagnes beheerd met een maandelijks budget van 150.000 euro en een gemiddelde ROAS van 4,5',
                    'Landing page optimalisatie doorgevoerd die de conversieratio met 18% verhoogde',
                ],
            },
        ],
        education: [
            {
                degree: 'Master Marketingcommunicatie',
                school: 'Universiteit van Amsterdam',
                location: 'Amsterdam',
                start: 'september 2013',
                end: 'juli 2015',
                description: 'Specialisatie Digitale Marketing. Scriptie over de invloed van personalisatie op online conversie in e-commerce.',
            },
            {
                degree: 'Bachelor Commerciele Economie',
                school: 'Hogeschool Rotterdam',
                location: 'Rotterdam',
                start: 'september 2009',
                end: 'juli 2013',
                description: 'Minor International Marketing. Afstudeerproject bij een e-commerce startup over groeistrategie.',
            },
        ],
        skills: [
            { name: 'Campagnestrategie', level: 5 },
            { name: 'Google Ads / SEA', level: 5 },
            { name: 'Marketing Automation (HubSpot)', level: 4 },
            { name: 'A/B Testing & CRO', level: 4 },
            { name: 'Brand Management', level: 4 },
            { name: 'Data-analyse (Google Analytics)', level: 4 },
        ],
        languages: [
            { name: 'Nederlands', level: 'Moedertaal' },
            { name: 'Engels', level: 'Vloeiend' },
            { name: 'Duits', level: 'Goed' },
        ],
        interests: ['Digitale trends', 'Podcasten', 'Hardlopen', 'Reizen'],
        courses: [
            { name: 'Google Ads Certification', institution: 'Google', year: '2023' },
            { name: 'HubSpot Inbound Marketing Certification', institution: 'HubSpot Academy', year: '2022' },
            { name: 'NIMA B Marketing', institution: 'NIMA', year: '2019' },
        ],
        internships: [],
        awards: [],
    },
};
