import { CVExample } from '../../types';

export const prAdviseur: CVExample = {
    slug: 'pr-adviseur',
    categorySlug: 'marketing-en-communicatie',
    name: 'PR-Adviseur',
    description: 'CV voorbeeld voor een PR-adviseur met ervaring in persrelaties, crisiscommunicatie en mediamanagement bij gerenommeerde organisaties.',
    templateId: 'elegant',
    colorThemeId: 'burgundy',

    metaTitle: 'CV Voorbeeld PR-Adviseur | WerkCV.nl',
    metaDesc: 'Professioneel CV voorbeeld voor PR-adviseurs en communicatiespecialisten. Met voorbeeldteksten voor persrelaties, crisiscommunicatie en mediabeheer. Maak direct je CV.',
    keywords: ['cv voorbeeld pr-adviseur', 'cv public relations', 'cv persvoorlichter', 'cv communicatiespecialist', 'pr adviseur cv'],
    heroTitle: 'CV Voorbeeld PR-Adviseur',
    heroText: 'Als PR-adviseur draait alles om reputatie, relaties en overtuigingskracht. Dit CV voorbeeld laat zien hoe je je ervaring met persrelaties, crisiscommunicatie en stakeholder management effectief presenteert. Ideaal voor communicatieprofessionals die hun carriere naar het volgende niveau willen tillen.',
    tips: [
        'Benoem concrete resultaten: media-aandacht, reputatiescores, bereik van persberichten',
        'Vermeld je medianetwerk en ervaring met het opbouwen van persrelaties',
        'Toon je ervaring met crisiscommunicatie en geef voorbeelden van situaties die je hebt gemanaged',
        'Benadruk je schrijfvaardigheid: persberichten, speeches, Q&A-documenten',
        'Laat zien dat je strategisch kunt adviseren op directie- of bestuursniveau',
    ],
    relatedSlugs: ['marketing-en-communicatie/communicatie-adviseur', 'marketing-en-communicatie/content-schrijver'],

    sampleCV: {
        personal: {
            name: 'Eva de Groot',
            title: 'Senior PR-Adviseur',
            email: 'eva.degroot@email.nl',
            phone: '06-45678901',
            location: 'Den Haag',
            address: 'Lange Voorhout 58',
            postalCode: '2514 EG',
            summary: 'Strategische PR-adviseur met meer dan 6 jaar ervaring in corporate communicatie, persrelaties en crisiscommunicatie. Bewezen vermogen om mediaaandacht te genereren, reputaties te beschermen en effectief te adviseren op directieniveau. Sterk netwerk binnen de Nederlandse media en ervaring met zowel B2B als B2C communicatie.',
            birthDate: '3 april 1991',
            birthPlace: 'Delft',
            nationality: 'Nederlands',
            driversLicense: 'B',
            gender: '',
            maritalStatus: '',
            linkedIn: 'linkedin.com/in/evadegroot',
            github: '',
            website: '',
            photo: '',
        },
        experience: [
            {
                role: 'Senior PR-Adviseur',
                company: 'KLM Royal Dutch Airlines',
                location: 'Amstelveen',
                start: 'februari 2021',
                end: 'heden',
                description: 'Verantwoordelijk voor de externe communicatiestrategie en persrelaties van KLM, met focus op corporate reputatie, duurzaamheidscommunicatie en crisismanagement.',
                highlights: [
                    'Mediastrategie ontwikkeld rondom het duurzaamheidsprogramma die resulteerde in 120+ positieve mediaplaatsingen in nationale en internationale media',
                    'Crisiscommunicatieprotocollen opgesteld en geimplementeerd die tijdens twee grote incidenten succesvol werden ingezet',
                    'Mediatrainingen verzorgd voor directieleden en woordvoerders ter voorbereiding op persconferenties en interviews',
                ],
            },
            {
                role: 'PR-Adviseur',
                company: 'Edelman Amsterdam',
                location: 'Amsterdam',
                start: 'september 2018',
                end: 'januari 2021',
                description: 'Adviseerde diverse klanten op het gebied van corporate communicatie, reputatiemanagement en mediarelaties, waaronder Unilever, Shell en ING.',
                highlights: [
                    'PR-campagnes ontwikkeld en uitgevoerd voor 6 klantaccounts met een gecombineerd mediawaarde van meer dan 4 miljoen euro',
                    'Stakeholder analyses en communicatieplannen opgesteld voor productlanceringen en corporate aankondigingen',
                    'Persrelaties opgebouwd met journalisten van NRC, Volkskrant, RTL en NOS',
                ],
            },
            {
                role: 'Junior Communicatieadviseur',
                company: 'Rijksoverheid (Ministerie van Infrastructuur en Waterstaat)',
                location: 'Den Haag',
                start: 'maart 2017',
                end: 'augustus 2018',
                description: 'Ondersteunde het communicatieteam bij persberichten, Kamerbrieven, social media en de woordvoering van de minister.',
                highlights: [
                    'Persberichten en Q&A-documenten geschreven voor parlementaire debatten en beleidsaankondigingen',
                    'Dagelijkse mediamonitoring uitgevoerd en communicatieadviezen opgesteld voor de woordvoerder',
                ],
            },
        ],
        education: [
            {
                degree: 'Master Communicatiewetenschappen',
                school: 'Universiteit van Amsterdam',
                location: 'Amsterdam',
                start: 'september 2015',
                end: 'juli 2017',
                description: 'Specialisatie Corporate Communicatie. Scriptie over de effectiviteit van crisiscommunicatie bij reputatieschade in de luchtvaartsector.',
            },
            {
                degree: 'Bachelor Communicatiewetenschap',
                school: 'Radboud Universiteit',
                location: 'Nijmegen',
                start: 'september 2011',
                end: 'juli 2015',
                description: 'Minor Politieke Communicatie. Afstudeerproject over framingeffecten in Nederlandse nieuwsmedia.',
            },
        ],
        skills: [
            { name: 'Persrelaties & mediamanagement', level: 5 },
            { name: 'Crisiscommunicatie', level: 5 },
            { name: 'Mediatraining & coaching', level: 4 },
            { name: 'Stakeholder Management', level: 4 },
            { name: 'Communicatiestrategie', level: 4 },
            { name: 'Persberichten & speeches', level: 5 },
        ],
        languages: [
            { name: 'Nederlands', level: 'Moedertaal' },
            { name: 'Engels', level: 'Vloeiend' },
            { name: 'Frans', level: 'Goed' },
        ],
        interests: ['Politiek', 'Debatteren', 'Theater', 'Reizen'],
        courses: [
            { name: 'Crisiscommunicatie Masterclass', institution: 'Logeion', year: '2022' },
            { name: 'Advanced Media Relations', institution: 'Nyenrode Business Universiteit', year: '2020' },
        ],
        internships: [],
        awards: [],
    },
};
