import { CVExample } from '../../types';

export const socialMediaSpecialist: CVExample = {
    slug: 'social-media-specialist',
    categorySlug: 'marketing-en-communicatie',
    name: 'Social Media Specialist',
    description: 'CV voorbeeld voor een social media specialist met ervaring in contentcreatie, community management en campagnes op Instagram, TikTok en LinkedIn.',
    templateId: 'jobboss',
    colorThemeId: 'modern-teal',

    metaTitle: 'CV Voorbeeld Social Media Specialist | WerkCV.nl',
    metaDesc: 'Professioneel CV voorbeeld voor social media specialisten. Met voorbeeldteksten voor contentcreatie, community management en social advertising. Maak direct je eigen CV.',
    keywords: ['cv voorbeeld social media specialist', 'cv social media', 'cv community manager', 'social media manager cv', 'cv contentcreator'],
    heroTitle: 'CV Voorbeeld Social Media Specialist',
    heroText: 'Als social media specialist is het essentieel dat je CV laat zien dat je de nieuwste platformen en trends beheerst. Dit voorbeeld toont hoe je groeiresultaten, contentstrategieen en community-engagement overtuigend presenteert aan werkgevers en opdrachtgevers.',
    tips: [
        'Vermeld concrete groeicijfers: aantal volgers, engagement rate, bereik en impressies',
        'Benoem alle platformen waarin je ervaring hebt en je specialisaties per kanaal',
        'Toon je kennis van social media tools zoals Hootsuite, Sprout Social of Later',
        'Voeg een link toe naar je eigen social media profielen of een portfolio met campagnevoorbeelden',
        'Benadruk je vermogen om trends te signaleren en snel in te spelen op actuele ontwikkelingen',
    ],
    relatedSlugs: ['marketing-en-communicatie/content-schrijver', 'marketing-en-communicatie/marketing-manager'],

    sampleCV: {
        personal: {
            name: 'Sophie Jansen',
            title: 'Social Media Specialist',
            email: 'sophie.jansen@email.nl',
            phone: '06-98765432',
            location: 'Utrecht',
            address: 'Oudegracht 178',
            postalCode: '3511 NR',
            summary: 'Creatieve en datagedreven social media specialist met ruim 4 jaar ervaring in het opzetten en uitvoeren van social media strategieen voor zowel B2C als B2B merken. Sterk in contentcreatie, community management en het analyseren van campagneresultaten. Altijd op de hoogte van de nieuwste trends op Instagram, TikTok en LinkedIn.',
            birthDate: '23 november 1996',
            birthPlace: 'Amersfoort',
            nationality: 'Nederlands',
            driversLicense: 'B',
            gender: '',
            maritalStatus: '',
            linkedIn: 'linkedin.com/in/sophiejansen',
            github: '',
            website: '',
            photo: '',
        },
        experience: [
            {
                role: 'Social Media Specialist',
                company: 'Bol.com',
                location: 'Utrecht',
                start: 'april 2022',
                end: 'heden',
                description: 'Verantwoordelijk voor de social media strategie en dagelijkse uitvoering op Instagram, TikTok, Facebook en LinkedIn voor het consumentenmerk.',
                highlights: [
                    'Instagram-volgersaantal gegroeid van 280K naar 520K door gerichte contentstrategie en Reels-campagnes',
                    'TikTok-kanaal gelanceerd dat binnen 8 maanden 150K volgers bereikte met een gemiddelde engagement rate van 6,2%',
                    'Maandelijkse rapportages opgezet in Sprout Social met KPI-dashboards voor het managementteam',
                ],
            },
            {
                role: 'Junior Social Media Manager',
                company: 'DDB Amsterdam',
                location: 'Amsterdam',
                start: 'augustus 2020',
                end: 'maart 2022',
                description: 'Beheerde social media kanalen voor diverse klanten waaronder Volkswagen, Centraal Beheer en C&A, als onderdeel van het digital team.',
                highlights: [
                    'Contentkalenders ontwikkeld en uitgevoerd voor 5 klantaccounts tegelijkertijd met consistente merkidentiteit',
                    'Social advertising campagnes opgezet in Meta Business Suite met een gemiddelde CTR van 3,8%',
                    'Community management uitgevoerd met een gemiddelde responstijd van 30 minuten tijdens kantooruren',
                ],
            },
            {
                role: 'Stagiair Social Media',
                company: 'MediaMarkt Nederland',
                location: 'Rotterdam',
                start: 'februari 2020',
                end: 'juli 2020',
                description: 'Ondersteunde het social media team bij contentcreatie, webcare en campagne-analyse.',
                highlights: [
                    'Content gecreeerd voor Instagram Stories en Facebook posts die samen meer dan 2 miljoen impressies opleverden',
                    'Webcare afgehandeld via Coosto met gemiddeld 50 berichten per dag',
                ],
            },
        ],
        education: [
            {
                degree: 'Bachelor Communicatie',
                school: 'Hogeschool Utrecht',
                location: 'Utrecht',
                start: 'september 2016',
                end: 'juli 2020',
                description: 'Specialisatie Digitale Media & Communicatie. Afstudeerscriptie over de effectiviteit van influencer marketing bij Gen Z.',
            },
        ],
        skills: [
            { name: 'Instagram / TikTok / LinkedIn', level: 5 },
            { name: 'Contentplanning & creatie', level: 5 },
            { name: 'Community Management', level: 4 },
            { name: 'Social Media Analytics', level: 4 },
            { name: 'Meta Business Suite / Ads Manager', level: 4 },
            { name: 'Canva / Adobe Express', level: 3 },
        ],
        languages: [
            { name: 'Nederlands', level: 'Moedertaal' },
            { name: 'Engels', level: 'Vloeiend' },
        ],
        interests: ['Contentcreatie', 'Fotografie', 'Podcasts', 'Yoga'],
        courses: [
            { name: 'Meta Certified Digital Marketing Associate', institution: 'Meta', year: '2023' },
            { name: 'Google Analytics 4 Certification', institution: 'Google', year: '2022' },
        ],
        internships: [],
        awards: [],
    },
};
