import { CVExample } from '../../types';

export const bezorger: CVExample = {
    slug: 'bezorger',
    categorySlug: 'vakmanschap-en-logistiek',
    name: 'Bezorger',
    description: 'CV voorbeeld voor bezorgers. Laat routekennis, klantcontact, verkeersveiligheid, bezorgapps, punctualiteit en voertuigervaring concreet zien.',
    templateId: 'simple',
    colorThemeId: 'modern-teal',

    metaTitle: 'CV Voorbeeld Bezorger | Pakket, Maaltijd & Routeplanning | WerkCV.nl',
    metaDesc: 'Professioneel cv voorbeeld voor bezorger. Met routeplanning, klantcontact, fiets/scooter/auto, bezorgapps, punctualiteit, veiligheid en beschikbaarheid.',
    keywords: [
        'cv voorbeeld bezorger',
        'bezorger cv',
        'cv bezorger',
        'cv pakketbezorger',
        'cv maaltijdbezorger',
        'cv fietsbezorger',
        'cv scooterbezorger',
    ],
    heroTitle: 'CV Voorbeeld Bezorger',
    heroText: 'Een bezorger CV moet snel laten zien dat je betrouwbaar, veilig en klantvriendelijk levert. Dit voorbeeld laat zien hoe je routeplanning, bezorgapps, klantcontact, voertuigervaring, punctualiteit en werken in weer en verkeer professioneel presenteert.',
    tips: [
        'Benoem wat je bezorgt: pakketten, maaltijden, boodschappen, medicijnen, post of interne goederen',
        'Vermeld voertuigervaring: fiets, e-bike, scooter, bestelbus, auto of bakfiets en eventuele rijbewijzen',
        'Laat zien dat je veilig werkt: verkeersregels, schadevrij rijden, HACCP, temperatuur, scancontrole of overdracht',
        'Gebruik concrete context zoals aantal stops, bezorggebied, op tijd geleverd, klantbeoordeling of piekuren',
        'Geef beschikbaarheid duidelijk aan voor avonden, weekenden, feestdagen, vakantieperiodes of fulltime routes',
    ],
    relatedSlugs: [
        'vakmanschap-en-logistiek/chauffeur',
        'vakmanschap-en-logistiek/logistiek-medewerker',
        'studenten-en-starters/bijbaan-deeltijd-cv',
    ],

    sampleCV: {
        personal: {
            name: 'Yassin Boukhari',
            title: 'Bezorger / Pakketbezorger',
            email: 'yassin.boukhari@email.nl',
            phone: '06-88990011',
            location: 'Utrecht',
            address: 'Kanaalstraat 188',
            postalCode: '3531 CP',
            summary: 'Betrouwbare bezorger met 3 jaar ervaring in pakket- en maaltijdbezorging. Ervaren met route-apps, scancontrole, klantcontact, avond- en weekenddiensten en veilig rijden met bestelbus, scooter en e-bike. Bekend om punctuele levering, nette communicatie en rustig blijven bij drukte, slecht weer en routewijzigingen.',
            birthDate: '11 maart 1999',
            birthPlace: 'Utrecht',
            nationality: 'Nederlands',
            driversLicense: 'B',
            gender: '',
            maritalStatus: '',
            linkedIn: '',
            github: '',
            website: '',
            photo: '',
        },
        experience: [
            {
                role: 'Pakketbezorger',
                company: 'PostNL',
                location: 'Utrecht',
                start: 'april 2023',
                end: 'heden',
                description: 'Pakketbezorging in vaste stadsroute met scancontrole, klantcontact en retourregistratie.',
                highlights: [
                    'Gemiddeld 85-110 stops per dag gereden met focus op veilige routekeuze en tijdige levering',
                    'Pakketten gescand, gecontroleerd en correct afgeleverd volgens bezorginstructies',
                    'Klanten vriendelijk geholpen bij niet-thuis, afhaalpunt, retour en beschadigde zendingen',
                    'Bestelbus schadevrij gereden en dagelijkse voertuigcontrole uitgevoerd voor vertrek',
                ],
            },
            {
                role: 'Maaltijdbezorger',
                company: 'Domino\'s Pizza',
                location: 'Utrecht',
                start: 'juni 2021',
                end: 'maart 2023',
                description: 'Maaltijdbezorging per e-bike en scooter tijdens avonden, weekenden en feestdagen.',
                highlights: [
                    'Bestellingen warm en compleet bezorgd tijdens piekuren en slecht weer',
                    'Bezorgapp gebruikt voor route, klantinformatie en statusupdates naar restaurant',
                    'Restaurantteam ondersteund met inpakken, voorraad aanvullen en schoonhouden tussen ritten',
                ],
            },
        ],
        education: [
            {
                degree: 'MBO 3 Logistiek Medewerker',
                school: 'ROC Midden Nederland',
                location: 'Utrecht',
                start: 'september 2016',
                end: 'juli 2020',
                description: 'Opleiding met praktijkervaring in magazijn, distributie, planning en klantgerichte logistiek.',
            },
        ],
        skills: [
            { name: 'Routeplanning', level: 5 },
            { name: 'Klantcontact', level: 5 },
            { name: 'Scancontrole', level: 4 },
            { name: 'Veilig rijden', level: 5 },
            { name: 'Avond/weekenddiensten', level: 5 },
        ],
        languages: [
            { name: 'Nederlands', level: 'Moedertaal' },
            { name: 'Engels', level: 'Goed' },
            { name: 'Arabisch', level: 'Basis' },
        ],
        interests: ['Fietsen', 'Fitness', 'Auto\'s'],
        courses: [
            { name: 'Veilig rijden bestelbus', institution: 'PostNL Academy', year: '2023' },
            { name: 'HACCP basis voor maaltijdbezorging', institution: 'Domino\'s Training', year: '2022' },
        ],
        internships: [],
        awards: [
            'Maandcompliment voor klantvriendelijke bezorging en schadevrij rijden, 2024',
        ],
    },
};
