import { CVExample } from '../../types';

export const chauffeur: CVExample = {
    slug: 'chauffeur',
    categorySlug: 'vakmanschap-en-logistiek',
    name: 'Chauffeur / Vrachtwagenchauffeur',
    description: 'CV voorbeeld voor chauffeurs en vrachtwagenchauffeurs. Laat rijbewijs, Code 95, routeplanning, klantcontact, schadevrij rijden en leverbetrouwbaarheid concreet zien.',
    templateId: 'ats',
    colorThemeId: 'charcoal',

    metaTitle: 'CV Voorbeeld Chauffeur | Transport & Code 95 | WerkCV.nl',
    metaDesc: 'Professioneel cv voorbeeld voor chauffeur en vrachtwagenchauffeur. Met CE-rijbewijs, Code 95, ADR, tachograaf, routeplanning en schadevrije kilometers.',
    keywords: [
        'cv voorbeeld chauffeur',
        'cv vrachtwagenchauffeur voorbeeld',
        'vrachtwagenchauffeur cv voorbeeld',
        'chauffeur cv',
        'cv transport',
        'cv rijbewijs CE',
        'cv code 95',
    ],
    heroTitle: 'CV Voorbeeld Chauffeur',
    heroText: 'Een sterk chauffeur-CV bewijst snel dat je veilig rijdt, afspraken nakomt en professioneel met klanten, lading en documenten omgaat. Dit voorbeeld laat zien hoe je rijbewijzen, Code 95, tachograaf, routeplanning, schadevrije kilometers en nationale of internationale ritervaring overtuigend presenteert.',
    tips: [
        'Vermeld rijbewijzen, Code 95, bestuurderskaart, ADR en eventuele geldigheidsdata duidelijk bij profiel of vaardigheden',
        'Maak betrouwbaarheid meetbaar met schadevrije kilometers, tijdige leveringen, routevolume of lage foutmarge in documenten',
        'Benoem transporttype: distributie, pakket, stukgoed, pallet, koeltransport, bouwtransport, internationaal of pendelritten',
        'Laat zien dat je lading, CMR, tachograaf, boordcomputer, laadklep en klantafhandeling correct beheerst',
        'Solliciteer je als gewone chauffeur, leg dan meer nadruk op rijbewijs B, routekennis, klantcontact en punctualiteit',
    ],
    relatedSlugs: [
        'vakmanschap-en-logistiek/bezorger',
        'vakmanschap-en-logistiek/koerier',
        'vakmanschap-en-logistiek/logistiek-medewerker',
    ],

    sampleCV: {
        personal: {
            name: 'Peter van Dijk',
            title: 'Chauffeur CE / Vrachtwagenchauffeur',
            email: 'peter.vandijk@email.nl',
            phone: '06-56789012',
            location: 'Rotterdam',
            address: 'Maashaven 23',
            postalCode: '3072 AK',
            summary: 'Ervaren chauffeur CE met 12 jaar ervaring in nationaal en internationaal transport. In bezit van rijbewijs B, C en CE, Code 95, bestuurderskaart en ADR-basiscertificaat. Sterk in routeplanning, klantafhandeling, ladingzekering, CMR-documentatie en werken met boordcomputer en tachograaf. Meer dan 1,5 miljoen schadevrije kilometers gereden.',
            birthDate: '8 september 1985',
            birthPlace: 'Dordrecht',
            nationality: 'Nederlands',
            driversLicense: 'B, C, CE',
            gender: '',
            maritalStatus: '',
            linkedIn: '',
            github: '',
            website: '',
            photo: '',
        },
        experience: [
            {
                role: 'Internationaal Vrachtwagenchauffeur',
                company: 'Vos Transport',
                location: 'Rotterdam',
                start: 'juni 2018',
                end: 'heden',
                description: 'Internationaal transport van stukgoed en palletladingen door heel Europa.',
                highlights: [
                    'Wekelijkse ritten naar Duitsland, België, Frankrijk en Scandinavië met tijdige leveringen volgens planning',
                    'Meer dan 600.000 schadevrije kilometers gereden in 6 jaar',
                    'Verantwoordelijk voor ladingzekering, laden, lossen en correcte CMR-documentatie',
                    'Boordcomputer, digitale tachograaf en routewijzigingen zelfstandig bijgehouden',
                ],
            },
            {
                role: 'Vrachtwagenchauffeur Nationaal',
                company: 'PostNL Pakketten',
                location: 'Dordrecht',
                start: 'maart 2012',
                end: 'mei 2018',
                description: 'Distributie van pakketten en palletgoederen binnen Nederland.',
                highlights: [
                    'Dagelijks 15-20 afleveradressen bediend met tijdige levering en correct klantcontact',
                    'Collega-chauffeurs ingewerkt op routes, depotprocedures en scanregistratie',
                    'Kleine afwijkingen in planning, schade of adresgegevens direct gemeld aan transportplanning',
                ],
            },
        ],
        education: [
            {
                degree: 'MBO 2 Chauffeur Goederenvervoer',
                school: 'ROC Zadkine',
                location: 'Rotterdam',
                start: 'september 2009',
                end: 'juli 2011',
                description: 'Opleiding tot beroepschauffeur met rijbewijs C en CE.',
            },
        ],
        skills: [
            { name: 'Rijbewijs CE & ADR', level: 5 },
            { name: 'Routeplanning', level: 5 },
            { name: 'Ladingzekering', level: 4 },
            { name: 'Boordcomputer & Tachograaf', level: 4 },
            { name: 'CMR-documentatie', level: 4 },
            { name: 'Klantafhandeling', level: 4 },
            { name: 'Code 95', level: 5 },
        ],
        languages: [
            { name: 'Nederlands', level: 'Moedertaal' },
            { name: 'Engels', level: 'Goed' },
            { name: 'Duits', level: 'Basis' },
        ],
        interests: ['Motorsport', 'Vissen', 'Kamperen'],
        courses: [
            { name: 'ADR Basiscertificaat', institution: 'NIWO', year: '2023' },
            { name: 'Code 95 Nascholing', institution: 'EVO-Fenedex', year: '2024' },
        ],
        internships: [],
        awards: [],
    },
};
