import { CVExample } from '../../types';

export const koerier: CVExample = {
    slug: 'koerier',
    categorySlug: 'vakmanschap-en-logistiek',
    name: 'Koerier',
    description: 'CV voorbeeld voor koeriers. Laat spoedritten, rijbewijs B, routeplanning, klantoverdracht, transportdocumenten en schadevrij rijden concreet zien.',
    templateId: 'ats',
    colorThemeId: 'elegant-navy',

    metaTitle: 'CV Voorbeeld Koerier | Rijbewijs B, Spoedritten & Transport | WerkCV.nl',
    metaDesc: 'Professioneel cv voorbeeld voor koerier. Met rijbewijs B, spoedritten, routeplanning, transportdocumenten, klantoverdracht en schadevrij rijden.',
    keywords: [
        'cv voorbeeld koerier',
        'koerier cv',
        'cv koerier',
        'cv pakket koerier',
        'cv chauffeur koerier',
        'cv rijbewijs B koerier',
        'cv spoedkoerier',
    ],
    heroTitle: 'CV Voorbeeld Koerier',
    heroText: 'Een koerier CV draait om vertrouwen: op tijd, schadevrij, professioneel aan de deur en netjes met documenten. Dit voorbeeld laat zien hoe je rijbewijs B, spoedritten, routeplanning, klantoverdracht, scanners en transportdocumenten overtuigend presenteert.',
    tips: [
        'Vermeld je rijbewijs, voertuigervaring en of je schadevrij hebt gereden',
        'Noem type koerierswerk: pakketten, documenten, medische zendingen, pallets, B2B, spoedritten of internationaal',
        'Maak punctualiteit concreet met stops per dag, tijdvensters, vaste routes of spoedleveringen',
        'Beschrijf klantoverdracht, handtekeningen, scancontrole, CMR/pakbonnen en retourdocumenten',
        'Laat zien dat je zelfstandig werkt en professioneel blijft bij vertraging, adreswijziging of verkeersdrukte',
    ],
    relatedSlugs: [
        'vakmanschap-en-logistiek/bezorger',
        'vakmanschap-en-logistiek/chauffeur',
        'vakmanschap-en-logistiek/logistiek-medewerker',
    ],

    sampleCV: {
        personal: {
            name: 'Ruben Smits',
            title: 'Koerier / Chauffeur B',
            email: 'ruben.smits@email.nl',
            phone: '06-99001122',
            location: 'Eindhoven',
            address: 'Boschdijk 210',
            postalCode: '5612 HE',
            summary: 'Zelfstandige koerier met 5 jaar ervaring in B2B-zendingen, spoedritten en pakketvervoer met bestelbus. In bezit van rijbewijs B, gewend aan routeplanning, scancontrole, klantoverdracht, pakbonnen en tijdvensters. Schadevrij gereden, representatief aan de deur en sterk in rustig schakelen bij vertragingen of routewijzigingen.',
            birthDate: '27 januari 1991',
            birthPlace: 'Eindhoven',
            nationality: 'Nederlands',
            driversLicense: 'B',
            gender: '',
            maritalStatus: '',
            linkedIn: '',
            github: '',
            website: '',
            photo: '',
        },
        experience: [
            {
                role: 'Koerier B2B',
                company: 'DHL Express',
                location: 'Eindhoven',
                start: 'augustus 2021',
                end: 'heden',
                description: 'Dagelijkse koeriersroutes voor zakelijke klanten, tijdvensters en spoedzendingen.',
                highlights: [
                    'Gemiddeld 55-75 zakelijke stops per dag gereden met scancontrole en correcte klantoverdracht',
                    'Tijdkritische zendingen binnen afgesproken vensters geleverd aan kantoren, labs en winkels',
                    'Pakbonnen, handtekeningen en retourzendingen zorgvuldig verwerkt in chauffeursapp',
                    'Bestelbus dagelijks gecontroleerd en schadevrij gereden op vaste en wisselende routes',
                ],
            },
            {
                role: 'Medisch Koerier',
                company: 'Eurofins Clinical Logistics',
                location: 'Veldhoven',
                start: 'mei 2019',
                end: 'juli 2021',
                description: 'Transport van medische monsters en documenten tussen zorglocaties en laboratoria.',
                highlights: [
                    'Zendingen opgehaald en afgeleverd volgens temperatuur-, tijd- en overdrachtsinstructies',
                    'Afwijkingen direct gemeld aan planning en overdracht vastgelegd in ritadministratie',
                    'Professioneel contact onderhouden met balies, labmedewerkers en zorglocaties',
                ],
            },
        ],
        education: [
            {
                degree: 'MBO 3 Mobiliteit & Transport',
                school: 'Summa College',
                location: 'Eindhoven',
                start: 'september 2008',
                end: 'juli 2012',
                description: 'Opleiding gericht op logistiek, voertuigcontrole, klantcontact en transportplanning.',
            },
        ],
        skills: [
            { name: 'Routeplanning', level: 5 },
            { name: 'Rijbewijs B / bestelbus', level: 5 },
            { name: 'Klantoverdracht', level: 5 },
            { name: 'Scan- en ritadministratie', level: 4 },
            { name: 'Spoedritten', level: 4 },
        ],
        languages: [
            { name: 'Nederlands', level: 'Moedertaal' },
            { name: 'Engels', level: 'Goed' },
            { name: 'Duits', level: 'Basis' },
        ],
        interests: ['Autorijden', 'Wielrennen', 'Reizen'],
        courses: [
            { name: 'Defensief rijden bestelbus', institution: 'DHL Academy', year: '2023' },
            { name: 'ADR bewustwording basis', institution: 'Transport Academy', year: '2021' },
        ],
        internships: [],
        awards: [
            'Schadevrij rijden en hoogste punctualiteit team Eindhoven, 2023',
        ],
    },
};
