import { CVExample } from '../../types';

export const logistiekMedewerker: CVExample = {
    slug: 'logistiek-medewerker',
    categorySlug: 'vakmanschap-en-logistiek',
    name: 'Logistiek Medewerker',
    description: 'CV voorbeeld voor logistiek medewerkers. Laat inbound, outbound, laden/lossen, voorraadbeheer, WMS, retouren en transportdocumenten concreet zien.',
    templateId: 'robust',
    colorThemeId: 'charcoal',

    metaTitle: 'CV Voorbeeld Logistiek Medewerker | Inbound, Outbound & WMS | WerkCV.nl',
    metaDesc: 'Professioneel cv voorbeeld voor logistiek medewerker. Met inbound, outbound, laden/lossen, voorraadbeheer, WMS, retouren, EPT en ploegendienst.',
    keywords: [
        'cv voorbeeld logistiek medewerker',
        'logistiek medewerker cv',
        'cv logistiek medewerker',
        'cv warehouse medewerker',
        'cv inbound outbound',
        'cv magazijn medewerker',
        'cv logistiek',
    ],
    heroTitle: 'CV Voorbeeld Logistiek Medewerker',
    heroText: 'Een logistiek medewerker CV moet laten zien dat je de goederenstroom begrijpt: ontvangen, controleren, opslaan, picken, verzendklaar maken en registreren. Dit voorbeeld toont hoe je inbound, outbound, WMS, EPT, voorraadbeheer, retouren en ploegendienst helder opschrijft.',
    tips: [
        'Maak duidelijk waar je ervaring ligt: inbound, outbound, orderpicking, retouren, crossdock, expeditie of voorraadbeheer',
        'Noem systemen en hulpmiddelen zoals WMS, ERP, handscanner, EPT, heftruck, reachtruck, palletwagen of labelprinter',
        'Gebruik concrete resultaten zoals verwerkte pallets, minder voorraadverschillen, foutloze verzending of snellere doorlooptijd',
        'Vermeld certificaten: heftruck, reachtruck, EPT, VCA, BHV, ADR-basis of veilig werken',
        'Benoem beschikbaarheid voor ploegendienst, weekend, piekperiodes en fysiek werk',
    ],
    relatedSlugs: [
        'vakmanschap-en-logistiek/magazijnmedewerker',
        'vakmanschap-en-logistiek/orderpicker',
        'vakmanschap-en-logistiek/chauffeur',
    ],

    sampleCV: {
        personal: {
            name: 'Kelly van der Meer',
            title: 'Logistiek Medewerker',
            email: 'kelly.vandermeer@email.nl',
            phone: '06-77889900',
            location: 'Venlo',
            address: 'Tegelseweg 72',
            postalCode: '5912 BL',
            summary: 'Allround logistiek medewerker met 6 jaar ervaring in inbound, outbound, orderpicking, retourverwerking en voorraadcontrole. Ervaren met WMS, handscanner, EPT, labelprinters en werken in 2-ploegendienst. Sterk in nauwkeurige goederencontrole, veilige werkplek en duidelijke overdracht tussen magazijn, planning en transport.',
            birthDate: '2 oktober 1992',
            birthPlace: 'Venlo',
            nationality: 'Nederlands',
            driversLicense: 'B',
            gender: '',
            maritalStatus: '',
            linkedIn: '',
            github: '',
            website: '',
            photo: '',
        },
        experience: [
            {
                role: 'Logistiek Medewerker Inbound & Outbound',
                company: 'DHL Supply Chain',
                location: 'Venlo',
                start: 'februari 2021',
                end: 'heden',
                description: 'Verwerken van inkomende en uitgaande goederen in een internationaal distributiecentrum.',
                highlights: [
                    'Dagelijks 70+ pallets ontvangen, gecontroleerd en geregistreerd in WMS met aandacht voor schade en aantallen',
                    'Outbound zendingen verzendklaar gemaakt met labels, pakbonnen en controle op juiste klantorder',
                    'EPT en handscanner gebruikt voor verplaatsingen, locatiebeheer en aanvullen van picklocaties',
                    'Voorraadverschillen onderzocht en teruggekoppeld aan teamleider en voorraadbeheer',
                ],
            },
            {
                role: 'Magazijnmedewerker Retouren',
                company: 'VidaXL',
                location: 'Venlo',
                start: 'juni 2018',
                end: 'januari 2021',
                description: 'Retourverwerking, kwaliteitscontrole en herverpakken van consumentenproducten.',
                highlights: [
                    'Retourartikelen gecontroleerd op schade, volledigheid en herverkoopbaarheid',
                    'Producten opnieuw verpakt, gelabeld en op juiste voorraadlocatie gezet',
                    'Nieuwe collega\'s ingewerkt op retourprocedure en veiligheidsregels',
                ],
            },
        ],
        education: [
            {
                degree: 'MBO 3 Logistiek Teamleider',
                school: 'Gilde Opleidingen',
                location: 'Venlo',
                start: 'september 2014',
                end: 'juli 2018',
                description: 'Opleiding gericht op warehouseprocessen, voorraadbeheer, transportdocumenten en veilig werken.',
            },
        ],
        skills: [
            { name: 'Inbound & outbound', level: 5 },
            { name: 'WMS & handscanner', level: 5 },
            { name: 'Voorraadcontrole', level: 4 },
            { name: 'Retourverwerking', level: 4 },
            { name: 'EPT & palletwerk', level: 5 },
        ],
        languages: [
            { name: 'Nederlands', level: 'Moedertaal' },
            { name: 'Engels', level: 'Goed' },
            { name: 'Duits', level: 'Basis' },
        ],
        interests: ['Wandelen', 'Fitness', 'Koken'],
        courses: [
            { name: 'EPT en veilig intern transport', institution: 'DHL Training', year: '2022' },
            { name: 'VCA Basis', institution: 'PBNA', year: '2020' },
            { name: 'WMS basisgebruik', institution: 'VidaXL Academy', year: '2019' },
        ],
        internships: [],
        awards: [
            'Teamcompliment voor foutloze inboundcontrole tijdens piekweek, 2023',
        ],
    },
};
