import { CVExample } from '../../types';

export const magazijnmedewerker: CVExample = {
    slug: 'magazijnmedewerker',
    categorySlug: 'vakmanschap-en-logistiek',
    name: 'Magazijnmedewerker',
    description: 'CV voorbeeld voor magazijnmedewerkers, orderpickers en logistiek medewerkers. Laat WMS, scanner, heftruck, veiligheid en productiviteit concreet zien.',
    templateId: 'simple',
    colorThemeId: 'charcoal',

    metaTitle: 'CV Voorbeeld Magazijnmedewerker | Orderpicker & WMS | WerkCV.nl',
    metaDesc: 'Professioneel cv voorbeeld voor magazijnmedewerker, orderpicker en logistiek medewerker. Met WMS, scanner, heftruck, reachtruck, veiligheid en picksnelheid.',
    keywords: ['cv voorbeeld magazijnmedewerker', 'magazijnmedewerker cv', 'cv orderpicker', 'cv logistiek medewerker', 'cv magazijn', 'cv heftruck', 'cv reachtruck', 'cv WMS'],
    heroTitle: 'CV Voorbeeld Magazijnmedewerker',
    heroText: 'Als magazijnmedewerker ben je een belangrijke schakel in de logistieke keten. Dit CV voorbeeld laat zien hoe je orderpicking, WMS, scanners, heftruck/reachtruck, voorraadcontrole, veiligheid en ploegendienst professioneel presenteert.',
    tips: [
        'Vermeld je certificaten met type: heftruck, reachtruck, EPT, VCA, BHV of ADR-basis',
        'Noem WMS-, ERP- en scannersystemen zoals SAP EWM, Reflex, Navision, Picqer of voice picking',
        'Geef aan of je ervaring hebt met inbound, outbound, retouren, voorraadcontrole, laden/lossen of crossdock',
        'Maak productiviteit meetbaar met orderregels per uur, picknauwkeurigheid, palletvolume of foutreductie',
        'Benoem beschikbaarheid voor 2- of 3-ploegendienst, nachtwerk, weekendwerk en fysieke belastbaarheid',
    ],
    relatedSlugs: ['vakmanschap-en-logistiek/logistiek-coordinator', 'vakmanschap-en-logistiek/productiemedewerker', 'vakmanschap-en-logistiek/chauffeur'],

    sampleCV: {
        personal: {
            name: 'Ricardo Bakker',
            title: 'Magazijnmedewerker / Orderpicker',
            email: 'ricardo.bakker@email.nl',
            phone: '06-67890123',
            location: 'Tilburg',
            address: 'Ringbaan Zuid 112',
            postalCode: '5021 DL',
            summary: 'Nauwkeurige magazijnmedewerker en orderpicker met 5 jaar ervaring in e-commerce en retaildistributie. Ervaren met SAP EWM, handscanner, voice picking, inbound, outbound, voorraadcontrole en reachtruckwerk. Bekend om hoge picknauwkeurigheid, veilig werken en stabiele inzet in 2- en 3-ploegendienst.',
            birthDate: '27 augustus 1995',
            birthPlace: 'Tilburg',
            nationality: 'Nederlands',
            driversLicense: 'B',
            gender: '',
            maritalStatus: '',
            linkedIn: '',
            github: '',
            website: '',
            photo: '',
        },
        experience: [
            {
                role: 'Magazijnmedewerker / Orderpicker',
                company: 'Bol.com Fulfilment Center',
                location: 'Waalwijk',
                start: 'augustus 2022',
                end: 'heden',
                description: 'Orderpicking, inslag en uitslag van goederen in een grootschalig distributiecentrum.',
                highlights: [
                    'Gemiddeld 150 orderregels per uur gepickt met 99,5% nauwkeurigheid',
                    'Reachtruck bediend voor palletplaatsing op hoogte, aanvullen van picklocaties en spoedorders',
                    'SAP EWM en handscanner gebruikt voor orderpicking, voorraadcorrecties en locatiecontroles',
                    'Nieuwe medewerkers ingewerkt op pickprocedures, looproutes, veiligheidsprotocollen en foutmeldingen',
                ],
            },
            {
                role: 'Logistiek Medewerker',
                company: 'Lidl Distributiecentrum',
                location: 'Heerenveen',
                start: 'januari 2019',
                end: 'juli 2022',
                description: 'Verwerken van inkomende en uitgaande goederen in het distributiecentrum.',
                highlights: [
                    'Dagelijks 80+ pallets verwerkt bij inslag en uitslag',
                    'Voorraadverschillen teruggebracht met 30% door nauwkeurige controle',
                    'Retouren en beschadigde goederen gecontroleerd, gelabeld en correct geregistreerd in het WMS',
                ],
            },
        ],
        education: [
            {
                degree: 'MBO 2 Logistiek Medewerker',
                school: 'ROC van Amsterdam',
                location: 'Amsterdam',
                start: 'september 2015',
                end: 'juli 2018',
                description: 'Opleiding tot logistiek medewerker met praktijkstages in distributiecentra.',
            },
        ],
        skills: [
            { name: 'Orderpicking', level: 5 },
            { name: 'Heftruck & Reachtruck', level: 5 },
            { name: 'SAP EWM & scanners', level: 4 },
            { name: 'Voorraadbeheer', level: 4 },
            { name: 'Inbound & outbound', level: 5 },
        ],
        languages: [
            { name: 'Nederlands', level: 'Moedertaal' },
            { name: 'Engels', level: 'Basis' },
        ],
        interests: ['Fitness', 'Gaming', 'Voetbal'],
        courses: [
            { name: 'Heftruckcertificaat (Reachtruck)', institution: 'BMWT', year: '2022' },
            { name: 'VCA-basis', institution: 'PBNA', year: '2021' },
            { name: 'Voice picking en scannertraining', institution: 'Bol.com Academy', year: '2022' },
        ],
        internships: [],
        awards: [],
    },
};
