import { CVExample } from '../../types';

export const orderpicker: CVExample = {
    slug: 'orderpicker',
    categorySlug: 'vakmanschap-en-logistiek',
    name: 'Orderpicker',
    description: 'CV voorbeeld voor orderpickers. Laat picksnelheid, scanner, WMS, voice picking, EPT, nauwkeurigheid en ploegendienst concreet zien.',
    templateId: 'ats',
    colorThemeId: 'charcoal',

    metaTitle: 'CV Voorbeeld Orderpicker | WMS, Scanner & Ploegendienst | WerkCV.nl',
    metaDesc: 'Professioneel cv voorbeeld voor orderpicker. Met picksnelheid, handscanner, WMS, voice picking, EPT, voorraadcontrole, nauwkeurigheid en ploegendienst.',
    keywords: [
        'cv voorbeeld orderpicker',
        'orderpicker cv',
        'cv orderpicker',
        'cv orderpicken',
        'cv magazijn orderpicker',
        'cv voice picking',
        'cv handscanner magazijn',
    ],
    heroTitle: 'CV Voorbeeld Orderpicker',
    heroText: 'Een orderpicker CV moet direct laten zien dat je snel, nauwkeurig en veilig kunt werken. Dit voorbeeld toont hoe je picksnelheid, handscanner, WMS, voice picking, EPT, voorraadcontrole en ploegendienst vertaalt naar sterke CV-bullets.',
    tips: [
        'Noem je pickmethode: handscanner, voice picking, picklijst, WMS of goods-to-person',
        'Maak nauwkeurigheid meetbaar met pickregels per uur, foutpercentage, retouren of voorraadverschillen',
        'Vermeld certificaten en hulpmiddelen zoals EPT, reachtruck, heftruck, VCA of veiligheidstraining',
        'Beschrijf het type magazijn: e-commerce, retail, food, koel/vries, pharma, crossdock of distributiecentrum',
        'Geef beschikbaarheid voor 2- of 3-ploegendienst, nachtwerk, weekendwerk en fysieke belasting duidelijk aan',
    ],
    relatedSlugs: [
        'vakmanschap-en-logistiek/magazijnmedewerker',
        'vakmanschap-en-logistiek/logistiek-coordinator',
        'vakmanschap-en-logistiek/productiemedewerker',
    ],

    sampleCV: {
        personal: {
            name: 'Samir Aydin',
            title: 'Orderpicker / Magazijnmedewerker',
            email: 'samir.aydin@email.nl',
            phone: '06-66778899',
            location: 'Tilburg',
            address: 'Korvelseweg 104',
            postalCode: '5025 JK',
            summary: 'Nauwkeurige orderpicker met 4 jaar ervaring in e-commerce en retaildistributie. Ervaren met handscanner, voice picking, SAP EWM, EPT, voorraadcontrole en werken in 2-ploegendienst. Bekend om hoge picksnelheid, lage foutmarge en veilig werken in drukke distributiecentra. Fysiek fit en direct inzetbaar voor fulltime magazijnwerk.',
            birthDate: '14 juni 1997',
            birthPlace: 'Tilburg',
            nationality: 'Nederlands',
            driversLicense: 'B',
            gender: '',
            maritalStatus: '',
            linkedIn: '',
            github: '',
            website: '',
            photo: '',
        },
        experience: [
            {
                role: 'Orderpicker E-commerce',
                company: 'Bol.com Fulfilment Center',
                location: 'Waalwijk',
                start: 'mei 2022',
                end: 'heden',
                description: 'Orderpicking, controle en verzendklaar maken van klantorders binnen een grootschalig fulfilment center.',
                highlights: [
                    'Gemiddeld 165 orderregels per uur gepickt met 99,6% nauwkeurigheid via handscanner en SAP EWM',
                    'EPT gebruikt voor verplaatsen van rolcontainers en aanvullen van picklocaties tijdens piekuren',
                    'Afwijkingen, beschadigde artikelen en voorraadverschillen direct geregistreerd in het WMS',
                    'Nieuwe uitzendkrachten ingewerkt op scanproces, looproutes, veiligheid en foutmeldingen',
                ],
            },
            {
                role: 'Orderpicker Retaildistributie',
                company: 'Jumbo Distributiecentrum',
                location: 'Breda',
                start: 'januari 2020',
                end: 'april 2022',
                description: 'Orderpicken van winkelbestellingen in gekoelde en droge zones.',
                highlights: [
                    'Voice picking gebruikt voor winkelorders in 2-ploegendienst en weekenddiensten',
                    'Producten gecontroleerd op code, aantal, houdbaarheid en beschadiging voor verzending',
                    'Werkplek veilig en schoon gehouden volgens HACCP- en magazijnafspraken',
                ],
            },
        ],
        education: [
            {
                degree: 'MBO 2 Logistiek Medewerker',
                school: 'ROC Tilburg',
                location: 'Tilburg',
                start: 'september 2016',
                end: 'juli 2019',
                description: 'Praktijkgerichte opleiding met stages in magazijn, orderpicking en goederenontvangst.',
            },
        ],
        skills: [
            { name: 'Orderpicking', level: 5 },
            { name: 'Handscanner & WMS', level: 5 },
            { name: 'Voice picking', level: 4 },
            { name: 'EPT & rolcontainers', level: 4 },
            { name: 'Ploegendienst', level: 5 },
        ],
        languages: [
            { name: 'Nederlands', level: 'Goed' },
            { name: 'Engels', level: 'Basis' },
            { name: 'Turks', level: 'Goed' },
        ],
        interests: ['Fitness', 'Voetbal', 'Auto\'s'],
        courses: [
            { name: 'EPT veilig werken', institution: 'Bol.com Academy', year: '2023' },
            { name: 'VCA Basis', institution: 'PBNA', year: '2021' },
            { name: 'Voice picking training', institution: 'Jumbo DC', year: '2020' },
        ],
        internships: [],
        awards: [
            'Top 5 picknauwkeurigheid team Waalwijk tijdens feestdagenpiek, 2023',
        ],
    },
};
