import { CVExample } from '../../types';

export const orderpicker: CVExample = {
    slug: 'orderpicker',
    categorySlug: 'vakmanschap-en-logistiek',
    name: 'Orderpicker',
    description: 'CV voorbeeld voor orderpickers. Laat picksnelheid, scanner, WMS, voice picking, EPT, nauwkeurigheid en ploegendienst concreet zien.',
    templateId: 'ats',
    colorThemeId: 'charcoal',

    metaTitle: 'CV Voorbeeld Orderpicker | WMS, Scanner & Ploegendienst | WerkCV.nl',
    metaDesc: 'Professioneel cv voorbeeld voor orderpicker. Met picksnelheid, handscanner, WMS, voice picking, EPT, voorraadcontrole, nauwkeurigheid en ploegendienst.',
    keywords: [
        'cv voorbeeld orderpicker',
        'orderpicker cv',
        'cv orderpicker',
        'cv orderpicken',
        'cv magazijn orderpicker',
        'cv voice picking',
        'cv handscanner magazijn',
    ],
    heroTitle: 'CV Voorbeeld Orderpicker',
    heroText: 'Een orderpicker CV moet direct laten zien dat je snel, nauwkeurig en veilig kunt werken. Dit voorbeeld toont hoe je picksnelheid, handscanner, WMS, voice picking, EPT, voorraadcontrole en ploegendienst vertaalt naar sterke CV-bullets.',
    tips: [
        'Noem je pickmethode: handscanner, voice picking, picklijst, WMS of goods-to-person',
        'Maak nauwkeurigheid meetbaar met pickregels per uur, foutpercentage, retouren of voorraadverschillen',
        'Vermeld certificaten en hulpmiddelen zoals EPT, reachtruck, heftruck, VCA of veiligheidstraining',
        'Beschrijf het type magazijn: e-commerce, retail, food, koel/vries, pharma, crossdock of distributiecentrum',
        'Geef beschikbaarheid voor 2- of 3-ploegendienst, nachtwerk, weekendwerk en fysieke belasting duidelijk aan',
    ],
    expertContent: {
        recruiterFocus: [
            'Een recruiter zoekt direct naar pickmethode, tempo en foutmarge. Zonder die context blijft "orderpicken" te algemeen.',
            'Systemen en hulpmiddelen zijn belangrijk: handscanner, voice picking, WMS, SAP EWM, EPT, reachtruck of palletwagen.',
            'Het type omgeving maakt verschil. E-commerce, retaildistributie, food, koel/vries en pharma vragen andere nauwkeurigheid en werkafspraken.',
            'Beschikbaarheid voor ploegendienst, piekperiodes en fysiek werk moet expliciet zijn, zeker bij distributiecentra met vaste shifts.',
        ],
        copyReadyBullets: [
            'Gemiddeld 150+ orderregels per uur gepickt met handscanner en WMS, met aandacht voor juiste locatie, aantal en artikelcode.',
            'Voice picking gebruikt in 2-ploegendienst voor winkelorders, inclusief controle op houdbaarheid, schade en verzendklaarheid.',
            'Voorraadverschillen, beschadigde artikelen en pickfouten direct geregistreerd en teruggekoppeld aan teamleider.',
            'EPT en rolcontainers veilig gebruikt voor aanvullen van picklocaties en verplaatsen van goederen tijdens piekuren.',
            'Nieuwe collega\'s ingewerkt op looproutes, scanproces, foutmeldingen en veiligheidsafspraken.',
        ],
        noExperienceAdvice: [
            'Heb je nog geen magazijnervaring, benadruk dan fysieke inzetbaarheid, nauwkeurig werken en beschikbaarheid voor shifts.',
            'Gebruik ervaring uit supermarkt, productie, pakketbezorging of horeca als bewijs voor tempo en discipline.',
            'Zet certificaten of bereidheid tot EPT/heftrucktraining duidelijk in je vaardigheden of profieltekst.',
        ],
        rewriteExamples: [
            {
                bad: 'Ik pickte orders in het magazijn.',
                good: 'Orders gepickt met handscanner en WMS, gemiddeld 150+ orderregels per uur met controle op artikelcode, aantal en locatie.',
                reason: 'De sterke versie geeft methode, tempo en nauwkeurigheidscontext.',
            },
            {
                bad: 'Ik kan goed werken onder druk.',
                good: 'Tijdens feestdagenpiek extra shifts gedraaid en picklocaties aangevuld met EPT zonder veiligheidsmeldingen.',
                reason: 'Druk aankunnen wordt concreet door piekperiode, extra inzet en veilig werken te benoemen.',
            },
        ],
        trustSignals: [
            'Pickmethode en WMS staan in profieltekst en werkervaring.',
            'Tempo of nauwkeurigheid is meetbaar gemaakt met aantallen of foutmarge.',
            'Ploegendienst, weekendwerk en fysieke inzetbaarheid zijn zichtbaar.',
            'Veilig werken en afwijkingen melden worden expliciet genoemd.',
        ],
    },
    relatedSlugs: [
        'vakmanschap-en-logistiek/magazijnmedewerker',
        'vakmanschap-en-logistiek/logistiek-coordinator',
        'vakmanschap-en-logistiek/productiemedewerker',
    ],

    sampleCV: {
        personal: {
            name: 'Samir Aydin',
            title: 'Orderpicker / Magazijnmedewerker',
            email: 'samir.aydin@email.nl',
            phone: '06-66778899',
            location: 'Tilburg',
            address: 'Korvelseweg 104',
            postalCode: '5025 JK',
            summary: 'Nauwkeurige orderpicker met 4 jaar ervaring in e-commerce en retaildistributie. Ervaren met handscanner, voice picking, SAP EWM, EPT, voorraadcontrole en werken in 2-ploegendienst. Bekend om hoge picksnelheid, lage foutmarge en veilig werken in drukke distributiecentra. Fysiek fit en direct inzetbaar voor fulltime magazijnwerk.',
            birthDate: '14 juni 1997',
            birthPlace: 'Tilburg',
            nationality: 'Nederlands',
            driversLicense: 'B',
            gender: '',
            maritalStatus: '',
            linkedIn: '',
            github: '',
            website: '',
            photo: '',
        },
        experience: [
            {
                role: 'Orderpicker E-commerce',
                company: 'Bol.com Fulfilment Center',
                location: 'Waalwijk',
                start: 'mei 2022',
                end: 'heden',
                description: 'Orderpicking, controle en verzendklaar maken van klantorders binnen een grootschalig fulfilment center.',
                highlights: [
                    'Gemiddeld 165 orderregels per uur gepickt met 99,6% nauwkeurigheid via handscanner en SAP EWM',
                    'EPT gebruikt voor verplaatsen van rolcontainers en aanvullen van picklocaties tijdens piekuren',
                    'Afwijkingen, beschadigde artikelen en voorraadverschillen direct geregistreerd in het WMS',
                    'Nieuwe uitzendkrachten ingewerkt op scanproces, looproutes, veiligheid en foutmeldingen',
                ],
            },
            {
                role: 'Orderpicker Retaildistributie',
                company: 'Jumbo Distributiecentrum',
                location: 'Breda',
                start: 'januari 2020',
                end: 'april 2022',
                description: 'Orderpicken van winkelbestellingen in gekoelde en droge zones.',
                highlights: [
                    'Voice picking gebruikt voor winkelorders in 2-ploegendienst en weekenddiensten',
                    'Producten gecontroleerd op code, aantal, houdbaarheid en beschadiging voor verzending',
                    'Werkplek veilig en schoon gehouden volgens HACCP- en magazijnafspraken',
                ],
            },
        ],
        education: [
            {
                degree: 'MBO 2 Logistiek Medewerker',
                school: 'ROC Tilburg',
                location: 'Tilburg',
                start: 'september 2016',
                end: 'juli 2019',
                description: 'Praktijkgerichte opleiding met stages in magazijn, orderpicking en goederenontvangst.',
            },
        ],
        skills: [
            { name: 'Orderpicking', level: 5 },
            { name: 'Handscanner & WMS', level: 5 },
            { name: 'Voice picking', level: 4 },
            { name: 'EPT & rolcontainers', level: 4 },
            { name: 'Ploegendienst', level: 5 },
        ],
        languages: [
            { name: 'Nederlands', level: 'Goed' },
            { name: 'Engels', level: 'Basis' },
            { name: 'Turks', level: 'Goed' },
        ],
        interests: ['Fitness', 'Voetbal', 'Auto\'s'],
        courses: [
            { name: 'EPT veilig werken', institution: 'Bol.com Academy', year: '2023' },
            { name: 'VCA Basis', institution: 'PBNA', year: '2021' },
            { name: 'Voice picking training', institution: 'Jumbo DC', year: '2020' },
        ],
        internships: [],
        awards: [
            'Top 5 picknauwkeurigheid team Waalwijk tijdens feestdagenpiek, 2023',
        ],
    },
};
