import { CVExample } from '../../types';

export const productiemedewerker: CVExample = {
    slug: 'productiemedewerker',
    categorySlug: 'vakmanschap-en-logistiek',
    name: 'Productiemedewerker',
    description: 'CV voorbeeld voor productiemedewerkers. Laat zien hoe je lijnwerk, machinebediening, kwaliteitscontrole, veiligheid en ploegendienst concreet presenteert.',
    templateId: 'robust',
    colorThemeId: 'charcoal',

    metaTitle: 'CV Voorbeeld Productiemedewerker | WerkCV.nl',
    metaDesc: 'Professioneel cv voorbeeld voor productiemedewerkers. Met profieltekst, werkervaring, productie, machinebediening, kwaliteitscontrole, veiligheid en ploegendienst.',
    keywords: [
        'cv voorbeeld productiemedewerker',
        'productiemedewerker cv',
        'cv productie medewerker',
        'cv fabrieksmedewerker',
        'cv assemblagemedewerker',
        'cv machinebediening',
        'cv ploegendienst',
    ],
    heroTitle: 'CV Voorbeeld Productiemedewerker',
    heroText: 'Een goed productiemedewerker CV bewijst dat je veilig, constant en nauwkeurig werkt. Dit voorbeeld laat zien hoe je lijnwerk, machinebediening, kwaliteitscontrole, HACCP/GMP, 5S en ploegendienst professioneel verwerkt in je profiel en werkervaring.',
    tips: [
        'Benoem het type productieomgeving: food, verpakking, assemblage, metaal, kunststof, logistieke productie of farmacie',
        'Laat veiligheid en kwaliteit terugkomen in je werkervaring, niet alleen in je vaardighedenlijst',
        'Gebruik concrete output: aantallen, lijnsnelheid, foutreductie, omsteltijd, afvalreductie of productiedoelen',
        'Vermeld ploegendiensten, heftruck/EPT, VCA, HACCP, GMP, 5S of lean als je daar ervaring mee hebt',
        'Maak duidelijk of je alleen uitvoert, machines instelt, collega’s inwerkt of meedenkt over procesverbetering',
    ],
    relatedSlugs: [
        'vakmanschap-en-logistiek/magazijnmedewerker',
        'vakmanschap-en-logistiek/logistiek-coordinator',
        'technologie-en-ict/technische-dienst',
    ],

    sampleCV: {
        personal: {
            name: 'Jordi van Dalen',
            title: 'Productiemedewerker',
            email: 'jordi.vandalen@email.nl',
            phone: '06-78901234',
            location: 'Eindhoven',
            address: 'Tongelresestraat 122',
            postalCode: '5613 DP',
            summary: 'Nauwkeurige productiemedewerker met 5 jaar ervaring in food- en verpakkingsproductie. Gewend aan werken aan productielijnen, visuele kwaliteitscontroles, machinebediening, omstellen en veilig werken volgens HACCP en 5S. Betrouwbaar in 2- en 3-ploegendienst, fysiek fit en sterk in samenwerken met operators, technische dienst en logistiek.',
            birthDate: '6 november 1993',
            birthPlace: 'Eindhoven',
            nationality: 'Nederlands',
            driversLicense: 'B',
            gender: '',
            maritalStatus: '',
            linkedIn: '',
            github: '',
            website: '',
            photo: '',
        },
        experience: [
            {
                role: 'Productiemedewerker Verpakking',
                company: 'Vion Food Group',
                location: 'Boxtel',
                start: 'juni 2021',
                end: 'heden',
                description: 'Werkzaam aan verpakkingslijnen binnen een foodproductieomgeving met focus op kwaliteit, hygiëne en constante output.',
                highlights: [
                    'Productielijn aangevuld, gecontroleerd en schoon overgedragen volgens HACCP- en werkinstructies',
                    'Visuele kwaliteitscontroles uitgevoerd op verpakking, etiketten, houdbaarheidsdatum en sealnaden',
                    'Kleine storingen tijdig gesignaleerd en samen met operator opgelost om stilstand te beperken',
                    'Nieuwe uitzendkrachten ingewerkt op lijnveiligheid, werktempo en hygiëneregels',
                ],
            },
            {
                role: 'Assemblagemedewerker',
                company: 'VDL Industrial Modules',
                location: 'Eindhoven',
                start: 'maart 2018',
                end: 'mei 2021',
                description: 'Assemblage van onderdelen en halffabricaten binnen een technische productieomgeving.',
                highlights: [
                    'Onderdelen gemonteerd volgens technische werkinstructies en kwaliteitsnormen',
                    'Dagelijkse productiedoelen gehaald met behoud van nauwkeurigheid en nette werkplek',
                    '5S-afspraken toegepast voor gereedschap, voorraadpunten en veilige looproutes',
                ],
            },
        ],
        education: [
            {
                degree: 'MBO 2 Entree Techniek',
                school: 'Summa College',
                location: 'Eindhoven',
                start: 'september 2015',
                end: 'juli 2017',
                description: 'Praktijkgerichte opleiding met stages in productie, techniek en logistiek.',
            },
        ],
        skills: [
            { name: 'Productielijnwerk', level: 5 },
            { name: 'Kwaliteitscontrole', level: 5 },
            { name: 'Machinebediening', level: 4 },
            { name: 'HACCP & hygiëne', level: 4 },
            { name: 'Ploegendienst', level: 5 },
        ],
        languages: [
            { name: 'Nederlands', level: 'Goed' },
            { name: 'Engels', level: 'Basis' },
        ],
        interests: ['Fitness', 'Auto\'s', 'Voetbal'],
        courses: [
            { name: 'HACCP Basis', institution: 'Vion Academy', year: '2022' },
            { name: 'VCA Basis', institution: 'PBNA', year: '2020' },
            { name: '5S op de werkvloer', institution: 'VDL Training', year: '2019' },
        ],
        internships: [],
        awards: [
            'Veiligheidsmelding van de maand bij Vion Food Group voor vroeg signaleren van een lijnrisico, 2023',
        ],
    },
};
