import { CVExample } from '../../types';

export const schoonmaker: CVExample = {
    slug: 'schoonmaker',
    categorySlug: 'vakmanschap-en-logistiek',
    name: 'Schoonmaker',
    description: 'CV voorbeeld voor schoonmakers en schoonmaakmedewerkers. Laat zien hoe je hygiëne, betrouwbaarheid, materiaalkennis en objectervaring concreet presenteert.',
    templateId: 'simple',
    colorThemeId: 'charcoal',

    metaTitle: 'CV Voorbeeld Schoonmaker | WerkCV.nl',
    metaDesc: 'Professioneel cv voorbeeld voor schoonmaker en schoonmaakmedewerker. Met profieltekst, werkervaring, hygiëne, materiaalkennis, certificaten en vaardigheden.',
    keywords: [
        'cv voorbeeld schoonmaker',
        'schoonmaker cv',
        'cv schoonmaakmedewerker',
        'cv schoonmaakster',
        'cv facilitair medewerker',
        'cv housekeeping',
        'cv schoonmaak',
    ],
    heroTitle: 'CV Voorbeeld Schoonmaker',
    heroText: 'Een sterk schoonmaak CV laat niet alleen zien dat je ruimtes schoonmaakt, maar ook dat je betrouwbaar, zorgvuldig en inzetbaar bent op verschillende locaties. Dit voorbeeld toont hoe je kantoor-, zorg-, school- en sanitairreiniging, materiaalkennis, sleutelbeheer en hygiënevoorschriften professioneel opschrijft.',
    tips: [
        'Noem de soorten objecten waar je hebt gewerkt, zoals kantoren, scholen, zorginstellingen, hotels of productieomgevingen',
        'Maak je materiaalkennis concreet: microvezelmethode, kleurcodering, sanitairreiniging, vloeronderhoud of schrobzuigmachine',
        'Vermeld beschikbaarheid voor vroege ochtenden, avonden, weekenden of vaste objecten als dat relevant is',
        'Laat betrouwbaarheid zien met voorbeelden zoals sleutelbeheer, zelfstandig afsluiten, voorraadcontrole of vaste klantlocaties',
        'Gebruik vacaturewoorden zoals schoonmaker, schoonmaakmedewerker, housekeeping, facilitair medewerker, hygiëne en veilig werken',
    ],
    relatedSlugs: [
        'vakmanschap-en-logistiek/magazijnmedewerker',
        'horeca-en-detailhandel/hotel-receptionist',
        'horeca-en-detailhandel/cateringmedewerker',
    ],

    sampleCV: {
        personal: {
            name: 'Naima El Amrani',
            title: 'Schoonmaker / Schoonmaakmedewerker',
            email: 'naima.elamrani@email.nl',
            phone: '06-23456789',
            location: 'Rotterdam',
            address: 'Mathenesserdijk 84',
            postalCode: '3027 BM',
            summary: 'Betrouwbare schoonmaakmedewerker met 6 jaar ervaring in kantoren, scholen en zorglocaties. Bekend met microvezelmethode, kleurcodering, sanitairreiniging, voorraadcontrole en veilig gebruik van reinigingsmiddelen. Werkt zelfstandig, nauwkeurig en klantvriendelijk op vaste objecten. Beschikbaar voor vroege diensten, avonden en weekenddiensten.',
            birthDate: '11 januari 1988',
            birthPlace: 'Rotterdam',
            nationality: 'Nederlands',
            driversLicense: 'B',
            gender: '',
            maritalStatus: '',
            linkedIn: '',
            github: '',
            website: '',
            photo: '',
        },
        experience: [
            {
                role: 'Schoonmaakmedewerker',
                company: 'Asito',
                location: 'Rotterdam',
                start: 'april 2021',
                end: 'heden',
                description: 'Dagelijkse schoonmaak van kantoorverdiepingen, sanitaire ruimtes, pantry\'s en vergaderruimtes bij meerdere vaste klantlocaties.',
                highlights: [
                    'Zelfstandig 3 vaste objecten per week schoongemaakt volgens werkprogramma, inclusief sleutelbeheer en afsluitronde',
                    'Sanitair, bureaus, vloeren en algemene ruimtes gereinigd met microvezelmethode en kleurcodering',
                    'Voorraad van schoonmaakmiddelen bijgehouden en tekorten tijdig gemeld aan objectleiding',
                    'Nieuwe collega ingewerkt op looproutes, veiligheidsafspraken en klantgerichte communicatie',
                ],
            },
            {
                role: 'Schoonmaker Schoolgebouw',
                company: 'Schoonmaakbedrijf CSU',
                location: 'Schiedam',
                start: 'februari 2018',
                end: 'maart 2021',
                description: 'Schoonmaak van klaslokalen, gangen, trappenhuizen en sanitaire ruimtes buiten schooltijden.',
                highlights: [
                    'Dagelijks 12 klaslokalen en algemene ruimtes schoongemaakt volgens vaste planning',
                    'Signaleringen zoals defecte verlichting, lekkages en beschadigingen direct doorgegeven aan facilitair beheer',
                    'Extra desinfectierondes uitgevoerd tijdens griepperiodes en drukke ouderavonden',
                ],
            },
        ],
        education: [
            {
                degree: 'VMBO Kader',
                school: 'Zuiderpark College',
                location: 'Rotterdam',
                start: 'september 2001',
                end: 'juli 2005',
                description: 'Algemene vooropleiding met stages in dienstverlening en facilitair werk.',
            },
        ],
        skills: [
            { name: 'Sanitairreiniging', level: 5 },
            { name: 'Microvezelmethode', level: 5 },
            { name: 'Kleurcodering & hygiëne', level: 4 },
            { name: 'Vloeronderhoud', level: 4 },
            { name: 'Zelfstandig werken', level: 5 },
        ],
        languages: [
            { name: 'Nederlands', level: 'Goed' },
            { name: 'Engels', level: 'Basis' },
            { name: 'Arabisch', level: 'Goed' },
        ],
        interests: ['Wandelen', 'Koken', 'Familie'],
        courses: [
            { name: 'Basisopleiding Schoonmaken', institution: 'SVS', year: '2022' },
            { name: 'Veilig werken met schoonmaakmiddelen', institution: 'Asito Academy', year: '2021' },
        ],
        internships: [],
        awards: [
            'Compliment vaste klantlocatie bij Asito voor betrouwbare uitvoering en klantvriendelijke communicatie, 2023',
        ],
    },
};
