import { CVExample } from '../../types';

export const calculator: CVExample = {
    slug: 'calculator',
    categorySlug: 'bouw-en-techniek',
    name: 'Calculator Bouw / Infra',
    description: 'CV voorbeeld voor calculators in de bouw en infra. Presenteer je expertise in kostenramingen, bestekken en aanbestedingen.',
    templateId: 'professional',
    colorThemeId: 'classic-blue',

    metaTitle: 'CV Voorbeeld Calculator Bouw | WerkCV.nl',
    metaDesc: 'Professioneel CV voorbeeld voor calculators in de bouw en infra. Met voorbeeldteksten voor kostenramingen en aanbestedingen. Maak direct je CV.',
    keywords: ['cv voorbeeld calculator', 'cv calculator bouw', 'cv kostenraming', 'cv aanbesteding bouw'],
    heroTitle: 'CV Voorbeeld Calculator Bouw',
    heroText: 'Als calculator in de bouw bepaal je of een project rendabel is. Dit CV voorbeeld toont hoe je je analytische vaardigheden, kennis van bestekken en ervaring met aanbestedingen professioneel presenteert aan bouwbedrijven.',
    tips: [
        'Vermeld je ervaring met specifieke calculatiesoftware (IBISwin, Kraan, 4PS)',
        'Benoem de omvang van projecten die je hebt gecalculeerd (budget, m2)',
        'Geef aan welk percentage van je inschrijvingen is gegund',
        'Laat zien dat je bestekken grondig kunt analyseren',
        'Benadruk je kennis van RAW-systematiek en UAV-voorwaarden',
    ],
    relatedSlugs: ['bouw-en-techniek/werkvoorbereider', 'bouw-en-techniek/projectleider-bouw'],

    sampleCV: {
        personal: {
            name: 'Thomas van den Berg',
            title: 'Calculator Bouw / Infra',
            email: 'thomas.vandenberg@email.nl',
            phone: '06-45678123',
            location: 'Breda',
            address: 'Ginnekenweg 178',
            postalCode: '4835 NH',
            summary: 'Calculator met 5 jaar ervaring in de bouw en infra. Gespecialiseerd in het opstellen van kostenramingen, het analyseren van bestekken en het begeleiden van aanbestedingstrajecten. Nauwkeurig, analytisch en sterk in het vertalen van technische specificaties naar heldere prijsopbouwen. Ervaren met IBISwin en Excel.',
            birthDate: '17 september 1992',
            birthPlace: 'Tilburg',
            nationality: 'Nederlands',
            driversLicense: 'B',
            gender: '',
            maritalStatus: '',
            linkedIn: 'linkedin.com/in/thomasvdberg-calculator',
            github: '',
            website: '',
            photo: '',
        },
        experience: [
            {
                role: 'Calculator',
                company: 'Strukton Civiel',
                location: 'Utrecht',
                start: 'februari 2022',
                end: 'heden',
                description: 'Verantwoordelijk voor het calculeren van infraprojecten en civiele werken. Opstellen van begrotingen, prijsaanbiedingen en risicoanalyses voor aanbestedingen.',
                highlights: [
                    'Jaarlijks gemiddeld 25 aanbestedingen gecalculeerd met een gunningspercentage van 35%',
                    'Kostenramingen opgesteld voor infraprojecten tot EUR 15 miljoen',
                    'RAW-bestekken geanalyseerd en vertaald naar gedetailleerde prijsopbouwen in IBISwin',
                ],
            },
            {
                role: 'Junior Calculator',
                company: 'Dura Vermeer',
                location: 'Breda',
                start: 'september 2019',
                end: 'januari 2022',
                description: 'Ondersteuning bij calculatie van woningbouw- en utiliteitsprojecten. Opstellen van deelbegrotingen en nacalculaties.',
                highlights: [
                    'Deelbegrotingen opgesteld voor ruwbouw, installaties en afbouw bij woningbouwprojecten',
                    'Nacalculaties uitgevoerd en afwijkingen geanalyseerd ter verbetering van toekomstige inschrijvingen',
                ],
            },
        ],
        education: [
            {
                degree: 'HBO Bouwkunde',
                school: 'Avans Hogeschool',
                location: 'Tilburg',
                start: 'september 2013',
                end: 'juli 2018',
                description: 'Opleiding Bouwkunde met specialisatie bouwmanagement en calculatie.',
            },
            {
                degree: 'Post-HBO Calculatie in de Bouw',
                school: 'PAO Techniek en Management',
                location: 'Utrecht',
                start: 'januari 2020',
                end: 'juni 2020',
                description: 'Verdiepingscursus calculatie, aanbestedingsrecht en risicobeheersing.',
            },
        ],
        skills: [
            { name: 'Kostenraming & Begroting', level: 5 },
            { name: 'IBISwin', level: 4 },
            { name: 'Excel (geavanceerd)', level: 5 },
            { name: 'Bestekanalyse (RAW)', level: 4 },
            { name: 'Aanbestedingen', level: 4 },
            { name: 'Risicoanalyse', level: 3 },
        ],
        languages: [
            { name: 'Nederlands', level: 'Moedertaal' },
            { name: 'Engels', level: 'Goed' },
        ],
        interests: ['Schaken', 'Wielrennen', 'Economie'],
        courses: [
            { name: 'RAW-systematiek', institution: 'CROW', year: '2022' },
            { name: 'VCA Basis', institution: 'PBNA', year: '2021' },
            { name: 'Aanbestedingsrecht', institution: 'Berghauser Pont Academy', year: '2023' },
        ],
        internships: [],
        awards: [],
    },
};
