import { CVExample } from '../../types';

export const installatiemonteur: CVExample = {
    slug: 'installatiemonteur',
    categorySlug: 'bouw-en-techniek',
    name: 'Installatiemonteur Werktuigbouwkunde',
    description: 'CV voorbeeld voor installatiemonteurs werktuigbouwkunde. Laat zien hoe je je ervaring met CV-installaties, leidingwerk en storingsanalyse presenteert.',
    templateId: 'ats',
    colorThemeId: 'charcoal',

    metaTitle: 'CV Voorbeeld Installatiemonteur | WerkCV.nl',
    metaDesc: 'Professioneel CV voorbeeld voor installatiemonteurs werktuigbouwkunde. Met voorbeeldteksten voor CV-installaties, leidingwerk en NEN-normen. Maak direct je CV.',
    keywords: ['cv voorbeeld installatiemonteur', 'cv werktuigbouwkunde', 'cv cv-installaties', 'cv monteur installatie'],
    heroTitle: 'CV Voorbeeld Installatiemonteur',
    heroText: 'Als installatiemonteur werktuigbouwkunde ben je een specialist in klimaat- en verwarmingssystemen. Dit CV voorbeeld toont hoe je je technische kennis van CV-installaties, leidingwerk en NEN-normen overtuigend presenteert aan installatiebedrijven.',
    tips: [
        'Vermeld je certificeringen (F-gassen, NEN 1010, STEK)',
        'Benoem ervaring met specifieke systemen: warmtepompen, WKO, luchtbehandeling',
        'Geef aan of je ervaring hebt met storingsdiagnose en preventief onderhoud',
        'Vermeld je VCA-certificering en rijbewijs',
        'Laat zien dat je technische tekeningen kunt lezen en zelfstandig kunt werken',
    ],
    relatedSlugs: ['bouw-en-techniek/timmerman', 'bouw-en-techniek/werkvoorbereider'],

    sampleCV: {
        personal: {
            name: 'Kevin Smits',
            title: 'Installatiemonteur Werktuigbouwkunde',
            email: 'kevin.smits@email.nl',
            phone: '06-67890123',
            location: 'Groningen',
            address: 'Hereweg 88',
            postalCode: '9725 AK',
            summary: 'Installatiemonteur werktuigbouwkunde met 5 jaar ervaring in de installatietechniek. Gespecialiseerd in aanleg en onderhoud van verwarmings-, ventilatie- en koelinstallaties. Ervaren met leidingwerk, lassen en storingsanalyse. Bekend met NEN-normen en moderne duurzame systemen zoals warmtepompen.',
            birthDate: '12 juli 1995',
            birthPlace: 'Assen',
            nationality: 'Nederlands',
            driversLicense: 'B, C',
            gender: '',
            maritalStatus: '',
            linkedIn: 'linkedin.com/in/kevinsmits-installatie',
            github: '',
            website: '',
            photo: '',
        },
        experience: [
            {
                role: 'Installatiemonteur Werktuigbouwkunde',
                company: 'Hoppenbrouwers Techniek',
                location: 'Groningen',
                start: 'augustus 2021',
                end: 'heden',
                description: 'Aanleg, onderhoud en reparatie van verwarmings- en koelinstallaties bij zakelijke en particuliere klanten. Uitvoering van leidingwerk en aansluiting van installaties conform NEN-normen.',
                highlights: [
                    'Klimaatinstallaties aangelegd in nieuwbouw kantoorpand van 3.000 m2',
                    'Warmtepompsystemen geinstalleerd bij renovatieproject van 40 woningen',
                    'Storingen gediagnosticeerd en verholpen met een first-time-fix-rate van 85%',
                ],
            },
            {
                role: 'Monteur Verwarming',
                company: 'Feenstra',
                location: 'Assen',
                start: 'maart 2019',
                end: 'juli 2021',
                description: 'Installatie en onderhoud van cv-ketels, radiatoren en vloerverwarmingssystemen bij particuliere klanten.',
                highlights: [
                    'Gemiddeld 5 servicebezoeken per dag uitgevoerd met hoge klanttevredenheid',
                    'Cv-ketels en vloerverwarming geinstalleerd in nieuwbouwprojecten',
                ],
            },
        ],
        education: [
            {
                degree: 'MBO 3 Installatiemonteur',
                school: 'Noorderpoort',
                location: 'Groningen',
                start: 'september 2015',
                end: 'juli 2019',
                description: 'Opleiding tot installatiemonteur met specialisatie werktuigbouwkundige installaties en klimaattechniek.',
            },
        ],
        skills: [
            { name: 'CV-installaties & Verwarming', level: 5 },
            { name: 'Leidingwerk & Lassen', level: 4 },
            { name: 'NEN-normen', level: 4 },
            { name: 'Storingsanalyse', level: 4 },
            { name: 'Warmtepompen & Duurzaam', level: 3 },
            { name: 'Technische tekeningen', level: 4 },
        ],
        languages: [
            { name: 'Nederlands', level: 'Moedertaal' },
            { name: 'Engels', level: 'Basis' },
            { name: 'Duits', level: 'Basis' },
        ],
        interests: ['Motorcross', 'Techniek', 'Fitness'],
        courses: [
            { name: 'VCA Basis', institution: 'PBNA', year: '2021' },
            { name: 'F-gassen certificaat', institution: 'Refrigeration Academy', year: '2022' },
            { name: 'NEN 3140', institution: 'ESTO', year: '2023' },
        ],
        internships: [],
        awards: [],
    },
};
