import { CVExample } from '../../types';

export const projectleiderBouw: CVExample = {
    slug: 'projectleider-bouw',
    categorySlug: 'bouw-en-techniek',
    name: 'Projectleider Bouw',
    description: 'CV voorbeeld voor projectleiders in de bouw. Toon je leiderschapskwaliteiten, projectmanagementervaring en resultaten bij grote bouwprojecten.',
    templateId: 'dynamic',
    colorThemeId: 'modern-teal',

    metaTitle: 'CV Voorbeeld Projectleider Bouw | WerkCV.nl',
    metaDesc: 'Professioneel CV voorbeeld voor projectleiders in de bouw. Met voorbeeldteksten voor projectmanagement, planning en budgetbewaking. Maak direct je CV.',
    keywords: ['cv voorbeeld projectleider bouw', 'cv projectmanagement bouw', 'cv bouwprojectleider', 'cv bouw leidinggevend'],
    heroTitle: 'CV Voorbeeld Projectleider Bouw',
    heroText: 'Als projectleider bouw ben je verantwoordelijk voor het succes van grote bouwprojecten. Dit CV voorbeeld laat zien hoe je je ervaring met projectmanagement, budgetbewaking en teamleiderschap overtuigend presenteert aan opdrachtgevers en bouwbedrijven.',
    tips: [
        'Vermeld concrete projectresultaten: budget, opleverdatum, klanttevredenheid',
        'Benoem de omvang van je projecten (EUR-waarde, aantal woningen, m2)',
        'Geef aan welke projectmanagementmethoden je beheerst (PRINCE2, LEAN)',
        'Laat zien dat je ervaring hebt met het aansturen van onderaannemers en teams',
        'Vermeld je kennis van aanbestedingen en contractvormen (UAV, UAV-GC)',
    ],
    relatedSlugs: ['bouw-en-techniek/werkvoorbereider', 'bouw-en-techniek/calculator'],

    sampleCV: {
        personal: {
            name: 'Robert Hendriks',
            title: 'Projectleider Bouw',
            email: 'robert.hendriks@email.nl',
            phone: '06-56789012',
            location: 'Rotterdam',
            address: 'Nieuwe Binnenweg 215',
            postalCode: '3021 GK',
            summary: 'Resultaatgerichte projectleider met meer dan 7 jaar ervaring in de woningbouw en utiliteitsbouw. Verantwoordelijk geweest voor projecten tot EUR 25 miljoen. Sterk in budgetbewaking, planning en het aansturen van multidisciplinaire teams. PRINCE2 gecertificeerd en ervaren met LEAN-bouwen.',
            birthDate: '30 juni 1988',
            birthPlace: 'Dordrecht',
            nationality: 'Nederlands',
            driversLicense: 'B',
            gender: '',
            maritalStatus: '',
            linkedIn: 'linkedin.com/in/roberthendriks-bouw',
            github: '',
            website: '',
            photo: '',
        },
        experience: [
            {
                role: 'Projectleider Woningbouw',
                company: 'Heijmans',
                location: 'Rotterdam',
                start: 'januari 2021',
                end: 'heden',
                description: 'Eindverantwoordelijk voor de realisatie van nieuwbouw woningbouwprojecten. Aansturing van uitvoerders, werkvoorbereiders en onderaannemers. Budgetbewaking, planning en opdrachtgeverscontact.',
                highlights: [
                    'Nieuwbouwproject van 90 woningen opgeleverd binnen budget (EUR 22 mln) en 2 weken voor planning',
                    'LEAN-planningssessies geintroduceerd waardoor doorlooptijd met 10% is verkort',
                    'Team van 8 uitvoerders en 15 onderaannemers aangestuurd',
                ],
            },
            {
                role: 'Assistent Projectleider',
                company: 'BAM Wonen',
                location: 'Den Haag',
                start: 'maart 2017',
                end: 'december 2020',
                description: 'Ondersteuning van de projectleider bij woningbouw- en renovatieprojecten. Verantwoordelijk voor deelplanningen, meer- en minderwerk en kwaliteitscontroles.',
                highlights: [
                    'Renovatieproject van 120 woningen begeleid van voorbereiding tot oplevering',
                    'Meer- en minderwerkadministratie opgezet met besparingen van EUR 300.000',
                    'Kwaliteitsaudits uitgevoerd en opleverpunten met 25% verminderd',
                ],
            },
        ],
        education: [
            {
                degree: 'HBO Bouwkunde',
                school: 'Hogeschool Rotterdam',
                location: 'Rotterdam',
                start: 'september 2009',
                end: 'juli 2014',
                description: 'Opleiding Bouwkunde met specialisatie bouwprojectmanagement en constructief ontwerpen.',
            },
            {
                degree: 'PRINCE2 Foundation & Practitioner',
                school: 'Quint Wellington Redwood',
                location: 'Utrecht',
                start: 'maart 2018',
                end: 'mei 2018',
                description: 'Certificering in PRINCE2-projectmanagementmethode.',
            },
        ],
        skills: [
            { name: 'Projectmanagement', level: 5 },
            { name: 'Budgetbewaking', level: 5 },
            { name: 'Planning & LEAN', level: 4 },
            { name: 'Aanbestedingen (UAV/UAV-GC)', level: 4 },
            { name: 'Teamleiderschap', level: 5 },
            { name: 'MS Project / Asta Powerproject', level: 4 },
        ],
        languages: [
            { name: 'Nederlands', level: 'Moedertaal' },
            { name: 'Engels', level: 'Goed' },
            { name: 'Duits', level: 'Basis' },
        ],
        interests: ['Zeilen', 'Golf', 'Architectuur'],
        courses: [
            { name: 'LEAN Bouwen', institution: 'Ketenstandaard Bouw & Techniek', year: '2021' },
            { name: 'VCA VOL', institution: 'PBNA', year: '2020' },
            { name: 'Bouwbesluit Toetsing', institution: 'Berghauser Pont Academy', year: '2022' },
        ],
        internships: [],
        awards: [],
    },
};
