import { CVExample } from '../../types';

export const timmerman: CVExample = {
    slug: 'timmerman',
    categorySlug: 'bouw-en-techniek',
    name: 'Timmerman / Aannemer',
    description: 'CV voorbeeld voor timmermannen en aannemers. Laat zien hoe je je ervaring met nieuwbouw, verbouw en houtbewerking professioneel presenteert.',
    templateId: 'robust',
    colorThemeId: 'forest-green',

    metaTitle: 'CV Voorbeeld Timmerman | WerkCV.nl',
    metaDesc: 'Professioneel CV voorbeeld voor timmermannen en aannemers. Met voorbeeldteksten voor nieuwbouw, verbouw en afbouw. Maak direct je eigen timmerman CV.',
    keywords: ['cv voorbeeld timmerman', 'cv aannemer', 'cv houtbewerking', 'cv bouw timmerman'],
    heroTitle: 'CV Voorbeeld Timmerman',
    heroText: 'Als timmerman ben je onmisbaar op elke bouwplaats. Dit CV voorbeeld laat zien hoe je je vakmanschap in houtbewerking, afbouw en constructief timmerwerk overtuigend presenteert aan werkgevers in de bouw.',
    tips: [
        'Vermeld je VCA-certificering en andere veiligheidscertificaten',
        'Benoem specifieke projecten met omvang (bijv. nieuwbouw van 30 woningen)',
        'Geef aan welke houtbewerkingstechnieken je beheerst',
        'Vermeld ervaring met kozijnen, dakconstructies en trappen',
        'Laat zien dat je bouwkundig tekeningen kunt lezen en zelfstandig kunt werken',
    ],
    relatedSlugs: ['bouw-en-techniek/metselaar', 'bouw-en-techniek/werkvoorbereider'],

    sampleCV: {
        personal: {
            name: 'Jan de Vries',
            title: 'Timmerman / Aannemer',
            email: 'jan.devries@email.nl',
            phone: '06-23456789',
            location: 'Amersfoort',
            address: 'Liendertseweg 82',
            postalCode: '3814 PJ',
            summary: 'Ervaren timmerman met meer dan 8 jaar ervaring in de nieuwbouw en verbouw. Gespecialiseerd in ruwbouw, afbouwtimmerwerk en kozijnen. Bekend met moderne bouwtechnieken en HSB-constructies. Nauwkeurig, oplossingsgericht en gewend om zelfstandig en in teamverband te werken op grote bouwprojecten.',
            birthDate: '22 maart 1990',
            birthPlace: 'Amersfoort',
            nationality: 'Nederlands',
            driversLicense: 'B, BE',
            gender: '',
            maritalStatus: '',
            linkedIn: 'linkedin.com/in/jandevries-timmerman',
            github: '',
            website: '',
            photo: '',
        },
        experience: [
            {
                role: 'Eerste Timmerman',
                company: 'BAM Bouw en Techniek',
                location: 'Utrecht',
                start: 'maart 2020',
                end: 'heden',
                description: 'Verantwoordelijk voor het aansturen van een ploeg timmerlieden bij nieuwbouw- en renovatieprojecten van woningen en utiliteitsgebouwen.',
                highlights: [
                    'Leiding gegeven aan een team van 4 timmerlieden op nieuwbouwproject van 45 woningen',
                    'HSB-gevelelementen en dakconstructies geplaatst conform bestek en bouwtekeningen',
                    'Afbouwtimmerwerk uitgevoerd waaronder kozijnen, binnenwanden en plafonds',
                ],
            },
            {
                role: 'Timmerman',
                company: 'Van Wijnen',
                location: 'Amersfoort',
                start: 'augustus 2016',
                end: 'februari 2020',
                description: 'Uitvoering van ruwbouw- en afbouwtimmerwerk bij diverse woningbouw- en verbouwprojecten in de regio Amersfoort.',
                highlights: [
                    'Kapconstructies en dakbeschot aangebracht op nieuwbouwproject van 25 eengezinswoningen',
                    'Kozijnen, trappen en binnenwanden geplaatst bij renovatie van monumentaal pand',
                    'Bekistingswerkzaamheden uitgevoerd voor betonconstructies',
                ],
            },
        ],
        education: [
            {
                degree: 'MBO 3 Timmerkracht',
                school: 'ROC Midden Nederland',
                location: 'Amersfoort',
                start: 'september 2012',
                end: 'juli 2016',
                description: 'Opleiding tot allround timmerman met aandacht voor houtbewerking, bouwkunde en constructief timmerwerk.',
            },
        ],
        skills: [
            { name: 'Houtbewerking & Constructie', level: 5 },
            { name: 'Bouwkundig tekenen lezen', level: 4 },
            { name: 'Afbouwtimmerwerk', level: 5 },
            { name: 'Kozijnen & Ramen', level: 5 },
            { name: 'Dakconstructies & HSB', level: 4 },
            { name: 'Bekistingswerk', level: 3 },
        ],
        languages: [
            { name: 'Nederlands', level: 'Moedertaal' },
            { name: 'Engels', level: 'Goed' },
            { name: 'Duits', level: 'Basis' },
        ],
        interests: ['Houtbewerking', 'Mountainbiken', 'Vissen'],
        courses: [
            { name: 'VCA Basis', institution: 'PBNA', year: '2020' },
            { name: 'BHV', institution: 'Falck', year: '2022' },
            { name: 'Hijsbewijs (HCM)', institution: 'KVGM Opleidingen', year: '2021' },
        ],
        internships: [],
        awards: [],
    },
};
