import { CVExample } from '../../types';

export const accountant: CVExample = {
    slug: 'accountant',
    categorySlug: 'zakelijk-en-financieel',
    name: 'Accountant',
    description: 'CV voorbeeld voor registeraccountants. Laat zien hoe je je audit-ervaring, IFRS-kennis en analytische vaardigheden overtuigend presenteert.',
    templateId: 'professional',
    colorThemeId: 'classic-blue',

    metaTitle: 'CV Voorbeeld Accountant | WerkCV.nl',
    metaDesc: 'Professioneel CV voorbeeld voor accountants. Met voorbeeldteksten voor audit, jaarrekeningen en fiscaliteit. Download gratis en maak direct je eigen CV.',
    keywords: ['cv voorbeeld accountant', 'cv registeraccountant', 'accountant cv maken', 'cv audit', 'ra cv voorbeeld'],
    heroTitle: 'CV Voorbeeld Accountant',
    heroText: 'Als accountant toon je nauwkeurigheid, integriteit en diepgaande financiele kennis. Dit CV voorbeeld laat zien hoe je je audit-ervaring, certificeringen en sectorkennis effectief presenteert. Benadruk je resultaten bij controles en advisering om je te onderscheiden.',
    tips: [
        'Vermeld je RA-titel en eventuele andere certificeringen prominent',
        'Kwantificeer je ervaring: omvang van controles, omzet van klantportfolio',
        'Benoem specifieke sectoren waarin je ervaring hebt opgedaan',
        'Toon je kennis van IFRS, Dutch GAAP en relevante wet- en regelgeving',
        'Benadruk je adviesvaardigheden naast je technische auditkennis',
    ],
    relatedSlugs: ['zakelijk-en-financieel/financieel-analist', 'zakelijk-en-financieel/controller'],

    sampleCV: {
        personal: {
            name: 'Mark de Vries',
            title: 'Registeraccountant (RA)',
            email: 'mark.devries@email.nl',
            phone: '06-23456789',
            location: 'Amsterdam',
            address: 'Herengracht 142',
            postalCode: '1015 BW',
            summary: 'Registeraccountant met ruim 9 jaar ervaring in de controle van jaarrekeningen en financiele advisering. Werkzaam geweest bij Big 4-kantoor en middelgroot accountantskantoor met focus op de MKB- en zorgsector. Sterk in het opbouwen van klantrelaties en het vertalen van complexe financiele vraagstukken naar heldere adviezen. Zoekt een uitdagende rol als senior accountant of audit manager.',
            birthDate: '12 maart 1990',
            birthPlace: 'Haarlem',
            nationality: 'Nederlands',
            driversLicense: 'B',
            gender: '',
            maritalStatus: '',
            linkedIn: 'linkedin.com/in/markdevries-ra',
            github: '',
            website: '',
            photo: '',
        },
        experience: [
            {
                role: 'Senior Accountant',
                company: 'BDO Nederland',
                location: 'Amsterdam',
                start: 'maart 2020',
                end: 'heden',
                description: 'Verantwoordelijk voor de controle van jaarrekeningen en advisering van MKB-klanten in diverse sectoren.',
                highlights: [
                    'Klantportfolio van 25+ MKB-ondernemingen beheerd met een gezamenlijke omzet van \u20AC500 miljoen',
                    'Leidinggevend aan auditteams van 3-5 personen en verantwoordelijk voor de kwaliteitsreview',
                    'Adviestrajecten uitgevoerd op het gebied van interne beheersing en financiele processen',
                ],
            },
            {
                role: 'Accountant / Auditor',
                company: 'KPMG',
                location: 'Amstelveen',
                start: 'september 2015',
                end: 'februari 2020',
                description: 'Wettelijke controles uitgevoerd bij grote ondernemingen in de zorg- en financiele sector.',
                highlights: [
                    'Jaarrekeningen gecontroleerd van zorginstellingen met een omzet tot \u20AC200 miljoen',
                    'IFRS-conversieproject begeleid voor een beursgenoteerde klant',
                    'Interne trainingen verzorgd op het gebied van frauderisico-analyse',
                ],
            },
        ],
        education: [
            {
                degree: 'Postdoctorale opleiding Registeraccountant (RA)',
                school: 'Universiteit van Amsterdam',
                location: 'Amsterdam',
                start: 'september 2016',
                end: 'juni 2020',
                description: 'Postdoctorale opleiding tot Registeraccountant. Afgerond naast voltijdbaan bij KPMG.',
            },
            {
                degree: 'HBO Accountancy',
                school: 'Hogeschool van Amsterdam',
                location: 'Amsterdam',
                start: 'september 2011',
                end: 'juli 2015',
                description: 'Afgestudeerd met specialisatie in externe verslaggeving en controleleer. Afstudeerscriptie over de impact van IFRS 15 op de bouwsector.',
            },
        ],
        skills: [
            { name: 'Jaarrekening & controleleer', level: 5 },
            { name: 'IFRS / Dutch GAAP', level: 5 },
            { name: 'Fiscaliteit (Vpb / IB)', level: 4 },
            { name: 'SAP / Exact', level: 4 },
            { name: 'Excel (geavanceerd)', level: 5 },
            { name: 'Caseware / Auditing software', level: 4 },
        ],
        languages: [
            { name: 'Nederlands', level: 'Moedertaal' },
            { name: 'Engels', level: 'Vloeiend' },
            { name: 'Duits', level: 'Basis' },
        ],
        interests: ['Financiele markten', 'Golf', 'Schaken', 'Hardlopen'],
        courses: [
            { name: 'IFRS Update 2024', institution: 'NBA', year: '2024' },
            { name: 'Data-analyse in de accountantscontrole', institution: 'SRA', year: '2023' },
        ],
        internships: [],
        awards: [],
    },
};
