import { CVExample } from '../../types';

export const administratiefMedewerker: CVExample = {
    slug: 'administratief-medewerker',
    categorySlug: 'zakelijk-en-financieel',
    name: 'Administratief Medewerker',
    description: 'CV voorbeeld voor administratief medewerkers. Laat zien hoe je nauwkeurigheid, systemenkennis, klantcontact en procesondersteuning concreet presenteert.',
    templateId: 'professional',
    colorThemeId: 'classic-blue',

    metaTitle: 'CV Voorbeeld Administratief Medewerker | WerkCV.nl',
    metaDesc: 'Sterk cv voorbeeld voor administratief medewerkers. Met profieltekst, werkervaring, vaardigheden, softwarekennis en concrete administratieve bullets.',
    keywords: [
        'cv voorbeeld administratief medewerker',
        'administratief medewerker cv',
        'cv administratie',
        'cv financieel administratief medewerker',
        'cv office medewerker',
        'cv administratieve vaardigheden',
        'cv voorbeeld administratie',
    ],
    heroTitle: 'CV Voorbeeld Administratief Medewerker',
    heroText: 'Als administratief medewerker moet je CV meteen laten zien dat je nauwkeurig werkt, overzicht houdt en systemen snel begrijpt. Dit voorbeeld toont hoe je taken als dossierbeheer, factuurcontrole, klantcontact, agendabeheer en rapportage omzet naar concrete, recruiterproof bullets.',
    tips: [
        'Benoem de systemen waarmee je werkt, zoals Excel, AFAS, Exact, SAP, Teams of een CRM-systeem',
        'Maak administratieve impact concreet: minder fouten, snellere verwerking, betere dossiervorming of kortere doorlooptijd',
        'Laat zien welk soort administratie je deed: financieel, HR, planning, klantenservice, projectadministratie of secretarieel',
        'Gebruik rustige, zakelijke opmaak met veel witruimte; dit past bij een functie waarin overzicht telt',
        'Benadruk nauwkeurigheid, prioriteiten stellen en vertrouwelijke informatie verwerken met voorbeelden uit je werk',
    ],
    relatedSlugs: [
        'zakelijk-en-financieel/hr-medewerker',
        'zakelijk-en-financieel/controller',
        'horeca-en-detailhandel/hotel-receptionist',
    ],

    sampleCV: {
        personal: {
            name: 'Sanne de Boer',
            title: 'Administratief Medewerker',
            email: 'sanne.deboer@email.nl',
            phone: '06-34567890',
            location: 'Utrecht',
            address: 'Biltstraat 84',
            postalCode: '3572 BH',
            summary: 'Nauwkeurige administratief medewerker met 5 jaar ervaring in kantooradministratie, factuurcontrole en klantcontact. Sterk in het verwerken van dossiers, controleren van gegevens en verbeteren van administratieve processen. Ervaren met Excel, AFAS, Exact Online en CRM-systemen. Werkt gestructureerd, communiceert helder en houdt overzicht bij meerdere deadlines tegelijk.',
            birthDate: '18 juni 1994',
            birthPlace: 'Amersfoort',
            nationality: 'Nederlands',
            driversLicense: 'B',
            gender: '',
            maritalStatus: '',
            linkedIn: 'linkedin.com/in/sannedeboer',
            github: '',
            website: '',
            photo: '',
        },
        experience: [
            {
                role: 'Administratief Medewerker',
                company: 'Bouwgroep Midden Nederland',
                location: 'Utrecht',
                start: 'februari 2021',
                end: 'heden',
                description: 'Verantwoordelijk voor projectadministratie, factuurcontrole en ondersteuning van planning en finance.',
                highlights: [
                    'Wekelijks 120+ inkoopfacturen gecontroleerd en verwerkt in Exact Online met minder dan 1% correcties achteraf',
                    'Projectdossiers opgeschoond en gestandaardiseerd, waardoor collega’s documenten gemiddeld 30% sneller terugvonden',
                    'Maandelijkse uren- en kostenrapportages voorbereid voor 8 projectleiders in Excel en Power BI',
                    'Vragen van leveranciers en klanten afgehandeld via telefoon en e-mail met duidelijke terugkoppeling binnen 24 uur',
                ],
            },
            {
                role: 'Junior Administratief Medewerker',
                company: 'Zorgservice Amersfoort',
                location: 'Amersfoort',
                start: 'september 2018',
                end: 'januari 2021',
                description: 'Ondersteuning van de backoffice bij personeelsadministratie, afsprakenplanning en gegevenscontrole.',
                highlights: [
                    'Personeelsmutaties verwerkt in AFAS voor 180 medewerkers en ontbrekende gegevens actief opgevolgd',
                    'Digitale archiefstructuur ingericht voor contracten, certificaten en verzuimdossiers',
                    'Planningsteam ondersteund bij roosterwijzigingen, afspraakbevestigingen en interne communicatie',
                ],
            },
        ],
        education: [
            {
                degree: 'MBO 4 Bedrijfsadministratie',
                school: 'ROC Midden Nederland',
                location: 'Utrecht',
                start: 'september 2014',
                end: 'juli 2018',
                description: 'Opleiding gericht op bedrijfsadministratie, boekhoudkundige basiskennis, zakelijke communicatie en digitale kantoorprocessen.',
            },
        ],
        skills: [
            { name: 'Excel (draaitabellen en formules)', level: 5 },
            { name: 'Exact Online', level: 4 },
            { name: 'AFAS', level: 4 },
            { name: 'Factuurcontrole', level: 5 },
            { name: 'Dossierbeheer', level: 5 },
            { name: 'CRM en klantcontact', level: 4 },
            { name: 'Agenda- en planningsondersteuning', level: 4 },
            { name: 'Nauwkeurig gegevens verwerken', level: 5 },
        ],
        languages: [
            { name: 'Nederlands', level: 'Moedertaal' },
            { name: 'Engels', level: 'Goed' },
            { name: 'Duits', level: 'Basis' },
        ],
        interests: ['Organiseren', 'Lezen', 'Wandelen', 'Vrijwilligersadministratie'],
        courses: [
            { name: 'Excel Gevorderd', institution: 'Computrain', year: '2023' },
            { name: 'Basiskennis Boekhouden (BKB)', institution: 'Associatie voor Examinering', year: '2021' },
            { name: 'Klantgericht communiceren per e-mail', institution: 'NCOI', year: '2020' },
        ],
        internships: [
            {
                role: 'Stagiair Administratie',
                company: 'Gemeente Amersfoort',
                location: 'Amersfoort',
                start: 'februari 2018',
                end: 'juni 2018',
                description: 'Stage op de afdeling publiekszaken met ondersteuning bij datacontrole en documentverwerking.',
                highlights: [
                    'Aanvragen gecontroleerd op volledigheid en ontbrekende informatie opgevolgd bij inwoners',
                    'Standaardbrieven bijgewerkt en administratieve instructies gedocumenteerd voor nieuwe stagiairs',
                ],
            },
        ],
        awards: [
            'Interne complimentenkaart voor foutloze maandafsluiting, 2023',
        ],
    },
};
