import { CVExample } from '../../types';

export const bedrijfsadviseur: CVExample = {
    slug: 'bedrijfsadviseur',
    categorySlug: 'zakelijk-en-financieel',
    name: 'Bedrijfsadviseur / Consultant',
    description: 'CV voorbeeld voor management consultants en bedrijfsadviseurs. Laat zien hoe je strategische projecten en klantresultaten overtuigend presenteert.',
    templateId: 'elegant',
    colorThemeId: 'elegant-navy',

    metaTitle: 'CV Voorbeeld Bedrijfsadviseur & Consultant | WerkCV.nl',
    metaDesc: 'Professioneel CV voorbeeld voor bedrijfsadviseurs en consultants. Met voorbeeldteksten voor strategie, procesoptimalisatie en adviesprojecten.',
    keywords: ['cv voorbeeld bedrijfsadviseur', 'cv consultant', 'cv management consultant', 'cv adviseur'],
    heroTitle: 'CV Voorbeeld Bedrijfsadviseur',
    heroText: 'Als bedrijfsadviseur of consultant draait alles om resultaat en impact. Dit CV voorbeeld laat zien hoe je adviestrajecten, strategische projecten en meetbare verbeteringen overtuigend presenteert aan potentiele opdrachtgevers.',
    tips: [
        'Kwantificeer de impact van je adviesprojecten (kostenbesparingen, omzetgroei)',
        'Benoem de sectoren en organisatietypes waarvoor je hebt gewerkt',
        'Vermeld je adviesspecialisaties: strategie, operations, change, digitalisering',
        'Benadruk stakeholder management en presentatievaardigheden',
        'Laat zien dat je zowel analytisch als communicatief sterk bent',
    ],
    relatedSlugs: ['zakelijk-en-financieel/controller', 'zakelijk-en-financieel/hr-medewerker'],

    sampleCV: {
        personal: {
            name: 'Laurens de Vries',
            title: 'Senior Bedrijfsadviseur',
            email: 'l.devries@email.nl',
            phone: '06-34567890',
            location: 'Amsterdam',
            address: 'Keizersgracht 312',
            postalCode: '1016 EZ',
            summary: 'Resultaatgerichte senior bedrijfsadviseur met 7 jaar ervaring in strategie en operationele verbetertrajecten. Gespecialiseerd in digitale transformatie en procesoptimalisatie voor middelgrote en grote organisaties. Bewezen track record in het realiseren van meetbare besparingen en groei voor klanten in diverse sectoren.',
            birthDate: '3 september 1990',
            birthPlace: 'Haarlem',
            nationality: 'Nederlands',
            driversLicense: 'B',
            gender: '',
            maritalStatus: '',
            linkedIn: 'linkedin.com/in/laurensdevries',
            github: '',
            website: '',
            photo: '',
        },
        experience: [
            {
                role: 'Senior Consultant',
                company: 'Berenschot',
                location: 'Utrecht',
                start: 'maart 2021',
                end: 'heden',
                description: 'Advisering van publieke en private organisaties op het gebied van strategie en organisatieontwikkeling.',
                highlights: [
                    'Geleid reorganisatietraject voor gemeente met 2.000+ medewerkers',
                    'Digitaliseringsstrategie ontwikkeld die leidde tot 30% efficiencywinst',
                    'Klantportfolio uitgebreid met 4 nieuwe langetermijnklanten',
                ],
            },
            {
                role: 'Management Consultant',
                company: 'Accenture',
                location: 'Amsterdam',
                start: 'september 2017',
                end: 'februari 2021',
                description: 'Strategie- en technologieadvies voor klanten in de financiele sector.',
                highlights: [
                    'Procesoptimalisatie doorgevoerd bij 3 grote banken (totale besparing \u20ac2,5M)',
                    'Projectteam van 8 consultants aangestuurd bij een agile transformatie',
                    'Winnaar interne innovatieprijs voor klantanalyse-tool',
                ],
            },
        ],
        education: [
            {
                degree: 'MSc Strategy & Organization',
                school: 'Universiteit van Amsterdam',
                location: 'Amsterdam',
                start: 'september 2015',
                end: 'juli 2017',
                description: 'Scriptie over digitale transformatie in de publieke sector (beoordeling: 8.5)',
            },
            {
                degree: 'BSc Bedrijfskunde',
                school: 'Rijksuniversiteit Groningen',
                location: 'Groningen',
                start: 'september 2011',
                end: 'juli 2015',
                description: '',
            },
        ],
        skills: [
            { name: 'Strategisch advies', level: 5 },
            { name: 'Procesoptimalisatie', level: 5 },
            { name: 'Stakeholder management', level: 4 },
            { name: 'Change management', level: 4 },
            { name: 'Data-analyse', level: 4 },
            { name: 'Projectmanagement', level: 4 },
        ],
        languages: [
            { name: 'Nederlands', level: 'Moedertaal' },
            { name: 'Engels', level: 'Vloeiend' },
            { name: 'Duits', level: 'Goed' },
        ],
        interests: ['Mountainbiken', 'Podcasts over strategie', 'Reizen'],
        courses: [
            { name: 'PRINCE2 Practitioner', institution: 'AXELOS', year: '2019' },
            { name: 'Lean Six Sigma Green Belt', institution: 'LSS Academy', year: '2018' },
        ],
        internships: [],
        awards: [],
    },
};
