import { CVExample } from '../../types';

export const controller: CVExample = {
    slug: 'controller',
    categorySlug: 'zakelijk-en-financieel',
    name: 'Controller',
    description: 'CV voorbeeld voor business controllers. Laat zien hoe je je ervaring met budgettering, rapportage en financiele sturing overtuigend presenteert.',
    templateId: 'classical',
    colorThemeId: 'charcoal',

    metaTitle: 'CV Voorbeeld Controller | WerkCV.nl',
    metaDesc: 'Professioneel CV voorbeeld voor controllers. Met voorbeeldteksten voor budgettering, management reporting en financiele analyse. Maak direct je eigen CV.',
    keywords: ['cv voorbeeld controller', 'cv business controller', 'controller cv maken', 'cv financieel controller', 'cv management reporting'],
    heroTitle: 'CV Voorbeeld Controller',
    heroText: 'Als controller ben je de financiele sparringpartner van het management. Dit CV voorbeeld laat zien hoe je je ervaring met budgettering, forecasting en management reporting effectief presenteert. Benadruk je vermogen om financiele data te vertalen naar strategische inzichten.',
    tips: [
        'Vermeld je RC-titel of vergelijkbare certificering prominent',
        'Kwantificeer je resultaten: omvang van budgetten, gerealiseerde besparingen',
        'Toon ervaring met ERP-systemen zoals SAP, Oracle of Exact',
        'Benadruk je rol als sparringpartner van het management',
        'Beschrijf verbeterprojecten die je hebt geinitieerd en de behaalde resultaten',
    ],
    relatedSlugs: ['zakelijk-en-financieel/accountant', 'zakelijk-en-financieel/financieel-analist'],

    sampleCV: {
        personal: {
            name: 'Robert van Dijk',
            title: 'Business Controller',
            email: 'robert.vandijk@email.nl',
            phone: '06-45678901',
            location: 'Eindhoven',
            address: 'Vestdijk 88',
            postalCode: '5611 CZ',
            summary: 'Ervaren business controller met 7 jaar ervaring in financiele sturing en rapportage binnen de maakindustrie. Sterk in het opzetten van management reportingstructuren, het begeleiden van budgetcycli en het adviseren van directie over financiele prestaties. Afgeronde RC-opleiding en ruime ervaring met SAP en Power BI. Zoekt een uitdagende controllerfunctie bij een groeiende organisatie.',
            birthDate: '4 november 1991',
            birthPlace: 'Tilburg',
            nationality: 'Nederlands',
            driversLicense: 'B',
            gender: '',
            maritalStatus: '',
            linkedIn: 'linkedin.com/in/robertvandijk-rc',
            github: '',
            website: '',
            photo: '',
        },
        experience: [
            {
                role: 'Business Controller',
                company: 'Philips',
                location: 'Eindhoven',
                start: 'april 2021',
                end: 'heden',
                description: 'Financieel verantwoordelijk voor de business unit Connected Care met een jaaromzet van \u20AC350 miljoen.',
                highlights: [
                    'Maandelijkse managementrapportage opgezet en geoptimaliseerd, waardoor rapportagetijd met 40% verkort werd',
                    'Jaarlijkse budgetcyclus begeleid voor 4 afdelingen met een totaalbudget van \u20AC85 miljoen',
                    'Kostenbesparingsprogramma geinitieerd dat leidde tot \u20AC2,3 miljoen structurele besparing per jaar',
                ],
            },
            {
                role: 'Financial Controller',
                company: 'VDL Groep',
                location: 'Eindhoven',
                start: 'september 2017',
                end: 'maart 2021',
                description: 'Verantwoordelijk voor de financiele administratie en controlling van twee productielocaties.',
                highlights: [
                    'Rolling forecast-proces geimplementeerd waardoor de voorspelnauwkeurigheid verbeterde van 82% naar 94%',
                    'SAP-implementatieproject mede aangestuurd als key user vanuit finance',
                    'Maandelijkse variance-analyses opgesteld en gepresenteerd aan de directie',
                ],
            },
        ],
        education: [
            {
                degree: 'Registercontroller (RC) opleiding',
                school: 'Tilburg University / TIAS',
                location: 'Tilburg',
                start: 'september 2019',
                end: 'juni 2022',
                description: 'Postdoctorale opleiding tot Registercontroller. Afstudeeronderzoek over de rol van de controller bij digitale transformatie.',
            },
            {
                degree: 'HBO Bedrijfseconomie',
                school: 'Fontys Hogescholen',
                location: 'Eindhoven',
                start: 'september 2010',
                end: 'juli 2014',
                description: 'Specialisatie Financial Management. Minor International Business.',
            },
        ],
        skills: [
            { name: 'Budgettering & forecasting', level: 5 },
            { name: 'Management reporting', level: 5 },
            { name: 'SAP FI/CO', level: 4 },
            { name: 'Power BI', level: 4 },
            { name: 'Excel (geavanceerd)', level: 5 },
            { name: 'Kostprijscalculatie', level: 4 },
        ],
        languages: [
            { name: 'Nederlands', level: 'Moedertaal' },
            { name: 'Engels', level: 'Vloeiend' },
            { name: 'Duits', level: 'Goed' },
        ],
        interests: ['Bedrijfsstrategie', 'Wielrennen', 'Lezen', 'Fotografie'],
        courses: [
            { name: 'SAP S/4HANA Finance', institution: 'SAP Nederland', year: '2023' },
            { name: 'Power BI Advanced Analytics', institution: 'Microsoft', year: '2022' },
        ],
        internships: [],
        awards: [],
    },
};
