import { CVExample } from '../../types';

export const controller: CVExample = {
    slug: 'controller',
    categorySlug: 'zakelijk-en-financieel',
    name: 'Controller',
    description: 'CV voorbeeld voor business controllers en financial controllers. Laat budgettering, forecasting, SAP, Power BI, variance-analyse en business partnering concreet zien.',
    templateId: 'classical',
    colorThemeId: 'charcoal',

    metaTitle: 'CV Voorbeeld Controller | SAP, Power BI & Forecasting | WerkCV.nl',
    metaDesc: 'Professioneel cv voorbeeld voor business controller en financial controller. Met SAP, Power BI, budgettering, forecasting, variance-analyse en rapportage.',
    keywords: ['cv voorbeeld controller', 'controller cv', 'cv business controller', 'controller cv maken', 'cv financieel controller', 'cv management reporting', 'cv SAP FI CO', 'cv Power BI'],
    heroTitle: 'CV Voorbeeld Controller',
    heroText: 'Als controller ben je de financiële sparringpartner van management en directie. Dit CV voorbeeld laat zien hoe je budgettering, forecasting, SAP FI/CO, Power BI, variance-analyse, kostenbesparing en business partnering effectief presenteert.',
    tips: [
        'Vermeld je scope: omzet, budget, afdelingen, entiteiten, FTE of landen waarvoor je verantwoordelijk bent',
        'Kwantificeer resultaten met besparingen, forecast accuracy, kortere closing, margeverbetering of rapportagetijd',
        'Toon ervaring met ERP, BI en finance tools zoals SAP FI/CO, Oracle, Exact, Power BI, SQL of Excel Power Query',
        'Benadruk je rol als business partner voor directie, operations, sales, supply chain of projectteams',
        'Beschrijf verbeterprojecten zoals rolling forecast, dashboarding, kostprijsmodel, month-end close of internal controls',
    ],
    relatedSlugs: ['zakelijk-en-financieel/financieel-analist', 'zakelijk-en-financieel/accountant', 'zakelijk-en-financieel/projectmanager'],

    sampleCV: {
        personal: {
            name: 'Robert van Dijk',
            title: 'Business Controller',
            email: 'robert.vandijk@email.nl',
            phone: '06-45678901',
            location: 'Eindhoven',
            address: 'Vestdijk 88',
            postalCode: '5611 CZ',
            summary: 'Business controller met 7 jaar ervaring in financiële sturing, budgettering, rolling forecast en managementrapportage binnen de maakindustrie. Sterk in SAP FI/CO, Power BI, Excel Power Query, variance-analyse en business partnering met directie en operations. Afgeronde RC-opleiding en bewezen impact op kostenbeheersing, forecast accuracy en rapportagekwaliteit.',
            birthDate: '4 november 1991',
            birthPlace: 'Tilburg',
            nationality: 'Nederlands',
            driversLicense: 'B',
            gender: '',
            maritalStatus: '',
            linkedIn: 'linkedin.com/in/robertvandijk-rc',
            github: '',
            website: '',
            photo: '',
        },
        experience: [
            {
                role: 'Business Controller',
                company: 'Philips',
                location: 'Eindhoven',
                start: 'april 2021',
                end: 'heden',
                description: 'Financieel verantwoordelijk voor de business unit Connected Care met een jaaromzet van \u20AC350 miljoen.',
                highlights: [
                    'Maandelijkse managementrapportage opgezet en geoptimaliseerd, waardoor rapportagetijd met 40% verkort werd',
                    'Jaarlijkse budgetcyclus begeleid voor 4 afdelingen met een totaalbudget van \u20AC85 miljoen',
                    'Kostenbesparingsprogramma geinitieerd dat leidde tot \u20AC2,3 miljoen structurele besparing per jaar',
                    'Power BI-dashboard gebouwd voor omzet, marge, OPEX en forecastafwijkingen per business unit',
                ],
            },
            {
                role: 'Financial Controller',
                company: 'VDL Groep',
                location: 'Eindhoven',
                start: 'september 2017',
                end: 'maart 2021',
                description: 'Verantwoordelijk voor de financiele administratie en controlling van twee productielocaties.',
                highlights: [
                    'Rolling forecast-proces geimplementeerd waardoor de voorspelnauwkeurigheid verbeterde van 82% naar 94%',
                    'SAP-implementatieproject mede aangestuurd als key user vanuit finance',
                    'Maandelijkse variance-analyses opgesteld en gepresenteerd aan de directie',
                    'Kostprijsmodel voor twee productielocaties aangescherpt met input van operations en supply chain',
                ],
            },
        ],
        education: [
            {
                degree: 'Registercontroller (RC) opleiding',
                school: 'Tilburg University / TIAS',
                location: 'Tilburg',
                start: 'september 2019',
                end: 'juni 2022',
                description: 'Postdoctorale opleiding tot Registercontroller. Afstudeeronderzoek over de rol van de controller bij digitale transformatie.',
            },
            {
                degree: 'HBO Bedrijfseconomie',
                school: 'Fontys Hogescholen',
                location: 'Eindhoven',
                start: 'september 2010',
                end: 'juli 2014',
                description: 'Specialisatie Financial Management. Minor International Business.',
            },
        ],
        skills: [
            { name: 'Budgettering & forecasting', level: 5 },
            { name: 'Management reporting', level: 5 },
            { name: 'SAP FI/CO', level: 4 },
            { name: 'Power BI', level: 4 },
            { name: 'Forecasting & variance analyse', level: 5 },
            { name: 'Kostprijs & margeanalyse', level: 4 },
        ],
        languages: [
            { name: 'Nederlands', level: 'Moedertaal' },
            { name: 'Engels', level: 'Vloeiend' },
            { name: 'Duits', level: 'Goed' },
        ],
        interests: ['Bedrijfsstrategie', 'Wielrennen', 'Lezen', 'Fotografie'],
        courses: [
            { name: 'SAP S/4HANA Finance', institution: 'SAP Nederland', year: '2023' },
            { name: 'Power BI Advanced Analytics', institution: 'Microsoft', year: '2022' },
            { name: 'Excel Power Query & Power Pivot', institution: 'Excel Academy', year: '2021' },
        ],
        internships: [],
        awards: [],
    },
};
