import { CVExample } from '../../types';

export const financieelAnalist: CVExample = {
    slug: 'financieel-analist',
    categorySlug: 'zakelijk-en-financieel',
    name: 'Financieel Analist',
    description: 'CV voorbeeld voor financieel analisten. Laat zien hoe je je analytische vaardigheden, modellerervaring en financiele inzichten overtuigend presenteert.',
    templateId: 'formal',
    colorThemeId: 'elegant-navy',

    metaTitle: 'CV Voorbeeld Financieel Analist | WerkCV.nl',
    metaDesc: 'Professioneel CV voorbeeld voor financieel analisten. Met voorbeeldteksten voor financiele modellen, rapportages en data-analyse. Maak direct je eigen CV.',
    keywords: ['cv voorbeeld financieel analist', 'cv financial analyst', 'financieel analist cv maken', 'cv finance', 'cv bedrijfseconomie'],
    heroTitle: 'CV Voorbeeld Financieel Analist',
    heroText: 'Als financieel analist combineer je scherp analytisch denkvermogen met zakelijk inzicht. Dit CV voorbeeld laat zien hoe je je ervaring met financiele modellen, rapportages en strategische analyses effectief presenteert. Toon je impact met concrete cijfers en resultaten.',
    tips: [
        'Kwantificeer je impact: besparingen, rendement, nauwkeurigheid van forecasts',
        'Vermeld ervaring met specifieke tools: Bloomberg, Power BI, Python, Excel',
        'Benadruk je vermogen om data te vertalen naar strategische aanbevelingen',
        'Toon je kennis van waarderingsmethoden en financiele modellering',
        'Voeg relevante certificeringen toe zoals CFA of VBA',
    ],
    relatedSlugs: ['zakelijk-en-financieel/controller', 'zakelijk-en-financieel/accountant'],

    sampleCV: {
        personal: {
            name: 'Eva Janssen',
            title: 'Financieel Analist',
            email: 'eva.janssen@email.nl',
            phone: '06-34567890',
            location: 'Rotterdam',
            address: 'Westersingel 58',
            postalCode: '3014 GS',
            summary: 'Resultaatgerichte financieel analist met 6 jaar ervaring in financiele modellering, rapportage en strategische analyse binnen de bancaire sector. Sterk in het vertalen van complexe datasets naar actionable business insights. Ervaren met Power BI, Python en Bloomberg Terminal. Op zoek naar een senior positie waar ik financiele strategie en data-analyse kan combineren.',
            birthDate: '28 augustus 1993',
            birthPlace: 'Dordrecht',
            nationality: 'Nederlands',
            driversLicense: 'B',
            gender: '',
            maritalStatus: '',
            linkedIn: 'linkedin.com/in/evajanssen-finance',
            github: '',
            website: '',
            photo: '',
        },
        experience: [
            {
                role: 'Senior Financieel Analist',
                company: 'Rabobank',
                location: 'Utrecht',
                start: 'januari 2022',
                end: 'heden',
                description: 'Verantwoordelijk voor financiele analyses en rapportages ter ondersteuning van strategische besluitvorming binnen de divisie Wholesale Banking.',
                highlights: [
                    'Financiele modellen ontwikkeld voor kredietbeoordeling van zakelijke klanten met een portefeuille van \u20AC2 miljard',
                    'Geautomatiseerd rapportageproces opgezet in Power BI waardoor maandelijkse rapportagetijd met 60% afnam',
                    'Scenarioanalyses uitgevoerd voor de impact van renteschommelingen op de kredietportefeuille',
                ],
            },
            {
                role: 'Financieel Analist',
                company: 'ING Bank',
                location: 'Amsterdam',
                start: 'september 2018',
                end: 'december 2021',
                description: 'Financiele analyses en ondersteuning van het managementteam bij budgettering en forecasting.',
                highlights: [
                    'Kwartaal- en jaarrapportages opgesteld voor het senior management over de financiele prestaties',
                    'Python-scripts ontwikkeld voor automatische data-extractie en -verwerking, waardoor de foutmarge met 35% daalde',
                    'Bijgedragen aan de ontwikkeling van een nieuw forecastmodel met een nauwkeurigheid van 95%',
                ],
            },
        ],
        education: [
            {
                degree: 'MSc Finance & Investments',
                school: 'Erasmus Universiteit Rotterdam',
                location: 'Rotterdam',
                start: 'september 2016',
                end: 'juli 2018',
                description: 'Specialisatie Corporate Finance. Scriptie over de waardering van fintech-bedrijven in de Europese markt (beoordeling: 8.5).',
            },
            {
                degree: 'BSc Bedrijfseconomie',
                school: 'Erasmus Universiteit Rotterdam',
                location: 'Rotterdam',
                start: 'september 2012',
                end: 'juli 2016',
                description: 'Brede economische basis met nadruk op financieel management en accounting.',
            },
        ],
        skills: [
            { name: 'Financiele modellering', level: 5 },
            { name: 'Power BI / Tableau', level: 5 },
            { name: 'Python (pandas, numpy)', level: 4 },
            { name: 'Excel (VBA, draaitabellen)', level: 5 },
            { name: 'Bloomberg Terminal', level: 4 },
            { name: 'SQL', level: 3 },
        ],
        languages: [
            { name: 'Nederlands', level: 'Moedertaal' },
            { name: 'Engels', level: 'Vloeiend' },
        ],
        interests: ['Beleggen', 'Datajournalistiek', 'Tennis', 'Reizen'],
        courses: [
            { name: 'CFA Level II Candidate', institution: 'CFA Institute', year: '2024' },
            { name: 'Python for Finance', institution: 'DataCamp', year: '2022' },
            { name: 'Financial Modeling & Valuation', institution: 'Wall Street Prep', year: '2021' },
        ],
        internships: [],
        awards: [],
    },
};
