import { CVExample } from '../../types';

export const hrMedewerker: CVExample = {
    slug: 'hr-medewerker',
    categorySlug: 'zakelijk-en-financieel',
    name: 'HR-medewerker / HR-adviseur',
    description: 'CV voorbeeld voor HR-medewerkers en HR-adviseurs. Laat recruitment, AFAS, onboarding, verzuim, arbeidsrecht en HR-administratie concreet zien.',
    templateId: 'dynamic',
    colorThemeId: 'purple-royal',

    metaTitle: 'CV Voorbeeld HR-medewerker | AFAS, Recruitment & Verzuim | WerkCV.nl',
    metaDesc: 'Professioneel cv voorbeeld voor HR-medewerker en HR-adviseur. Met AFAS, recruitment, onboarding, verzuim, arbeidsrecht, AVG en HR-administratie.',
    keywords: ['cv voorbeeld hr-medewerker', 'hr medewerker cv', 'cv hr-adviseur', 'cv human resources', 'cv personeelszaken', 'cv AFAS', 'cv recruitment', 'cv verzuim'],
    heroTitle: 'CV Voorbeeld HR-medewerker',
    heroText: 'Als HR-professional moet je CV laten zien dat je zorgvuldig met mensen, data en processen omgaat. Dit voorbeeld toont hoe je recruitment, AFAS, onboarding, offboarding, verzuim, arbeidsrecht, AVG en HR-rapportages overtuigend presenteert.',
    tips: [
        'Vermeld scope: aantal medewerkers, afdelingen, vacatures, casussen of managers die je ondersteunt',
        'Benoem HR-systemen en ATS-tools zoals AFAS, Visma Raet, Workday, Recruitee, LinkedIn Recruiter of Nmbrs',
        'Maak processen concreet: onboarding, offboarding, contracten, mutaties, verzuim, personeelsdossiers en AVG',
        'Laat resultaten zien met time-to-hire, medewerkerstevredenheid, procesdoorlooptijd of datakwaliteit',
        'Toon dat je vertrouwelijkheid, arbeidsrecht, CAO-afspraken en gesprekstechniek professioneel beheerst',
    ],
    relatedSlugs: ['zakelijk-en-financieel/administratief-medewerker', 'zakelijk-en-financieel/office-manager', 'zakelijk-en-financieel/bedrijfsadviseur'],

    sampleCV: {
        personal: {
            name: 'Femke van Dijk',
            title: 'HR-adviseur',
            email: 'f.vandijk@email.nl',
            phone: '06-56789012',
            location: 'Den Haag',
            address: 'Laan van Meerdervoort 155',
            postalCode: '2517 AZ',
            summary: 'HR-adviseur met 4 jaar ervaring in recruitment, AFAS, onboarding, verzuimbegeleiding, personeelsadministratie en arbeidsrechtelijke ondersteuning. Ervaren in advies aan lijnmanagers, vertrouwelijke dossiers, HR-rapportages en procesverbetering. Werkt zorgvuldig, discreet en datagedreven met oog voor medewerker en organisatie.',
            birthDate: '8 maart 1995',
            birthPlace: 'Leiden',
            nationality: 'Nederlands',
            driversLicense: 'B',
            gender: '',
            maritalStatus: '',
            linkedIn: 'linkedin.com/in/femkevandijk',
            github: '',
            website: '',
            photo: '',
        },
        experience: [
            {
                role: 'HR-adviseur',
                company: 'Nationale-Nederlanden',
                location: 'Den Haag',
                start: 'april 2022',
                end: 'heden',
                description: 'HR-advies voor 3 afdelingen met totaal 450 medewerkers.',
                highlights: [
                    'Time-to-hire teruggebracht van 62 naar 38 dagen door procesoptimalisatie',
                    'Onboarding programma vernieuwd, medewerkerstevredenheid steeg naar 8.4',
                    'Geadviseerd bij 15+ arbeidsrechtelijke casussen (ziekte, ontslag, reorganisatie)',
                    'Verzuimcases, contractmutaties en HR-rapportages afgestemd met managers, casemanager en payroll',
                ],
            },
            {
                role: 'HR-medewerker',
                company: 'Randstad',
                location: 'Diemen',
                start: 'september 2020',
                end: 'maart 2022',
                description: 'Operationele HR-taken en ondersteuning van het recruitmentteam.',
                highlights: [
                    'Personeelsadministratie verzorgd voor 300+ medewerkers in AFAS',
                    'Recruitmentcampagnes gecoordineerd met gemiddeld 25 vacatures per kwartaal',
                    'Arbeidsovereenkomsten, mutaties, indiensttreding en uitdiensttreding verwerkt met controle op datakwaliteit',
                    'Sollicitatiegesprekken gepland en kandidaatcommunicatie bewaakt via ATS en Outlook',
                ],
            },
        ],
        education: [
            {
                degree: 'HBO Human Resource Management',
                school: 'Hogeschool Leiden',
                location: 'Leiden',
                start: 'september 2016',
                end: 'juli 2020',
                description: 'Minor: Arbeidsrecht. Afstudeeronderzoek over employer branding bij MKB-bedrijven.',
            },
        ],
        skills: [
            { name: 'Werving & selectie', level: 5 },
            { name: 'Arbeidsrecht', level: 4 },
            { name: 'AFAS & HR-administratie', level: 4 },
            { name: 'Onboarding & offboarding', level: 5 },
            { name: 'Gespreksvoering', level: 5 },
            { name: 'Verzuimbegeleiding', level: 4 },
        ],
        languages: [
            { name: 'Nederlands', level: 'Moedertaal' },
            { name: 'Engels', level: 'Vloeiend' },
        ],
        interests: ['Yoga', 'Persoonlijke ontwikkeling', 'Vrijwilligerswerk'],
        courses: [
            { name: 'Arbeidsrecht Basis', institution: 'GITP', year: '2022' },
            { name: 'Competentiegericht Interviewen', institution: 'SHL', year: '2021' },
            { name: 'AFAS HRM Beheer', institution: 'AFAS Academy', year: '2023' },
        ],
        internships: [],
        awards: [],
    },
};
