import { CVExample } from '../../types';

export const inkoper: CVExample = {
    slug: 'inkoper',
    categorySlug: 'zakelijk-en-financieel',
    name: 'Inkoper / Purchaser',
    description: 'CV voorbeeld voor strategische en operationele inkopers. Presenteer je onderhandelvaardigheden, leveranciersbeheer en kostenbesparingen effectief.',
    templateId: 'modern',
    colorThemeId: 'ocean-blue',

    metaTitle: 'CV Voorbeeld Inkoper | Strategisch & Operationeel | WerkCV.nl',
    metaDesc: 'Professioneel CV voorbeeld voor inkopers. Met voorbeeldteksten voor leveranciersbeheer, contractonderhandeling en kostenoptimalisatie.',
    keywords: ['cv voorbeeld inkoper', 'cv purchaser', 'cv strategisch inkoper', 'cv procurement'],
    heroTitle: 'CV Voorbeeld Inkoper',
    heroText: 'Als inkoper is het belangrijk om je onderhandelresultaten en procesverbeteringen concreet te maken. Dit CV voorbeeld laat zien hoe je je inkoopervaring, leveranciersmanagement en besparingen overtuigend presenteert.',
    tips: [
        'Kwantificeer besparingen: bedragen, percentages, volumes',
        'Vermeld ervaring met inkoopsystemen (SAP MM, Coupa, Ariba)',
        'Beschrijf je leveranciersportfolio: sectoren, omvang, internationaal',
        'Benadruk onderhandelvaardigheden en contractbeheer',
        'Toon kennis van duurzaam inkopen en compliance',
    ],
    relatedSlugs: ['zakelijk-en-financieel/bedrijfsadviseur', 'zakelijk-en-financieel/controller'],

    sampleCV: {
        personal: {
            name: 'Nienke Bakker',
            title: 'Strategisch Inkoper',
            email: 'n.bakker@email.nl',
            phone: '06-45678901',
            location: 'Eindhoven',
            address: 'Vestdijk 88',
            postalCode: '5611 AZ',
            summary: 'Ervaren strategisch inkoper met 5 jaar ervaring in de maakindustrie. Specialisatie in leveranciersselectie, contractonderhandeling en total cost of ownership analyses. Bewezen resultaten in het realiseren van structurele kostenbesparingen en het verbeteren van de supply chain.',
            birthDate: '22 november 1993',
            birthPlace: 'Tilburg',
            nationality: 'Nederlands',
            driversLicense: 'B',
            gender: '',
            maritalStatus: '',
            linkedIn: 'linkedin.com/in/nienkebakker',
            github: '',
            website: '',
            photo: '',
        },
        experience: [
            {
                role: 'Strategisch Inkoper',
                company: 'Philips',
                location: 'Eindhoven',
                start: 'januari 2022',
                end: 'heden',
                description: 'Verantwoordelijk voor de inkoop van elektronische componenten en uitbestede productie.',
                highlights: [
                    'Jaarlijkse inkoopbesparing van \u20ac1,2M gerealiseerd door leveranciersconsolidatie',
                    'Preferred supplier programma opgezet voor 25 strategische leveranciers',
                    'Raamcontracten onderhandeld met gemiddeld 12% kostenverlaging',
                ],
            },
            {
                role: 'Junior Inkoper',
                company: 'ASML',
                location: 'Veldhoven',
                start: 'maart 2019',
                end: 'december 2021',
                description: 'Operationele en tactische inkoop van technische onderdelen.',
                highlights: [
                    'Inkoopproces gedigitaliseerd via SAP MM, doorlooptijd met 40% verkort',
                    'Leveranciersbeoordelingen opgezet voor 50+ leveranciers',
                ],
            },
        ],
        education: [
            {
                degree: 'HBO Commerciele Economie',
                school: 'Fontys Hogescholen',
                location: 'Eindhoven',
                start: 'september 2014',
                end: 'juli 2018',
                description: 'Afstudeerrichting: Inkoop & Supply Chain Management',
            },
        ],
        skills: [
            { name: 'Contractonderhandeling', level: 5 },
            { name: 'SAP MM', level: 4 },
            { name: 'Leveranciersbeheer', level: 5 },
            { name: 'TCO-analyse', level: 4 },
            { name: 'Excel / Power BI', level: 4 },
            { name: 'Duurzaam inkopen', level: 3 },
        ],
        languages: [
            { name: 'Nederlands', level: 'Moedertaal' },
            { name: 'Engels', level: 'Vloeiend' },
            { name: 'Duits', level: 'Goed' },
        ],
        interests: ['Tennis', 'Duurzaamheid', 'Koken'],
        courses: [
            { name: 'NEVI 2 Tactisch Inkopen', institution: 'NEVI', year: '2021' },
            { name: 'Lean Six Sigma Yellow Belt', institution: 'LSS Academy', year: '2020' },
        ],
        internships: [],
        awards: [],
    },
};
