import { CVExample } from '../../types';

export const officeManager: CVExample = {
    slug: 'office-manager',
    categorySlug: 'zakelijk-en-financieel',
    name: 'Office Manager',
    description: 'CV voorbeeld voor office managers. Laat zien hoe je kantoororganisatie, leveranciers, onboarding, HR-support en procesverbetering professioneel presenteert.',
    templateId: 'elegant',
    colorThemeId: 'elegant-navy',

    metaTitle: 'CV Voorbeeld Office Manager | WerkCV.nl',
    metaDesc: 'Sterk office manager cv voorbeeld met profieltekst, werkervaring, vaardigheden, leveranciersbeheer, onboarding, facilities en office operations.',
    keywords: [
        'cv voorbeeld office manager',
        'office manager cv',
        'cv office management',
        'cv officemanager',
        'cv management assistent',
        'cv office administrator',
        'cv kantoor manager',
    ],
    heroTitle: 'CV Voorbeeld Office Manager',
    heroText: 'Als office manager ben je vaak de organisatorische spil van het kantoor. Dit CV voorbeeld laat zien hoe je kantoorprocessen, leveranciers, onboarding, HR-ondersteuning, agendabeheer en interne communicatie concreet maakt zonder dat je CV een losse takenlijst wordt.',
    tips: [
        'Maak duidelijk of je vooral office operations, directieondersteuning, HR-support, facilities of finance ondersteunt',
        'Benoem leveranciers, contracten, budgetten, kantoorverhuizingen of onboardingprocessen waar je verantwoordelijkheid voor had',
        'Gebruik concrete resultaten zoals lagere kosten, snellere onboarding, betere voorraadcontrole of minder ad-hoc verstoringen',
        'Vermeld systemen zoals Microsoft 365, Teams, SharePoint, Exact, AFAS, Slack, Notion of facilitair managementsoftware',
        'Laat zien dat je vertrouwelijke informatie, prioriteiten en meerdere stakeholders tegelijk aankunt',
    ],
    relatedSlugs: [
        'zakelijk-en-financieel/administratief-medewerker',
        'zakelijk-en-financieel/hr-medewerker',
        'zakelijk-en-financieel/bedrijfsadviseur',
    ],

    sampleCV: {
        personal: {
            name: 'Laura Meijer',
            title: 'Office Manager',
            email: 'laura.meijer@email.nl',
            phone: '06-56789012',
            location: 'Amsterdam',
            address: 'Wibautstraat 127',
            postalCode: '1091 GL',
            summary: 'Proactieve office manager met 6 jaar ervaring in kantoororganisatie, leveranciersbeheer, onboarding en directieondersteuning binnen groeiende MKB- en scale-upomgevingen. Sterk in het aanbrengen van structuur, verbeteren van interne processen en ontzorgen van teams. Ervaren met Microsoft 365, SharePoint, Slack, Exact Online en AFAS. Combineert gastvrijheid met zakelijke scherpte en discretie.',
            birthDate: '11 oktober 1992',
            birthPlace: 'Haarlem',
            nationality: 'Nederlands',
            driversLicense: 'B',
            gender: '',
            maritalStatus: '',
            linkedIn: 'linkedin.com/in/laurameijer',
            github: '',
            website: '',
            photo: '',
        },
        experience: [
            {
                role: 'Office Manager',
                company: 'FinTech Scale-up NovaPay',
                location: 'Amsterdam',
                start: 'januari 2021',
                end: 'heden',
                description: 'Verantwoordelijk voor kantoororganisatie, onboarding, leveranciersbeheer en ondersteuning van directie en HR.',
                highlights: [
                    'Onboardingproces voor 65 nieuwe medewerkers gestandaardiseerd met checklists, apparatuurplanning en welkomstcommunicatie',
                    'Leverancierscontracten voor schoonmaak, lunch en kantoorartikelen herzien, wat leidde tot 18% lagere maandkosten',
                    'Interne office-wiki in Notion opgezet waardoor terugkerende vragen over faciliteiten, tools en procedures sterk afnamen',
                    'Directie ondersteund met agendabeheer, boardmeeting voorbereiding en vertrouwelijke documentstromen',
                ],
            },
            {
                role: 'Management Assistant / Office Coordinator',
                company: 'Buro Noord',
                location: 'Haarlem',
                start: 'augustus 2017',
                end: 'december 2020',
                description: 'Ondersteuning van managementteam en dagelijkse kantoororganisatie voor een adviesbureau met 45 medewerkers.',
                highlights: [
                    'Vergaderingen, klantbezoeken en interne events gepland voor consultants en directie',
                    'Declaraties, inkoopfacturen en contractdocumenten voorbereid in Exact Online en SharePoint',
                    'Voorraadbeheer en facilitaire meldingen gecentraliseerd, waardoor minder spoedbestellingen nodig waren',
                ],
            },
        ],
        education: [
            {
                degree: 'HBO Facility Management',
                school: 'Hogeschool Inholland',
                location: 'Diemen',
                start: 'september 2012',
                end: 'juli 2016',
                description: 'Afstudeerrichting gericht op hospitality, huisvesting, serviceprocessen en organisatie van facilitaire dienstverlening.',
            },
        ],
        skills: [
            { name: 'Office operations', level: 5 },
            { name: 'Leveranciersbeheer', level: 5 },
            { name: 'Onboarding coordinatie', level: 4 },
            { name: 'Directieondersteuning', level: 4 },
            { name: 'Microsoft 365 / SharePoint', level: 5 },
            { name: 'Exact Online', level: 4 },
            { name: 'AFAS', level: 3 },
            { name: 'Event- en vergaderplanning', level: 5 },
        ],
        languages: [
            { name: 'Nederlands', level: 'Moedertaal' },
            { name: 'Engels', level: 'Vloeiend' },
            { name: 'Duits', level: 'Goed' },
        ],
        interests: ['Interieur & werkplekontwerp', 'Hospitality', 'Yoga', 'Stedentrips'],
        courses: [
            { name: 'Lean Office Management', institution: 'Lean Six Sigma Partners', year: '2023' },
            { name: 'Notuleren en besluitvorming', institution: 'NCOI', year: '2021' },
            { name: 'BHV ploegleider', institution: 'Het Oranje Kruis', year: '2022' },
        ],
        internships: [],
        awards: [
            'Office Hero Award NovaPay, 2022',
        ],
    },
};
