import { CVExample } from '../../types';

export const projectmanager: CVExample = {
    slug: 'projectmanager',
    categorySlug: 'zakelijk-en-financieel',
    name: 'Projectmanager',
    description: 'CV voorbeeld voor projectmanagers en projectleiders. Laat scope, budget, planning, risico, stakeholders en opleverresultaten concreet zien.',
    templateId: 'formal',
    colorThemeId: 'elegant-navy',

    metaTitle: 'CV Voorbeeld Projectmanager | WerkCV.nl',
    metaDesc: 'Professioneel cv voorbeeld voor projectmanager en projectleider. Met profieltekst, werkervaring, scope, budget, stakeholders, Agile, risico en resultaten.',
    keywords: [
        'cv voorbeeld projectmanager',
        'projectmanager cv',
        'cv projectleider',
        'cv project management',
        'cv agile projectmanager',
        'cv stakeholdermanagement',
        'cv programmamanager',
    ],
    heroTitle: 'CV Voorbeeld Projectmanager',
    heroText: 'Een sterk projectmanager CV laat meteen zien welke projecten je hebt geleid, met welke scope, welk team, welk budget en welk resultaat. Dit voorbeeld helpt je om planning, stakeholdermanagement, risico’s, budgetbewaking en oplevering professioneel en meetbaar te presenteren.',
    tips: [
        'Maak per rol de scope zichtbaar: projecttype, teamgrootte, budget, doorlooptijd, regio of business impact',
        'Gebruik resultaatgerichte bullets: op tijd opgeleverd, budget bewaakt, risico verlaagd, adoptie verhoogd of proces versneld',
        'Vermeld methodieken en tools zoals Agile, Scrum, Kanban, PRINCE2, IPMA, Jira, MS Project, Asana of Monday',
        'Laat stakeholdermanagement concreet zien: stuurgroep, directie, leveranciers, gebruikers, IT, operations of klantteams',
        'Beschrijf niet alleen dat je overleg organiseert, maar welke besluiten, afhankelijkheden of escalaties je hebt opgelost',
    ],
    relatedSlugs: [
        'technologie-en-ict/ict-projectleider',
        'bouw-en-techniek/projectleider-bouw',
        'zakelijk-en-financieel/bedrijfsadviseur',
    ],

    sampleCV: {
        personal: {
            name: 'Erkan Demir',
            title: 'Projectmanager',
            email: 'erkan.demir@email.nl',
            phone: '06-67890123',
            location: 'Rotterdam',
            address: 'Wilhelminaplein 18',
            postalCode: '3072 DE',
            summary: 'Projectmanager met 8 jaar ervaring in digitale transformatie, procesverbetering en operationele implementaties. Ervaren in het aansturen van multidisciplinaire teams, stakeholdermanagement, budgetbewaking, risicomanagement en Agile delivery. Sterk in het vertalen van doelen naar heldere planning, besluitvorming en meetbare oplevering.',
            birthDate: '12 december 1987',
            birthPlace: 'Rotterdam',
            nationality: 'Nederlands',
            driversLicense: 'B',
            gender: '',
            maritalStatus: '',
            linkedIn: 'linkedin.com/in/erkandemir',
            github: '',
            website: '',
            photo: '',
        },
        experience: [
            {
                role: 'Projectmanager Digital Operations',
                company: 'Stedin',
                location: 'Rotterdam',
                start: 'maart 2021',
                end: 'heden',
                description: 'Leiding aan digitale verbeterprojecten voor operationele teams, met focus op procesoptimalisatie, datakwaliteit en gebruikersadoptie.',
                highlights: [
                    'Projectportfolio van 6 verbetertrajecten beheerd met totaalbudget van EUR 850.000 en teams van 8-14 specialisten',
                    'Nieuwe planningsworkflow uitgerold naar 120 gebruikers; handmatige overdrachten met 35% verminderd',
                    'Risicolog en besluitvormingsritme opgezet voor stuurgroep, waardoor escalaties sneller werden afgehandeld',
                    'Samenwerking tussen IT, operations, leveranciers en gebruikersgroepen begeleid van intake tot nazorg',
                ],
            },
            {
                role: 'Projectleider Procesverbetering',
                company: 'Coolblue',
                location: 'Rotterdam',
                start: 'januari 2018',
                end: 'februari 2021',
                description: 'Projectleiding voor verbeteringen in customer operations, retourprocessen en interne tooling.',
                highlights: [
                    'Retourproces opnieuw ingericht met service, warehouse en data-analyse; doorlooptijd met 22% verkort',
                    'Jira-board, sprintplanning en wekelijkse demo\'s ingevoerd voor een team van 9 collega\'s',
                    'Businesscases opgesteld met kosten, risico\'s, afhankelijkheden en verwachte klantimpact',
                ],
            },
        ],
        education: [
            {
                degree: 'HBO Bedrijfskunde',
                school: 'Hogeschool Rotterdam',
                location: 'Rotterdam',
                start: 'september 2009',
                end: 'juli 2013',
                description: 'Afstudeerrichting organisatieverandering en procesmanagement.',
            },
        ],
        skills: [
            { name: 'Projectplanning', level: 5 },
            { name: 'Stakeholdermanagement', level: 5 },
            { name: 'Budget & scope control', level: 4 },
            { name: 'Agile/Scrum', level: 4 },
            { name: 'Risicomanagement', level: 5 },
        ],
        languages: [
            { name: 'Nederlands', level: 'Moedertaal' },
            { name: 'Engels', level: 'Vloeiend' },
            { name: 'Turks', level: 'Goed' },
        ],
        interests: ['Schaken', 'Reizen', 'Hardlopen'],
        courses: [
            { name: 'PRINCE2 Practitioner', institution: 'PeopleCert', year: '2023' },
            { name: 'Professional Scrum Master I', institution: 'Scrum.org', year: '2021' },
            { name: 'Stakeholdermanagement', institution: 'Nyenrode Executive Education', year: '2020' },
        ],
        internships: [],
        awards: [
            'Project Excellence Award bij Stedin voor heldere projectsturing en sterke gebruikersadoptie, 2023',
        ],
    },
};
