import { CVExample } from '../../types';

export const receptionist: CVExample = {
    slug: 'receptionist',
    categorySlug: 'zakelijk-en-financieel',
    name: 'Receptionist / Telefonist',
    description: 'CV voorbeeld voor receptionisten en telefonisten. Laat zien hoe je ontvangst, telefoon, agendabeheer, bezoekersregistratie en administratie professioneel presenteert.',
    templateId: 'classical',
    colorThemeId: 'elegant-navy',

    metaTitle: 'CV Voorbeeld Receptionist & Telefonist | WerkCV.nl',
    metaDesc: 'Professioneel cv voorbeeld voor receptionist, receptioniste en telefonist. Met profieltekst, werkervaring, balie, telefoon, planning en administratieve vaardigheden.',
    keywords: [
        'cv voorbeeld receptionist',
        'receptionist cv',
        'cv receptioniste',
        'cv telefonist',
        'cv baliemedewerker',
        'cv receptiemedewerker',
        'cv front office medewerker',
    ],
    heroTitle: 'CV Voorbeeld Receptionist / Telefonist',
    heroText: 'Als receptionist ben je vaak het eerste contactmoment van een organisatie. Dit CV voorbeeld laat zien hoe je gastvrijheid, telefoonafhandeling, bezoekersregistratie, agendabeheer en administratieve ondersteuning professioneel presenteert.',
    tips: [
        'Benoem of je ervaring hebt met balie, telefooncentrale, afspraakplanning, bezoekersregistratie of front office',
        'Laat zien met welke systemen je werkte, zoals Outlook, Teams, Topdesk, Microsoft Bookings, CRM of toegangsregistratie',
        'Gebruik voorbeelden van drukke momenten, vertrouwelijke informatie en schakelen tussen bezoekers, collega’s en leveranciers',
        'Vermeld talen duidelijk als je internationale bezoekers of telefoongesprekken ontvangt',
        'Kies een rustige, representatieve template; voor deze rol is overzicht belangrijker dan opvallend design',
    ],
    relatedSlugs: [
        'horeca-en-detailhandel/hotel-receptionist',
        'zakelijk-en-financieel/administratief-medewerker',
        'zakelijk-en-financieel/office-manager',
    ],

    sampleCV: {
        personal: {
            name: 'Mila Jansen',
            title: 'Receptionist / Telefonist',
            email: 'mila.jansen@email.nl',
            phone: '06-67890123',
            location: 'Breda',
            address: 'Baronielaan 38',
            postalCode: '4818 RA',
            summary: 'Representatieve receptionist met 5 jaar ervaring in ontvangst, telefoonafhandeling, afspraakplanning en administratieve ondersteuning. Sterk in het professioneel te woord staan van bezoekers, snel schakelen tussen vragen en zorgvuldig vastleggen van informatie. Ervaren met Outlook, Teams, Topdesk, bezoekersregistratie en CRM-systemen. Gastvrij, rustig onder druk en betrouwbaar met vertrouwelijke gegevens.',
            birthDate: '24 mei 1996',
            birthPlace: 'Breda',
            nationality: 'Nederlands',
            driversLicense: 'B',
            gender: '',
            maritalStatus: '',
            linkedIn: 'linkedin.com/in/milajansen',
            github: '',
            website: '',
            photo: '',
        },
        experience: [
            {
                role: 'Receptionist / Telefonist',
                company: 'Medisch Centrum Brabant',
                location: 'Breda',
                start: 'maart 2021',
                end: 'heden',
                description: 'Ontvangst, telefonie en administratieve ondersteuning binnen een drukke zorg- en kantooromgeving.',
                highlights: [
                    'Dagelijks 80+ telefoongesprekken professioneel afgehandeld en correct doorgezet naar artsen, administratie of planning',
                    'Bezoekersregistratie, afspraakbevestigingen en wachtruimtecommunicatie verzorgd tijdens piekmomenten',
                    'Afspraken gepland en gewijzigd in Outlook en intern planningssysteem met aandacht voor privacy en urgentie',
                    'Veelgestelde vragen gedocumenteerd, waardoor nieuwe collega’s sneller zelfstandig konden meedraaien',
                ],
            },
            {
                role: 'Baliemedewerker',
                company: 'Gemeente Breda',
                location: 'Breda',
                start: 'september 2018',
                end: 'februari 2021',
                description: 'Eerste aanspreekpunt voor bezoekers bij publiekszaken en ondersteuning bij administratieve balieprocessen.',
                highlights: [
                    'Inwoners ontvangen, gecontroleerd op afspraak en geholpen met route, documenten en vervolgstappen',
                    'Aanvragen en identiteitsgegevens zorgvuldig gecontroleerd volgens interne werkinstructies',
                    'Balieteam ondersteund met dagplanning, wachtrijcommunicatie en het bijwerken van standaardteksten',
                ],
            },
        ],
        education: [
            {
                degree: 'MBO 4 Office & Management Support',
                school: 'Curio',
                location: 'Breda',
                start: 'september 2014',
                end: 'juli 2018',
                description: 'Opleiding gericht op front office, zakelijke communicatie, agendabeheer, administratie en klantgericht werken.',
            },
        ],
        skills: [
            { name: 'Telefonische etiquette', level: 5 },
            { name: 'Bezoekersontvangst', level: 5 },
            { name: 'Agenda- en afspraakplanning', level: 4 },
            { name: 'Outlook / Teams', level: 5 },
            { name: 'Bezoekersregistratie', level: 4 },
            { name: 'Topdesk', level: 3 },
            { name: 'Administratieve ondersteuning', level: 4 },
            { name: 'Omgaan met vertrouwelijke informatie', level: 5 },
        ],
        languages: [
            { name: 'Nederlands', level: 'Moedertaal' },
            { name: 'Engels', level: 'Vloeiend' },
            { name: 'Duits', level: 'Goed' },
        ],
        interests: ['Hospitality', 'Taal', 'Pilates', 'Vrijwilligerswerk bij evenementen'],
        courses: [
            { name: 'Professioneel telefoneren', institution: 'NCOI', year: '2022' },
            { name: 'Omgaan met agressie aan de balie', institution: 'Schouten & Nelissen', year: '2021' },
            { name: 'BHV', institution: 'Het Oranje Kruis', year: '2023' },
        ],
        internships: [],
        awards: [
            'Compliment van het kwartaal voor gastvrije ontvangst, 2023',
        ],
    },
};
