import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "MatchPack privacy, retentie en DPA | WerkCV",
  description: "Hoe WerkCV MatchPack bronbestanden, kandidaatdata, revisies en agency-toegang verwerkt.",
  alternates: { canonical: "https://werkcv.nl/agency/privacy" },
};

export default function AgencyPrivacyPage() {
  return (
    <main className="min-h-screen bg-[#FFFEF9] px-4 py-10 text-slate-900 sm:px-6 lg:px-8">
      <article className="mx-auto max-w-4xl">
        <header className="flex flex-wrap items-center justify-between gap-4 border-b-2 border-slate-900 pb-5"><Link href="/agency" className="text-xl font-black tracking-tight">Werk<span className="bg-[#4ECDC4] px-1">CV</span>.nl</Link><Link href="/agency/account" className="text-sm font-bold text-emerald-700 underline underline-offset-4">Naar je account</Link></header>
        <p className="mt-12 text-xs font-black uppercase tracking-[0.18em] text-emerald-700">MatchPack privacy</p>
        <h1 className="mt-2 text-4xl font-black tracking-tight sm:text-5xl">Wat er wordt opgeslagen, hoelang en onder wiens verantwoordelijkheid.</h1>
        <p className="mt-5 max-w-3xl text-lg leading-relaxed text-slate-600">Deze pagina beschrijft de huidige MatchPack-workspace voor bureaus. Het is productinformatie, geen juridisch advies. Je bureau blijft verwerkingsverantwoordelijke voor kandidaatdata en moet een geldige grondslag, passende instructies en afspraken met klanten hebben.</p>

        <div className="mt-10 space-y-8 text-sm leading-relaxed text-slate-700">
          <section><h2 className="text-2xl font-black text-slate-950">Wat gebeurt er met het bronbestand?</h2><p className="mt-3">Het geüploade PDF- of DOCX-bestand wordt alleen gebruikt om tekst uit te lezen. Het originele bestand wordt na de analyse niet als downloadbaar bronbestand opgeslagen. Wel bewaren we de uitgelezen vacaturetekst, gestructureerde kandidaatdata, de versie zonder directe contactgegevens, analyse-uitkomsten, bewijsverwijzingen, revisies en goedkeuringsinformatie zodat je de review kunt uitvoeren.</p></section>
          <section><h2 className="text-2xl font-black text-slate-950">Retentie en verwijderen</h2><p className="mt-3">MatchPack-data blijft bewaard totdat je die verwijdert via <Link href="/agency/account/settings" className="font-bold text-emerald-700 underline">Instellingen → Agency-data verwijderen</Link> of totdat het account wordt gesloten. Er is op dit moment geen automatische bewaartermijn voor inhoudelijke MatchPack-data. Abonnementen, betaalbewijzen en noodzakelijke administratie kunnen langer worden bewaard volgens wettelijke en contractuele verplichtingen.</p></section>
          <section><h2 className="text-2xl font-black text-slate-950">Contactgegevens verwijderen is geen anonimiseren</h2><p className="mt-3">De optionele variant maakt bekende naam- en contactvelden leeg en verwijdert contactachtige tekst waar dat herkenbaar is. Namen in lopende tekst, werkgevers, scholen, projecten en zeldzame combinaties kunnen nog steeds naar een persoon verwijzen. Controleer het normale én het contactvrije PDF/DOCX-bestand vóór delen met een klant. Gebruik geen gevoelige of live kandidaatdata zonder de vereiste toestemming en instructies.</p></section>
          <section><h2 className="text-2xl font-black text-slate-950">Rollen en toegangsbeheer</h2><p className="mt-3">De eigenaar beheert templates, teamleden en verwijderen. Editors kunnen nieuw werk maken en wijzigen. Reviewers kunnen bewijs controleren, corrigeren en goedkeuren. Viewers kunnen alleen lezen. Toegang is gekoppeld aan het login-e-mailadres; verwijder een teamlid zodra de samenwerking stopt.</p></section>
          <section><h2 className="text-2xl font-black text-slate-950">Verwerkers en subverwerkers</h2><p className="mt-3">De huidige configuratie gebruikt OpenAI voor AI-verwerking van CV-tekst, Dodo Payments voor de Agency-billing tier, een geconfigureerde SMTP-provider (bijvoorbeeld Resend) voor login-codes en PostgreSQL op de gekozen hostingomgeving voor account- en MatchPack-data. Leveranciers, regio&apos;s en contractvoorwaarden kunnen per deployment wijzigen. De actuele contractuele lijst en DPA-voorwaarden zijn op verzoek beschikbaar via <a className="font-bold text-emerald-700 underline" href="mailto:contact@werkcv.nl">contact@werkcv.nl</a>. Op dit moment moet je MatchPack niet als volledige juridische anonimiserings- of DPA-oplossing presenteren.</p><div className="mt-4 overflow-x-auto border-2 border-slate-200"><table className="min-w-full text-left text-sm"><thead className="bg-slate-50"><tr><th className="px-3 py-3 font-black">Verwerker</th><th className="px-3 py-3 font-black">Doel</th><th className="px-3 py-3 font-black">Wat jij moet controleren</th></tr></thead><tbody><tr className="border-t"><td className="px-3 py-3">OpenAI</td><td className="px-3 py-3">CV uitlezen en functie-eisen koppelen</td><td className="px-3 py-3">grondslag, instructies en actuele data-controls</td></tr><tr className="border-t"><td className="px-3 py-3">Dodo Payments</td><td className="px-3 py-3">abonnement en betaalstatus</td><td className="px-3 py-3">factuur- en klantgegevens</td></tr><tr className="border-t"><td className="px-3 py-3">SMTP-provider</td><td className="px-3 py-3">login-code per e-mail</td><td className="px-3 py-3">provider, regio en bewaartermijn van mailmetadata</td></tr><tr className="border-t"><td className="px-3 py-3">Hosting/PostgreSQL</td><td className="px-3 py-3">account, MatchPacks en revisies</td><td className="px-3 py-3">infrastructuurregio, beveiliging en retentie</td></tr></tbody></table></div></section>
          <section className="border-2 border-amber-400 bg-amber-50 p-5"><h2 className="text-2xl font-black text-amber-950">DPA-aanvraag</h2><p className="mt-3 text-amber-950">Wil je MatchPack voor echte kandidaatdata inzetten? Vraag vóór gebruik de actuele verwerkersinformatie en DPA op via contact@werkcv.nl. Beschrijf je use-case, landen/regio&apos;s en gewenste bewaartermijn. Tot die afspraken rond zijn, gebruik je fictieve of correct geautoriseerde CV&apos;s voor tests.</p></section>
        </div>
        <div className="mt-10 border-t-2 border-slate-900 pt-6 text-sm font-bold"><Link href="/agency" className="text-emerald-700 underline underline-offset-4">← Terug naar MatchPack</Link></div>
      </article>
    </main>
  );
}
