import type { EnglishRoleCvExamplePageProps } from "./EnglishRoleCvExamplePage";
import { makeEnglishRoleExampleCV } from "./englishRoleFixtures";

export type EnglishLogisticsRoleConfig = EnglishRoleCvExamplePageProps & {
  articleDescription: string;
};

const sources = [
  {
    label: "Work in NL — CV guidance",
    href: "https://www.workinnl.nl/en/employment/cv-en/default.aspx",
    note: "Official guidance on a clear CV for work in the Netherlands.",
    reviewedOn: "29 August 2026",
  },
  {
    label: "UWV — working in the Netherlands",
    href: "https://www.uwv.nl/en/individuals/working-in-the-netherlands",
    note: "Official context for working in the Netherlands; check current rules with the employer.",
    reviewedOn: "29 August 2026",
  },
  {
    label: "Government.nl — work permits",
    href: "https://www.government.nl/faq/foreign-citizens-working-in-the-netherlands/what-permits-do-foreign-workers-need",
    note: "Official starting point for work-permit questions; eligibility is not assessed by this CV example.",
    reviewedOn: "29 August 2026",
  },
  {
    label: "WerkCV English templates",
    href: "https://werkcv.nl/en/templates",
    note: "Templates and a free editor route for replacing the fictional content.",
    reviewedOn: "29 August 2026",
  },
];

const languageNote = [
  { term: "Warehouse management system", meaning: "Warehousemanagementsysteem", note: "Name the actual system, such as SAP EWM or Manhattan, only when you have used it." },
  { term: "Goods receiving", meaning: "Goederenontvangst", note: "Useful for inbound work; pair it with the checks or system you used." },
  { term: "Load safety", meaning: "Laadveiligheid", note: "Describe the real safety or loading procedure rather than claiming a generic safety record." },
  { term: "Reach truck", meaning: "Reachtruck", note: "List the certificate and date only when you can confirm them." },
];

export const forkliftReachTruckExample: EnglishLogisticsRoleConfig = {
  roleSlug: "forklift_reach_truck",
  pagePath: "/en/english-cv-example-forklift-reach-truck-netherlands",
  articleDescription: "A fictional English forklift and reach-truck CV example for warehouse jobs in the Netherlands, with safety, equipment, and evidence guidance.",
  lastReviewed: "29 August 2026",
  eyebrow: "English forklift CV example",
  h1: "Forklift and reach-truck CV example for the Netherlands",
  intro: "See how an equipment-focused warehouse CV makes certificates, safe loading, systems, and shift work easy to check. Use the fictional structure, then replace every detail with your own evidence.",
  audience: "forklift and reach-truck operators applying to Dutch warehouses and distribution centres",
  previewAlt: "Fictional forklift and reach-truck CV preview showing summary, equipment experience, and certificate sections",
  themeColor: "amber",
  templateId: "simple",
  colorThemeId: "charcoal",
  sampleCV: makeEnglishRoleExampleCV({
    name: "Milan de Boer",
    title: "Forklift and Reach Truck Operator",
    email: "milan.deboer@example.com",
    phone: "+31 6 0000 1111",
    location: "Venlo, Netherlands",
    summary: "Safety-minded forklift and reach-truck operator with 6 years of experience in goods receiving, pallet movement, replenishment, loading checks, and WMS registration. Experienced in busy distribution centres and rotating shifts, with a practical focus on accurate locations and safe loads.",
    current: {
      role: "Forklift and Reach Truck Operator",
      company: "NorthGate Distribution (fictional)",
      location: "Venlo",
      start: "May 2021",
      highlights: [
        "Moved inbound and outbound pallets with forklift and reach truck while following site traffic and load-safety procedures.",
        "Replenished pick locations and recorded put-away movements in a warehouse management system.",
        "Checked pallet labels, quantities, and visible damage before staging loads for transport.",
        "Supported new operators with equipment checks, safe routes, and escalation of damaged or unstable pallets.",
      ],
    },
    previous: {
      role: "Warehouse Operator",
      company: "GreenLine Wholesale (fictional)",
      location: "Roermond",
      start: "Jan 2018",
      end: "Apr 2021",
      highlights: [
        "Loaded and unloaded delivery vehicles and kept inbound paperwork matched to warehouse locations.",
        "Used hand scanners for stock moves, cycle counts, and returns in a two-shift operation.",
        "Reported equipment defects and product damage before goods were released to the next process.",
      ],
    },
    education: {
      degree: "MBO 2 Logistics Employee",
      school: "Rivermark Logistics College (fictional)",
      location: "Roermond",
      start: "2015",
      end: "2017",
      description: "Warehouse operations, transport preparation, stock control, and workplace safety.",
    },
    skills: ["Forklift operation", "Reach truck", "Load safety", "WMS registration", "Goods receiving", "Put-away", "Stock checks", "Shift work"],
    properties: ["Safety-minded", "Reliable", "Calm under pressure"],
    courses: [
      { name: "Forklift certificate", institution: "Fictional Logistics Training Centre", year: "2024" },
      { name: "Reach-truck certificate", institution: "Fictional Logistics Training Centre", year: "2024" },
      { name: "VCA Basic Safety", institution: "Fictional Safety Institute", year: "2023" },
    ],
    languages: [
      { name: "English", level: "Good" },
      { name: "Dutch", level: "Fluent" },
    ],
  }),
  scanTitle: "What equipment-led warehouse hiring teams scan first",
  scanBody: "Put the exact equipment, certificate status, safe-working evidence, warehouse systems, and current shift availability near the top. Avoid implying a certificate or licence you cannot document.",
  scanChecks: [
    "Exact equipment: forklift, reach truck, EPT, order picker, or other machinery.",
    "Certificate or licence name and year, with no claim beyond the document you hold.",
    "Safe process evidence: checks, load stability, traffic routes, damage escalation, and PPE.",
    "Warehouse system and scanner experience connected to a real stock movement.",
    "Current availability for day, evening, night, weekend, or rotating shifts.",
  ],
  summaryLabel: "Target: forklift and reach-truck roles, Netherlands",
  experienceTitle: "Bullets that show safe equipment work",
  fictionalLabel: "Fictional candidate — Milan de Boer and every employer are invented",
  evidenceExamples: [
    { claim: "Reach-truck experience", evidence: "The current role explicitly names reach-truck operation and replenishment.", source: "Experience · NorthGate Distribution", status: "supported" },
    { claim: "Certificate claim", evidence: "The courses section lists fictional forklift, reach-truck, and VCA certificates with years.", source: "Courses / certificates", status: "supported" },
    { claim: "Safety claim", evidence: "The bullets describe traffic, load checks, defect reporting, and damage escalation rather than an unsupported score.", source: "Experience bullets", status: "supported" },
    { claim: "Current availability", evidence: "Shift work is shown as experience; present-day availability still needs candidate confirmation.", source: "Skills + current facts", status: "partial" },
  ],
  noNumbersExample: "No verified productivity number? Keep the operational evidence: “Replenished pick locations and recorded put-away movements in the WMS.” A truthful process claim is stronger than an invented pallet count.",
  vocabulary: languageNote,
  localContext: "For a Netherlands application, show location, Dutch/English level, certificate details, and shift availability clearly. Questions about work authorisation belong with the employer and official guidance; a CV example cannot determine eligibility.",
  relatedLinks: [
    { href: "/en/english-cv-example-logistics-warehouse-netherlands", label: "Logistics and warehouse CV example" },
    { href: "/en/english-cv-example-order-picker-fulfilment-netherlands", label: "Order picker CV example" },
  ],
  mistakesTitle: "Mistakes that weaken a forklift CV",
  mistakes: [
    "Writing “licensed” without naming the certificate or checking that it is current.",
    "Listing machinery without showing the warehouse process it supported.",
    "Claiming a perfect safety record without evidence or context.",
    "Leaving shift availability and language level hidden in a cover note.",
    "Using a generic logistics CV when the vacancy is specifically equipment-led.",
  ],
  bottomTitle: "Build from this forklift example",
  bottomBody: "Open the filled fictional CV, then replace the equipment, certificates, employers, shifts, and evidence with your own details before you share it.",
  sources,
  faqs: [
    { question: "Should I put a forklift certificate near the top?", answer: "Yes, when it is relevant and current. State the exact certificate or training and year; do not imply a licence you cannot confirm." },
    { question: "What if my forklift or reach-truck certificate has expired?", answer: "Do not present it as current. List the training with its date only if it helps explain your background, mark the status honestly, and confirm renewal requirements with the employer or training provider." },
    { question: "Can I apply in English to a Dutch warehouse?", answer: "Yes when the vacancy and team use English. Keep your Dutch level and practical safety-language ability visible and honest." },
    { question: "How should I describe equipment experience honestly?", answer: "Name the equipment, warehouse task, and safety or checking procedure you actually performed. Do not turn a short induction or supervised task into independent operator experience." },
    { question: "What if I do not know my exact productivity?", answer: "Describe the process, systems, equipment, and quality checks. Add a number only when you can defend its source." },
    { question: "What if I am new to warehouse work?", answer: "Lead with transferable evidence such as safe manual handling, stock work, reliability, and relevant training. Add equipment or productivity claims only when you can support them." },
  ],
};

export const orderPickerFulfilmentExample: EnglishLogisticsRoleConfig = {
  roleSlug: "order_picker_fulfilment",
  pagePath: "/en/english-cv-example-order-picker-fulfilment-netherlands",
  articleDescription: "A fictional English order-picker and fulfilment CV example for the Netherlands, showing picking, packing, returns, WMS, and shift evidence.",
  lastReviewed: "29 August 2026",
  eyebrow: "English order-picker CV example",
  h1: "Order picker and fulfilment CV example for jobs in the Netherlands",
  intro: "Use a complete fictional example to see how picking accuracy, packing, returns, scanners, and shift work can be explained without inflated claims.",
  audience: "order pickers and fulfilment workers applying to Dutch e-commerce and distribution operations",
  previewAlt: "Fictional order-picker CV preview showing picking, packing, returns, and WMS evidence",
  themeColor: "teal",
  templateId: "robust",
  colorThemeId: "modern-teal",
  sampleCV: makeEnglishRoleExampleCV({
    name: "Sana El Idrissi",
    title: "Order Picker / Fulfilment Associate",
    email: "sana.elidrissi@example.com",
    phone: "+31 6 0000 2222",
    location: "Eindhoven, Netherlands",
    summary: "Careful fulfilment associate with 4 years of experience in order picking, packing, returns, replenishment, and handheld-scanner workflows. Used to high-volume e-commerce operations, quality checks, and clear handovers across morning, evening, and weekend shifts.",
    current: {
      role: "Order Picker / Fulfilment Associate",
      company: "BrightCart Fulfilment (fictional)",
      location: "Eindhoven",
      start: "Oct 2022",
      highlights: [
        "Picked multi-line customer orders with handheld scanners and location checks before packing.",
        "Packed fragile and temperature-sensitive items according to packing instructions and carrier cut-off times.",
        "Processed returns and exceptions in the WMS, escalating missing, damaged, or substituted items.",
        "Helped new colleagues learn pick paths, quality checks, and safe manual handling in a busy operation.",
      ],
    },
    previous: {
      role: "Warehouse Assistant",
      company: "EastPoint Retail Logistics (fictional)",
      location: "Helmond",
      start: "Mar 2020",
      end: "Sep 2022",
      highlights: [
        "Replenished forward-pick locations and completed cycle-count tasks with a hand scanner.",
        "Prepared outbound cages for parcel carriers and checked labels against the order record.",
        "Supported stockroom housekeeping and reported recurring location or packaging issues.",
      ],
    },
    education: {
      degree: "MBO 2 Logistics Employee",
      school: "Northgate Logistics College (fictional)",
      location: "Eindhoven",
      start: "2017",
      end: "2019",
      description: "Order fulfilment, warehouse systems, safe manual handling, and stock administration.",
    },
    skills: ["Order picking", "Packing", "Returns processing", "Handheld scanner", "WMS", "Replenishment", "Quality checks", "Manual handling"],
    properties: ["Accurate", "Team-oriented", "Fast learner"],
    courses: [
      { name: "Safe manual handling", institution: "Fictional Workplace Academy", year: "2024" },
      { name: "Basic warehouse safety", institution: "Fictional Workplace Academy", year: "2023" },
    ],
    languages: [
      { name: "English", level: "Fluent" },
      { name: "Dutch", level: "Good" },
    ],
  }),
  scanTitle: "What fulfilment teams scan first",
  scanBody: "Make the flow visible: where you picked, how you checked it, what systems you used, and how you handled exceptions. The result should be understandable even when a recruiter scans it quickly.",
  scanChecks: [
    "Pick, pack, replenishment, returns, and exception-handling responsibilities.",
    "Scanner or WMS evidence tied to locations, orders, stock, or returns.",
    "Quality and safety checks rather than unsupported speed claims.",
    "Carrier cut-offs, cold-chain or fragile-item processes when genuinely relevant.",
    "Language, location, and current shift availability in a visible section.",
  ],
  summaryLabel: "Target: order picker and fulfilment, Netherlands",
  experienceTitle: "Bullets that show accurate fulfilment",
  fictionalLabel: "Fictional candidate — Sana El Idrissi and every employer are invented",
  evidenceExamples: [
    { claim: "Scanner workflow", evidence: "The current role names handheld scanners and location checks before packing.", source: "Experience · BrightCart Fulfilment", status: "supported" },
    { claim: "Returns handling", evidence: "Returns and exceptions are described as WMS work with escalation of missing or damaged items.", source: "Experience · BrightCart Fulfilment", status: "supported" },
    { claim: "Speed claim", evidence: "No pick-rate number is stated, so the example avoids presenting an unverified performance metric.", source: "Profile design decision", status: "not shown" },
    { claim: "Current shift availability", evidence: "Past morning, evening, and weekend work does not prove current availability; ask the candidate.", source: "Summary + changing facts", status: "partial" },
  ],
  noNumbersExample: "If you cannot verify a pick rate, write what makes the work reliable: “Picked multi-line orders with scanner and location checks before packing.” It tells the reader what you actually did.",
  vocabulary: [
    { term: "Order picking", meaning: "Orderpicken", note: "Use both terms when a local vacancy mixes English and Dutch." },
    { term: "Returns processing", meaning: "Retourverwerking", note: "Add the system and decision you used for exceptions." },
    { term: "Pick path", meaning: "Pickroute", note: "Explain route or location work only when it reflects your real process." },
    { term: "Packing instructions", meaning: "Verpakkingsinstructies", note: "Mention fragile, cold-chain, or carrier rules only when relevant." },
  ],
  localContext: "International fulfilment teams may use English, while safety instructions and daily coordination can still include Dutch. State both language levels and show where you have worked with local procedures.",
  relatedLinks: [
    { href: "/en/english-cv-example-logistics-warehouse-netherlands", label: "Logistics and warehouse CV example" },
    { href: "/en/english-cv-example-forklift-reach-truck-netherlands", label: "Forklift and reach-truck CV example" },
  ],
  mistakesTitle: "Mistakes that weaken an order-picker CV",
  mistakes: [
    "Leading with an impressive pick rate that cannot be checked.",
    "Saying “warehouse experience” without naming picking, packing, returns, or systems.",
    "Ignoring damaged, missing, or substituted-item handling.",
    "Hiding shift and weekend availability in an email instead of the CV.",
    "Using the same wording for fulfilment, inbound, and forklift roles.",
  ],
  bottomTitle: "Build from this order-picker example",
  bottomBody: "Open the fictional content in the editor and replace every process, system, shift, and employer with facts you can stand behind.",
  sources,
  faqs: [
    { question: "Do I need a number on every fulfilment bullet?", answer: "No. A clear process, system, quality check, or exception handled is useful evidence. Use numbers only when you can verify them." },
    { question: "Should I mention weekend or night shifts?", answer: "Mention past shift experience and state current availability separately, because availability can change." },
    { question: "How should I describe physical-work experience?", answer: "Describe the real handling, packing, standing, lifting, temperature, or pace requirements and the safety routines you followed. Avoid unsupported claims about strength, fitness, or injury-free performance." },
    { question: "Do I need Dutch if I apply to an English-speaking fulfilment team?", answer: "Follow the vacancy honestly: show your English level, state your Dutch level, and mention whether you can understand the safety or team instructions required for the role." },
    { question: "What is the difference between an order picker and a warehouse operator?", answer: "Titles vary by employer. Describe the actual flow—picking, packing, replenishment, returns, or stock work—so the reader can assess the fit." },
    { question: "Can agency work count as fulfilment experience?", answer: "Yes. Name the real client or site only when you are allowed to, describe the process you performed, and separate temporary assignment dates from your current availability." },
  ],
};

export const logisticsCoordinatorExample: EnglishLogisticsRoleConfig = {
  roleSlug: "logistics_coordinator",
  pagePath: "/en/english-cv-example-logistics-coordinator-netherlands",
  articleDescription: "A fictional English logistics coordinator CV example for the Netherlands, with transport planning, carrier communication, ERP records, and measurable but defensible outcomes.",
  lastReviewed: "29 August 2026",
  eyebrow: "English logistics coordinator CV example",
  h1: "Logistics coordinator CV example for jobs in the Netherlands",
  intro: "See how to present planning, carrier communication, shipment records, warehouse handovers, and problem-solving in a concise English CV for the Dutch market.",
  audience: "logistics coordinators and transport administrators applying to international Dutch operations",
  previewAlt: "Fictional logistics coordinator CV preview showing planning, systems, and exception-handling evidence",
  themeColor: "blue",
  templateId: "professional",
  colorThemeId: "ocean-blue",
  sampleCV: makeEnglishRoleExampleCV({
    name: "Jonas Vermeer",
    title: "Logistics Coordinator",
    email: "jonas.vermeer@example.com",
    phone: "+31 6 0000 3333",
    location: "Rotterdam, Netherlands",
    summary: "Logistics coordinator with 5 years of experience organising inbound and outbound shipments, carrier communication, warehouse handovers, and transport documentation. Comfortable balancing changing priorities, keeping ERP records accurate, and escalating delays with a clear action plan.",
    current: {
      role: "Logistics Coordinator",
      company: "HarbourLink Supply (fictional)",
      location: "Rotterdam",
      start: "Feb 2022",
      highlights: [
        "Coordinated daily inbound and outbound bookings with warehouse teams, carriers, and customer-service colleagues.",
        "Maintained shipment status, delivery notes, and exception records in the ERP and transport-planning tools.",
        "Escalated delays and shortages with a concise impact, owner, and next-action summary.",
        "Created a handover checklist that made open shipments and delivery risks visible at shift change.",
      ],
    },
    previous: {
      role: "Transport Administration Assistant",
      company: "Delta Freight Services (fictional)",
      location: "Dordrecht",
      start: "Aug 2019",
      end: "Jan 2022",
      highlights: [
        "Prepared transport documents and checked references before bookings were released to carriers.",
        "Updated delivery appointments and contacted customers when plans changed.",
        "Maintained daily spreadsheets for open shipments, proof of delivery, and unresolved exceptions.",
      ],
    },
    education: {
      degree: "MBO 4 Logistics Supervisor",
      school: "Harbourline Logistics College (fictional)",
      location: "Rotterdam",
      start: "2015",
      end: "2019",
      description: "Transport planning, logistics administration, warehouse processes, and customer communication.",
    },
    skills: ["Transport planning", "Carrier communication", "ERP records", "Shipment tracking", "Exception handling", "Excel", "Warehouse handover", "Customer updates"],
    properties: ["Organised", "Clear communicator", "Solution-focused"],
    courses: [
      { name: "Excel for logistics planning", institution: "Fictional Skills Academy", year: "2023" },
      { name: "Incoterms foundations", institution: "Fictional Trade Institute", year: "2022" },
    ],
    languages: [
      { name: "English", level: "Fluent" },
      { name: "Dutch", level: "Fluent" },
    ],
  }),
  scanTitle: "What logistics coordinator hiring teams scan first",
  scanBody: "Show the operational chain you coordinated, the systems or documents you maintained, and how you made delays or exceptions visible. Separate your own contribution from the wider team outcome.",
  scanChecks: [
    "Inbound, outbound, transport planning, carrier, warehouse, or customer-service scope.",
    "ERP, TMS, Excel, shipment tracking, proof of delivery, or document control evidence.",
    "A clear method for handling delays, shortages, changes, and escalation.",
    "Handover, reporting, and stakeholder communication that another person can understand.",
    "Languages and location fit for the Netherlands operation.",
  ],
  summaryLabel: "Target: logistics coordinator, Netherlands",
  experienceTitle: "Bullets that show coordination ownership",
  fictionalLabel: "Fictional candidate — Jonas Vermeer and every employer are invented",
  evidenceExamples: [
    { claim: "Planning ownership", evidence: "The current role says Jonas coordinated daily bookings with warehouse teams and carriers.", source: "Experience · HarbourLink Supply", status: "supported" },
    { claim: "Systems claim", evidence: "ERP and transport-planning tools are named as the place where shipment status and exceptions were maintained.", source: "Experience · HarbourLink Supply", status: "supported" },
    { claim: "Improvement claim", evidence: "The handover checklist is described, but no unsupported time-saving percentage is added.", source: "Experience bullets", status: "supported" },
    { claim: "Commercial responsibility", evidence: "The example does not claim ownership of freight costs or contracts without source evidence.", source: "Scope boundary", status: "not shown" },
  ],
  noNumbersExample: "A coordinator CV can prove value without a percentage: explain the exception, your action, the owner, and the operational result. Add a metric only when the source records it.",
  vocabulary: [
    { term: "Shipment tracking", meaning: "Zending volgen", note: "Name the tool or record only when it is part of your real workflow." },
    { term: "Proof of delivery", meaning: "POD / afleverbewijs", note: "Useful for transport administration and customer updates." },
    { term: "Exception handling", meaning: "Uitzonderingen oplossen", note: "Show the decision or escalation you made, not just the word “exceptions”." },
    { term: "Handover", meaning: "Overdracht", note: "Describe the information that made the next shift effective." },
  ],
  localContext: "For Dutch logistics employers, an English CV can work in international operations. Make Dutch and English levels, location, systems, and availability easy to scan, and confirm any changing commercial or work-authorisation details separately.",
  relatedLinks: [
    { href: "/en/english-cv-example-logistics-warehouse-netherlands", label: "Logistics and warehouse CV example" },
    { href: "/en/english-cv-example-order-picker-fulfilment-netherlands", label: "Order picker CV example" },
  ],
  mistakesTitle: "Mistakes that weaken a logistics coordinator CV",
  mistakes: [
    "Calling yourself a planner without describing shipments, carriers, systems, or decisions.",
    "Claiming team-wide savings or on-time performance as your personal result.",
    "Listing Excel or ERP without showing what record or workflow you maintained.",
    "Hiding problem-solving behind vague phrases such as “handled issues”.",
    "Using a warehouse-operator CV for a coordination and communication vacancy.",
  ],
  bottomTitle: "Build from this logistics coordinator example",
  bottomBody: "Start with the fictional structure, then replace the systems, shipment flows, stakeholders, and outcomes with evidence from your own work.",
  sources,
  faqs: [
    { question: "What is the most useful logistics coordinator evidence?", answer: "Show the shipment or process scope, systems or documents, stakeholders, exceptions, and the action you owned." },
    { question: "Which planning metrics can I include?", answer: "Use a metric only when you can trace it to a real record, such as shipment volume, planning horizon, on-time performance, open exceptions, or handover time. Explain your contribution instead of claiming the whole team’s result." },
    { question: "Should I include Incoterms?", answer: "Include them when they are relevant to the vacancy and you can explain how you used them; a course alone is not the same as operational responsibility." },
    { question: "How can I translate Dutch logistics vacancy terms?", answer: "Keep the English role title readable and add the Dutch term in parentheses when it clarifies the vacancy, for example transport planning (transportplanning) or proof of delivery (afleverbewijs). Only use terms that describe your actual work." },
    { question: "Do I need Dutch for a logistics coordinator role?", answer: "It depends on the employer and stakeholders. State your Dutch and English levels clearly, and do not imply that an English-language CV removes a language requirement in the vacancy." },
    { question: "Can a logistics coordinator CV be two pages?", answer: "Yes when the second page adds relevant shipment, system, stakeholder, and outcome evidence rather than repeating duties." },
    { question: "How is a coordinator CV different from a warehouse CV?", answer: "Lead with planning, records, carriers, handovers, exceptions, and stakeholder decisions. Do not present operational warehouse duties as coordination ownership." },
  ],
};
