import { CVExample } from '../../types';

export const cybersecuritySpecialist: CVExample = {
    slug: 'cybersecurity-specialist',
    categorySlug: 'technologie-en-ict',
    name: 'Cybersecurity Specialist',
    description: 'CV voorbeeld voor cybersecurity specialisten. Laat zien hoe je je expertise in informatiebeveiliging, ethical hacking en risicoanalyse presenteert.',
    templateId: 'modern',
    colorThemeId: 'charcoal',

    metaTitle: 'CV Voorbeeld Cybersecurity Specialist | WerkCV.nl',
    metaDesc: 'Professioneel CV voorbeeld voor cybersecurity specialisten. Met voorbeeldteksten voor informatiebeveiliging, pentesting en compliance. Maak direct je eigen CV.',
    keywords: ['cv voorbeeld cybersecurity', 'cv informatiebeveiliging', 'cv security specialist', 'cybersecurity cv', 'ethical hacker cv'],
    heroTitle: 'CV Voorbeeld Cybersecurity Specialist',
    heroText: 'Als cybersecurity specialist bescherm je organisaties tegen digitale dreigingen. Dit CV voorbeeld laat zien hoe je je technische beveiligingsexpertise, certificeringen en concrete resultaten overtuigend presenteert. Benadruk zowel je offensieve als defensieve vaardigheden en je kennis van compliance-frameworks.',
    tips: [
        'Zet je certificeringen prominent neer: CISSP, CEH, OSCP en CompTIA Security+ zijn zeer gewild',
        'Beschrijf concrete resultaten: "12 kritieke kwetsbaarheden geïdentificeerd en verholpen voor productierelease"',
        'Benoem frameworks en standaarden die je kent: ISO 27001, NIST, NIS2, AVG/GDPR',
        'Toon je ervaring met zowel offensieve (pentesting) als defensieve (SIEM, SOC) beveiliging',
        'Vermeld je ervaring met security awareness-trainingen om je communicatieve vaardigheden te tonen',
    ],
    relatedSlugs: ['technologie-en-ict/systeembeheerder', 'technologie-en-ict/software-ontwikkelaar'],

    sampleCV: {
        personal: {
            name: 'Youssef El Amrani',
            title: 'Cybersecurity Specialist',
            email: 'youssef.elamrani@email.nl',
            phone: '06-67890123',
            location: 'Utrecht',
            address: 'Oudegracht 142',
            postalCode: '3511 AX',
            summary: 'Gedreven cybersecurity specialist met 7 jaar ervaring in informatiebeveiliging en risicoanalyse. Gespecialiseerd in penetratietesten, incidentrespons en het implementeren van beveiligingsframeworks conform ISO 27001 en NIS2. CISSP- en OSCP-gecertificeerd met een passie voor het veiliger maken van digitale omgevingen.',
            birthDate: '19 juni 1992',
            birthPlace: 'Utrecht',
            nationality: 'Nederlands',
            driversLicense: 'B',
            gender: '',
            maritalStatus: '',
            linkedIn: 'linkedin.com/in/youssefea',
            github: 'github.com/youssefea',
            website: '',
            photo: '',
        },
        experience: [
            {
                role: 'Senior Cybersecurity Specialist',
                company: 'Deloitte',
                location: 'Amsterdam',
                start: 'april 2021',
                end: 'heden',
                description: 'Leidt het offensieve beveiligingsteam dat penetratietesten en security assessments uitvoert voor grote enterprise-klanten.',
                highlights: [
                    'Ruim 40 penetratietesten uitgevoerd voor klanten in de financiële en zorgsector, met 200+ kritieke kwetsbaarheden geïdentificeerd',
                    'Red team-oefeningen geleid voor een grote bank, wat leidde tot een volledige herziening van hun incidentresponsplan',
                    'Security awareness-programma ontwikkeld en uitgerold bij 3 organisaties (5.000+ medewerkers), phishing-gevoeligheid daalde met 65%',
                ],
            },
            {
                role: 'Security Analyst',
                company: 'KPN',
                location: 'Den Haag',
                start: 'september 2017',
                end: 'maart 2021',
                description: 'Werkzaam in het Security Operations Center (SOC) voor de monitoring en bescherming van kritieke telecomunicatie-infrastructuur.',
                highlights: [
                    'SIEM-platform (Splunk) beheerd en tuned, waardoor het aantal false positives met 40% afnam',
                    'ISO 27001-certificeringstraject begeleid en succesvol afgerond voor de afdeling',
                    'Incidentresponsproces geoptimaliseerd, waardoor gemiddelde reactietijd van 45 naar 15 minuten daalde',
                ],
            },
        ],
        education: [
            {
                degree: 'Master Cyber Security',
                school: 'Technische Universiteit Delft',
                location: 'Delft',
                start: 'september 2015',
                end: 'juli 2017',
                description: 'Specialisatie in offensive security en cryptografie. Masterscriptie over detectie van advanced persistent threats in enterprise-netwerken.',
            },
            {
                degree: 'Bachelor Informatica',
                school: 'Universiteit Utrecht',
                location: 'Utrecht',
                start: 'september 2011',
                end: 'juli 2015',
                description: 'Minor Security & Privacy. Deelname aan Capture The Flag-competities.',
            },
        ],
        skills: [
            { name: 'Penetratietesten (Burp Suite, Metasploit)', level: 5 },
            { name: 'SIEM (Splunk, Microsoft Sentinel)', level: 4 },
            { name: 'Netwerk- & applicatiebeveiliging', level: 5 },
            { name: 'ISO 27001 / NIS2 / AVG', level: 4 },
            { name: 'Python / Bash scripting', level: 4 },
            { name: 'Cloud Security (AWS, Azure)', level: 4 },
        ],
        languages: [
            { name: 'Nederlands', level: 'Moedertaal' },
            { name: 'Engels', level: 'Vloeiend' },
            { name: 'Arabisch', level: 'Goed' },
        ],
        interests: ['CTF-competities', 'Bug bounty programma\'s', 'Padel', 'Technologie-podcasts'],
        courses: [
            { name: 'Certified Information Systems Security Professional (CISSP)', institution: 'ISC2', year: '2023' },
            { name: 'Offensive Security Certified Professional (OSCP)', institution: 'Offensive Security', year: '2021' },
        ],
        internships: [],
        awards: [],
    },
};
