import { CVExample } from '../../types';

export const ictProjectleider: CVExample = {
    slug: 'ict-projectleider',
    categorySlug: 'technologie-en-ict',
    name: 'ICT Projectleider',
    description: 'CV voorbeeld voor ICT projectleiders. Laat zien hoe je je leiderschapsvaardigheden, Agile-ervaring en projectresultaten overtuigend presenteert.',
    templateId: 'formal',
    colorThemeId: 'elegant-navy',

    metaTitle: 'CV Voorbeeld ICT Projectleider | WerkCV.nl',
    metaDesc: 'Professioneel CV voorbeeld voor ICT projectleiders. Met voorbeeldteksten voor IT-projectmanagement, Agile/Scrum en stakeholdermanagement. Maak direct je eigen CV.',
    keywords: ['cv voorbeeld ict projectleider', 'cv it projectmanager', 'cv agile scrum', 'ict projectleider cv', 'it manager cv'],
    heroTitle: 'CV Voorbeeld ICT Projectleider',
    heroText: 'Als ICT projectleider combineer je technische kennis met leiderschapsvaardigheden. Dit CV voorbeeld laat zien hoe je je ervaring met het aansturen van IT-projecten, budgetbeheer en stakeholdermanagement effectief presenteert. Benadruk je resultaten en je vermogen om complexe projecten tot een goed einde te brengen.',
    tips: [
        'Benoem de omvang van je projecten: budget, teamgrootte en doorlooptijd',
        'Vermeld je projectmanagement-certificeringen: PMP, PRINCE2, SAFe, PSM',
        'Toon resultaten: "project opgeleverd binnen budget en 2 weken voor deadline"',
        'Beschrijf je ervaring met zowel waterval- als Agile-methodieken',
        'Laat zien hoe je samenwerkt met zowel technische teams als business stakeholders',
    ],
    relatedSlugs: ['technologie-en-ict/software-ontwikkelaar', 'technologie-en-ict/systeembeheerder'],

    sampleCV: {
        personal: {
            name: 'Linda Vermeer',
            title: 'ICT Projectleider',
            email: 'linda.vermeer@email.nl',
            phone: '06-56789012',
            location: 'Den Haag',
            address: 'Lange Voorhout 18',
            postalCode: '2514 EE',
            summary: 'Resultaatgerichte ICT projectleider met 10 jaar ervaring in het succesvol leiden van complexe IT-projecten. Gecertificeerd in PRINCE2 Practitioner en SAFe Agilist met een bewezen track record in het opleveren van projecten binnen budget en planning. Sterk in stakeholdermanagement, teamcoaching en het vertalen van bedrijfsdoelen naar concrete IT-oplossingen.',
            birthDate: '5 januari 1988',
            birthPlace: 'Leiden',
            nationality: 'Nederlands',
            driversLicense: 'B',
            gender: '',
            maritalStatus: '',
            linkedIn: 'linkedin.com/in/lindavermeer',
            github: '',
            website: '',
            photo: '',
        },
        experience: [
            {
                role: 'Senior ICT Projectleider',
                company: 'Rijkswaterstaat',
                location: 'Den Haag',
                start: 'september 2019',
                end: 'heden',
                description: 'Leiding over grote ICT-transformatieprojecten binnen de Rijksoverheid, gericht op digitalisering en procesoptimalisatie.',
                highlights: [
                    'Programma van 3 gerelateerde projecten geleid met een totaalbudget van \u20AC4,5 miljoen en een team van 25 professionals',
                    'Cloudmigratie naar Azure succesvol afgerond voor 2.000+ gebruikers, binnen budget en 3 weken voor deadline',
                    'Agile werkwijze (SAFe) geïntroduceerd in een traditionele watervalorganisatie, waardoor time-to-market met 40% verbeterde',
                ],
            },
            {
                role: 'ICT Projectleider',
                company: 'Capgemini',
                location: 'Utrecht',
                start: 'januari 2015',
                end: 'augustus 2019',
                description: 'Projectleiding van diverse IT-implementatieprojecten bij klanten in de financiële en publieke sector.',
                highlights: [
                    'ERP-implementatieproject geleid bij een verzekeraar (budget \u20AC1,8 miljoen, team van 12 personen)',
                    'Scrum Master rol vervuld naast projectleiding, wat leidde tot 30% hogere teamvelocity',
                    'Risicoanalyses en voortgangsrapportages opgesteld voor stuurgroepen en directie',
                ],
            },
        ],
        education: [
            {
                degree: 'Master Bedrijfsinformatica',
                school: 'Universiteit Utrecht',
                location: 'Utrecht',
                start: 'september 2010',
                end: 'juli 2012',
                description: 'Specialisatie IT Governance. Scriptie over succesfactoren bij agile transformaties in grote organisaties.',
            },
            {
                degree: 'Bachelor Informatiekunde',
                school: 'Universiteit Leiden',
                location: 'Leiden',
                start: 'september 2006',
                end: 'juli 2010',
                description: 'Brede basis in informatica, organisatiekunde en projectmanagement.',
            },
        ],
        skills: [
            { name: 'Projectmanagement (PRINCE2, Agile)', level: 5 },
            { name: 'Stakeholdermanagement', level: 5 },
            { name: 'Budgetbeheer & planning', level: 4 },
            { name: 'Scrum / SAFe', level: 4 },
            { name: 'Risicomanagement', level: 4 },
            { name: 'JIRA / Azure DevOps', level: 4 },
        ],
        languages: [
            { name: 'Nederlands', level: 'Moedertaal' },
            { name: 'Engels', level: 'Vloeiend' },
            { name: 'Duits', level: 'Goed' },
        ],
        interests: ['Leiderschap & coaching', 'Zeilen', 'Non-fictie lezen', 'Wandelen'],
        courses: [
            { name: 'PRINCE2 Practitioner', institution: 'AXELOS', year: '2019' },
            { name: 'SAFe 6.0 Agilist (SA)', institution: 'Scaled Agile', year: '2023' },
        ],
        internships: [],
        awards: [],
    },
};
