import { CVExample } from "../../types";

export const ictMedewerker: CVExample = {
    slug: "ict-medewerker",
    categorySlug: "technologie-en-ict",
    name: "ICT Medewerker",
    description: "CV voorbeeld voor ICT medewerkers. Laat zien hoe je support, werkplekbeheer, Microsoft 365 en ticketafhandeling professioneel presenteert.",
    templateId: "ats",
    colorThemeId: "ocean-blue",

    metaTitle: "CV Voorbeeld ICT Medewerker | WerkCV.nl",
    metaDesc: "Professioneel CV voorbeeld voor ICT medewerker. Met voorbeeldteksten voor werkplekbeheer, Microsoft 365, tickets, support en systeembeheer. Maak direct je eigen CV.",
    keywords: [
        "cv ict medewerker",
        "cv voorbeeld ict medewerker",
        "ict medewerker cv",
        "cv it support medewerker",
        "cv werkplekbeheer",
        "cv servicedesk medewerker ict",
    ],
    heroTitle: "CV voorbeeld ICT medewerker",
    heroText: "Als ICT medewerker moet je CV snel laten zien dat je storingen oplost, gebruikers helpt en werkplekken stabiel houdt. Dit voorbeeld laat zien hoe je support, Microsoft 365, Active Directory, hardware-uitrol en ticketafhandeling concreet en recruiter-proof presenteert.",
    tips: [
        "Noem concrete tools zoals Microsoft 365, Intune, Active Directory, Topdesk of Jira Service Management.",
        "Beschrijf hoeveel tickets of gebruikers je ondersteunt en welke SLA's of oplostijden je haalt.",
        "Laat zien dat je zowel support als basisbeheer oppakt: accounts, devices, rechten en onboarding.",
        "Vermeld certificeringen zoals ITIL, MD-102, AZ-900 of Microsoft 365 Fundamentals als je die hebt.",
        "Gebruik functietermen uit de vacature, zoals ICT medewerker, IT support, servicedesk of werkplekbeheer.",
    ],
    relatedSlugs: ["technologie-en-ict/systeembeheerder", "technologie-en-ict/cybersecurity-specialist"],

    sampleCV: {
        personal: {
            name: "Sanne Vermeer",
            title: "ICT Medewerker / IT Support",
            email: "sanne.vermeer@email.nl",
            phone: "06-34567890",
            location: "Eindhoven",
            address: "Stratumsedijk 42",
            postalCode: "5611 ND",
            summary: "Praktische ICT medewerker met 5 jaar ervaring in werkplekbeheer, Microsoft 365 support en ticketafhandeling. Ervaren in het oplossen van storingen, inrichten van laptops en accounts, en ondersteunen van eindgebruikers op kantoor en remote. Sterk in duidelijke communicatie, prioriteren op impact en het stabiel houden van dagelijkse IT-processen.",
            birthDate: "17 mei 1996",
            birthPlace: "Helmond",
            nationality: "Nederlands",
            driversLicense: "B",
            gender: "",
            maritalStatus: "",
            linkedIn: "linkedin.com/in/sannevermeer",
            github: "",
            website: "",
            photo: "",
        },
        experience: [
            {
                role: "ICT Medewerker",
                company: "DLL",
                location: "Eindhoven",
                start: "februari 2022",
                end: "heden",
                description: "Ondersteunt eindgebruikers op kantoor en thuiswerkplekken met focus op Microsoft 365, werkplekbeheer en ticketafhandeling binnen een internationale omgeving.",
                highlights: [
                    "Gemiddeld 35 tot 45 tickets per week afgehandeld met een first-time-fix rate van 78%",
                    "Onboardingproces voor nieuwe medewerkers gestandaardiseerd, waardoor werkplekken gemiddeld 1 dag sneller klaarstonden",
                    "Intune- en Entra ID-beheer ondersteund voor 600+ devices en gebruikersaccounts",
                ],
            },
            {
                role: "Support Medewerker IT",
                company: "Simac IT NL",
                location: "Veldhoven",
                start: "augustus 2020",
                end: "januari 2022",
                description: "Servicedesk en werkplekondersteuning voor mkb-klanten met focus op Microsoft-omgevingen, printers, hardware en toegangsbeheer.",
                highlights: [
                    "Dagelijks 20+ supportverzoeken opgepakt via telefoon, mail en ticketsysteem",
                    "Laptopuitrol en accountmigraties ondersteund bij een Microsoft 365 migratie voor 120 gebruikers",
                    "Handleidingen voor veelvoorkomende supportvragen geschreven, waardoor terugkerende tickets met 18% afnamen",
                ],
            },
        ],
        education: [
            {
                degree: "MBO 4 Expert IT Systems and Devices",
                school: "Summa College",
                location: "Eindhoven",
                start: "september 2016",
                end: "juli 2020",
                description: "Opleiding gericht op werkplekbeheer, systeembeheer, netwerken en gebruikersondersteuning.",
            },
        ],
        skills: [
            { name: "Microsoft 365 / Entra ID / Intune", level: 5 },
            { name: "Windows 10/11 werkplekbeheer", level: 5 },
            { name: "Active Directory / rechtenbeheer", level: 4 },
            { name: "Topdesk / ticketafhandeling", level: 4 },
            { name: "Hardware-uitrol en onboarding", level: 4 },
            { name: "Basis netwerken / printers / VPN", level: 3 },
        ],
        languages: [
            { name: "Nederlands", level: "Moedertaal" },
            { name: "Engels", level: "Goed" },
        ],
        interests: ["Slimme thuisnetwerken", "Padel", "Tech podcasts", "Vrijwillig ICT-hulp"],
        courses: [
            { name: "ITIL 4 Foundation", institution: "PeopleCert", year: "2024" },
            { name: "Microsoft 365 Fundamentals (MS-900)", institution: "Microsoft", year: "2023" },
        ],
        internships: [],
        awards: [],
    },
};
