import { CVExample } from '../../types';

export const softwareOntwikkelaar: CVExample = {
    slug: 'software-ontwikkelaar',
    categorySlug: 'technologie-en-ict',
    name: 'Software Ontwikkelaar',
    description: 'CV voorbeeld voor software ontwikkelaars. Laat zien hoe je technische vaardigheden, projecten en resultaten overtuigend presenteert.',
    templateId: 'modern',
    colorThemeId: 'ocean-blue',

    metaTitle: 'CV Voorbeeld Software Ontwikkelaar | WerkCV.nl',
    metaDesc: 'Professioneel CV voorbeeld voor software ontwikkelaars. Met voorbeeldteksten voor full-stack developers, tips en een gratis template. Maak direct je eigen CV.',
    keywords: ['cv voorbeeld software ontwikkelaar', 'cv developer', 'cv programmeur', 'software engineer cv', 'full-stack developer cv'],
    heroTitle: 'CV Voorbeeld Software Ontwikkelaar',
    heroText: 'Als software ontwikkelaar is het belangrijk dat je CV zowel je technische expertise als je vermogen om in teamverband te werken laat zien. Dit voorbeeld toont hoe je projecten, technische vaardigheden en meetbare resultaten effectief presenteert aan recruiters en hiring managers.',
    tips: [
        'Vermeld je tech stack duidelijk: programmeertalen, frameworks en tools die je beheerst',
        'Gebruik meetbare resultaten: "performance verbeterd met 40%" in plaats van "performance geoptimaliseerd"',
        'Voeg een link naar je GitHub-profiel of portfolio toe voor bewijs van je werk',
        'Benoem de methodologie waarin je werkt (Scrum, Kanban, DevOps) om teamfit te tonen',
        'Houd je CV op maximaal 2 pagina\'s: focus op de meest relevante ervaring en projecten',
    ],
    relatedSlugs: ['technologie-en-ict/data-engineer', 'technologie-en-ict/cybersecurity-specialist'],

    sampleCV: {
        personal: {
            name: 'Daan de Vries',
            title: 'Full-Stack Software Ontwikkelaar',
            email: 'daan.devries@email.nl',
            phone: '06-23456789',
            location: 'Amsterdam',
            address: 'Prinsengracht 114',
            postalCode: '1015 EA',
            summary: 'Ervaren full-stack software ontwikkelaar met ruim 6 jaar ervaring in het bouwen van schaalbare webapplicaties. Gespecialiseerd in TypeScript, React en Node.js met een sterke focus op code-kwaliteit en testbare architectuur. Bewezen vermogen om complexe technische problemen op te lossen en effectief samen te werken in multidisciplinaire Agile teams.',
            birthDate: '12 maart 1994',
            birthPlace: 'Haarlem',
            nationality: 'Nederlands',
            driversLicense: 'B',
            gender: '',
            maritalStatus: '',
            linkedIn: 'linkedin.com/in/daandevries',
            github: 'github.com/daandevries',
            website: '',
            photo: '',
        },
        experience: [
            {
                role: 'Senior Software Ontwikkelaar',
                company: 'Adyen',
                location: 'Amsterdam',
                start: 'maart 2021',
                end: 'heden',
                description: 'Ontwikkeling en onderhoud van het interne dashboardplatform voor betalingsverwerking binnen een Scrum-team van 8 ontwikkelaars.',
                highlights: [
                    'Microservices-architectuur opgezet in Node.js en TypeScript, waardoor deploymenttijd met 60% afnam',
                    'React frontend herschreven van class-based naar functionele componenten met hooks, wat de laadtijd met 35% verbeterde',
                    'CI/CD-pipelines ingericht met GitHub Actions en Docker, resulterend in meerdere releases per dag',
                ],
            },
            {
                role: 'Medior Software Ontwikkelaar',
                company: 'Bol.com',
                location: 'Utrecht',
                start: 'september 2018',
                end: 'februari 2021',
                description: 'Werkte aan het productcatalogussysteem en de zoekfunctionaliteit van het e-commerceplatform.',
                highlights: [
                    'REST API\'s ontwikkeld in Java/Spring Boot voor productdata, gebruikt door 10+ interne teams',
                    'Zoekperformance geoptimaliseerd met Elasticsearch, wat de responstijd met 45% verlaagde',
                    'Junior developers begeleid en code reviews uitgevoerd om codekwaliteit te waarborgen',
                ],
            },
        ],
        education: [
            {
                degree: 'Master Computer Science',
                school: 'Universiteit van Amsterdam',
                location: 'Amsterdam',
                start: 'september 2016',
                end: 'juli 2018',
                description: 'Specialisatie Software Engineering. Masterscriptie over microservices-architectuur in cloud-native applicaties.',
            },
            {
                degree: 'Bachelor Informatica',
                school: 'Hogeschool van Amsterdam',
                location: 'Amsterdam',
                start: 'september 2012',
                end: 'juli 2016',
                description: 'Afstudeerproject bij een fintech-startup: ontwikkeling van een real-time transactiemonitor.',
            },
        ],
        skills: [
            { name: 'TypeScript / JavaScript', level: 5 },
            { name: 'React / Next.js', level: 5 },
            { name: 'Node.js / Express', level: 4 },
            { name: 'Java / Spring Boot', level: 4 },
            { name: 'PostgreSQL / MongoDB', level: 4 },
            { name: 'Docker / Kubernetes', level: 3 },
        ],
        languages: [
            { name: 'Nederlands', level: 'Moedertaal' },
            { name: 'Engels', level: 'Vloeiend' },
        ],
        interests: ['Open source bijdragen', 'Tech meetups', 'Boulderen', 'Schaken'],
        courses: [
            { name: 'AWS Certified Developer - Associate', institution: 'Amazon Web Services', year: '2023' },
            { name: 'Professional Scrum Developer (PSD I)', institution: 'Scrum.org', year: '2021' },
        ],
        internships: [],
        awards: [],
    },
};
