import { CVExample } from '../../types';

export const softwareOntwikkelaar: CVExample = {
    slug: 'software-ontwikkelaar',
    categorySlug: 'technologie-en-ict',
    name: 'Software Ontwikkelaar',
    description: 'CV voorbeeld voor softwareontwikkelaars. Laat tech stack, projecten, architectuur, performance, testing, CI/CD en productimpact overtuigend zien.',
    templateId: 'modern',
    colorThemeId: 'ocean-blue',

    metaTitle: 'Softwareontwikkelaar CV Voorbeeld | WerkCV.nl',
    metaDesc: 'Professioneel softwareontwikkelaar cv voorbeeld met TypeScript, React, Node.js, projectimpact en recruiter-proof bullets. Gebruik het als basis voor je eigen developer-CV.',
    keywords: ['softwareontwikkelaar cv', 'cv softwareontwikkelaar', 'cv voorbeeld software ontwikkelaar', 'cv software ontwikkelaar', 'cv developer', 'cv programmeur', 'software engineer cv', 'full-stack developer cv'],
    heroTitle: 'Softwareontwikkelaar CV voorbeeld',
    heroText: 'Als softwareontwikkelaar moet je CV niet alleen een lijst technologieën zijn. Dit voorbeeld toont hoe je TypeScript, React, Node.js, Java, APIs, CI/CD, cloud, testing, code reviews en productimpact verwerkt in concrete werkervaring.',
    tips: [
        'Vermeld je tech stack duidelijk, maar laat dezelfde technologieën ook terugkomen in je werkervaringsbullets',
        'Gebruik meetbare resultaten: performance, laadtijd, deploymenttijd, incidenten, testdekking of ontwikkelsnelheid',
        'Voeg een link naar je GitHub-profiel of portfolio toe voor bewijs van je werk',
        'Benoem API-ontwerp, databasekeuzes, tests, CI/CD, observability en cloud als ze relevant zijn voor de vacature',
        'Maak teamfit zichtbaar met code reviews, mentoring, Scrum/Kanban, incidentrespons en samenwerken met product/design',
    ],
    relatedSlugs: ['technologie-en-ict/ict-medewerker', 'technologie-en-ict/data-engineer', 'technologie-en-ict/cybersecurity-specialist'],

    sampleCV: {
        personal: {
            name: 'Daan de Vries',
            title: 'Full-Stack Software Ontwikkelaar',
            email: 'daan.devries@email.nl',
            phone: '06-23456789',
            location: 'Amsterdam',
            address: 'Prinsengracht 114',
            postalCode: '1015 EA',
            summary: 'Full-stack softwareontwikkelaar met 6 jaar ervaring in schaalbare webapplicaties, interne tooling en e-commerceplatformen. Gespecialiseerd in TypeScript, React, Next.js, Node.js, Java/Spring Boot, PostgreSQL en CI/CD. Sterk in performance, testbare architectuur, API-ontwerp, code reviews en samenwerken met product, design en DevOps.',
            birthDate: '12 maart 1994',
            birthPlace: 'Haarlem',
            nationality: 'Nederlands',
            driversLicense: 'B',
            gender: '',
            maritalStatus: '',
            linkedIn: 'linkedin.com/in/daandevries',
            github: 'github.com/daandevries',
            website: '',
            photo: '',
        },
        experience: [
            {
                role: 'Senior Software Ontwikkelaar',
                company: 'Adyen',
                location: 'Amsterdam',
                start: 'maart 2021',
                end: 'heden',
                description: 'Ontwikkeling en onderhoud van het interne dashboardplatform voor betalingsverwerking binnen een Scrum-team van 8 ontwikkelaars.',
                highlights: [
                    'Microservices opgezet in Node.js en TypeScript voor interne betalingsflows, waardoor deploymenttijd met 60% afnam',
                    'React-dashboard gemigreerd naar functionele componenten, hooks en gedeelde UI-library; laadtijd met 35% verbeterd',
                    'CI/CD-pipelines ingericht met GitHub Actions, Docker en automatische tests, resulterend in meerdere releases per dag',
                    'API-contracten, logging en foutafhandeling verbeterd waardoor supportvragen over dashboarddata merkbaar afnamen',
                ],
            },
            {
                role: 'Medior Software Ontwikkelaar',
                company: 'Bol.com',
                location: 'Utrecht',
                start: 'september 2018',
                end: 'februari 2021',
                description: 'Werkte aan het productcatalogussysteem en de zoekfunctionaliteit van het e-commerceplatform.',
                highlights: [
                    'REST API\'s ontwikkeld in Java/Spring Boot voor productdata, gebruikt door 10+ interne teams',
                    'Zoekperformance geoptimaliseerd met Elasticsearch, wat de responstijd met 45% verlaagde',
                    'PostgreSQL-query\'s en caching verbeterd voor cataloguspagina\'s tijdens piekbelasting',
                    'Junior developers begeleid en code reviews uitgevoerd op testbaarheid, security en onderhoudbaarheid',
                ],
            },
        ],
        education: [
            {
                degree: 'Master Computer Science',
                school: 'Universiteit van Amsterdam',
                location: 'Amsterdam',
                start: 'september 2016',
                end: 'juli 2018',
                description: 'Specialisatie Software Engineering. Masterscriptie over microservices-architectuur in cloud-native applicaties.',
            },
            {
                degree: 'Bachelor Informatica',
                school: 'Hogeschool van Amsterdam',
                location: 'Amsterdam',
                start: 'september 2012',
                end: 'juli 2016',
                description: 'Afstudeerproject bij een fintech-startup: ontwikkeling van een real-time transactiemonitor.',
            },
        ],
        skills: [
            { name: 'TypeScript / JavaScript', level: 5 },
            { name: 'React / Next.js', level: 5 },
            { name: 'Node.js / Express', level: 4 },
            { name: 'Java / Spring Boot', level: 4 },
            { name: 'PostgreSQL / MongoDB', level: 4 },
            { name: 'CI/CD & Docker', level: 4 },
        ],
        languages: [
            { name: 'Nederlands', level: 'Moedertaal' },
            { name: 'Engels', level: 'Vloeiend' },
        ],
        interests: ['Open source bijdragen', 'Tech meetups', 'Boulderen', 'Schaken'],
        courses: [
            { name: 'AWS Certified Developer - Associate', institution: 'Amazon Web Services', year: '2023' },
            { name: 'Professional Scrum Developer (PSD I)', institution: 'Scrum.org', year: '2021' },
            { name: 'Testing JavaScript Applications', institution: 'Kent C. Dodds', year: '2022' },
        ],
        internships: [],
        awards: [],
    },
};
