import { CVExample } from '../../types';

export const systeembeheerder: CVExample = {
    slug: 'systeembeheerder',
    categorySlug: 'technologie-en-ict',
    name: 'Systeembeheerder',
    description: 'CV voorbeeld voor systeembeheerders. Laat zien hoe je je ervaring met infrastructuur, servers en netwerken overtuigend presenteert.',
    templateId: 'ats',
    colorThemeId: 'charcoal',

    metaTitle: 'CV Voorbeeld Systeembeheerder | WerkCV.nl',
    metaDesc: 'Professioneel CV voorbeeld voor systeembeheerders. Met voorbeeldteksten voor infrastructuur, servers en netwerken, tips en een gratis template.',
    keywords: ['cv voorbeeld systeembeheerder', 'cv system administrator', 'cv infrastructuur', 'systeembeheer cv', 'netwerk beheerder cv'],
    heroTitle: 'CV Voorbeeld Systeembeheerder',
    heroText: 'Als systeembeheerder zorg je ervoor dat de IT-infrastructuur betrouwbaar en veilig draait. Dit CV voorbeeld laat zien hoe je je technische kennis van servers, netwerken en cloud-omgevingen combineert met je probleemoplossend vermogen en resultaatgerichtheid.',
    tips: [
        'Vermeld specifieke systemen en platforms: Windows Server, Linux, VMware, Azure AD',
        'Benoem je uptime-resultaten en SLA-prestaties als meetbare resultaten',
        'Toon je certificeringen prominent: MCSA, CCNA, ITIL en CompTIA zijn zeer gewaardeerd',
        'Beschrijf je ervaring met monitoring, backup en disaster recovery',
        'Laat zien dat je zowel zelfstandig als in een team kunt werken bij het oplossen van incidenten',
    ],
    relatedSlugs: ['technologie-en-ict/cybersecurity-specialist', 'technologie-en-ict/ict-projectleider'],

    sampleCV: {
        personal: {
            name: 'Mark Jansen',
            title: 'Systeembeheerder',
            email: 'mark.jansen@email.nl',
            phone: '06-45678901',
            location: 'Rotterdam',
            address: 'Westersingel 56',
            postalCode: '3014 GS',
            summary: 'Ervaren systeembeheerder met 8 jaar ervaring in het beheren van complexe IT-infrastructuren. Gespecialiseerd in Windows Server, Linux en virtualisatie met VMware. Sterk in het waarborgen van bedrijfscontinuïteit door proactief monitoring, onderhoud en het implementeren van beveiligingsmaatregelen. ITIL-gecertificeerd met een bewezen staat van dienst in het behalen van 99,9% uptime.',
            birthDate: '23 september 1990',
            birthPlace: 'Dordrecht',
            nationality: 'Nederlands',
            driversLicense: 'B',
            gender: '',
            maritalStatus: '',
            linkedIn: 'linkedin.com/in/markjansen',
            github: '',
            website: '',
            photo: '',
        },
        experience: [
            {
                role: 'Senior Systeembeheerder',
                company: 'Erasmus MC',
                location: 'Rotterdam',
                start: 'mei 2020',
                end: 'heden',
                description: 'Verantwoordelijk voor het beheer van de IT-infrastructuur van het grootste universitair medisch centrum van Nederland.',
                highlights: [
                    'Serverpark van 200+ Windows- en Linux-servers beheerd met een uptime van 99,95%',
                    'Migratie naar hybride cloud-omgeving (Azure) geleid, waardoor infrastructuurkosten met 30% daalden',
                    'Geautomatiseerd patchmanagement geïmplementeerd met WSUS en Ansible, waardoor handmatig werk met 80% afnam',
                ],
            },
            {
                role: 'Systeembeheerder',
                company: 'Simac ICT',
                location: 'Veldhoven',
                start: 'maart 2016',
                end: 'april 2020',
                description: 'Beheer van IT-infrastructuur voor diverse klanten in de regio als onderdeel van een managed services team.',
                highlights: [
                    'VMware vSphere-omgevingen beheerd voor 15+ klanten met in totaal 500+ virtuele machines',
                    'Backup- en disaster recovery-oplossingen geïmplementeerd met Veeam, waardoor hersteltijd van 8 naar 2 uur daalde',
                    'Netwerkomgeving geoptimaliseerd met Cisco-switches en firewalls voor verbeterde beveiliging',
                ],
            },
        ],
        education: [
            {
                degree: 'HBO Informatica',
                school: 'Hogeschool Rotterdam',
                location: 'Rotterdam',
                start: 'september 2010',
                end: 'juli 2014',
                description: 'Specialisatie Infrastructuur & Netwerken. Afstudeerproject over het ontwerpen van een high-availability serveromgeving.',
            },
        ],
        skills: [
            { name: 'Windows Server / Active Directory', level: 5 },
            { name: 'Linux (Ubuntu, CentOS)', level: 4 },
            { name: 'VMware vSphere / Hyper-V', level: 5 },
            { name: 'Azure / Microsoft 365', level: 4 },
            { name: 'Netwerken (TCP/IP, DNS, DHCP)', level: 4 },
            { name: 'PowerShell / Bash scripting', level: 4 },
        ],
        languages: [
            { name: 'Nederlands', level: 'Moedertaal' },
            { name: 'Engels', level: 'Vloeiend' },
        ],
        interests: ['Homelabben', 'Mountainbiken', 'Domotica', 'Vrijwillig IT-beheer voetbalclub'],
        courses: [
            { name: 'ITIL 4 Foundation', institution: 'AXELOS', year: '2022' },
            { name: 'Microsoft Certified: Azure Administrator Associate', institution: 'Microsoft', year: '2023' },
        ],
        internships: [],
        awards: [],
    },
};
