import { CVExample } from '../../types';

export const systeembeheerder: CVExample = {
    slug: 'systeembeheerder',
    categorySlug: 'technologie-en-ict',
    name: 'Systeembeheerder',
    description: 'CV voorbeeld voor systeembeheerders. Laat Windows Server, Linux, Azure AD, VMware, backups, monitoring, patching en uptime concreet zien.',
    templateId: 'ats',
    colorThemeId: 'charcoal',

    metaTitle: 'CV Voorbeeld Systeembeheerder | Azure, VMware & AD | WerkCV.nl',
    metaDesc: 'Professioneel cv voorbeeld voor systeembeheerder met Windows Server, Linux, Azure AD, Microsoft 365, VMware, Veeam, monitoring en patchmanagement.',
    keywords: ['cv voorbeeld systeembeheerder', 'systeembeheerder cv', 'cv system administrator', 'cv infrastructuur', 'systeembeheer cv', 'netwerk beheerder cv', 'cv Azure AD', 'cv VMware'],
    heroTitle: 'CV Voorbeeld Systeembeheerder',
    heroText: 'Als systeembeheerder zorg je ervoor dat de IT-infrastructuur betrouwbaar, veilig en herstelbaar draait. Dit CV voorbeeld laat zien hoe je Windows Server, Active Directory, Azure AD, VMware, Veeam, monitoring, patchmanagement, incidenten en uptime resultaatgericht presenteert.',
    tips: [
        'Vermeld specifieke systemen en platforms: Windows Server, Linux, VMware, Azure AD, Microsoft 365 en Intune',
        'Benoem je uptime-resultaten en SLA-prestaties als meetbare resultaten',
        'Toon certificeringen prominent: Azure Administrator, ITIL, CCNA, CompTIA of security-trainingen',
        'Beschrijf monitoring, backup, disaster recovery, RTO/RPO, patchmanagement en incidentafhandeling concreet',
        'Laat zien met welke ITSM- en monitoringtools je werkt, zoals TOPdesk, ServiceNow, PRTG, Zabbix of SolarWinds',
    ],
    relatedSlugs: ['technologie-en-ict/ict-medewerker', 'technologie-en-ict/cybersecurity-specialist', 'technologie-en-ict/ict-projectleider'],

    sampleCV: {
        personal: {
            name: 'Mark Jansen',
            title: 'Systeembeheerder',
            email: 'mark.jansen@email.nl',
            phone: '06-45678901',
            location: 'Rotterdam',
            address: 'Westersingel 56',
            postalCode: '3014 GS',
            summary: 'Ervaren systeembeheerder met 8 jaar ervaring in Windows Server, Linux, Active Directory, Azure AD, Microsoft 365, VMware en Veeam. Sterk in monitoring, patchmanagement, incidentoplossing, backup en disaster recovery. ITIL-gecertificeerd met bewezen ervaring in 99,9%+ uptime, security hardening en ondersteuning van kritieke zorg- en klantomgevingen.',
            birthDate: '23 september 1990',
            birthPlace: 'Dordrecht',
            nationality: 'Nederlands',
            driversLicense: 'B',
            gender: '',
            maritalStatus: '',
            linkedIn: 'linkedin.com/in/markjansen',
            github: '',
            website: '',
            photo: '',
        },
        experience: [
            {
                role: 'Senior Systeembeheerder',
                company: 'Erasmus MC',
                location: 'Rotterdam',
                start: 'mei 2020',
                end: 'heden',
                description: 'Verantwoordelijk voor het beheer van de IT-infrastructuur van het grootste universitair medisch centrum van Nederland.',
                highlights: [
                    'Serverpark van 200+ Windows- en Linux-servers beheerd met een uptime van 99,95%',
                    'Migratie naar hybride cloud-omgeving (Azure) geleid, waardoor infrastructuurkosten met 30% daalden',
                    'Geautomatiseerd patchmanagement geïmplementeerd met WSUS en Ansible, waardoor handmatig werk met 80% afnam',
                    'Active Directory, Azure AD en Microsoft 365-beheer gestandaardiseerd voor gebruikers, groepen en toegangsrechten',
                ],
            },
            {
                role: 'Systeembeheerder',
                company: 'Simac ICT',
                location: 'Veldhoven',
                start: 'maart 2016',
                end: 'april 2020',
                description: 'Beheer van IT-infrastructuur voor diverse klanten in de regio als onderdeel van een managed services team.',
                highlights: [
                    'VMware vSphere-omgevingen beheerd voor 15+ klanten met in totaal 500+ virtuele machines',
                    'Backup- en disaster recovery-oplossingen geïmplementeerd met Veeam, waardoor hersteltijd van 8 naar 2 uur daalde',
                    'Incidenten afgehandeld via TOPdesk en SLA-rapportages gebruikt om terugkerende storingen te prioriteren',
                    'Netwerkomgeving geoptimaliseerd met Cisco-switches, VLANs, DNS, DHCP en firewalls voor betere beveiliging',
                ],
            },
        ],
        education: [
            {
                degree: 'HBO Informatica',
                school: 'Hogeschool Rotterdam',
                location: 'Rotterdam',
                start: 'september 2010',
                end: 'juli 2014',
                description: 'Specialisatie Infrastructuur & Netwerken. Afstudeerproject over het ontwerpen van een high-availability serveromgeving.',
            },
        ],
        skills: [
            { name: 'Windows Server / Active Directory', level: 5 },
            { name: 'Linux (Ubuntu, CentOS)', level: 4 },
            { name: 'VMware vSphere / Hyper-V', level: 5 },
            { name: 'Azure / Microsoft 365', level: 4 },
            { name: 'Veeam backup & DR', level: 4 },
            { name: 'PowerShell / Ansible', level: 4 },
        ],
        languages: [
            { name: 'Nederlands', level: 'Moedertaal' },
            { name: 'Engels', level: 'Vloeiend' },
        ],
        interests: ['Homelabben', 'Mountainbiken', 'Domotica', 'Vrijwillig IT-beheer voetbalclub'],
        courses: [
            { name: 'ITIL 4 Foundation', institution: 'AXELOS', year: '2022' },
            { name: 'Microsoft Certified: Azure Administrator Associate', institution: 'Microsoft', year: '2023' },
            { name: 'Veeam Backup & Replication', institution: 'Veeam University', year: '2021' },
        ],
        internships: [],
        awards: [],
    },
};
