import { CVExample } from '../../types';

export const technischeDienst: CVExample = {
    slug: 'technische-dienst',
    categorySlug: 'technologie-en-ict',
    name: 'Technische Dienst',
    description: 'CV voorbeeld voor medewerkers technische dienst. Laat zien hoe je je ervaring met technisch onderhoud, storingsbeheer en facility management presenteert.',
    templateId: 'simple',
    colorThemeId: 'charcoal',

    metaTitle: 'CV Voorbeeld Technische Dienst | WerkCV.nl',
    metaDesc: 'Professioneel CV voorbeeld voor medewerkers technische dienst. Met voorbeeldteksten voor technisch onderhoud, facility management en storingsoplossing. Maak direct je eigen CV.',
    keywords: ['cv voorbeeld technische dienst', 'cv technisch medewerker', 'cv facility management', 'technische dienst cv', 'onderhoudsmonteur cv'],
    heroTitle: 'CV Voorbeeld Technische Dienst',
    heroText: 'Als medewerker technische dienst ben je verantwoordelijk voor het draaiende houden van gebouwen, installaties en apparatuur. Dit CV voorbeeld laat zien hoe je je praktische technische vaardigheden, certificeringen en probleemoplossend vermogen overtuigend presenteert aan werkgevers.',
    tips: [
        'Benoem je specifieke technische kennis: elektrotechniek, werktuigbouw, klimaattechniek, gebouwbeheer',
        'Vermeld relevante certificeringen: VCA, NEN 3140, F-gassen, BHV',
        'Beschrijf je ervaring met preventief en correctief onderhoud en geef voorbeelden',
        'Toon je vermogen om snel en effectief storingen op te lossen onder druk',
        'Laat zien dat je kunt werken met onderhoudsmanagementsystemen (CMMS) en planningssoftware',
    ],
    relatedSlugs: ['technologie-en-ict/systeembeheerder', 'technologie-en-ict/ict-projectleider'],

    sampleCV: {
        personal: {
            name: 'Henk Willems',
            title: 'Medewerker Technische Dienst',
            email: 'henk.willems@email.nl',
            phone: '06-78901234',
            location: 'Breda',
            address: 'Ginnekenweg 85',
            postalCode: '4835 NA',
            summary: 'Allround medewerker technische dienst met 12 jaar ervaring in het onderhouden en beheren van technische installaties in grote gebouwen. Ervaren in elektrotechniek, klimaattechniek en werktuigbouwkunde met een sterke focus op preventief onderhoud en het minimaliseren van stilstandtijden. VCA- en NEN 3140-gecertificeerd, met een hands-on mentaliteit en oog voor veiligheid.',
            birthDate: '14 augustus 1985',
            birthPlace: 'Tilburg',
            nationality: 'Nederlands',
            driversLicense: 'B, BE',
            gender: '',
            maritalStatus: '',
            linkedIn: 'linkedin.com/in/henkwillems',
            github: '',
            website: '',
            photo: '',
        },
        experience: [
            {
                role: 'Senior Medewerker Technische Dienst',
                company: 'Amphia Ziekenhuis',
                location: 'Breda',
                start: 'juni 2018',
                end: 'heden',
                description: 'Verantwoordelijk voor het technisch beheer en onderhoud van het ziekenhuiscomplex, inclusief alle elektrische, mechanische en klimaatinstallaties.',
                highlights: [
                    'Preventief onderhoudsplan opgezet voor 300+ installaties, waardoor ongeplande storingen met 45% afnamen',
                    'Coördinatie van externe aannemers bij renovatieprojecten ter waarde van \u20AC2 miljoen',
                    'Energiebesparingsproject geleid dat resulteerde in 20% lager energieverbruik door optimalisatie van klimaatinstallaties',
                ],
            },
            {
                role: 'Medewerker Technische Dienst',
                company: 'Universiteit van Tilburg',
                location: 'Tilburg',
                start: 'maart 2012',
                end: 'mei 2018',
                description: 'Allround technisch onderhoud van onderwijsgebouwen, laboratoria en kantoorruimtes op de universiteitscampus.',
                highlights: [
                    'Dagelijks onderhoud uitgevoerd aan elektrische installaties, verlichting, sanitair en HVAC-systemen',
                    'Storingsdienst gedraaid en binnen 95% van de gevallen storingen binnen 2 uur opgelost',
                    'Onderhoudsmanagementsysteem (Planon) geïmplementeerd voor het bijhouden van werkorders en planningen',
                ],
            },
        ],
        education: [
            {
                degree: 'MBO 4 Middenkaderfunctionaris Elektrotechniek',
                school: 'ROC Tilburg',
                location: 'Tilburg',
                start: 'september 2003',
                end: 'juli 2007',
                description: 'Opleiding in elektrotechnische installaties, industriële automatisering en gebouwbeheer.',
            },
        ],
        skills: [
            { name: 'Elektrotechniek (NEN 3140)', level: 5 },
            { name: 'Klimaattechniek / HVAC', level: 4 },
            { name: 'Werktuigbouwkundig onderhoud', level: 4 },
            { name: 'Gebouwbeheersystemen (GBS)', level: 4 },
            { name: 'Storingsanalyse & -oplossing', level: 5 },
            { name: 'Planon / CMMS', level: 3 },
        ],
        languages: [
            { name: 'Nederlands', level: 'Moedertaal' },
            { name: 'Engels', level: 'Goed' },
        ],
        interests: ['Klussen', 'Elektronica', 'Vissen', 'Voetbal'],
        courses: [
            { name: 'VCA Vol (Veiligheid, Gezondheid en Milieu)', institution: 'PBNA', year: '2024' },
            { name: 'NEN 3140 - Veilig werken aan elektrische installaties', institution: 'Opleidingsinstituut Thomas', year: '2023' },
        ],
        internships: [],
        awards: [],
    },
};
