export const proposalMistakes = [
  {
    title: "1. Opgeblazen verantwoordelijkheid",
    claim: "Nina leidde zelfstandig de volledige HR-transformatie.",
    source: "CV · sectie Profiel: ‘Senior HR-adviseur met zeven jaar ervaring in verzuimbegeleiding, organisatieverandering en HR-advies.’",
    why: "De bron noemt ervaring en advies, maar geen leiding over een volledige transformatie.",
    correction: "Nina heeft zeven jaar HR-ervaring in verzuimbegeleiding, organisatieverandering en HR-advies.",
    action: "Beperken tot de bron; vraag de scope van verantwoordelijkheid na.",
  },
  {
    title: "2. Verkeerde werkgever aan een resultaat koppelen",
    claim: "Bij Middenland Services adviseerde Nina 24 teamleiders.",
    source: "CV · sectie Werkervaring · HR-adviseur: ‘Adviseerde 24 teamleiders over verzuim, ontwikkeling en arbeidsvoorwaarden.’ In de volledige CV-werkervaring staat dit resultaat bij Fictieve Zorgdiensten, niet bij Middenland Services.",
    why: "Een bronpassage mag niet stilzwijgend aan een andere werkgever worden toegeschreven.",
    correction: "Bij Fictieve Zorgdiensten adviseerde Nina 24 teamleiders over verzuim, ontwikkeling en arbeidsvoorwaarden.",
    action: "Controleer de werkgever en vermeld hem pas wanneer de bron dit ondersteunt.",
  },
  {
    title: "3. Verkeerde datum of duur",
    claim: "Nina werkt al tien jaar als HR-adviseur.",
    source: "CV · sectie Profiel: ‘zeven jaar ervaring’.",
    why: "Tien jaar wijkt af van de bron; afronden of optellen zonder definitie maakt de duur oncontroleerbaar.",
    correction: "Het CV noemt zeven jaar HR-ervaring.",
    action: "Corrigeer de duur of leg vast welke periode en rol precies wordt bedoeld.",
  },
  {
    title: "4. Onbewezen systeemexpertise",
    claim: "Nina configureert zelfstandig AFAS-workflows.",
    source: "CV · sectie Vaardigheden: ‘HR-systemen: personeelsadministratie, verzuimregistratie en rapportage.’ AFAS wordt niet genoemd.",
    why: "Algemene systeemervaring is geen bewijs voor een specifieke applicatie of configuratietaak.",
    correction: "AFAS-workflowconfiguratie is niet aangetoond in het CV.",
    action: "Verwijder de claim of vraag de specifieke ervaring na.",
  },
  {
    title: "5. Verzonnen numerieke scope",
    claim: "Nina adviseerde 40 teamleiders.",
    source: "CV · sectie Werkervaring: ‘Adviseerde 24 teamleiders …’.",
    why: "Het getal 40 kan niet worden afgeleid uit de bron en verandert de indruk van de ervaring.",
    correction: "Adviseerde 24 teamleiders over verzuim, ontwikkeling en arbeidsvoorwaarden.",
    action: "Gebruik het brongetal en controleer dat het op dezelfde populatie en periode slaat.",
  },
  {
    title: "6. Veranderlijke informatie als vaststaand feit",
    claim: "Nina is vanaf 1 oktober beschikbaar voor 32–36 uur.",
    source: "Geen passende passage in het CV. 1 oktober en 32–36 uur staan in de fictieve vacature.",
    why: "Vacaturevoorwaarden bewijzen geen beschikbaarheid of werkweek van de kandidaat.",
    correction: "Startdatum en uren: nog te bevestigen.",
    action: "Vraag de kandidaat na en label de bevestiging apart van CV-bewijs.",
  },
  {
    title: "7. Te stellige samenvatting",
    claim: "Nina past perfect bij deze functie en beheerst alle gevraagde systemen.",
    source: "De bron ondersteunt HR-ervaring en advies aan 24 teamleiders, maar noemt AFAS en Power BI niet.",
    why: "‘Perfect’ en ‘alle’ verbergen open punten en maken geen onderscheid tussen bewijs en oordeel.",
    correction: "Nina heeft zeven jaar HR-ervaring en adviseerde volgens haar CV 24 teamleiders. AFAS, Power BI en haar startdatum worden nog bevestigd.",
    action: "Schrijf een brongebonden samenvatting en laat resterende onzekerheid zichtbaar.",
  },
] as const;
