import { CVExample } from '../../types';

export const apotheekassistent: CVExample = {
    slug: 'apotheekassistent',
    categorySlug: 'zorg-en-welzijn',
    name: 'Apotheekassistent',
    description: 'CV voorbeeld voor apotheekassistenten. Presenteer je farmaceutische kennis, medicatiebegeleiding en ervaring in de openbare of ziekenhuisapotheek.',
    templateId: 'formal',
    colorThemeId: 'classic-blue',

    metaTitle: 'CV Voorbeeld Apotheekassistent | WerkCV.nl',
    metaDesc: 'Professioneel CV voorbeeld voor apotheekassistenten. Met voorbeeldteksten voor medicatiekennis, receptverwerking en patiëntvoorlichting. Direct te gebruiken.',
    keywords: ['cv voorbeeld apotheekassistent', 'apotheekassistent cv', 'cv apotheek', 'cv farmaceutisch', 'apotheek cv maken'],
    heroTitle: 'CV Voorbeeld Apotheekassistent',
    heroText: 'Als apotheekassistent ben je de schakel tussen patiënt en medicatie. Dit CV voorbeeld laat zien hoe je je farmaceutische kennis, ervaring met receptverwerking en vaardigheden in medicatiebegeleiding professioneel presenteert aan apotheken.',
    tips: [
        'Vermeld je diploma Apotheekassistent en eventuele BIG-registratie',
        'Benoem ervaring met apotheeksystemen zoals Pharmacom, Eureka of Zavin',
        'Beschrijf je rol bij medicatiebewaking, interactiecontroles en eerste uitgifte',
        'Voeg relevante nascholingen toe zoals farmacotherapie of zelfzorgadvisering',
        'Laat je communicatieve vaardigheden zien: voorlichting aan patiënten, overleg met huisartsen',
    ],
    relatedSlugs: ['zorg-en-welzijn/verpleegkundige', 'zorg-en-welzijn/opticien'],

    sampleCV: {
        personal: {
            name: 'Anne Kuijpers',
            title: 'Apotheekassistent',
            email: 'anne.kuijpers@email.nl',
            phone: '06-67890123',
            location: 'Eindhoven',
            address: 'Stratumseind 31',
            postalCode: '5611 EN',
            summary: 'Nauwkeurige en servicegerichte apotheekassistent met 7 jaar ervaring in de openbare apotheek. Gespecialiseerd in medicatiebegeleiding, receptverwerking en patiëntvoorlichting. Ervaren met het apotheeksysteem Pharmacom en bekwaam in farmacotherapeutisch overleg met huisartsen. Altijd gericht op veilige en patiëntvriendelijke zorg.',
            birthDate: '19 april 1993',
            birthPlace: 'Helmond',
            nationality: 'Nederlands',
            driversLicense: 'B',
            gender: '',
            maritalStatus: '',
            linkedIn: 'linkedin.com/in/annekuijpers',
            github: '',
            website: '',
            photo: '',
        },
        experience: [
            {
                role: 'Apotheekassistent',
                company: 'Apotheek De Geldropseweg',
                location: 'Eindhoven',
                start: 'augustus 2020',
                end: 'heden',
                description: 'Apotheekassistent in een drukke openbare apotheek met circa 12.000 patiënten.',
                highlights: [
                    'Dagelijks 150+ recepten verwerkt en gecontroleerd op interacties en contra-indicaties',
                    'Eerste-uitgifte-begeleiding en medicatiereviews uitgevoerd bij polyfarmaciepatiënten',
                    'Farmacotherapeutisch overleg gevoerd met huisartsen over medicatieaanpassingen',
                    'Nieuwe medewerkers en stagiaires ingewerkt en begeleid',
                ],
            },
            {
                role: 'Apotheekassistent',
                company: 'Service Apotheek Helmond',
                location: 'Helmond',
                start: 'juli 2017',
                end: 'juli 2020',
                description: 'Apotheekassistent in een apotheek met focus op zelfzorg en patiëntgerichte farmaceutische zorg.',
                highlights: [
                    'Zelfzorgadvisering en triage uitgevoerd bij balieklanten',
                    'Weekvoorraad en medicijnbeheer voor 3 zorginstellingen gecoördineerd',
                    'Bijgedragen aan het behalen van het KNMP-keurmerk door procesverbetering',
                ],
            },
        ],
        education: [
            {
                degree: 'MBO Apotheekassistent (niveau 4)',
                school: 'Summa College',
                location: 'Eindhoven',
                start: 'september 2013',
                end: 'juli 2017',
                description: 'Stages bij Service Apotheek Helmond en Apotheek Catharina Ziekenhuis.',
            },
            {
                degree: 'HAVO Profiel Natuur & Gezondheid',
                school: 'Valuascollege',
                location: 'Venlo',
                start: 'september 2008',
                end: 'juni 2013',
                description: '',
            },
        ],
        skills: [
            { name: 'Receptverwerking & medicatiebewaking', level: 5 },
            { name: 'Pharmacom (apotheeksysteem)', level: 5 },
            { name: 'Patiëntvoorlichting & zelfzorg', level: 4 },
            { name: 'Farmacotherapeutisch overleg', level: 4 },
            { name: 'Voorraadbeheer & logistiek', level: 4 },
            { name: 'Nauwkeurig & zorgvuldig werken', level: 5 },
        ],
        languages: [
            { name: 'Nederlands', level: 'Moedertaal' },
            { name: 'Engels', level: 'Goed' },
            { name: 'Duits', level: 'Basis' },
        ],
        interests: ['Tuinieren', 'Bakken', 'Lezen'],
        courses: [
            { name: 'Nascholing Farmacotherapie bij Ouderen', institution: 'KNMP Academie', year: '2024' },
            { name: 'Cursus Inhalatie-instructie', institution: 'Long Alliantie Nederland', year: '2023' },
        ],
        internships: [],
        awards: [],
    },
};
