import { CVExample } from '../../types';

export const artsAnios: CVExample = {
    slug: 'arts-anios',
    categorySlug: 'zorg-en-welzijn',
    name: 'Arts (ANIOS)',
    description: 'CV voorbeeld voor recent afgestudeerde artsen op zoek naar een ANIOS-positie. Presenteer je coschappen en medische vaardigheden overtuigend.',
    templateId: 'classical',
    colorThemeId: 'elegant-navy',

    metaTitle: 'CV Voorbeeld Arts ANIOS | WerkCV.nl',
    metaDesc: 'Professioneel CV voorbeeld voor artsen en ANIOS. Met voorbeeldteksten voor coschappen, BIG-registratie en medische ervaring. Direct te gebruiken als template.',
    keywords: ['cv voorbeeld arts', 'cv anios', 'arts cv maken', 'cv basisarts', 'cv coschappen', 'medisch cv'],
    heroTitle: 'CV Voorbeeld Arts (ANIOS)',
    heroText: 'Als recent afgestudeerde basisarts wil je opvallen bij ziekenhuizen en klinieken. Dit CV voorbeeld laat zien hoe je je coschappen, wetenschappelijke ervaring en BIG-registratie professioneel presenteert voor een ANIOS-positie.',
    tips: [
        'Vermeld je BIG-registratie als arts prominent bovenaan je CV',
        'Beschrijf je coschappen met concrete leermomenten en verantwoordelijkheden',
        'Benoem wetenschappelijk onderzoek, publicaties of presentaties',
        'Geef aan welke specialisatie je ambieert en waarom',
        'Voeg relevante cursussen toe zoals ATLS, ALS of echografie',
    ],
    relatedSlugs: ['zorg-en-welzijn/verpleegkundige', 'zorg-en-welzijn/ggz-medewerker'],

    sampleCV: {
        personal: {
            name: 'Daan Vermeulen',
            title: 'Basisarts (BIG-geregistreerd)',
            email: 'daan.vermeulen@email.nl',
            phone: '06-45678901',
            location: 'Leiden',
            address: 'Rapenburg 56',
            postalCode: '2311 EZ',
            summary: 'Gemotiveerde basisarts, recent afgestudeerd aan de Universiteit Leiden, op zoek naar een ANIOS-positie in de interne geneeskunde. Brede klinische ervaring opgedaan tijdens coschappen in academische en perifere ziekenhuizen. Bijzondere interesse in acute interne geneeskunde en wetenschappelijk onderzoek.',
            birthDate: '3 juli 1997',
            birthPlace: 'Delft',
            nationality: 'Nederlands',
            driversLicense: 'B',
            gender: '',
            maritalStatus: '',
            linkedIn: 'linkedin.com/in/daanvermeulen-md',
            github: '',
            website: '',
            photo: '',
        },
        experience: [
            {
                role: 'ANIOS Spoedeisende Hulp',
                company: 'Haaglanden Medisch Centrum',
                location: 'Den Haag',
                start: 'januari 2025',
                end: 'heden',
                description: 'Arts niet in opleiding tot specialist op de afdeling Spoedeisende Hulp.',
                highlights: [
                    'Zelfstandig beoordelen en behandelen van patiënten op de SEH',
                    'Deelname aan traumaopvang en reanimatiebehandelingen',
                    'Supervisie van coassistenten en verpleegkundig personeel bij medische handelingen',
                    'Overleg met specialisten en huisartsen over verwijzingen en ontslagbeleid',
                ],
            },
            {
                role: 'Onderzoeksstagiair Interne Geneeskunde',
                company: 'Leids Universitair Medisch Centrum (LUMC)',
                location: 'Leiden',
                start: 'januari 2024',
                end: 'augustus 2024',
                description: 'Wetenschappelijk onderzoek naar biomarkers bij sepsis op de afdeling Interne Geneeskunde.',
                highlights: [
                    'Klinische data verzameld en geanalyseerd van 200+ patiënten',
                    'Resultaten gepresenteerd op de Nederlandse Internistendagen 2024',
                    'Wetenschappelijk artikel ingediend bij Netherlands Journal of Medicine',
                ],
            },
        ],
        education: [
            {
                degree: 'Geneeskunde (MSc)',
                school: 'Universiteit Leiden',
                location: 'Leiden',
                start: 'september 2017',
                end: 'december 2024',
                description: 'Coschappen in LUMC, Haaglanden MC en Alrijne Ziekenhuis. Semi-arts stage op de afdeling Interne Geneeskunde (LUMC). Cum laude afgestudeerd.',
            },
            {
                degree: 'VWO Profiel Natuur & Gezondheid + Natuur & Techniek',
                school: 'Gymnasium Novum',
                location: 'Voorburg',
                start: 'september 2011',
                end: 'juni 2017',
                description: 'Cum laude geslaagd.',
            },
        ],
        skills: [
            { name: 'Klinisch redeneren', level: 4 },
            { name: 'Acute geneeskunde & SEH', level: 4 },
            { name: 'Wetenschappelijk onderzoek', level: 4 },
            { name: 'Medische verslaglegging (EPD/HiX)', level: 4 },
            { name: 'Patiëntcommunicatie', level: 5 },
            { name: 'Samenwerken in medisch team', level: 5 },
        ],
        languages: [
            { name: 'Nederlands', level: 'Moedertaal' },
            { name: 'Engels', level: 'Vloeiend' },
            { name: 'Frans', level: 'Basis' },
        ],
        interests: ['Wielrennen', 'Medische podcasts', 'Schaken'],
        courses: [
            { name: 'Advanced Trauma Life Support (ATLS)', institution: 'ATLS Nederland', year: '2025' },
            { name: 'Advanced Life Support (ALS)', institution: 'Nederlandse Reanimatie Raad', year: '2024' },
        ],
        internships: [],
        awards: [],
    },
};
