import { CVExample } from '../../types';

export const ggzMedewerker: CVExample = {
    slug: 'ggz-medewerker',
    categorySlug: 'zorg-en-welzijn',
    name: 'GGZ Medewerker',
    description: 'CV voorbeeld voor GGZ-professionals zoals psychologen en GGZ-agogen. Laat zien hoe je behandelervaring en therapeutische vaardigheden presenteert.',
    templateId: 'professional',
    colorThemeId: 'sage-green',

    metaTitle: 'CV Voorbeeld GGZ Medewerker | WerkCV.nl',
    metaDesc: 'Professioneel CV voorbeeld voor GGZ-medewerkers, psychologen en agogen. Met voorbeeldteksten voor behandelervaring en therapeutische vaardigheden. Direct te gebruiken.',
    keywords: ['cv voorbeeld ggz', 'cv psycholoog', 'ggz medewerker cv', 'cv ggz agoog', 'cv geestelijke gezondheidszorg'],
    heroTitle: 'CV Voorbeeld GGZ Medewerker',
    heroText: 'Werken in de geestelijke gezondheidszorg vraagt om specialistische kennis en sterke interpersoonlijke vaardigheden. Dit CV voorbeeld laat zien hoe je als GGZ-psycholoog of agoog je behandelervaring, diagnostische vaardigheden en therapeutische competenties professioneel presenteert.',
    tips: [
        'Vermeld je BIG-registratie of SKJ-registratie en relevante specialisaties',
        'Benoem specifieke behandelmethoden die je beheerst (CGT, EMDR, schematherapie)',
        'Beschrijf de doelgroepen waarmee je hebt gewerkt (angst, depressie, persoonlijkheidsproblematiek)',
        'Voeg relevante intervisie- en supervisie-ervaring toe',
        'Toon je ervaring met multidisciplinaire samenwerking en ROM-metingen',
    ],
    relatedSlugs: ['zorg-en-welzijn/verpleegkundige', 'zorg-en-welzijn/arts-anios'],

    sampleCV: {
        personal: {
            name: 'Marieke Jansen',
            title: 'GZ-Psycholoog (BIG-geregistreerd)',
            email: 'marieke.jansen@email.nl',
            phone: '06-56789012',
            location: 'Utrecht',
            address: 'Oudegracht 122',
            postalCode: '3511 AX',
            summary: 'BIG-geregistreerd GZ-psycholoog met 6 jaar ervaring in de ambulante en klinische GGZ. Gespecialiseerd in de behandeling van angst- en stemmingsstoornissen bij volwassenen. Ervaren in cognitieve gedragstherapie, EMDR en groepsbehandelingen. Betrokken bij het opleiden van basispsychologen en het ontwikkelen van behandelprotocollen.',
            birthDate: '25 september 1990',
            birthPlace: 'Amersfoort',
            nationality: 'Nederlands',
            driversLicense: 'B',
            gender: '',
            maritalStatus: '',
            linkedIn: 'linkedin.com/in/mariekejansen-psy',
            github: '',
            website: '',
            photo: '',
        },
        experience: [
            {
                role: 'GZ-Psycholoog',
                company: 'Altrecht GGZ',
                location: 'Utrecht',
                start: 'mei 2021',
                end: 'heden',
                description: 'Behandelend psycholoog binnen het team Angst en Stemming, ambulante volwassenen-GGZ.',
                highlights: [
                    'Diagnostiek en behandeling van complexe angst- en stemmingsstoornissen (caseload 45 cliënten)',
                    'Individuele en groepsbehandelingen uitgevoerd met CGT, EMDR en gedragsactivatie',
                    'ROM-metingen geanalyseerd om behandeleffectiviteit te monitoren',
                    'Werkbegeleiding en supervisie gegeven aan 3 basispsychologen in opleiding',
                ],
            },
            {
                role: 'Basispsycholoog',
                company: 'GGZ Centraal',
                location: 'Amersfoort',
                start: 'september 2018',
                end: 'april 2021',
                description: 'Basispsycholoog op de afdeling volwassenenpsychiatrie, klinische opnames.',
                highlights: [
                    'Psychodiagnostisch onderzoek uitgevoerd bij patiënten met persoonlijkheidsproblematiek',
                    'Behandelplannen opgesteld in multidisciplinair overleg met psychiaters en verpleegkundigen',
                    'Crisisinterventies uitgevoerd en risicotaxaties opgesteld',
                ],
            },
        ],
        education: [
            {
                degree: 'GZ-opleiding (postmaster)',
                school: 'RINO Groep',
                location: 'Utrecht',
                start: 'september 2019',
                end: 'september 2021',
                description: 'Postmasteropleding tot Gezondheidszorgpsycholoog. Praktijkopleiding bij Altrecht GGZ.',
            },
            {
                degree: 'MSc Klinische Psychologie',
                school: 'Universiteit Utrecht',
                location: 'Utrecht',
                start: 'september 2016',
                end: 'augustus 2018',
                description: 'Klinische stage bij GGZ Centraal. Masterscriptie over werkzame factoren in CGT bij depressie.',
            },
        ],
        skills: [
            { name: 'Cognitieve gedragstherapie (CGT)', level: 5 },
            { name: 'EMDR', level: 4 },
            { name: 'Psychodiagnostiek', level: 5 },
            { name: 'ROM & effectmeting', level: 4 },
            { name: 'Crisisinterventie', level: 4 },
            { name: 'Supervisie & werkbegeleiding', level: 4 },
        ],
        languages: [
            { name: 'Nederlands', level: 'Moedertaal' },
            { name: 'Engels', level: 'Vloeiend' },
        ],
        interests: ['Mindfulness', 'Lezen', 'Wandelen in de natuur'],
        courses: [
            { name: 'EMDR Practitioner', institution: 'EMDR Nederland', year: '2022' },
            { name: 'Schematherapie basis', institution: 'RINO Groep', year: '2023' },
        ],
        internships: [],
        awards: [],
    },
};
