import { CVExample } from '../../types';

export const opticien: CVExample = {
    slug: 'opticien',
    categorySlug: 'zorg-en-welzijn',
    name: 'Opticien',
    description: 'CV voorbeeld voor opticiens en optometristen. Presenteer je expertise in oogmetingen, brillen en contactlenzen op een professionele manier.',
    templateId: 'elegant',
    colorThemeId: 'elegant-navy',

    metaTitle: 'CV Voorbeeld Opticien | WerkCV.nl',
    metaDesc: 'Professioneel CV voorbeeld voor opticiens en optometristen. Met voorbeeldteksten voor oogzorgervaring, refractie en contactlensaanpassing. Direct te gebruiken.',
    keywords: ['cv voorbeeld opticien', 'opticien cv', 'cv optometrist', 'cv oogzorg', 'cv brillenspecialist'],
    heroTitle: 'CV Voorbeeld Opticien',
    heroText: 'Als opticien combineer je oogzorgkennis met klantgerichtheid en commercieel inzicht. Dit CV voorbeeld laat zien hoe je je ervaring met refracties, contactlensaanpassingen en brillenadvisering professioneel presenteert aan optiekzaken en oogzorgketens.',
    tips: [
        'Vermeld je diploma Opticien of Optometrie en eventuele OVN-registratie',
        'Benoem je ervaring met oogmetingen, refracties en contactlensaanpassingen',
        'Beschrijf commerciële resultaten: omzetgroei, klanttevredenheid, verkoopadvies',
        'Voeg relevante bijscholingen toe zoals contactlens-specialisatie of screening',
        'Toon je combinatie van zorgvaardigheid en verkooptalent',
    ],
    relatedSlugs: ['zorg-en-welzijn/apotheekassistent', 'zorg-en-welzijn/verpleegkundige'],

    sampleCV: {
        personal: {
            name: 'Jasper van Doorn',
            title: 'Opticien / Optometrist',
            email: 'jasper.vandoorn@email.nl',
            phone: '06-78901234',
            location: 'Groningen',
            address: 'Herestraat 45',
            postalCode: '9711 LD',
            summary: 'Vakbekwaam opticien en optometrist met 6 jaar ervaring in de optiekbranche. Gespecialiseerd in refracties, contactlensaanpassingen en het adviseren van klanten over brillen en oogzorg. Commercieel sterk met oog voor kwaliteit en klanttevredenheid. Zoekt een uitdagende functie waar oogzorg en klantenservice samenkomen.',
            birthDate: '14 januari 1994',
            birthPlace: 'Assen',
            nationality: 'Nederlands',
            driversLicense: 'B',
            gender: '',
            maritalStatus: '',
            linkedIn: 'linkedin.com/in/jaspervandoorn-optiek',
            github: '',
            website: '',
            photo: '',
        },
        experience: [
            {
                role: 'Opticien / Optometrist',
                company: 'Pearle Opticiens',
                location: 'Groningen',
                start: 'juni 2021',
                end: 'heden',
                description: 'Opticien in een drukbezochte vestiging in het centrum van Groningen.',
                highlights: [
                    'Gemiddeld 15 refracties en oogmetingen per week uitgevoerd',
                    'Contactlensaanpassingen inclusief multifocale en torische lenzen',
                    'Filiaatomzet met 12% verhoogd door actief klantenadvies en upselling',
                    'Screeningsmetingen verricht (oogdruk, gezichtsveld, OCT) en doorverwijzingen naar oogartsen',
                ],
            },
            {
                role: 'Assistent-opticien',
                company: 'Eye Wish Opticiens',
                location: 'Assen',
                start: 'september 2018',
                end: 'mei 2021',
                description: 'Opticien in opleiding, later zelfstandig werkend als gediplomeerd opticien.',
                highlights: [
                    'Klanten geadviseerd bij montuur- en glaskeuze passend bij leefstijl en sterkte',
                    'Brillen technisch afgewerkt: slijpen, monteren en aanpassen',
                    'Voorraad- en bestellingenbeheer van monturen en contactlenzen',
                ],
            },
        ],
        education: [
            {
                degree: 'HBO Optometrie',
                school: 'Hogeschool Utrecht',
                location: 'Utrecht',
                start: 'september 2014',
                end: 'juli 2018',
                description: 'Afstudeerstage bij Oogziekenhuis Rotterdam. Specialisatieproject: screening van glaucoom in de optiekpraktijk.',
            },
            {
                degree: 'HAVO Profiel Natuur & Gezondheid',
                school: 'Nassau College',
                location: 'Assen',
                start: 'september 2009',
                end: 'juni 2014',
                description: '',
            },
        ],
        skills: [
            { name: 'Refractie & oogmetingen', level: 5 },
            { name: 'Contactlensaanpassing', level: 4 },
            { name: 'Brillenadvisering & montage', level: 5 },
            { name: 'Oogheelkundige screening (OCT, tonometrie)', level: 4 },
            { name: 'Commercieel advies & verkoop', level: 4 },
            { name: 'Klantenservice', level: 5 },
        ],
        languages: [
            { name: 'Nederlands', level: 'Moedertaal' },
            { name: 'Engels', level: 'Goed' },
            { name: 'Duits', level: 'Basis' },
        ],
        interests: ['Fotografie', 'Tennissen', 'Technologie'],
        courses: [
            { name: 'Specialisatie Contactlenzen Gevorderd', institution: 'OVN Academie', year: '2023' },
            { name: 'Nascholing Oogheelkundige Screening', institution: 'Hogeschool Utrecht', year: '2024' },
        ],
        internships: [],
        awards: [],
    },
};
