import { CVExample } from '../../types';

export const verpleegkundige: CVExample = {
    slug: 'verpleegkundige',
    categorySlug: 'zorg-en-welzijn',
    name: 'Verpleegkundige',
    description: 'CV voorbeeld voor verpleegkundigen met BIG-registratie. Laat klinische vaardigheden, EPD, triage, zorgcoördinatie en patiëntenzorg concreet zien.',
    templateId: 'professional',
    colorThemeId: 'classic-blue',

    metaTitle: 'CV Voorbeeld Verpleegkundige | BIG, EPD & Zorg | WerkCV.nl',
    metaDesc: 'Professioneel cv voorbeeld voor verpleegkundige met BIG-registratie, EPD, triage, klinische vaardigheden, patiëntenzorg en multidisciplinair samenwerken.',
    keywords: ['cv voorbeeld verpleegkundige', 'verpleegkundige cv', 'cv zorg', 'verpleegkunde cv maken', 'BIG-registratie cv', 'cv HBO verpleegkundige', 'cv EPD', 'cv triage'],
    heroTitle: 'CV Voorbeeld Verpleegkundige',
    heroText: 'Als verpleegkundige combineer je klinische kennis met empathie, overzicht en verantwoordelijkheid. Dit CV voorbeeld laat zien hoe je BIG-registratie, EPD-ervaring, verpleegtechnische handelingen, triage, zorgcoördinatie en multidisciplinair samenwerken overtuigend presenteert.',
    tips: [
        'Vermeld altijd je BIG-registratie en registratienummer bovenaan je CV',
        'Benoem specifieke afdelingen en specialisaties waar je ervaring hebt: SEH, IC, interne, oncologie, thuiszorg of VVT',
        'Beschrijf concrete context: aantal patiënten per dienst, type zorgzwaarte, triage, protocollen of verbeterprojecten',
        'Voeg relevante bijscholing toe zoals ALS, BLS, wondzorg, medicatieveiligheid, palliatieve zorg of klinisch redeneren',
        'Noem EPD/ECD-systemen zoals Epic, HiX, ONS of Medimo als je daarmee werkt',
    ],
    relatedSlugs: ['zorg-en-welzijn/verzorgende-ig', 'zorg-en-welzijn/arts-anios', 'zorg-en-welzijn/ggz-medewerker'],

    sampleCV: {
        personal: {
            name: 'Linda de Vries',
            title: 'Verpleegkundige (BIG-geregistreerd)',
            email: 'linda.devries@email.nl',
            phone: '06-23456789',
            location: 'Amsterdam',
            address: 'Prinsengracht 214',
            postalCode: '1016 HE',
            summary: 'BIG-geregistreerd verpleegkundige met 8 jaar ervaring in klinische zorg, interne geneeskunde en SEH. Ervaren met Epic, triage, medicatieveiligheid, wondzorg, klinisch redeneren en zorgcoördinatie binnen multidisciplinaire teams. Sterk in patiëntvoorlichting, familiecommunicatie en het begeleiden van studenten en nieuwe collega\'s.',
            birthDate: '12 maart 1992',
            birthPlace: 'Haarlem',
            nationality: 'Nederlands',
            driversLicense: 'B',
            gender: '',
            maritalStatus: '',
            linkedIn: 'linkedin.com/in/lindadevries-vpk',
            github: '',
            website: '',
            photo: '',
        },
        experience: [
            {
                role: 'Verpleegkundige Afdeling Interne Geneeskunde',
                company: 'Amsterdam UMC',
                location: 'Amsterdam',
                start: 'maart 2019',
                end: 'heden',
                description: 'Verpleegkundige zorg op de afdeling interne geneeskunde in een academisch ziekenhuis.',
                highlights: [
                    'Verantwoordelijk voor dagelijkse zorg aan gemiddeld 8 patiënten per dienst',
                    'Zorgplannen gecoördineerd in Epic in samenwerking met artsen, fysiotherapeuten en diëtisten',
                    'Medicatie, infusen, wondzorg en klinische observaties uitgevoerd volgens protocol en overdracht',
                    'Nieuwe verpleegkundigen en studenten begeleid als werkbegeleider',
                    'Meegewerkt aan EPD-werkinstructies, waardoor overdracht en registratie op de afdeling eenduidiger werden',
                ],
            },
            {
                role: 'Verpleegkundige Spoedeisende Hulp',
                company: 'Spaarne Gasthuis',
                location: 'Haarlem',
                start: 'september 2016',
                end: 'februari 2019',
                description: 'Verpleegkundige op de SEH met focus op triage en acute zorgverlening.',
                highlights: [
                    'Triage uitgevoerd volgens het Manchester Triage Systeem',
                    'Zorg verleend bij trauma, cardiologische en neurologische spoedgevallen',
                    'Deelgenomen aan reanimatieteam en BLS/ALS-trainingen verzorgd voor collega\'s',
                    'Patiënten en familie geïnformeerd tijdens acute situaties met duidelijke, rustige communicatie',
                ],
            },
        ],
        education: [
            {
                degree: 'HBO-V Verpleegkunde',
                school: 'Hogeschool van Amsterdam',
                location: 'Amsterdam',
                start: 'september 2012',
                end: 'juli 2016',
                description: 'Afstudeerrichting: Acute Zorg. Stage gelopen in het VUmc en het Rode Kruis Ziekenhuis.',
            },
            {
                degree: 'HAVO Profiel Natuur & Gezondheid',
                school: 'Coornhert Lyceum',
                location: 'Haarlem',
                start: 'september 2007',
                end: 'juni 2012',
                description: '',
            },
        ],
        skills: [
            { name: 'Klinische verpleegkunde', level: 5 },
            { name: 'Triage & acute zorg', level: 4 },
            { name: 'Medicatietoediening', level: 5 },
            { name: 'Epic EPD', level: 4 },
            { name: 'Patiëntenvoorlichting', level: 4 },
            { name: 'Zorgcoördinatie', level: 5 },
        ],
        languages: [
            { name: 'Nederlands', level: 'Moedertaal' },
            { name: 'Engels', level: 'Goed' },
            { name: 'Duits', level: 'Basis' },
        ],
        interests: ['Hardlopen', 'Yoga', 'Medische vakliteratuur'],
        courses: [
            { name: 'Advanced Life Support (ALS)', institution: 'Nederlandse Reanimatie Raad', year: '2023' },
            { name: 'Cursus Wondverzorging', institution: 'V&VN', year: '2022' },
            { name: 'Klinisch redeneren', institution: 'Amsterdam UMC Academy', year: '2021' },
        ],
        internships: [],
        awards: [],
    },
};
