import { CVExample } from '../../types';

export const verpleegkundige: CVExample = {
    slug: 'verpleegkundige',
    categorySlug: 'zorg-en-welzijn',
    name: 'Verpleegkundige',
    description: 'CV voorbeeld voor verpleegkundigen met ziekenhuiservaring. Laat zien hoe je klinische vaardigheden en patiëntenzorg professioneel presenteert.',
    templateId: 'professional',
    colorThemeId: 'classic-blue',

    metaTitle: 'CV Voorbeeld Verpleegkundige | WerkCV.nl',
    metaDesc: 'Professioneel CV voorbeeld voor verpleegkundigen. Met voorbeeldteksten voor ziekenhuiservaring, BIG-registratie en klinische vaardigheden. Direct te gebruiken.',
    keywords: ['cv voorbeeld verpleegkundige', 'verpleegkundige cv', 'cv zorg', 'verpleegkunde cv maken', 'BIG-registratie cv'],
    heroTitle: 'CV Voorbeeld Verpleegkundige',
    heroText: 'Als verpleegkundige combineer je medische kennis met empathie en daadkracht. Dit CV voorbeeld laat zien hoe je je klinische ervaring, BIG-registratie en specialisaties overtuigend presenteert aan ziekenhuizen en zorginstellingen.',
    tips: [
        'Vermeld altijd je BIG-registratie en registratienummer bovenaan je CV',
        'Benoem specifieke afdelingen en specialisaties waar je ervaring hebt (IC, SEH, oncologie)',
        'Beschrijf concrete resultaten: aantal patiënten per dienst, verbeterprojecten, protocollen',
        'Voeg relevante bijscholingen en certificeringen toe zoals ACLS, BLS of wondverzorging',
        'Toon je soft skills: communicatie met patiënten en families, samenwerking in multidisciplinaire teams',
    ],
    relatedSlugs: ['zorg-en-welzijn/arts-anios', 'zorg-en-welzijn/ggz-medewerker'],

    sampleCV: {
        personal: {
            name: 'Linda de Vries',
            title: 'Verpleegkundige (BIG-geregistreerd)',
            email: 'linda.devries@email.nl',
            phone: '06-23456789',
            location: 'Amsterdam',
            address: 'Prinsengracht 214',
            postalCode: '1016 HE',
            summary: 'Ervaren en betrokken verpleegkundige met 8 jaar ervaring in de klinische zorg. Gespecialiseerd in interne geneeskunde en acute zorg. BIG-geregistreerd met ruime ervaring in het werken binnen multidisciplinaire teams. Gedreven om hoogwaardige patiëntenzorg te leveren en continu te blijven leren.',
            birthDate: '12 maart 1992',
            birthPlace: 'Haarlem',
            nationality: 'Nederlands',
            driversLicense: 'B',
            gender: '',
            maritalStatus: '',
            linkedIn: 'linkedin.com/in/lindadevries-vpk',
            github: '',
            website: '',
            photo: '',
        },
        experience: [
            {
                role: 'Verpleegkundige Afdeling Interne Geneeskunde',
                company: 'Amsterdam UMC',
                location: 'Amsterdam',
                start: 'maart 2019',
                end: 'heden',
                description: 'Verpleegkundige zorg op de afdeling interne geneeskunde in een academisch ziekenhuis.',
                highlights: [
                    'Verantwoordelijk voor dagelijkse zorg aan gemiddeld 8 patiënten per dienst',
                    'Coördinatie van zorgplannen in samenwerking met artsen, fysiotherapeuten en diëtisten',
                    'Nieuwe verpleegkundigen en studenten begeleid als werkbegeleider',
                    'Meegewerkt aan implementatie van het elektronisch patiëntendossier (EPD)',
                ],
            },
            {
                role: 'Verpleegkundige Spoedeisende Hulp',
                company: 'Spaarne Gasthuis',
                location: 'Haarlem',
                start: 'september 2016',
                end: 'februari 2019',
                description: 'Verpleegkundige op de SEH met focus op triage en acute zorgverlening.',
                highlights: [
                    'Triage uitgevoerd volgens het Manchester Triage Systeem',
                    'Zorg verleend bij trauma, cardiologische en neurologische spoedgevallen',
                    'Deelgenomen aan reanimatieteam en BLS/ALS-trainingen verzorgd voor collega\'s',
                ],
            },
        ],
        education: [
            {
                degree: 'HBO-V Verpleegkunde',
                school: 'Hogeschool van Amsterdam',
                location: 'Amsterdam',
                start: 'september 2012',
                end: 'juli 2016',
                description: 'Afstudeerrichting: Acute Zorg. Stage gelopen in het VUmc en het Rode Kruis Ziekenhuis.',
            },
            {
                degree: 'HAVO Profiel Natuur & Gezondheid',
                school: 'Coornhert Lyceum',
                location: 'Haarlem',
                start: 'september 2007',
                end: 'juni 2012',
                description: '',
            },
        ],
        skills: [
            { name: 'Klinische verpleegkunde', level: 5 },
            { name: 'Triage & acute zorg', level: 4 },
            { name: 'Medicatietoediening', level: 5 },
            { name: 'Elektronisch Patiëntendossier (EPD)', level: 4 },
            { name: 'Patiëntenvoorlichting', level: 4 },
            { name: 'Multidisciplinair samenwerken', level: 5 },
        ],
        languages: [
            { name: 'Nederlands', level: 'Moedertaal' },
            { name: 'Engels', level: 'Goed' },
            { name: 'Duits', level: 'Basis' },
        ],
        interests: ['Hardlopen', 'Yoga', 'Medische vakliteratuur'],
        courses: [
            { name: 'Advanced Life Support (ALS)', institution: 'Nederlandse Reanimatie Raad', year: '2023' },
            { name: 'Cursus Wondverzorging', institution: 'V&VN', year: '2022' },
        ],
        internships: [],
        awards: [],
    },
};
