import { CVExample } from '../../types';

export const verzorgendeIg: CVExample = {
    slug: 'verzorgende-ig',
    categorySlug: 'zorg-en-welzijn',
    name: 'Verzorgende IG',
    description: 'CV voorbeeld voor verzorgenden IG. Laat zien hoe je ADL, zorgleefplan, medicatie, rapportage en cliëntgerichte zorg professioneel presenteert.',
    templateId: 'professional',
    colorThemeId: 'classic-blue',

    metaTitle: 'CV Voorbeeld Verzorgende IG | WerkCV.nl',
    metaDesc: 'Professioneel cv voorbeeld voor Verzorgende IG niveau 3. Met profieltekst, werkervaring, ADL, zorgleefplan, medicatie, rapportage en zorgvaardigheden.',
    keywords: [
        'cv voorbeeld verzorgende ig',
        'verzorgende ig cv',
        'cv verzorgende individuele gezondheidszorg',
        'cv ouderenzorg',
        'cv thuiszorg',
        'cv vvt',
        'cv mbo 3 zorg',
    ],
    heroTitle: 'CV Voorbeeld Verzorgende IG',
    heroText: 'Een Verzorgende IG CV moet snel vertrouwen geven: je diploma, doelgroep, zorghandelingen, rapportage en samenwerking moeten direct zichtbaar zijn. Dit voorbeeld laat zien hoe je ADL, medicatie, zorgleefplannen, familiecontact en signaleren professioneel verwoordt.',
    tips: [
        'Vermeld duidelijk je diploma Verzorgende IG niveau 3 en relevante bijscholing zoals medicatie, wondzorg of tiltechnieken',
        'Benoem de setting: VVT, thuiszorg, verpleeghuis, somatiek, PG, revalidatie of gehandicaptenzorg',
        'Maak zorghandelingen concreet: ADL, medicatie delen, wondzorg, steunkousen, katheterzorg of bloedsuiker meten',
        'Laat zien dat je rapporteert en samenwerkt via zorgleefplan, familie, verpleegkundige en behandelaren',
        'Gebruik voorbeelden van signaleren, valpreventie, onbegrepen gedrag of verandering in gezondheid',
    ],
    relatedSlugs: [
        'zorg-en-welzijn/zorgmedewerker-helpende',
        'zorg-en-welzijn/verpleegkundige',
        'zorg-en-welzijn/ggz-medewerker',
    ],

    sampleCV: {
        personal: {
            name: 'Marieke van den Berg',
            title: 'Verzorgende IG',
            email: 'marieke.vandenberg@email.nl',
            phone: '06-45678901',
            location: 'Apeldoorn',
            address: 'Loolaan 73',
            postalCode: '7315 AB',
            summary: 'Verzorgende IG niveau 3 met 7 jaar ervaring in ouderenzorg, PG en thuiszorg. Ervaren in ADL-ondersteuning, medicatie, zorgleefplannen, rapportage en het signaleren van veranderingen in gezondheid en gedrag. Werkt rustig, respectvol en zorgvuldig samen met cliënten, familie, verpleegkundigen en behandelaren. Beschikbaar voor dag-, avond- en weekenddiensten.',
            birthDate: '3 februari 1991',
            birthPlace: 'Apeldoorn',
            nationality: 'Nederlands',
            driversLicense: 'B',
            gender: '',
            maritalStatus: '',
            linkedIn: 'linkedin.com/in/mariekevandenberg',
            github: '',
            website: '',
            photo: '',
        },
        experience: [
            {
                role: 'Verzorgende IG',
                company: 'Zorggroep Apeldoorn',
                location: 'Apeldoorn',
                start: 'mei 2020',
                end: 'heden',
                description: 'Persoonsgerichte zorg op een PG-afdeling met bewoners met dementie en complexe zorgvragen.',
                highlights: [
                    'ADL-zorg, medicatieverstrekking en dagelijkse observaties uitgevoerd volgens zorgleefplan en protocol',
                    'Veranderingen in gedrag, eetlust, mobiliteit en huidconditie tijdig gesignaleerd en gerapporteerd in ONS',
                    'Familiecontact onderhouden tijdens overdrachten, evaluaties en veranderingen in de zorgsituatie',
                    'Valpreventie-afspraken aangescherpt met verpleegkundige en fysiotherapeut na meerdere bijna-valincidenten',
                ],
            },
            {
                role: 'Verzorgende IG Thuiszorg',
                company: 'Buurtzorg',
                location: 'Deventer',
                start: 'augustus 2017',
                end: 'april 2020',
                description: 'Zelfstandige routes in de wijkzorg met persoonlijke verzorging, medicatie en ondersteuning bij herstel thuis.',
                highlights: [
                    'Cliënten ondersteund bij wassen, aankleden, steunkousen, medicatie en lichte verpleegtechnische handelingen',
                    'Zorgmomenten afgestemd met mantelzorgers, huisarts, wijkverpleegkundige en huishoudelijke hulp',
                    'Digitale rapportages bijgehouden en bijzonderheden direct teruggekoppeld aan het team',
                ],
            },
        ],
        education: [
            {
                degree: 'MBO 3 Verzorgende IG',
                school: 'Aventus',
                location: 'Apeldoorn',
                start: 'september 2014',
                end: 'juli 2017',
                description: 'Opleiding tot Verzorgende Individuele Gezondheidszorg met stages in VVT en thuiszorg.',
            },
        ],
        skills: [
            { name: 'ADL & persoonlijke zorg', level: 5 },
            { name: 'Medicatie & protocollen', level: 5 },
            { name: 'Zorgleefplan & rapportage', level: 4 },
            { name: 'PG & dementiezorg', level: 5 },
            { name: 'Familiecommunicatie', level: 4 },
        ],
        languages: [
            { name: 'Nederlands', level: 'Moedertaal' },
            { name: 'Engels', level: 'Basis' },
        ],
        interests: ['Wandelen', 'Koken', 'Lezen'],
        courses: [
            { name: 'Medicatieveiligheid', institution: 'Zorggroep Apeldoorn Academy', year: '2024' },
            { name: 'Omgaan met onbegrepen gedrag bij dementie', institution: 'Vilans', year: '2022' },
            { name: 'Ergonomisch werken en tilliften', institution: 'ArboNed', year: '2021' },
        ],
        internships: [],
        awards: [
            'Compliment familiegesprek bij Zorggroep Apeldoorn voor duidelijke communicatie tijdens veranderende zorgsituatie, 2023',
        ],
    },
};
