import { CVExample } from '../../types';

export const zorgmedewerkerHelpende: CVExample = {
    slug: 'zorgmedewerker-helpende',
    categorySlug: 'zorg-en-welzijn',
    name: 'Zorgmedewerker / Helpende',
    description: 'CV voorbeeld voor zorgmedewerkers en helpenden niveau 2. Laat ADL, rapportage, cliëntcontact, thuiszorg en ouderenzorg concreet zien.',
    templateId: 'simple',
    colorThemeId: 'charcoal',

    metaTitle: 'CV Voorbeeld Helpende Zorg & Welzijn | ADL & Thuiszorg | WerkCV.nl',
    metaDesc: 'CV voorbeeld voor helpende en zorgmedewerker. Met ADL, persoonlijke verzorging, thuiszorg, ouderenzorg, rapportage, zorgplan en cliëntcontact.',
    keywords: ['cv voorbeeld zorgmedewerker', 'cv helpende', 'helpende cv', 'zorgmedewerker cv', 'cv helpende zorg en welzijn', 'cv ouderenzorg', 'cv thuiszorg', 'cv ADL'],
    heroTitle: 'CV Voorbeeld Zorgmedewerker / Helpende',
    heroText: 'Als zorgmedewerker of helpende ben je het hart van de dagelijkse zorg. Dit CV voorbeeld laat zien hoe je ADL, persoonlijke verzorging, rapportage, cliëntcontact, thuiszorg en ouderenzorg professioneel presenteert zonder dat je CV te algemeen wordt.',
    tips: [
        'Benoem je diploma-niveau duidelijk: Helpende Zorg & Welzijn niveau 2, Verzorgende IG niveau 3 of zorgstudent',
        'Maak ADL concreet: wassen, aankleden, eten, mobiliseren, steunkousen, tillift of dagstructuur',
        'Beschrijf doelgroepen zoals ouderen, dementie, somatiek, revalidatie, thuiszorg of gehandicaptenzorg',
        'Laat zien dat je rapporteert, bijzonderheden signaleert en werkt volgens zorgplan of werkafspraken',
        'Benadruk betrouwbaarheid met voorbeelden rond routes, overdracht, familiecontact en werken in wisselende diensten',
    ],
    relatedSlugs: ['zorg-en-welzijn/verzorgende-ig', 'zorg-en-welzijn/verpleegkundige', 'zorg-en-welzijn/ggz-medewerker'],

    sampleCV: {
        personal: {
            name: 'Fatima El Amrani',
            title: 'Zorgmedewerker / Helpende',
            email: 'fatima.elamrani@email.nl',
            phone: '06-34567890',
            location: 'Den Haag',
            address: 'Schilderswijk 67',
            postalCode: '2525 KN',
            summary: 'Warme en betrouwbare zorgmedewerker met 5 jaar ervaring in ouderenzorg, thuiszorg en PG. Ervaren in ADL-ondersteuning, persoonlijke verzorging, maaltijden, mobiliteit, rapportage en het signaleren van veranderingen in welzijn. Werkt rustig, respectvol en zorgvuldig samen met cliënten, familie en zorgteam.',
            birthDate: '8 november 1995',
            birthPlace: 'Den Haag',
            nationality: 'Nederlands',
            driversLicense: 'B',
            gender: '',
            maritalStatus: '',
            linkedIn: '',
            github: '',
            website: '',
            photo: '',
        },
        experience: [
            {
                role: 'Zorgmedewerker / Helpende',
                company: 'Florence Zorggroep',
                location: 'Den Haag',
                start: 'april 2021',
                end: 'heden',
                description: 'Dagelijkse ondersteuning in verpleeghuis De Schildershoek, afdeling psychogeriatrie.',
                highlights: [
                    'Persoonlijke verzorging en ADL-ondersteuning geboden aan 12 bewoners per dienst',
                    'Bijzonderheden over eten, mobiliteit, stemming en huidconditie gerapporteerd in het zorgdossier',
                    'Dagactiviteiten ondersteund voor welzijn, structuur en sociale interactie op de afdeling',
                    'Rustige overdracht gegeven aan collega\'s en familie bij veranderingen in gedrag of behoefte',
                ],
            },
            {
                role: 'Thuiszorgmedewerker',
                company: 'Buurtzorg Nederland',
                location: 'Den Haag',
                start: 'september 2019',
                end: 'maart 2021',
                description: 'Zelfstandig werkend in de wijkverpleging en thuiszorg.',
                highlights: [
                    'Zorg en praktische ondersteuning verleend aan gemiddeld 8 cliënten per dag in de thuissituatie',
                    'Cliënten geholpen met wassen, aankleden, eten, mobiliseren en lichte huishoudelijke taken',
                    'Veranderingen in gezondheid en welzijn gesignaleerd en teruggekoppeld aan wijkteam',
                ],
            },
        ],
        education: [
            {
                degree: 'MBO 2 Helpende Zorg & Welzijn',
                school: 'ROC Mondriaan',
                location: 'Den Haag',
                start: 'september 2016',
                end: 'juli 2019',
                description: 'Beroepspraktijkvorming (BPV) in woonzorg en thuiszorg met focus op ADL, begeleiding en cliëntcontact.',
            },
            {
                degree: 'VMBO-TL',
                school: 'Segbroek College',
                location: 'Den Haag',
                start: 'september 2012',
                end: 'juni 2016',
                description: '',
            },
        ],
        skills: [
            { name: 'Persoonlijke verzorging & ADL', level: 5 },
            { name: 'Cliëntcontact', level: 5 },
            { name: 'Zorgplan & rapportage', level: 4 },
            { name: 'Dementiezorg', level: 4 },
            { name: 'Communicatie met cliënten & familie', level: 5 },
        ],
        languages: [
            { name: 'Nederlands', level: 'Moedertaal' },
            { name: 'Arabisch', level: 'Moedertaal' },
            { name: 'Engels', level: 'Basis' },
        ],
        interests: ['Koken', 'Wandelen', 'Vrijwilligerswerk moskee'],
        courses: [
            { name: 'Omgaan met dementie en onbegrepen gedrag', institution: 'V&VN', year: '2023' },
            { name: 'BHV (Bedrijfshulpverlening)', institution: 'Het Oranje Kruis', year: '2024' },
            { name: 'Ergonomisch werken en tilliften', institution: 'Florence Academy', year: '2022' },
        ],
        internships: [],
        awards: [],
    },
};
