import { CVExample } from '../../types';

export const zorgmedewerkerHelpende: CVExample = {
    slug: 'zorgmedewerker-helpende',
    categorySlug: 'zorg-en-welzijn',
    name: 'Zorgmedewerker / Helpende',
    description: 'CV voorbeeld voor zorgmedewerkers en helpenden in de ouderenzorg of thuiszorg. Ideaal voor MBO-niveau zorgprofessionals.',
    templateId: 'simple',
    colorThemeId: 'charcoal',

    metaTitle: 'CV Voorbeeld Zorgmedewerker & Helpende | WerkCV.nl',
    metaDesc: 'CV voorbeeld voor zorgmedewerkers en helpenden (MBO). Met voorbeeldteksten voor ouderenzorg, thuiszorg en ADL-ondersteuning. Direct je eigen CV maken.',
    keywords: ['cv voorbeeld zorgmedewerker', 'cv helpende', 'zorgmedewerker cv', 'cv ouderenzorg', 'cv thuiszorg'],
    heroTitle: 'CV Voorbeeld Zorgmedewerker / Helpende',
    heroText: 'Als zorgmedewerker of helpende ben je het hart van de dagelijkse zorg. Dit CV voorbeeld laat zien hoe je je praktijkervaring in ouderenzorg of thuiszorg, je MBO-opleiding en je persoonlijke betrokkenheid overtuigend presenteert.',
    tips: [
        'Benoem concreet welk type zorg je hebt verleend: ADL, persoonlijke verzorging, huishoudelijke ondersteuning',
        'Vermeld je diploma-niveau (Helpende Zorg & Welzijn niveau 2 of Verzorgende IG niveau 3)',
        'Beschrijf je ervaring met specifieke doelgroepen: ouderen, dementerenden, lichamelijk beperkten',
        'Laat zien dat je kunt werken met zorgplannen en rapportagesystemen',
        'Benadruk je betrouwbaarheid, geduld en communicatieve vaardigheden',
    ],
    relatedSlugs: ['zorg-en-welzijn/verpleegkundige', 'zorg-en-welzijn/ggz-medewerker'],

    sampleCV: {
        personal: {
            name: 'Fatima El Amrani',
            title: 'Zorgmedewerker - Verzorgende IG',
            email: 'fatima.elamrani@email.nl',
            phone: '06-34567890',
            location: 'Den Haag',
            address: 'Schilderswijk 67',
            postalCode: '2525 KN',
            summary: 'Warme en betrokken verzorgende IG met 5 jaar ervaring in de ouderenzorg en thuiszorg. Ervaren in het verlenen van persoonlijke verzorging, ADL-ondersteuning en begeleiding van ouderen met dementie. Werkt graag in een team en staat altijd klaar voor bewoners en cliënten.',
            birthDate: '8 november 1995',
            birthPlace: 'Den Haag',
            nationality: 'Nederlands',
            driversLicense: 'B',
            gender: '',
            maritalStatus: '',
            linkedIn: '',
            github: '',
            website: '',
            photo: '',
        },
        experience: [
            {
                role: 'Verzorgende IG',
                company: 'Florence Zorggroep',
                location: 'Den Haag',
                start: 'april 2021',
                end: 'heden',
                description: 'Verzorgende in verpleeghuis De Schildershoek, afdeling psychogeriatrie (dementie).',
                highlights: [
                    'Persoonlijke verzorging en ADL-ondersteuning voor 12 bewoners per dienst',
                    'Zorgplannen opgesteld en bijgehouden in samenwerking met verpleegkundigen en artsen',
                    'Dagactiviteiten georganiseerd ter bevordering van welzijn en sociale interactie',
                    'Familiegesprekken gevoerd over zorgbehoeften en wensen van bewoners',
                ],
            },
            {
                role: 'Thuiszorgmedewerker',
                company: 'Buurtzorg Nederland',
                location: 'Den Haag',
                start: 'september 2019',
                end: 'maart 2021',
                description: 'Zelfstandig werkend in de wijkverpleging en thuiszorg.',
                highlights: [
                    'Zorg verleend aan gemiddeld 8 cliënten per dag in de thuissituatie',
                    'Medicatie beheerd en toegediend volgens protocol',
                    'Signalering van veranderingen in gezondheid en welzijn van cliënten',
                ],
            },
        ],
        education: [
            {
                degree: 'MBO Verzorgende IG (niveau 3)',
                school: 'ROC Mondriaan',
                location: 'Den Haag',
                start: 'september 2016',
                end: 'juli 2019',
                description: 'Beroepspraktijkvorming (BPV) bij Haaglanden Medisch Centrum en Haagse Wijk- en Woonzorg.',
            },
            {
                degree: 'VMBO-TL',
                school: 'Segbroek College',
                location: 'Den Haag',
                start: 'september 2012',
                end: 'juni 2016',
                description: '',
            },
        ],
        skills: [
            { name: 'Persoonlijke verzorging & ADL', level: 5 },
            { name: 'Medicatietoediening', level: 4 },
            { name: 'Zorgplannen & rapportage', level: 4 },
            { name: 'Dementiezorg', level: 4 },
            { name: 'Communicatie met cliënten & familie', level: 5 },
            { name: 'Samenwerken in zorgteam', level: 4 },
        ],
        languages: [
            { name: 'Nederlands', level: 'Moedertaal' },
            { name: 'Arabisch', level: 'Moedertaal' },
            { name: 'Engels', level: 'Basis' },
        ],
        interests: ['Koken', 'Wandelen', 'Vrijwilligerswerk moskee'],
        courses: [
            { name: 'Omgaan met dementie en onbegrepen gedrag', institution: 'V&VN', year: '2023' },
            { name: 'BHV (Bedrijfshulpverlening)', institution: 'Het Oranje Kruis', year: '2024' },
        ],
        internships: [],
        awards: [],
    },
};
