import { CVExample } from '../../types';

export const speciaaalOnderwijs: CVExample = {
    slug: 'speciaal-onderwijs',
    categorySlug: 'onderwijs',
    name: 'Docent Speciaal Onderwijs',
    description: 'CV voorbeeld voor docenten in het speciaal onderwijs. Laat zien hoe je je specialistische kennis, pedagogische vaardigheden en ervaring met zorgleerlingen presenteert.',
    templateId: 'elegant',
    colorThemeId: 'sage-green',

    metaTitle: 'CV Voorbeeld Speciaal Onderwijs | WerkCV.nl',
    metaDesc: 'Professioneel CV voorbeeld voor docenten speciaal onderwijs. Met voorbeeldteksten voor zorgleerlingen, gedragsproblematiek en passend onderwijs. Maak direct je eigen CV.',
    keywords: ['cv voorbeeld speciaal onderwijs', 'cv docent SBO', 'cv leerkracht SO', 'cv passend onderwijs'],
    heroTitle: 'CV Voorbeeld Speciaal Onderwijs',
    heroText: 'Als docent in het speciaal onderwijs werk je met leerlingen die extra ondersteuning nodig hebben. Dit CV voorbeeld laat zien hoe je je specialistische kennis, ervaring met gedragsproblematiek en pedagogische aanpak overtuigend presenteert.',
    tips: [
        'Vermeld je PABO-diploma en aanvullende specialisatie (Master SEN, orthopedagogiek)',
        'Beschrijf je ervaring met specifieke doelgroepen (ASS, ADHD, gedragsproblematiek)',
        'Noem je kennis van handelingsgerichte diagnostiek en ontwikkelingsperspectieven',
        'Toon je ervaring met multidisciplinaire samenwerking (psychologen, logopedisten)',
        'Vermeld vaardigheden in het opstellen en uitvoeren van individuele handelingsplannen',
    ],
    relatedSlugs: ['onderwijs/onderwijsassistent', 'onderwijs/basisschool-docent'],

    sampleCV: {
        personal: {
            name: 'Marieke de Vries',
            title: 'Leerkracht Speciaal Onderwijs',
            email: 'marieke.devries@email.nl',
            phone: '06-34210987',
            location: 'Amersfoort',
            address: 'Leusderweg 28',
            postalCode: '3818 EA',
            summary: 'Ervaren en betrokken leerkracht speciaal onderwijs met 8 jaar ervaring in het (V)SO. Gespecialiseerd in het werken met leerlingen met gedragsproblematiek en ontwikkelingsstoornissen. Sterk in het opstellen van ontwikkelingsperspectieven en het samenwerken in multidisciplinaire teams. Altijd gericht op de individuele mogelijkheden van elk kind.',
            birthDate: '23 februari 1990',
            birthPlace: 'Utrecht',
            nationality: 'Nederlands',
            driversLicense: 'B',
            gender: '',
            maritalStatus: '',
            linkedIn: 'linkedin.com/in/mariekedevries',
            github: '',
            website: '',
            photo: '',
        },
        experience: [
            {
                role: 'Leerkracht Speciaal Onderwijs',
                company: 'De Aventurijn (Cluster 4)',
                location: 'Amersfoort',
                start: 'augustus 2019',
                end: 'heden',
                description: 'Lesgeven aan leerlingen met gedragsproblematiek en psychiatrische stoornissen in het VSO.',
                highlights: [
                    'Individuele ontwikkelingsperspectieven (OPP) opgesteld en geëvalueerd voor 12 leerlingen',
                    'Trainingen gegeven aan collega\'s over omgaan met agressie en de-escalatie',
                    'Nauw samengewerkt met orthopedagoog, psycholoog en jeugdzorg',
                ],
            },
            {
                role: 'Leerkracht SBO',
                company: 'SBO De Wissel',
                location: 'Utrecht',
                start: 'augustus 2016',
                end: 'juli 2019',
                description: 'Lesgeven aan leerlingen met leer- en gedragsproblemen in het speciaal basisonderwijs.',
                highlights: [
                    'Groepshandelingsplannen opgesteld voor lezen, rekenen en sociaal-emotionele ontwikkeling',
                    'Oudergesprekken gevoerd en samengewerkt met externe hulpverleners',
                ],
            },
        ],
        education: [
            {
                degree: 'Master Special Educational Needs (SEN)',
                school: 'Hogeschool Utrecht',
                location: 'Utrecht',
                start: 'september 2018',
                end: 'juli 2020',
                description: 'Specialisatie gedragsproblematiek en leraar-specialist. Afstudeeronderzoek naar trauma-sensitief onderwijs.',
            },
            {
                degree: 'Bachelor PABO',
                school: 'Hogeschool Utrecht',
                location: 'Utrecht',
                start: 'september 2012',
                end: 'juli 2016',
                description: 'Afgestudeerd met minor speciaal onderwijs. Stages in regulier en speciaal basisonderwijs.',
            },
        ],
        skills: [
            { name: 'Handelingsgericht werken', level: 5 },
            { name: 'Gedragsproblematiek', level: 5 },
            { name: 'Ontwikkelingsperspectieven', level: 4 },
            { name: 'Multidisciplinaire samenwerking', level: 4 },
            { name: 'De-escalatietechnieken', level: 4 },
        ],
        languages: [
            { name: 'Nederlands', level: 'Moedertaal' },
            { name: 'Engels', level: 'Goed' },
        ],
        interests: ['Pedagogische literatuur', 'Mindfulness', 'Wandelen', 'Schilderen'],
        courses: [
            { name: 'Traumasensitief lesgeven', institution: 'Augeo Foundation', year: '2023' },
            { name: 'NVBA De-escalatietraining', institution: 'NVBA', year: '2022' },
        ],
        internships: [],
        awards: [],
    },
};
