import { CVExample } from '../../types';

export const advocaatStagiair: CVExample = {
    slug: 'advocaat-stagiair',
    categorySlug: 'juridisch-en-overheid',
    name: 'Advocaat-Stagiair',
    description: 'CV voorbeeld voor advocaat-stagiairs bij Nederlandse advocatenkantoren. Laat zien hoe je je juridische opleiding, stage-ervaring en procesvaardigheden presenteert.',
    templateId: 'formal',
    colorThemeId: 'classic-blue',

    metaTitle: 'CV Voorbeeld Advocaat-Stagiair | WerkCV.nl',
    metaDesc: 'Professioneel CV voorbeeld voor advocaat-stagiairs. Met voorbeeldteksten voor procederen, juridisch onderzoek en de beroepsopleiding advocatuur. Direct te gebruiken.',
    keywords: ['cv voorbeeld advocaat-stagiair', 'advocaat stagiair cv', 'cv advocaat', 'cv advocatenkantoor', 'togastage cv'],
    heroTitle: 'CV Voorbeeld Advocaat-Stagiair',
    heroText: 'Als advocaat-stagiair combineer je de beroepsopleiding advocatuur met het werken aan echte juridische zaken. Dit CV voorbeeld laat zien hoe je je juridische kennis, proceservaring en je ontwikkeling tijdens de togastage overtuigend presenteert aan advocatenkantoren.',
    tips: [
        'Vermeld je voortgang in de beroepsopleiding advocatuur en eventuele specialisatiecursussen',
        'Beschrijf concrete zaken waar je aan hebt gewerkt, inclusief rechtsgebied en resultaat',
        'Benoem je procesvoering: zittingen bijgewoond, pleitnota\'s opgesteld, cliënten geadviseerd',
        'Toon je juridisch onderzoeksvaardigheden door publicaties of scriptiethema te vermelden',
        'Verwijs naar je patroon en de rechtsgebieden van het kantoor waar je werkzaam bent',
    ],
    relatedSlugs: ['juridisch-en-overheid/juridisch-medewerker', 'juridisch-en-overheid/griffier'],

    sampleCV: {
        personal: {
            name: 'Daan Vermeer',
            title: 'Advocaat-Stagiair',
            email: 'daan.vermeer@email.nl',
            phone: '06-67234518',
            location: 'Amsterdam',
            address: 'Keizersgracht 412',
            postalCode: '1016 GD',
            summary: 'Gemotiveerde advocaat-stagiair met 1,5 jaar ervaring in de civiele procespraktijk bij een toonaangevend Zuidas-kantoor. Bezig met de beroepsopleiding advocatuur met specialisatie burgerlijk procesrecht. Ervaring met het zelfstandig voeren van procedures bij de rechtbank, het adviseren van cliënten en het opstellen van processtukken. Ambitieus en leergierig met een scherp analytisch vermogen.',
            birthDate: '18 augustus 1997',
            birthPlace: 'Arnhem',
            nationality: 'Nederlands',
            driversLicense: 'B',
            gender: '',
            maritalStatus: '',
            linkedIn: 'linkedin.com/in/daanvermeer-advocaat',
            github: '',
            website: '',
            photo: '',
        },
        experience: [
            {
                role: 'Advocaat-Stagiair Sectie Litigation & Arbitration',
                company: 'De Brauw Blackstone Westbroek',
                location: 'Amsterdam',
                start: 'september 2023',
                end: 'heden',
                description: 'Togastage in de civiele procespraktijk bij een van de grootste advocatenkantoren van Nederland.',
                highlights: [
                    'Zelfstandig 12 zaken behandeld bij de rechtbank Amsterdam en Den Haag op het gebied van contractenrecht en aansprakelijkheidsrecht',
                    'Dagvaardingen, conclusies en pleitnota\'s opgesteld in complexe handelszaken met belangen tot €5 miljoen',
                    'Cliëntadviezen geschreven over procesrisico\'s, executiemogelijkheden en schikkingsonderhandelingen',
                ],
            },
            {
                role: 'Student-stagiair Ondernemingsrecht',
                company: 'NautaDutilh',
                location: 'Amsterdam',
                start: 'februari 2023',
                end: 'juli 2023',
                description: 'Studentstage op de sectie ondernemingsrecht ter voorbereiding op de togastage.',
                highlights: [
                    'Juridisch onderzoek verricht voor transacties op het gebied van fusies en overnames',
                    'Due diligence-rapporten opgesteld en aandeelhoudersovereenkomsten geanalyseerd',
                    'Memoranda geschreven over vennootschapsrechtelijke vraagstukken voor partners',
                ],
            },
        ],
        education: [
            {
                degree: 'Beroepsopleiding Advocatuur (BA)',
                school: 'CPO / Radboud Universiteit',
                location: 'Nijmegen',
                start: 'september 2023',
                end: 'heden',
                description: 'Driejarige beroepsopleiding naast de togastage, met vakken in ethiek, procesrecht en kantoorvaardigheden.',
            },
            {
                degree: 'Master Privaatrecht (WO Rechtsgeleerdheid)',
                school: 'Universiteit van Amsterdam',
                location: 'Amsterdam',
                start: 'september 2021',
                end: 'juli 2023',
                description: 'Cum laude afgestudeerd. Scriptie over de grenzen van partijautonomie in arbitrageprocedures (beoordeling: 8,5). Lid van de Moot Court-commissie.',
            },
            {
                degree: 'Bachelor Rechtsgeleerdheid',
                school: 'Universiteit van Amsterdam',
                location: 'Amsterdam',
                start: 'september 2017',
                end: 'juli 2021',
                description: 'Met getuigschrift. Honours programme met extra vakken in rechtsfilosofie en internationaal privaatrecht.',
            },
        ],
        skills: [
            { name: 'Civiel procesrecht & procederen', level: 4 },
            { name: 'Juridisch onderzoek & analyse', level: 5 },
            { name: 'Opstellen processtukken', level: 4 },
            { name: 'Cliëntadvisering', level: 3 },
            { name: 'Contractenrecht & aansprakelijkheid', level: 4 },
            { name: 'Legal Intelligence & jurisprudentie', level: 4 },
        ],
        languages: [
            { name: 'Nederlands', level: 'Moedertaal' },
            { name: 'Engels', level: 'Vloeiend' },
            { name: 'Duits', level: 'Goed' },
        ],
        interests: ['Moot Court', 'Roeien', 'Juridische vakliteratuur'],
        courses: [
            { name: 'Beroepsopleiding Advocatuur - Jaar 1', institution: 'CPO Radboud Universiteit', year: '2024' },
            { name: 'Masterclass Arbitrage & Mediation', institution: 'Nederlands Arbitrage Instituut', year: '2023' },
        ],
        internships: [],
        awards: [],
    },
};
