import { CVExample } from '../../types';

export const ambtenaar: CVExample = {
    slug: 'ambtenaar',
    categorySlug: 'juridisch-en-overheid',
    name: 'Senior Beleidsmedewerker Rijksoverheid',
    description: 'CV voorbeeld voor senior beleidsmedewerkers bij de Rijksoverheid. Laat zien hoe je ervaring met Kamervragen, regelgeving en interdepartementaal overleg presenteert.',
    templateId: 'classical',
    colorThemeId: 'slate-modern',

    metaTitle: 'CV Voorbeeld Ambtenaar Rijksoverheid | WerkCV.nl',
    metaDesc: 'Professioneel CV voorbeeld voor ambtenaren bij de Rijksoverheid. Met voorbeeldteksten voor beleidsvorming, Kamervragen en interdepartementaal overleg. Direct bruikbaar.',
    keywords: ['cv voorbeeld ambtenaar', 'cv rijksoverheid', 'cv beleidsmedewerker', 'ambtenaar cv maken', 'cv ministerie'],
    heroTitle: 'CV Voorbeeld Ambtenaar Rijksoverheid',
    heroText: 'Als senior beleidsmedewerker bij de Rijksoverheid werk je aan complexe maatschappelijke vraagstukken op het hoogste bestuurlijke niveau. Dit CV voorbeeld laat zien hoe je je ervaring met wetgeving, Kamervragen en interdepartementaal overleg professioneel presenteert aan ministeries en uitvoeringsorganisaties.',
    tips: [
        'Beschrijf je ervaring met het beantwoorden van Kamervragen en het opstellen van beleidsnota\'s',
        'Vermeld specifieke beleidsterreinen en wetgevingstrajecten waar je aan hebt bijgedragen',
        'Toon je vermogen om op strategisch niveau te adviseren aan bewindspersonen en directeuren',
        'Benoem je ervaring met interdepartementaal en interbestuurlijk samenwerken',
        'Laat zien dat je complexe politieke dossiers kunt vertalen naar uitvoerbaar beleid',
    ],
    relatedSlugs: ['juridisch-en-overheid/beleidsadviseur', 'juridisch-en-overheid/griffier'],

    sampleCV: {
        personal: {
            name: 'Martijn de Groot',
            title: 'Senior Beleidsmedewerker',
            email: 'martijn.degroot@email.nl',
            phone: '06-45612378',
            location: 'Den Haag',
            address: 'Statenlaan 42',
            postalCode: '2582 GR',
            summary: 'Gedreven senior beleidsmedewerker met meer dan 6 jaar ervaring bij de Rijksoverheid. Gespecialiseerd in justitieel beleid en wetgevingsprocessen. Ervaren in het beantwoorden van Kamervragen, het voorbereiden van wetsvoorstellen en het coördineren van interdepartementaal overleg. Politiek-bestuurlijk sensitief met een sterk analytisch vermogen.',
            birthDate: '15 mei 1989',
            birthPlace: 'Utrecht',
            nationality: 'Nederlands',
            driversLicense: 'B',
            gender: '',
            maritalStatus: '',
            linkedIn: 'linkedin.com/in/martijndegroot-beleid',
            github: '',
            website: '',
            photo: '',
        },
        experience: [
            {
                role: 'Senior Beleidsmedewerker Directie Rechtsbestel',
                company: 'Ministerie van Justitie en Veiligheid',
                location: 'Den Haag',
                start: 'januari 2021',
                end: 'heden',
                description: 'Beleidsontwikkeling en wetgevingsadvisering op het terrein van het civiele recht en de toegang tot het recht.',
                highlights: [
                    'Meer dan 60 Kamervragen beantwoord namens de minister op het terrein van rechtsbijstand en geschilbeslechting',
                    'Mede-auteur van het wetsvoorstel tot herziening van het stelsel van gesubsidieerde rechtsbijstand',
                    'Interdepartementaal beleidsonderzoek gecoördineerd naar de maatschappelijke kosten van juridische geschillen',
                ],
            },
            {
                role: 'Beleidsmedewerker Directie Migratiebeleid',
                company: 'Ministerie van Justitie en Veiligheid',
                location: 'Den Haag',
                start: 'maart 2018',
                end: 'december 2020',
                description: 'Beleidsvoorbereiding en -uitvoering op het gebied van asiel- en migratiebeleid.',
                highlights: [
                    'Beleidsnota\'s en Kamerbrief opgesteld over de herziening van het Gemeenschappelijk Europees Asielstelsel',
                    'Nederlandse inzet voorbereid voor JBZ-Raad overleggen in Brussel over migratiedossiers',
                    'Ambtelijk vooroverleg geleid met IND, COA en ketenpartners over uitvoerbaarheid van nieuw beleid',
                ],
            },
            {
                role: 'Junior Beleidsmedewerker',
                company: 'Raad van State',
                location: 'Den Haag',
                start: 'september 2016',
                end: 'februari 2018',
                description: 'Ondersteuning bij de advisering over wetsvoorstellen en algemene maatregelen van bestuur.',
                highlights: [
                    'Juridische analyses opgesteld van wetsvoorstellen ten behoeve van de Afdeling advisering',
                    'Onderzoek verricht naar Europese rechtspraak en de gevolgen voor nationale wetgeving',
                ],
            },
        ],
        education: [
            {
                degree: 'Master Staats- en Bestuursrecht (WO Rechtsgeleerdheid)',
                school: 'Universiteit Utrecht',
                location: 'Utrecht',
                start: 'september 2014',
                end: 'juli 2016',
                description: 'Afstudeerrichting Publiekrecht. Scriptie over de constitutionele toetsing van wetgeving in Nederland (beoordeling: 8,0).',
            },
            {
                degree: 'Bachelor Politicologie',
                school: 'Universiteit Utrecht',
                location: 'Utrecht',
                start: 'september 2010',
                end: 'juli 2014',
                description: 'Brede basis in politieke theorie, vergelijkende politicologie en bestuurskunde.',
            },
        ],
        skills: [
            { name: 'Kamervragen & parlementaire dossiers', level: 5 },
            { name: 'Wetgevingsprocessen & regelgeving', level: 5 },
            { name: 'Interdepartementaal overleg', level: 4 },
            { name: 'Beleidsanalyse & advies', level: 5 },
            { name: 'Europees recht & internationale samenwerking', level: 4 },
            { name: 'Bestuurlijke nota\'s & rapportages', level: 4 },
        ],
        languages: [
            { name: 'Nederlands', level: 'Moedertaal' },
            { name: 'Engels', level: 'Vloeiend' },
            { name: 'Frans', level: 'Goed' },
            { name: 'Duits', level: 'Basis' },
        ],
        interests: ['Staatsrecht', 'Schaatsen', 'Politieke non-fictie'],
        courses: [
            { name: 'Leergang Wetgevingstechniek', institution: 'Academie voor Wetgeving', year: '2022' },
            { name: 'Masterclass Politiek-bestuurlijke Sensitiviteit', institution: 'Rijksacademie voor Financiën, Economie en Bedrijfsvoering', year: '2021' },
        ],
        internships: [],
        awards: [],
    },
};
