import { CVExample } from '../../types';

export const beleidsadviseur: CVExample = {
    slug: 'beleidsadviseur',
    categorySlug: 'juridisch-en-overheid',
    name: 'Beleidsadviseur',
    description: 'CV voorbeeld voor beleidsadviseurs bij gemeenten, provincies en ministeries. Presenteer je beleidsmatige ervaring en adviesvaardigheden op een overtuigende manier.',
    templateId: 'professional',
    colorThemeId: 'charcoal',

    metaTitle: 'CV Voorbeeld Beleidsadviseur | WerkCV.nl',
    metaDesc: 'Professioneel CV voorbeeld voor beleidsadviseurs bij de overheid. Met voorbeeldteksten voor beleidsanalyse, rapportage en bestuurlijk advies. Direct bruikbaar.',
    keywords: ['cv voorbeeld beleidsadviseur', 'beleidsadviseur cv', 'cv overheid', 'cv gemeente beleidsadviseur', 'beleidsmedewerker cv'],
    heroTitle: 'CV Voorbeeld Beleidsadviseur',
    heroText: 'Als beleidsadviseur vertaal je politieke en maatschappelijke vraagstukken naar concreet beleid. Dit CV voorbeeld laat zien hoe je je analytische vaardigheden, bestuurlijke sensitiviteit en stakeholder management overtuigend presenteert aan overheidsinstellingen en adviesbureaus.',
    tips: [
        'Benoem specifieke beleidsterreinen waar je ervaring mee hebt, zoals sociaal domein, ruimtelijke ordening of veiligheid',
        'Beschrijf de impact van je beleidsadviezen: welke besluiten zijn genomen op basis van jouw analyses?',
        'Toon je vermogen om complexe informatie toegankelijk te maken in bestuurlijke nota\'s en raadsstukken',
        'Vermeld ervaring met participatietrajecten, stakeholderbijeenkomsten en bestuurlijke overleggen',
        'Laat zien dat je kunt schakelen tussen politiek, bestuur en uitvoering',
    ],
    relatedSlugs: ['juridisch-en-overheid/ambtenaar', 'juridisch-en-overheid/juridisch-medewerker'],

    sampleCV: {
        personal: {
            name: 'Thomas Bakker',
            title: 'Senior Beleidsadviseur',
            email: 'thomas.bakker@email.nl',
            phone: '06-28934567',
            location: 'Den Haag',
            address: 'Laan van Meerdervoort 88',
            postalCode: '2517 AM',
            summary: 'Resultaatgerichte senior beleidsadviseur met meer dan 5 jaar ervaring in het openbaar bestuur. Gespecialiseerd in het sociaal domein en veiligheidsbeleid. Ervaren in het opstellen van bestuurlijke nota\'s, het begeleiden van participatietrajecten en het adviseren van college en gemeenteraad. Sterk in het verbinden van beleid, politiek en uitvoering.',
            birthDate: '22 januari 1991',
            birthPlace: 'Rotterdam',
            nationality: 'Nederlands',
            driversLicense: 'B',
            gender: '',
            maritalStatus: '',
            linkedIn: 'linkedin.com/in/thomasbakker-beleid',
            github: '',
            website: '',
            photo: '',
        },
        experience: [
            {
                role: 'Senior Beleidsadviseur Sociaal Domein',
                company: 'Gemeente Den Haag',
                location: 'Den Haag',
                start: 'februari 2021',
                end: 'heden',
                description: 'Verantwoordelijk voor beleidsontwikkeling en advisering op het gebied van Wmo, Jeugdzorg en Participatiewet.',
                highlights: [
                    'Beleidsnotitie opgesteld die leidde tot herziening van het Wmo-beleid, met een besparing van €2,5 miljoen per jaar',
                    'Participatietraject georganiseerd met 300+ bewoners voor de ontwikkeling van het nieuwe sociaal beleidsplan',
                    'Bestuurlijke nota\'s en raadsinformatiebrieven opgesteld voor wethouder en gemeenteraad',
                ],
            },
            {
                role: 'Beleidsadviseur Veiligheid',
                company: 'Gemeente Rotterdam',
                location: 'Rotterdam',
                start: 'september 2019',
                end: 'januari 2021',
                description: 'Beleidsontwikkeling en uitvoering op het gebied van openbare orde en veiligheid.',
                highlights: [
                    'Integraal veiligheidsplan opgesteld in samenwerking met politie, OM en welzijnsorganisaties',
                    'Evaluatierapporten geschreven over de effectiviteit van het ondermijningsbeleid',
                    'Ambtelijk secretaris geweest van het Driehoeksoverleg (burgemeester, politie, OM)',
                ],
            },
            {
                role: 'Junior Beleidsmedewerker',
                company: 'Provincie Zuid-Holland',
                location: 'Den Haag',
                start: 'juni 2018',
                end: 'augustus 2019',
                description: 'Ondersteuning bij beleidsontwikkeling op het terrein van ruimtelijke ordening en mobiliteit.',
                highlights: [
                    'Onderzoeksrapporten opgesteld over woningbouwopgaven en bereikbaarheidsvraagstukken',
                    'Bijgedragen aan de provinciale Omgevingsvisie door stakeholderanalyses en beleidsverkenningen',
                ],
            },
        ],
        education: [
            {
                degree: 'Master Bestuurskunde (WO)',
                school: 'Erasmus Universiteit Rotterdam',
                location: 'Rotterdam',
                start: 'september 2016',
                end: 'juli 2018',
                description: 'Specialisatie Beleid & Politiek. Scriptie over de effectiviteit van decentralisaties in het sociaal domein (beoordeling: 8,5).',
            },
            {
                degree: 'Bachelor Bestuurskunde',
                school: 'Erasmus Universiteit Rotterdam',
                location: 'Rotterdam',
                start: 'september 2012',
                end: 'juli 2016',
                description: 'Afgestudeerd met keuzevakken in publiek management en beleidsanalyse.',
            },
        ],
        skills: [
            { name: 'Beleidsanalyse & -ontwikkeling', level: 5 },
            { name: 'Bestuurlijke rapportage', level: 5 },
            { name: 'Stakeholder management', level: 4 },
            { name: 'Participatietrajecten', level: 4 },
            { name: 'Bestuurlijk advies', level: 4 },
            { name: 'Onderzoeksmethodologie', level: 3 },
        ],
        languages: [
            { name: 'Nederlands', level: 'Moedertaal' },
            { name: 'Engels', level: 'Vloeiend' },
            { name: 'Frans', level: 'Basis' },
        ],
        interests: ['Politieke geschiedenis', 'Wielrennen', 'Debatteren'],
        courses: [
            { name: 'Leergang Beleidsadviseur in het Openbaar Bestuur', institution: 'Bestuursacademie Nederland', year: '2022' },
            { name: 'Cursus Bestuurlijke Sensitiviteit', institution: 'NSOB', year: '2021' },
        ],
        internships: [],
        awards: [],
    },
};
