import { CVExample } from '../../types';

export const complianceOfficer: CVExample = {
    slug: 'compliance-officer',
    categorySlug: 'juridisch-en-overheid',
    name: 'Compliance Officer',
    description: 'CV voorbeeld voor compliance officers bij banken, verzekeraars en financiële instellingen. Presenteer je expertise in Wwft, risicobeoordeling en interne audits.',
    templateId: 'robust',
    colorThemeId: 'ocean-blue',

    metaTitle: 'CV Voorbeeld Compliance Officer | WerkCV.nl',
    metaDesc: 'Professioneel CV voorbeeld voor compliance officers. Met voorbeeldteksten voor Wwft, risicobeoordeling, interne audits en toezicht. Direct te gebruiken als template.',
    keywords: ['cv voorbeeld compliance officer', 'compliance officer cv', 'cv Wwft', 'cv financiële sector', 'compliance cv maken'],
    heroTitle: 'CV Voorbeeld Compliance Officer',
    heroText: 'Als compliance officer zorg je ervoor dat organisaties voldoen aan wet- en regelgeving en interne richtlijnen. Dit CV voorbeeld laat zien hoe je je kennis van de Wwft, risicobeoordeling en interne audits overtuigend presenteert aan banken, verzekeraars en andere financiële instellingen.',
    tips: [
        'Vermeld specifieke wet- en regelgeving waar je ervaring mee hebt: Wwft, Wft, MiFID II, Solvency II',
        'Beschrijf concrete resultaten: aantal uitgevoerde audits, geïdentificeerde risico\'s, geïmplementeerde verbeteringen',
        'Benoem relevante certificeringen zoals DSI, ACAMS of ICA Diploma in Compliance',
        'Toon je vermogen om compliance-bewustzijn te creëren door trainingen en communicatie',
        'Laat zien dat je ervaring hebt met toezichthouders zoals DNB, AFM of ECB',
    ],
    relatedSlugs: ['juridisch-en-overheid/juridisch-medewerker', 'juridisch-en-overheid/advocaat-stagiair'],

    sampleCV: {
        personal: {
            name: 'Priya Nair',
            title: 'Compliance Officer',
            email: 'priya.nair@email.nl',
            phone: '06-51237894',
            location: 'Amsterdam',
            address: 'Apollolaan 56',
            postalCode: '1077 BD',
            summary: 'Ervaren compliance officer met meer dan 5 jaar ervaring in de financiële sector. Gespecialiseerd in Wwft-compliance, klantenonderzoek (CDD/EDD) en transactiemonitoring. Bewezen track record in het opzetten van compliance-programma\'s, het uitvoeren van risicobeoordelingen en het onderhouden van contacten met toezichthouders. DSI- en ACAMS-gecertificeerd.',
            birthDate: '3 november 1992',
            birthPlace: 'Den Haag',
            nationality: 'Nederlands',
            driversLicense: 'B',
            gender: '',
            maritalStatus: '',
            linkedIn: 'linkedin.com/in/priyanair-compliance',
            github: '',
            website: '',
            photo: '',
        },
        experience: [
            {
                role: 'Compliance Officer',
                company: 'ING Bank',
                location: 'Amsterdam',
                start: 'mei 2021',
                end: 'heden',
                description: 'Verantwoordelijk voor Wwft-compliance en anti-witwasbeleid binnen de afdeling Wholesale Banking.',
                highlights: [
                    'Compliance-framework voor Enhanced Due Diligence (EDD) ontwikkeld en geïmplementeerd voor 500+ zakelijke klanten',
                    'Meer dan 80 interne audits uitgevoerd op naleving van Wwft en sanctieregelgeving, met 95% opvolgingspercentage',
                    'Compliance-trainingen ontwikkeld en gegeven aan 300+ medewerkers over witwasrisico\'s en verdachte transacties',
                ],
            },
            {
                role: 'Junior Compliance Analyst',
                company: 'Rabobank',
                location: 'Utrecht',
                start: 'september 2019',
                end: 'april 2021',
                description: 'Ondersteuning van het compliance-team bij klantenonderzoek, transactiemonitoring en regelgevingsrapportages.',
                highlights: [
                    'Maandelijks 150+ transactiealerts beoordeeld en ongebruikelijke transacties gemeld bij de FIU-Nederland',
                    'CDD- en KYC-dossiers opgesteld en beoordeeld voor de afdeling Wholesale & Rural Banking',
                    'Bijgedragen aan de voorbereiding van DNB-onderzoeken en opvolging van bevindingen',
                ],
            },
            {
                role: 'Werkstudent Compliance',
                company: 'ABN AMRO',
                location: 'Amsterdam',
                start: 'februari 2018',
                end: 'augustus 2019',
                description: 'Parttime ondersteuning van het compliance-team naast de masteropleiding.',
                highlights: [
                    'Onderzoek uitgevoerd naar de impact van de vijfde Anti-witwasrichtlijn op het CDD-beleid',
                    'Compliance-procedures en -handboeken geactualiseerd conform nieuwe wet- en regelgeving',
                ],
            },
        ],
        education: [
            {
                degree: 'Master Financieel Recht (WO Rechtsgeleerdheid)',
                school: 'Universiteit van Amsterdam',
                location: 'Amsterdam',
                start: 'september 2017',
                end: 'juli 2019',
                description: 'Specialisatie financieel toezichtrecht en compliance. Scriptie over de effectiviteit van de Wwft in de bestrijding van witwassen (beoordeling: 7,5).',
            },
            {
                degree: 'Bachelor Rechtsgeleerdheid',
                school: 'Universiteit van Amsterdam',
                location: 'Amsterdam',
                start: 'september 2013',
                end: 'juli 2017',
                description: 'Afgestudeerd met keuzevakken in financieel recht en Europees recht.',
            },
        ],
        skills: [
            { name: 'Wwft & anti-witwasregelgeving', level: 5 },
            { name: 'Risicobeoordeling (CDD/EDD/KYC)', level: 5 },
            { name: 'Interne audits & monitoring', level: 4 },
            { name: 'Regelgeving (Wft, MiFID II)', level: 4 },
            { name: 'Compliance-trainingen & awareness', level: 4 },
            { name: 'Toezichthoudercontact (DNB, AFM)', level: 3 },
        ],
        languages: [
            { name: 'Nederlands', level: 'Moedertaal' },
            { name: 'Engels', level: 'Vloeiend' },
            { name: 'Hindi', level: 'Goed' },
        ],
        interests: ['Fintech & regtech', 'Yoga', 'Reizen'],
        courses: [
            { name: 'ACAMS Certified Anti-Money Laundering Specialist', institution: 'ACAMS', year: '2023' },
            { name: 'DSI Compliance Officer Registratie', institution: 'DSI', year: '2022' },
            { name: 'Wwft Intensief voor Compliance Professionals', institution: 'NIBE-SVV', year: '2021' },
        ],
        internships: [],
        awards: [],
    },
};
