import { CVExample } from '../../types';

export const griffier: CVExample = {
    slug: 'griffier',
    categorySlug: 'juridisch-en-overheid',
    name: 'Griffier',
    description: 'CV voorbeeld voor griffiers bij de rechtbank. Presenteer je ervaring met procesrecht, zittingsvoorbereiding en het opstellen van vonnissen op een professionele manier.',
    templateId: 'simple',
    colorThemeId: 'charcoal',

    metaTitle: 'CV Voorbeeld Griffier | WerkCV.nl',
    metaDesc: 'Professioneel CV voorbeeld voor griffiers bij de rechtspraak. Met voorbeeldteksten voor zittingsvoorbereiding, procesrecht en vonnissen. Direct te gebruiken als template.',
    keywords: ['cv voorbeeld griffier', 'griffier cv', 'cv rechtbank', 'cv rechtspraak', 'griffier cv maken'],
    heroTitle: 'CV Voorbeeld Griffier',
    heroText: 'Als griffier vorm je een essentieel onderdeel van de rechtspraak. Je bereidt zittingen voor, stelt vonnissen op en ondersteunt rechters bij hun werk. Dit CV voorbeeld laat zien hoe je je juridische kennis, procesrechtelijke ervaring en organisatorische vaardigheden overtuigend presenteert aan rechtbanken en gerechtshoven.',
    tips: [
        'Vermeld bij welke rechtsgebieden en kamers je ervaring hebt opgedaan (civiel, straf, bestuursrecht)',
        'Beschrijf je rol bij zittingen: procesverbaal, regie, communicatie met procespartijen',
        'Benoem hoeveel vonnissen en beschikkingen je hebt opgesteld of geconcipieerd',
        'Toon je organisatorische vaardigheden: zaakplanning, dossiervoorbereiding, termijnbewaking',
        'Vermeld relevante opleidingen zoals de SSR-opleiding tot griffier of rechterlijke leergang',
    ],
    relatedSlugs: ['juridisch-en-overheid/ambtenaar', 'juridisch-en-overheid/advocaat-stagiair'],

    sampleCV: {
        personal: {
            name: 'Anne-Marie Jansen',
            title: 'Griffier',
            email: 'annemarie.jansen@email.nl',
            phone: '06-19845623',
            location: 'Den Haag',
            address: 'Laan van NOI 15',
            postalCode: '2514 GH',
            summary: 'Ervaren griffier met meer dan 5 jaar werkervaring bij de Rechtspraak. Werkzaam geweest bij zowel de sector civiel recht als de sector strafrecht. Sterk in het voorbereiden van zittingen, het opstellen van vonnissen en beschikkingen, en het bewaken van procesrechtelijke termijnen. Nauwkeurig, stressbestendig en gewend aan een hoge werkdruk.',
            birthDate: '29 april 1990',
            birthPlace: 'Breda',
            nationality: 'Nederlands',
            driversLicense: 'B',
            gender: '',
            maritalStatus: '',
            linkedIn: 'linkedin.com/in/amjansen-griffier',
            github: '',
            website: '',
            photo: '',
        },
        experience: [
            {
                role: 'Griffier Sector Civiel Recht',
                company: 'Rechtbank Den Haag',
                location: 'Den Haag',
                start: 'april 2021',
                end: 'heden',
                description: 'Griffier bij de civiele kamer met focus op handelsrecht en familierecht.',
                highlights: [
                    'Gemiddeld 8 zittingen per week voorbereid en begeleid, waaronder comparities, kort gedingen en familiezaken',
                    'Jaarlijks meer dan 200 concept-vonnissen en beschikkingen opgesteld ter beoordeling door rechters',
                    'Procesverbalen opgesteld van zittingen en communicatie verzorgd met advocaten en procespartijen',
                ],
            },
            {
                role: 'Griffier Sector Strafrecht',
                company: 'Rechtbank Rotterdam',
                location: 'Rotterdam',
                start: 'september 2019',
                end: 'maart 2021',
                description: 'Griffier bij de meervoudige strafkamer voor complexe strafzaken.',
                highlights: [
                    'Zittingen voorbereid en begeleid in zware strafzaken waaronder zedenzaken, drugscriminaliteit en fraude',
                    'Gedetailleerde procesverbalen opgesteld van meerdaagse zittingen met meerdere verdachten',
                    'Nauw samengewerkt met rechters bij het concipiëren van strafvonnissen en motivering van strafoplegging',
                ],
            },
            {
                role: 'Juridisch Medewerker (Gerechtssecretaris)',
                company: 'Gerechtshof Den Haag',
                location: 'Den Haag',
                start: 'januari 2018',
                end: 'augustus 2019',
                description: 'Juridische ondersteuning bij de civiele kamer van het gerechtshof in hoger beroepszaken.',
                highlights: [
                    'Dossiers geanalyseerd en juridische adviezen opgesteld voor raadsheren in hoger beroepszaken',
                    'Concept-arresten opgesteld op het gebied van verbintenissenrecht en goederenrecht',
                ],
            },
        ],
        education: [
            {
                degree: 'Master Privaatrecht (WO Rechtsgeleerdheid)',
                school: 'Universiteit Leiden',
                location: 'Leiden',
                start: 'september 2014',
                end: 'juli 2016',
                description: 'Specialisatie burgerlijk procesrecht. Scriptie over de regie van de rechter bij comparities na antwoord (beoordeling: 7,5).',
            },
            {
                degree: 'Bachelor Rechtsgeleerdheid',
                school: 'Universiteit Leiden',
                location: 'Leiden',
                start: 'september 2010',
                end: 'juli 2014',
                description: 'Brede juridische basis met keuzevakken in strafrecht en strafprocesrecht.',
            },
        ],
        skills: [
            { name: 'Procesrecht (civiel & straf)', level: 5 },
            { name: 'Zittingsvoorbereiding & begeleiding', level: 5 },
            { name: 'Vonnissen & beschikkingen opstellen', level: 5 },
            { name: 'Procesverbaal & verslaglegging', level: 4 },
            { name: 'Termijnbewaking & zaakplanning', level: 4 },
            { name: 'Juridisch informatiesysteem (JIS/KEI)', level: 4 },
        ],
        languages: [
            { name: 'Nederlands', level: 'Moedertaal' },
            { name: 'Engels', level: 'Vloeiend' },
            { name: 'Frans', level: 'Basis' },
        ],
        interests: ['Rechtsgeschiedenis', 'Hardlopen', 'Lezen'],
        courses: [
            { name: 'SSR Opleiding tot Griffier', institution: 'Studiecentrum Rechtspleging (SSR)', year: '2020' },
            { name: 'Cursus Strafprocesrecht voor Griffiers', institution: 'Studiecentrum Rechtspleging (SSR)', year: '2019' },
        ],
        internships: [],
        awards: [],
    },
};
