import { CVExample } from '../../types';

export const juridischMedewerker: CVExample = {
    slug: 'juridisch-medewerker',
    categorySlug: 'juridisch-en-overheid',
    name: 'Juridisch Medewerker',
    description: 'CV voorbeeld voor juridisch medewerkers bij advocatenkantoren en bedrijfsjuridische afdelingen. Laat zien hoe je je juridische kennis en adviesvaardigheden professioneel presenteert.',
    templateId: 'formal',
    colorThemeId: 'elegant-navy',

    metaTitle: 'CV Voorbeeld Juridisch Medewerker | WerkCV.nl',
    metaDesc: 'Professioneel CV voorbeeld voor juridisch medewerkers. Met voorbeeldteksten voor contractrecht, arbeidsrecht en juridisch advies. Direct te gebruiken als template.',
    keywords: ['cv voorbeeld juridisch medewerker', 'juridisch medewerker cv', 'cv jurist', 'juridisch cv maken', 'cv advocatenkantoor'],
    heroTitle: 'CV Voorbeeld Juridisch Medewerker',
    heroText: 'Als juridisch medewerker combineer je juridische kennis met analytisch denkvermogen en oog voor detail. Dit CV voorbeeld laat zien hoe je je ervaring met contractrecht, arbeidsrecht en juridisch advies overtuigend presenteert aan advocatenkantoren en bedrijfsjuridische afdelingen.',
    tips: [
        'Vermeld specifieke rechtsgebieden waarin je ervaring hebt, zoals contractrecht, arbeidsrecht of ondernemingsrecht',
        'Beschrijf concrete resultaten: aantal contracten beoordeeld, succesvolle adviezen, of procesbesparingen',
        'Benoem je ervaring met juridische databases en software zoals Legal Intelligence, Kluwer Navigator of Cobalt',
        'Toon je adviesvaardigheden door voorbeelden te geven van complexe juridische vraagstukken die je hebt opgelost',
        'Vermeld relevante cursussen en lidmaatschappen zoals NJB of de Nederlandse Orde van Advocaten',
    ],
    relatedSlugs: ['juridisch-en-overheid/advocaat-stagiair', 'juridisch-en-overheid/compliance-officer'],

    sampleCV: {
        personal: {
            name: 'Sophie van der Berg',
            title: 'Juridisch Medewerker',
            email: 'sophie.vanderberg@email.nl',
            phone: '06-34521789',
            location: 'Amsterdam',
            address: 'Herengracht 318',
            postalCode: '1016 CE',
            summary: 'Nauwkeurige en analytisch sterke juridisch medewerker met ruim 4 jaar ervaring in het contractenrecht en arbeidsrecht. Werkzaam geweest bij zowel een gerenommeerd advocatenkantoor als een corporate juridische afdeling. Sterk in het opstellen en beoordelen van contracten, het adviseren van interne stakeholders en het bijhouden van wet- en regelgeving.',
            birthDate: '7 september 1994',
            birthPlace: 'Leiden',
            nationality: 'Nederlands',
            driversLicense: 'B',
            gender: '',
            maritalStatus: '',
            linkedIn: 'linkedin.com/in/sophievdberg',
            github: '',
            website: '',
            photo: '',
        },
        experience: [
            {
                role: 'Juridisch Medewerker Ondernemingsrecht',
                company: 'Houthoff',
                location: 'Amsterdam',
                start: 'maart 2022',
                end: 'heden',
                description: 'Juridische ondersteuning binnen de sectie ondernemingsrecht van een toonaangevend internationaal advocatenkantoor.',
                highlights: [
                    'Jaarlijks meer dan 120 commerciële contracten beoordeeld en opgesteld voor nationale en internationale cliënten',
                    'Due diligence-onderzoeken uitgevoerd bij fusies en overnames met een transactiewaarde tot €50 miljoen',
                    'Juridische memoranda opgesteld over vennootschapsrechtelijke vraagstukken voor partners en cliënten',
                ],
            },
            {
                role: 'Junior Juridisch Medewerker',
                company: 'Philips',
                location: 'Eindhoven',
                start: 'september 2020',
                end: 'februari 2022',
                description: 'Werkzaam op de bedrijfsjuridische afdeling met focus op arbeidsrecht en contractenrecht.',
                highlights: [
                    'Arbeidsovereenkomsten en bijbehorende documentatie opgesteld en beoordeeld voor 200+ medewerkers',
                    'Interne trainingen verzorgd over contractuele risico\'s en AVG-compliance voor afdelingshoofden',
                    'Juridisch advies gegeven bij reorganisatietrajecten en sociaal plan-onderhandelingen',
                ],
            },
        ],
        education: [
            {
                degree: 'Master Privaatrecht (WO Rechtsgeleerdheid)',
                school: 'Universiteit Leiden',
                location: 'Leiden',
                start: 'september 2017',
                end: 'juli 2019',
                description: 'Specialisatie contractenrecht en aansprakelijkheidsrecht. Masterscriptie over de reikwijdte van exoneratieclausules in B2B-contracten (beoordeling: 8,0).',
            },
            {
                degree: 'Bachelor Rechtsgeleerdheid',
                school: 'Universiteit Leiden',
                location: 'Leiden',
                start: 'september 2013',
                end: 'juli 2017',
                description: 'Brede juridische basis met keuzevakken in arbeidsrecht en ondernemingsrecht.',
            },
        ],
        skills: [
            { name: 'Contractrecht & contractbeheer', level: 5 },
            { name: 'Arbeidsrecht', level: 4 },
            { name: 'Juridisch advies & onderzoek', level: 5 },
            { name: 'Due diligence', level: 4 },
            { name: 'AVG / privacyrecht', level: 3 },
            { name: 'Legal Intelligence & Kluwer Navigator', level: 4 },
        ],
        languages: [
            { name: 'Nederlands', level: 'Moedertaal' },
            { name: 'Engels', level: 'Vloeiend' },
            { name: 'Duits', level: 'Goed' },
        ],
        interests: ['Juridische vakliteratuur', 'Tennissen', 'Reizen'],
        courses: [
            { name: 'Leergang Contractenrecht Verdieping', institution: 'Grotius Academie', year: '2023' },
            { name: 'Cursus AVG voor Juristen', institution: 'Sdu Opleidingen', year: '2022' },
        ],
        internships: [],
        awards: [],
    },
};
