import Link from "next/link";
import { claimBenchmarkPublicationEnabled } from "@/lib/agency-feature-flags";
import { publicClaimEvidenceBenchmarkV1Checksum } from "@/lib/benchmark/claim-evidence-public-v1";

export default function ClaimEvidenceMethodology({ locale }: { locale: "nl" | "en" }) {
  const published = claimBenchmarkPublicationEnabled();
  const nl = locale === "nl";
  const toolUrl = nl ? "/tools/kandidaatvoorstel-checker" : "/en/candidate-proposal-checker";
  const datasetJsonLd = published ? {
    "@context": "https://schema.org", "@type": "Dataset", name: "WerkCV Claim–Evidence Benchmark v1", version: "1.0.0", creator: { "@type": "Organization", name: "WerkCV", url: "https://werkcv.nl" }, license: "https://creativecommons.org/licenses/by/4.0/", inLanguage: ["nl", "en"], description: "A fictional bilingual dataset for evaluating whether atomic candidate-proposal claims are supported by CV source spans.", distribution: ["jsonl", "csv"].map((format) => ({ "@type": "DataDownload", encodingFormat: format === "csv" ? "text/csv" : "application/x-ndjson", contentUrl: `https://werkcv.nl/api/benchmark/claim-evidence-v1?format=${format}` })),
  } : null;
  return <main className="wk-page-shell"><div className="wk-container wk-content-wrap py-12 sm:py-20">
    {datasetJsonLd ? <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(datasetJsonLd).replace(/</g, "\\u003c") }} /> : null}
    <header className="max-w-4xl"><p className="wk-eyebrow">WerkCV Claim–Evidence Benchmark v1</p><h1 className="mt-3 text-4xl font-black tracking-tight sm:text-6xl">{nl ? "Zo toetsen we of voorstelclaims echt naar CV-bronnen terugwijzen." : "How we test whether proposal claims trace back to CV sources."}</h1><p className="mt-5 text-lg leading-8 text-slate-700">{nl ? "De benchmark meet bronondersteuning, niet de waarheid van een kandidaat, geschiktheid voor een baan of identiteit." : "The benchmark measures source support—not candidate truthfulness, job suitability or identity."}</p></header>
    <section className="mt-10 rounded-2xl border border-amber-300 bg-amber-50 p-6"><p className="text-xs font-black uppercase tracking-[0.15em] text-amber-800">{published ? (nl ? "Gepubliceerd" : "Published") : (nl ? "Onafhankelijke review loopt" : "Independent review pending")}</p><h2 className="mt-2 text-2xl font-black">{published ? (nl ? "De versie is vrijgegeven." : "This version is released.") : (nl ? "We publiceren nog geen prestatiescore." : "We are not publishing performance claims yet.")}</h2><p className="mt-3 max-w-3xl leading-7 text-slate-700">{published ? (nl ? "De download bevat de onafhankelijk beoordeelde openbare transparantieset." : "The download contains the independently reviewed public transparency set.") : (nl ? "De 60 fictieve conceptcases en evaluatiecode zijn technisch voorbereid, maar de vereiste onafhankelijke tweetalige beoordeling en adjudicatie zijn niet afgerond. De datasetdownloads blijven daarom gesloten en moeilijke cases worden niet stil verwijderd." : "The 60 fictional draft cases and evaluation code are technically prepared, but the required independent bilingual review and adjudication are incomplete. Dataset downloads therefore remain closed, and difficult cases will not be silently removed.")}</p></section>
    <div className="mt-10 grid gap-6 lg:grid-cols-2">
      <section className="rounded-2xl border border-slate-200 bg-white p-6"><h2 className="text-2xl font-black">{nl ? "Wat iedere case bevat" : "What every case contains"}</h2><ul className="mt-4 list-disc space-y-2 pl-5 leading-7 text-slate-700"><li>{nl ? "Exacte claimspan in het voorstel" : "Exact proposal claim span"}</li><li>{nl ? "Verwacht oordeel en geaccepteerde bronspan of aantoonbare afwezigheid" : "Expected verdict and accepted source span or documented absence"}</li><li>{nl ? "Foutcategorie, annotatiereden, documentversie en SHA-256-checksum" : "Error category, annotation rationale, document version and SHA-256 checksum"}</li><li>{nl ? "30 Nederlandse en 30 Engelse cases; zes oordeelklassen met elk tien cases" : "30 Dutch and 30 English cases; six verdict classes with ten cases each"}</li><li>{nl ? "Tien beroepsfamilies en junior-, medior- en seniorcases" : "Ten occupational families and junior, mid-level and senior cases"}</li></ul></section>
      <section className="rounded-2xl border border-slate-200 bg-white p-6"><h2 className="text-2xl font-black">{nl ? "Wat we rapporteren" : "What we report"}</h2><ul className="mt-4 list-disc space-y-2 pl-5 leading-7 text-slate-700"><li>{nl ? "Claimextractieprecisie en -recall" : "Claim extraction precision and recall"}</li><li>{nl ? "Macro-F1 en cijfers per oordeelklasse" : "Macro-F1 and per-verdict metrics"}</li><li>{nl ? "Vangst van niet-onderbouwde en strijdige claims" : "Unsupported and contradicted claim catch rate"}</li><li>{nl ? "Geldigheid van broncitaten; lancering vereist 100%" : "Citation validity; launch requires 100%"}</li><li>{nl ? "Numerieke tegenstrijdigheden, actuele feiten, taalverschil en stabiliteit over drie runs" : "Numerical contradictions, current facts, language difference and stability over three runs"}</li><li>{nl ? "Bootstrap-betrouwbaarheidsintervallen, mislukkingen en bekende beperkingen" : "Bootstrap confidence intervals, failures and known limitations"}</li></ul></section>
    </div>
    <section className="mt-6 rounded-2xl border border-slate-200 bg-white p-6"><h2 className="text-2xl font-black">{nl ? "Publicatiepoorten" : "Publication gates"}</h2><div className="mt-5 overflow-x-auto"><table className="min-w-full border-collapse text-left text-sm"><thead><tr className="border-b border-slate-300"><th className="p-3">{nl ? "Maatstaf" : "Measure"}</th><th className="p-3">{nl ? "Minimum" : "Minimum"}</th></tr></thead><tbody>{[[nl ? "Geldige broncitaten" : "Valid source citations", "100%"], [nl ? "Recall niet-onderbouwd/strijdig" : "Unsupported/contradicted recall", "≥ 90%"], [nl ? "Ernstige false alarms op ondersteunde claims" : "Severe false alarms on supported claims", "≤ 5%"], ["Macro-F1", "≥ 0.80"], [nl ? "Recall actuele feiten" : "Current-fact recall", "≥ 90%"], [nl ? "Stabiliteit over herhaalde runs" : "Repeated-run stability", "≥ 95%"]].map(([name, threshold]) => <tr className="border-b border-slate-100" key={name}><td className="p-3 font-bold">{name}</td><td className="p-3">{threshold}</td></tr>)}</tbody></table></div></section>
    <section className="mt-6 rounded-2xl border border-slate-200 bg-slate-50 p-6"><h2 className="text-2xl font-black">{nl ? "Versie en reproduceerbaarheid" : "Version and reproducibility"}</h2><p className="mt-3 break-all text-sm leading-6 text-slate-700">Public draft checksum: <code>{publicClaimEvidenceBenchmarkV1Checksum}</code></p><p className="mt-2 text-sm text-slate-700">{nl ? "Laatst technisch geëvalueerd: nog niet. Laatst bijgewerkt: 22 augustus 2026." : "Last technically evaluated: not yet. Last updated: 22 August 2026."}</p>{published ? <div className="mt-4 flex flex-wrap gap-3"><a className="wk-button wk-button-secondary" href="/api/benchmark/claim-evidence-v1?format=jsonl">JSONL</a><a className="wk-button wk-button-secondary" href="/api/benchmark/claim-evidence-v1?format=csv">CSV</a></div> : null}</section>
    <div className="mt-8 flex flex-wrap gap-3"><Link className="wk-button wk-button-primary" href={toolUrl}>{nl ? "Open de gratis claimchecker" : "Open the free claim verifier"}</Link><Link className="wk-button wk-button-secondary" href="/agency">MatchPack</Link></div>
  </div></main>;
}
