import { CVExample } from '../../types';

export const afgestudeerdeCv: CVExample = {
    slug: 'afgestudeerde-cv',
    categorySlug: 'studenten-en-starters',
    name: 'Afgestudeerde WO/HBO',
    description: 'CV voorbeeld voor WO- en HBO-afgestudeerden die hun eerste professionele baan zoeken na hun studie.',
    templateId: 'professional',
    colorThemeId: 'elegant-navy',

    metaTitle: 'CV Voorbeeld Afgestudeerde HBO/WO | Na je Studie | WerkCV.nl',
    metaDesc: 'CV voorbeeld speciaal voor afgestudeerden. Van universiteit of hogeschool naar de arbeidsmarkt. Met tips voor je eerste professionele CV.',
    keywords: ['cv afgestudeerde', 'cv na studie', 'cv hbo afgestudeerd', 'cv wo afgestudeerd', 'cv master'],
    heroTitle: 'CV Voorbeeld Afgestudeerde WO/HBO',
    heroText: 'Net afgestudeerd en klaar voor de arbeidsmarkt? Dit CV voorbeeld laat zien hoe je je academische achtergrond, stages en onderzoeksvaardigheden vertaalt naar een professioneel CV dat werkgevers overtuigt.',
    tips: [
        'Vertaal academische vaardigheden naar werkgeversvoordelen',
        'Vermeld je afstudeeronderwerp als het relevant is voor de functie',
        'Benadruk je analytisch vermogen en onderzoeksvaardigheden',
        'Toon eventuele publicaties, presentaties of conferenties',
        'Gebruik een professionele profieltekst - niet te bescheiden, niet te zelfverzekerd',
    ],
    relatedSlugs: ['studenten-en-starters/student-cv', 'studenten-en-starters/eerste-baan-starter'],

    sampleCV: {
        personal: {
            name: 'Daan Vermeulen',
            title: 'MSc Bedrijfseconomie | Financieel Analist',
            email: 'daan.vermeulen@email.nl',
            phone: '06-33445566',
            location: 'Amsterdam',
            address: 'Keizersgracht 200',
            postalCode: '1016 DZ',
            summary: 'Analytisch sterke bedrijfseconoom met een Master in Finance van de Vrije Universiteit Amsterdam. Ervaring opgedaan via een afstudeerstage bij ING en werkstudentschap bij een accountantskantoor. Zoekt een startersfunctie als financieel analist of junior controller.',
            birthDate: '10 november 1999',
            birthPlace: 'Haarlem',
            nationality: 'Nederlands',
            driversLicense: 'B',
            gender: '',
            maritalStatus: '',
            linkedIn: 'linkedin.com/in/daanvermeulen',
            github: '',
            website: '',
            photo: '',
        },
        experience: [
            {
                role: 'Afstudeerstage Financial Risk',
                company: 'ING Bank',
                location: 'Amsterdam',
                start: 'januari 2024',
                end: 'juli 2024',
                description: 'Afstudeerstage bij de afdeling Financial Risk Management.',
                highlights: [
                    'Risicomodellen geanalyseerd en gevalideerd met Python',
                    'Stresstest rapportage opgesteld voor toezichthouder DNB',
                    'Afstudeerscriptie over klimaatrisico in beleggingsportefeuilles (beoordeling: 8.5)',
                ],
            },
            {
                role: 'Werkstudent Accountancy',
                company: 'BDO Accountants',
                location: 'Amstelveen',
                start: 'september 2022',
                end: 'december 2023',
                description: 'Parttime werkstudent op de audit afdeling.',
                highlights: [
                    'Jaarrekeningcontroles ondersteund voor 10+ MKB-klanten',
                    'Data-analyse uitgevoerd in Excel en ACL',
                ],
            },
        ],
        education: [
            {
                degree: 'MSc Finance',
                school: 'Vrije Universiteit Amsterdam',
                location: 'Amsterdam',
                start: 'september 2023',
                end: 'augustus 2024',
                description: 'Specialisatie Financial Risk Management. GPA: 7.8',
            },
            {
                degree: 'BSc Bedrijfseconomie',
                school: 'Vrije Universiteit Amsterdam',
                location: 'Amsterdam',
                start: 'september 2019',
                end: 'juli 2023',
                description: 'Minor: Data Science for Business. Propedeuse cum laude.',
            },
        ],
        skills: [
            { name: 'Financiële analyse', level: 4 },
            { name: 'Excel (Advanced)', level: 5 },
            { name: 'Python (Pandas)', level: 3 },
            { name: 'Power BI', level: 3 },
            { name: 'Bloomberg Terminal', level: 3 },
        ],
        languages: [
            { name: 'Nederlands', level: 'Moedertaal' },
            { name: 'Engels', level: 'Vloeiend' },
            { name: 'Frans', level: 'Basis' },
        ],
        interests: ['Financiële markten', 'Tennis', 'Reizen'],
        courses: [
            { name: 'CFA Level I', institution: 'CFA Institute', year: '2024' },
            { name: 'Financial Modeling', institution: 'Wall Street Prep', year: '2023' },
        ],
        internships: [],
        awards: [],
    },
};
