import { CVExample } from '../../types';

export const bijbaanDeeltijdCv: CVExample = {
    slug: 'bijbaan-deeltijd-cv',
    categorySlug: 'studenten-en-starters',
    name: 'Bijbaan / Deeltijd',
    description: 'CV voorbeeld voor een bijbaan of deeltijdbaan. Perfect voor scholieren en studenten die naast hun studie willen werken.',
    templateId: 'remarkable',
    colorThemeId: 'modern-teal',

    metaTitle: 'CV Voorbeeld Bijbaan & Deeltijd | Scholier & Student | WerkCV.nl',
    metaDesc: 'CV voorbeeld voor bijbanen en deeltijdwerk. Ideaal voor scholieren en studenten. Met tips voor beschikbaarheid en relevante ervaring.',
    keywords: ['cv bijbaan', 'cv deeltijd', 'cv scholier', 'cv student bijbaan', 'cv weekendwerk'],
    heroTitle: 'CV Voorbeeld Bijbaan & Deeltijd',
    heroText: 'Op zoek naar een bijbaan naast je studie of school? Een kort maar krachtig CV maakt het verschil. Dit voorbeeld laat zien hoe je je beschikbaarheid, motivatie en relevante ervaring presenteert.',
    tips: [
        'Vermeld duidelijk je beschikbaarheid (avonden, weekenden, vakanties)',
        'Benadruk klantvriendelijkheid, flexibiliteit en betrouwbaarheid',
        'Houd je CV kort en bondig - maximaal 1 pagina',
        'Vermeld eerdere bijbaantjes, ook als ze kort waren',
        'Toon dat je snel kunt leren en aanpakken',
    ],
    relatedSlugs: ['studenten-en-starters/student-cv', 'studenten-en-starters/stage-cv'],

    sampleCV: {
        personal: {
            name: 'Noah de Wit',
            title: 'MBO-student | Beschikbaar voor bijbaan',
            email: 'noah.dewit@email.nl',
            phone: '06-55667788',
            location: 'Eindhoven',
            address: 'Schoolstraat 24',
            postalCode: '5611 GH',
            summary: 'Enthousiaste en betrouwbare MBO-student (18 jaar) op zoek naar een bijbaan in de avonden en weekenden. Ervaring als vakkenvuller en als vrijwilliger bij sportvereniging. Sociaal, energiek en niet bang om aan te pakken.',
            birthDate: '3 januari 2006',
            birthPlace: 'Eindhoven',
            nationality: 'Nederlands',
            driversLicense: '',
            gender: '',
            maritalStatus: '',
            linkedIn: '',
            github: '',
            website: '',
            photo: '',
        },
        experience: [
            {
                role: 'Vakkenvuller',
                company: 'Albert Heijn',
                location: 'Eindhoven',
                start: 'maart 2023',
                end: 'heden',
                description: 'Bijbaan in de avonden en weekenden.',
                highlights: [
                    'Schappen vullen en winkel opruimen',
                    'Klanten helpen en doorverwijzen',
                    'Sluitdiensten draaien (zelfstandig werken)',
                ],
            },
            {
                role: 'Vrijwilliger Kantinedienst',
                company: 'Voetbalvereniging PSV Amateurs',
                location: 'Eindhoven',
                start: 'september 2021',
                end: 'heden',
                description: 'Bardienst tijdens wedstrijden op zaterdag.',
                highlights: [
                    'Bestellingen opnemen en kassa bedienen',
                    'Voorraad bijhouden en bestellen',
                ],
            },
        ],
        education: [
            {
                degree: 'MBO Handel & Administratie Niveau 3',
                school: 'Summa College',
                location: 'Eindhoven',
                start: 'september 2023',
                end: 'heden (verwacht 2026)',
                description: '',
            },
            {
                degree: 'VMBO-TL Diploma',
                school: 'Heerbeeck College',
                location: 'Best',
                start: 'september 2019',
                end: 'juli 2023',
                description: 'Diploma behaald',
            },
        ],
        skills: [
            { name: 'Klantvriendelijkheid', level: 4 },
            { name: 'Kassabeheer', level: 4 },
            { name: 'Teamwork', level: 4 },
            { name: 'Stiptheid', level: 5 },
            { name: 'Flexibiliteit', level: 5 },
        ],
        languages: [
            { name: 'Nederlands', level: 'Moedertaal' },
            { name: 'Engels', level: 'Goed' },
        ],
        interests: ['Voetbal', 'Gaming', 'Fitness'],
        courses: [],
        internships: [],
        awards: [],
    },
};
