import { CVExample } from '../../types';

export const bijbaanDeeltijdCv: CVExample = {
    slug: 'bijbaan-deeltijd-cv',
    categorySlug: 'studenten-en-starters',
    name: 'Bijbaan / Deeltijd',
    description: 'CV voorbeeld voor een bijbaan, weekendwerk of deeltijdbaan. Perfect voor scholieren en studenten die beschikbaarheid, betrouwbaarheid en werkhouding snel willen laten zien.',
    templateId: 'remarkable',
    colorThemeId: 'modern-teal',

    metaTitle: 'CV Voorbeeld Bijbaan | Student, Scholier & Weekendwerk | WerkCV.nl',
    metaDesc: 'Sterk cv voorbeeld voor bijbaan, weekendwerk en deeltijdwerk. Met beschikbaarheid, profieltekst, kassawerk, vakkenvullen en student/scholier voorbeeld.',
    keywords: ['cv voorbeeld bijbaan', 'cv bijbaan', 'bijbaan cv voorbeeld', 'cv student bijbaan', 'cv scholier bijbaan', 'cv weekendwerk', 'cv deeltijd', 'cv supermarkt bijbaan'],
    heroTitle: 'CV Voorbeeld Bijbaan',
    heroText: 'Voor een bijbaan willen werkgevers snel zien wanneer je beschikbaar bent, of je betrouwbaar bent en of je met klanten, kassa of drukte om kunt gaan. Dit voorbeeld laat zien hoe je school, kleine werkervaring, vrijwilligerswerk en beschikbaarheid omzet naar een kort CV dat direct bruikbaar is voor supermarkt, winkel, horeca of weekendwerk.',
    tips: [
        'Zet je beschikbaarheid bovenaan: avonden, weekenden, koopavond, vakanties en aantal uren per week',
        'Gebruik concrete bijbaanwoorden zoals kassa, vakkenvullen, klanten helpen, schoonhouden, voorraad en openen/sluiten',
        'Heb je weinig ervaring? Gebruik schoolprojecten, sport, oppassen, vrijwilligerswerk of helpen in een familiezaak als bewijs',
        'Houd het CV op 1 pagina en laat vooral betrouwbaarheid, op tijd komen, klantvriendelijkheid en snel leren zien',
        'Pas je profielregel aan per type bijbaan: supermarkt, winkel, horeca, magazijn, bezorging of administratief werk',
    ],
    relatedSlugs: ['studenten-en-starters/student-cv', 'studenten-en-starters/eerste-baan-starter', 'horeca-en-detailhandel/winkelmedewerker'],

    sampleCV: {
        personal: {
            name: 'Noah de Wit',
            title: 'MBO-student | Bijbaan avonden en weekend',
            email: 'noah.dewit@email.nl',
            phone: '06-55667788',
            location: 'Eindhoven',
            address: 'Schoolstraat 24',
            postalCode: '5611 GH',
            summary: 'Betrouwbare MBO-student van 18 jaar, beschikbaar voor een bijbaan in avonden, weekenden en schoolvakanties. Ervaring met vakkenvullen, klanten helpen, kassawerk en kantinedienst bij een sportvereniging. Vriendelijk, leergierig en gewend om afspraken na te komen in een team.',
            birthDate: '3 januari 2006',
            birthPlace: 'Eindhoven',
            nationality: 'Nederlands',
            driversLicense: '',
            gender: '',
            maritalStatus: '',
            linkedIn: '',
            github: '',
            website: '',
            photo: '',
        },
        experience: [
            {
                role: 'Vakkenvuller',
                company: 'Albert Heijn',
                location: 'Eindhoven',
                start: 'maart 2023',
                end: 'heden',
                description: 'Bijbaan in supermarkt tijdens avonden, weekenden en vakantieperiodes.',
                highlights: [
                    'Schappen gevuld, producten gespiegeld en acties netjes gepresenteerd volgens winkelplanning',
                    'Klanten geholpen met productvragen en doorverwezen naar collega\'s bij specifieke vragen',
                    'Kassa ondersteund tijdens drukke momenten en retourvragen netjes afgehandeld',
                    'Sluitdiensten meegedraaid, inclusief opruimen, voorraadcontrole en zelfstandig werken volgens checklist',
                ],
            },
            {
                role: 'Vrijwilliger Kantinedienst',
                company: 'Voetbalvereniging PSV Amateurs',
                location: 'Eindhoven',
                start: 'september 2021',
                end: 'heden',
                description: 'Vrijwillige kantinedienst tijdens wedstrijden en toernooien op zaterdag.',
                highlights: [
                    'Bestellingen opgenomen, pinbetalingen verwerkt en bezoekers vriendelijk geholpen',
                    'Voorraad van drinken, snacks en schoonmaakspullen bijgehouden voor wedstrijddagen',
                    'Samen met vrijwilligers de kantine schoon en georganiseerd achtergelaten na piekdrukte',
                ],
            },
        ],
        education: [
            {
                degree: 'MBO Handel & Administratie Niveau 3',
                school: 'Summa College',
                location: 'Eindhoven',
                start: 'september 2023',
                end: 'heden (verwacht 2026)',
                description: 'Relevante vakken: Nederlands, rekenen, ondernemerschap en digitale vaardigheden. Beschikbaar naast school voor 12-16 uur per week.',
            },
            {
                degree: 'VMBO-TL Diploma',
                school: 'Heerbeeck College',
                location: 'Best',
                start: 'september 2019',
                end: 'juli 2023',
                description: 'Diploma behaald',
            },
        ],
        skills: [
            { name: 'Klantvriendelijkheid', level: 4 },
            { name: 'Kassabeheer', level: 4 },
            { name: 'Teamwork', level: 4 },
            { name: 'Stiptheid', level: 5 },
            { name: 'Avond- en weekendwerk', level: 5 },
        ],
        languages: [
            { name: 'Nederlands', level: 'Moedertaal' },
            { name: 'Engels', level: 'Goed' },
        ],
        interests: ['Voetbal', 'Fitness', 'Gaming', 'Vrijwilligerswerk bij de club'],
        courses: [
            { name: 'Kassatraining en klantcontact', institution: 'Albert Heijn', year: '2023' },
        ],
        internships: [],
        awards: [],
    },
};
