import { CVExample } from '../../types';

export const eersteBaanStarter: CVExample = {
    slug: 'eerste-baan-starter',
    categorySlug: 'studenten-en-starters',
    name: 'Eerste Baan / Starter',
    description: 'CV voorbeeld voor starters en je eerste echte baan. Laat stage, afstudeerproject, bijbaan, vaardigheden en junior potentieel professioneel zien.',
    templateId: 'modern',
    colorThemeId: 'ocean-blue',

    metaTitle: 'CV Voorbeeld Starter | Eerste Baan na Studie | WerkCV.nl',
    metaDesc: 'Sterk cv voorbeeld voor starters en eerste baan. Met profieltekst, stage, afstudeerproject, bijbaan, junior skills en template.',
    keywords: ['cv voorbeeld starter', 'cv starter', 'cv eerste baan', 'cv voorbeeld eerste baan', 'starter cv voorbeeld', 'cv na afstuderen', 'cv zonder werkervaring'],
    heroTitle: 'CV Voorbeeld Eerste Baan / Starter',
    heroText: 'Je eerste baan zoeken vraagt om een ander CV dan een studentenbijbaan. Dit voorbeeld laat zien hoe je stage, afstudeerproject, bijbaan, studievaardigheden, tools en motivatie vertaalt naar bewijs dat je klaar bent voor een juniorfunctie.',
    tips: [
        'Zet je doelrol in je titel: junior marketeer, junior consultant, traineeship, junior projectmedewerker of starter bedrijfskunde',
        'Beschrijf stage en afstudeerproject alsof het werkervaring is, met opdrachtgever, resultaat en gebruikte tools',
        'Gebruik bijbanen als bewijs van klantcontact, verantwoordelijkheid, tempo, planning en samenwerken',
        'Noem junior-relevante tools zoals Excel, Power BI, GA4, CRM, Canva, Trello, HubSpot of Google Ads',
        'Houd het CV compact, maar voeg concrete resultaten toe: budget, campagne, cijfer, onderzoek, dashboard of teamgrootte',
        'Gebruik woorden uit de vacature zodat recruiters direct zien waarom je als starter past',
    ],
    relatedSlugs: ['studenten-en-starters/student-cv', 'studenten-en-starters/stage-cv', 'studenten-en-starters/afgestudeerde-cv'],

    sampleCV: {
        personal: {
            name: 'Tim Bakker',
            title: 'Junior Marketing & Business Starter',
            email: 'tim.bakker@email.nl',
            phone: '06-98765432',
            location: 'Rotterdam',
            address: 'Westersingel 88',
            postalCode: '3015 LC',
            summary: 'HBO Bedrijfskunde afgestudeerde met stage-ervaring in online marketing, marktonderzoek en campagnebeheer. Sterk in Excel, Google Ads, klantpresentaties en gestructureerd werken. Combineert commerciële blik met ervaring uit bijbaan en bestuursfunctie. Op zoek naar een juniorfunctie in marketing, projectcoördinatie of business development.',
            birthDate: '22 maart 2000',
            birthPlace: 'Dordrecht',
            nationality: 'Nederlands',
            driversLicense: 'B',
            gender: '',
            maritalStatus: '',
            linkedIn: 'linkedin.com/in/timbakker',
            github: '',
            website: '',
            photo: '',
        },
        experience: [
            {
                role: 'Stagiaire Marketing',
                company: 'Digital Agency Bright',
                location: 'Rotterdam',
                start: 'februari 2024',
                end: 'juli 2024',
                description: 'Meewerkstage op de marketingafdeling met focus op MKB-campagnes en klantpresentaties.',
                highlights: [
                    'Social media campagnes opgezet voor 5 MKB-klanten en resultaten wekelijks gerapporteerd',
                    'Marktonderzoek uitgevoerd, concurrentie-inzichten samengevat en gepresenteerd aan 3 klanten',
                    'Google Ads campagnes ondersteund met totaalbudget van EUR 10.000 per maand',
                    'Dashboard in Google Sheets gemaakt voor klikken, kosten, conversies en belangrijkste verbeterpunten',
                ],
            },
            {
                role: 'Penningmeester',
                company: 'Studievereniging Mercurius',
                location: 'Rotterdam',
                start: 'september 2022',
                end: 'september 2023',
                description: 'Financieel bestuurslid van studievereniging met 500 leden.',
                highlights: [
                    'Jaarlijks budget van EUR 45.000 beheerd en uitgaven afgestemd met bestuur en commissies',
                    'Financiële rapportages opgesteld voor ALV en begroting toegankelijk uitgelegd aan leden',
                    'Sponsoring en evenementbudgetten bewaakt voor introductieweek, borrels en carrière-events',
                ],
            },
            {
                role: 'Bijbaan Verkoper',
                company: 'HEMA',
                location: 'Dordrecht',
                start: 'april 2019',
                end: 'augustus 2022',
                description: 'Weekendwerk en vakantieperiodes.',
                highlights: [
                    'Klanten geadviseerd, kassa beheerd en retouren afgehandeld tijdens weekend- en vakantiediensten',
                    'Nieuwe medewerkers ingewerkt op winkelproces, klantvriendelijkheid en voorraad aanvullen',
                ],
            },
        ],
        education: [
            {
                degree: 'HBO Bedrijfskunde',
                school: 'Hogeschool Rotterdam',
                location: 'Rotterdam',
                start: 'september 2020',
                end: 'juli 2024',
                description: 'Specialisatie Marketing Management. Afstudeerproject over digitale transformatie in het MKB, inclusief interviews met 12 ondernemers en adviesrapport beoordeeld met een 8.1.',
            },
            {
                degree: 'HAVO Profiel Economie & Maatschappij',
                school: 'Johan de Witt College',
                location: 'Dordrecht',
                start: 'september 2015',
                end: 'juni 2020',
                description: '',
            },
        ],
        skills: [
            { name: 'Marketing & Social Media', level: 4 },
            { name: 'Excel & rapportage', level: 4 },
            { name: 'Google Ads & GA4 basis', level: 3 },
            { name: 'Presenteren', level: 4 },
            { name: 'Projectcoördinatie', level: 4 },
        ],
        languages: [
            { name: 'Nederlands', level: 'Moedertaal' },
            { name: 'Engels', level: 'Vloeiend' },
            { name: 'Duits', level: 'Basis' },
        ],
        interests: ['Voetbal', 'Podcasts', 'Reizen'],
        courses: [
            { name: 'Google Ads Certificering', institution: 'Google', year: '2024' },
            { name: 'Excel voor business analyse', institution: 'Hogeschool Rotterdam', year: '2023' },
        ],
        internships: [],
        awards: [],
    },
};
