import { CVExample } from '../../types';

export const eersteBaanStarter: CVExample = {
    slug: 'eerste-baan-starter',
    categorySlug: 'studenten-en-starters',
    name: 'Eerste Baan / Starter',
    description: 'CV voorbeeld voor je allereerste echte baan. Hoe presenteer je jezelf als je nog geen werkervaring hebt?',
    templateId: 'modern',
    colorThemeId: 'ocean-blue',

    metaTitle: 'CV Voorbeeld Eerste Baan & Starter | Zonder Ervaring | WerkCV.nl',
    metaDesc: 'CV voorbeeld voor starters op de arbeidsmarkt. Geen werkervaring? Dit template laat zien hoe je toch een professioneel CV maakt. Direct te gebruiken.',
    keywords: ['cv eerste baan', 'cv starter', 'cv zonder werkervaring', 'eerste cv maken', 'cv voorbeeld starter'],
    heroTitle: 'CV Voorbeeld Eerste Baan / Starter',
    heroText: 'Je eerste baan zoeken zonder werkervaring? Geen probleem. Dit CV voorbeeld laat zien hoe je met je opleiding, soft skills en motivatie toch opvalt bij werkgevers. Focus op wat je kunt en wilt leren.',
    tips: [
        'Focus op transferable skills: communicatie, samenwerken, organiseren',
        'Vermeld vrijwilligerswerk, verenigingsactiviteiten en bijbaantjes',
        'Schrijf een sterke profieltekst die je motivatie en leergierigheid toont',
        'Houd je CV op 1 pagina - werkgevers verwachten geen lang CV van starters',
        'Pas je CV aan per vacature en gebruik keywords uit de vacaturetekst',
    ],
    relatedSlugs: ['studenten-en-starters/student-cv', 'studenten-en-starters/bijbaan-deeltijd-cv'],

    sampleCV: {
        personal: {
            name: 'Tim Bakker',
            title: 'HBO Bedrijfskunde - Op zoek naar eerste functie',
            email: 'tim.bakker@email.nl',
            phone: '06-98765432',
            location: 'Rotterdam',
            address: 'Westersingel 88',
            postalCode: '3015 LC',
            summary: 'Gedreven HBO-afgestudeerde in Bedrijfskunde met sterke analytische en communicatieve vaardigheden. Ervaring opgedaan via stage bij een marketingbureau en bestuursfunctie bij studievereniging. Zoekt een startersfunctie waar ik kan groeien en bijdragen.',
            birthDate: '22 maart 2000',
            birthPlace: 'Dordrecht',
            nationality: 'Nederlands',
            driversLicense: 'B',
            gender: '',
            maritalStatus: '',
            linkedIn: 'linkedin.com/in/timbakker',
            github: '',
            website: '',
            photo: '',
        },
        experience: [
            {
                role: 'Stagiaire Marketing',
                company: 'Digital Agency Bright',
                location: 'Rotterdam',
                start: 'februari 2024',
                end: 'juli 2024',
                description: 'Meewerkstage op de marketingafdeling.',
                highlights: [
                    'Social media campagnes opgezet voor 5 MKB-klanten',
                    'Marktonderzoek uitgevoerd en gepresenteerd aan klanten',
                    'Google Ads campagnes beheerd met totaalbudget van €10.000/maand',
                ],
            },
            {
                role: 'Penningmeester',
                company: 'Studievereniging Mercurius',
                location: 'Rotterdam',
                start: 'september 2022',
                end: 'september 2023',
                description: 'Financieel bestuurslid van studievereniging met 500 leden.',
                highlights: [
                    'Jaarlijks budget van €45.000 beheerd',
                    'Financiële rapportages opgesteld voor ALV',
                ],
            },
            {
                role: 'Bijbaan Verkoper',
                company: 'HEMA',
                location: 'Dordrecht',
                start: 'april 2019',
                end: 'augustus 2022',
                description: 'Weekendwerk en vakantieperiodes.',
                highlights: [
                    'Klanten geadviseerd en kassa beheerd',
                    'Nieuwe medewerkers ingewerkt',
                ],
            },
        ],
        education: [
            {
                degree: 'HBO Bedrijfskunde',
                school: 'Hogeschool Rotterdam',
                location: 'Rotterdam',
                start: 'september 2020',
                end: 'juli 2024',
                description: 'Specialisatie Marketing Management. Afstudeerproject: digitale transformatie in het MKB.',
            },
            {
                degree: 'HAVO Profiel Economie & Maatschappij',
                school: 'Johan de Witt College',
                location: 'Dordrecht',
                start: 'september 2015',
                end: 'juni 2020',
                description: '',
            },
        ],
        skills: [
            { name: 'Marketing & Social Media', level: 4 },
            { name: 'Microsoft Office', level: 4 },
            { name: 'Google Analytics', level: 3 },
            { name: 'Presenteren', level: 4 },
            { name: 'Projectmanagement', level: 3 },
        ],
        languages: [
            { name: 'Nederlands', level: 'Moedertaal' },
            { name: 'Engels', level: 'Vloeiend' },
            { name: 'Duits', level: 'Basis' },
        ],
        interests: ['Voetbal', 'Podcasts', 'Reizen'],
        courses: [
            { name: 'Google Ads Certificering', institution: 'Google', year: '2024' },
        ],
        internships: [],
        awards: [],
    },
};
