import { CVExample } from '../../types';

export const stageCv: CVExample = {
    slug: 'stage-cv',
    categorySlug: 'studenten-en-starters',
    name: 'Stage CV',
    description: 'CV voorbeeld speciaal voor stagiairs. Hoe schrijf je een CV voor je meewerk- of afstudeerstage?',
    templateId: 'jobboss',
    colorThemeId: 'ocean-blue',

    metaTitle: 'CV Voorbeeld Stage | Meewerkstage & Afstudeerstage | WerkCV.nl',
    metaDesc: 'CV voorbeeld voor stageplaatsen. Of het nu een meewerkstage of afstudeerstage is - dit template helpt je om de perfecte stage te vinden.',
    keywords: ['cv voorbeeld stage', 'cv stagiair', 'cv meewerkstage', 'cv afstudeerstage', 'stage cv maken'],
    heroTitle: 'CV Voorbeeld voor je Stage',
    heroText: 'Op zoek naar een stage? Een goed CV is je toegangskaart. Dit voorbeeld is speciaal gemaakt voor studenten die een meewerkstage of afstudeerstage zoeken. Laat zien wat je al kunt en wat je wilt leren.',
    tips: [
        'Vermeld duidelijk welk type stage je zoekt (meewerk, afstuderen) en de gewenste periode',
        'Beschrijf relevante vakken en projecten uit je opleiding',
        'Toon je leergierigheid en motivatie in je profieltekst',
        'Vermeld eerder opgedane ervaring, ook bijbanen en vrijwilligerswerk',
        'Voeg je onderzoeksinteresses of afstudeeronderwerp toe als relevant',
    ],
    relatedSlugs: ['studenten-en-starters/student-cv', 'studenten-en-starters/bijbaan-deeltijd-cv'],

    sampleCV: {
        personal: {
            name: 'Lotte Janssen',
            title: 'HBO-student Toegepaste Psychologie | Op zoek naar afstudeerstage',
            email: 'lotte.janssen@email.nl',
            phone: '06-11223344',
            location: 'Nijmegen',
            address: 'Studentenweg 15',
            postalCode: '6525 HP',
            summary: 'Derde-jaars HBO-student Toegepaste Psychologie op zoek naar een afstudeerstage (februari - juli 2025). Geïnteresseerd in arbeids- en organisatiepsychologie. Ervaring met onderzoek, gespreksvoering en testafname.',
            birthDate: '8 september 2002',
            birthPlace: 'Nijmegen',
            nationality: 'Nederlands',
            driversLicense: '',
            gender: '',
            maritalStatus: '',
            linkedIn: 'linkedin.com/in/lottejanssen',
            github: '',
            website: '',
            photo: '',
        },
        experience: [
            {
                role: 'Stagiaire HR',
                company: 'Radboud UMC',
                location: 'Nijmegen',
                start: 'februari 2024',
                end: 'juni 2024',
                description: 'Meewerkstage op de afdeling HR & Organisatieontwikkeling.',
                highlights: [
                    'Medewerkerstevredenheidsonderzoek uitgevoerd (300+ respondenten)',
                    'Gespreksverslagen gemaakt van functioneringsgesprekken',
                    'Workshop stressmanagement mede-ontwikkeld en gefaciliteerd',
                ],
            },
            {
                role: 'Vrijwilliger Kindertelefoon',
                company: 'De Kindertelefoon',
                location: 'Nijmegen',
                start: 'september 2022',
                end: 'heden',
                description: 'Wekelijks chatten en bellen met kinderen en jongeren.',
                highlights: [
                    'Gemiddeld 8 gesprekken per dienst',
                    'Training in gesprekstechnieken en crisisinterventie afgerond',
                ],
            },
        ],
        education: [
            {
                degree: 'HBO Toegepaste Psychologie',
                school: 'HAN University of Applied Sciences',
                location: 'Nijmegen',
                start: 'september 2021',
                end: 'heden (verwacht juli 2025)',
                description: 'Richting: Arbeids- en Organisatiepsychologie. Propedeuse cum laude behaald.',
            },
            {
                degree: 'HAVO Profiel Natuur & Gezondheid',
                school: 'Dominicus College',
                location: 'Nijmegen',
                start: 'september 2016',
                end: 'juni 2021',
                description: '',
            },
        ],
        skills: [
            { name: 'Gespreksvoering', level: 4 },
            { name: 'Onderzoeksmethoden', level: 4 },
            { name: 'SPSS', level: 3 },
            { name: 'Testafname', level: 3 },
            { name: 'Rapportage schrijven', level: 4 },
        ],
        languages: [
            { name: 'Nederlands', level: 'Moedertaal' },
            { name: 'Engels', level: 'Vloeiend' },
        ],
        interests: ['Psychologie podcasts', 'Yoga', 'Lezen'],
        courses: [
            { name: 'Motiverende Gespreksvoering', institution: 'HAN', year: '2023' },
            { name: 'EHBO', institution: 'Rode Kruis', year: '2022' },
        ],
        internships: [],
        awards: [],
    },
};
