import { CVExample } from '../../types';

export const stageCv: CVExample = {
    slug: 'stage-cv',
    categorySlug: 'studenten-en-starters',
    name: 'Stage CV',
    description: 'CV voorbeeld voor meewerkstage, afstudeerstage en onderzoeksstage. Laat opleiding, stageperiode, leerdoelen, projecten en motivatie concreet zien.',
    templateId: 'jobboss',
    colorThemeId: 'ocean-blue',

    metaTitle: 'CV Voorbeeld Stage | Meewerkstage, Afstuderen & Leerdoelen | WerkCV.nl',
    metaDesc: 'Sterk stage CV voorbeeld voor meewerkstage of afstudeerstage. Met stageperiode, leerdoelen, opleiding, projecten, vaardigheden en profieltekst.',
    keywords: ['cv voorbeeld stage', 'stage cv voorbeeld', 'cv stagiair', 'cv meewerkstage', 'cv afstudeerstage', 'stage cv maken', 'cv stage zoeken'],
    heroTitle: 'CV Voorbeeld Stage',
    heroText: 'Een stage-CV moet niet alleen laten zien wat je al kunt, maar ook wat je wilt leren. Dit voorbeeld helpt je om stageperiode, opleiding, relevante vakken, projecten, leerdoelen, eerdere ervaring en motivatie helder te presenteren voor een meewerkstage, afstudeerstage of onderzoeksstage.',
    tips: [
        'Vermeld duidelijk het type stage, periode, aantal dagen per week en je opleidingsniveau',
        'Beschrijf relevante vakken, projecten, portfolio-opdrachten of praktijkopdrachten uit je opleiding',
        'Noem je leerdoelen concreet: onderzoek doen, klantcontact, data analyseren, ontwerpen, begeleiden of rapporteren',
        'Gebruik eerdere bijbanen, vrijwilligerswerk en schoolprojecten als bewijs van werkhouding en samenwerking',
        'Voeg onderzoeksinteresse, afstudeeronderwerp of stageopdracht toe als die al bekend is',
        'Maak het makkelijk voor stagebegeleiders: laat zien wat school verwacht en wanneer je beschikbaar bent',
    ],
    relatedSlugs: ['studenten-en-starters/student-cv', 'studenten-en-starters/zonder-werkervaring', 'studenten-en-starters/eerste-baan-starter'],

    sampleCV: {
        personal: {
            name: 'Lotte Janssen',
            title: 'HBO-student Toegepaste Psychologie | Afstudeerstage februari-juli',
            email: 'lotte.janssen@email.nl',
            phone: '06-11223344',
            location: 'Nijmegen',
            address: 'Studentenweg 15',
            postalCode: '6525 HP',
            summary: 'Derdejaars HBO-student Toegepaste Psychologie, beschikbaar voor een afstudeerstage van februari tot en met juli voor 4 dagen per week. Geïnteresseerd in arbeids- en organisatiepsychologie, medewerkerstevredenheid en duurzame inzetbaarheid. Ervaring met onderzoek, SPSS, gespreksvoering, testafname en vertrouwelijke verslaglegging.',
            birthDate: '8 september 2002',
            birthPlace: 'Nijmegen',
            nationality: 'Nederlands',
            driversLicense: '',
            gender: '',
            maritalStatus: '',
            linkedIn: 'linkedin.com/in/lottejanssen',
            github: '',
            website: '',
            photo: '',
        },
        experience: [
            {
                role: 'Stagiaire HR',
                company: 'Radboud UMC',
                location: 'Nijmegen',
                start: 'februari 2024',
                end: 'juni 2024',
                description: 'Meewerkstage op de afdeling HR & Organisatieontwikkeling met onderzoeks- en communicatieopdrachten.',
                highlights: [
                    'Medewerkerstevredenheidsonderzoek ondersteund met vragenlijst, datacleaning en analyse van 300+ respondenten',
                    'Gespreksverslagen gemaakt van ontwikkelgesprekken met aandacht voor vertrouwelijkheid en structuur',
                    'Workshop stressmanagement mede-ontwikkeld en gefaciliteerd voor 18 medewerkers',
                    'Stagebegeleider wekelijks bijgepraat over voortgang, leerdoelen en onderzoeksvragen',
                ],
            },
            {
                role: 'Vrijwilliger Kindertelefoon',
                company: 'De Kindertelefoon',
                location: 'Nijmegen',
                start: 'september 2022',
                end: 'heden',
                description: 'Wekelijks chatten en bellen met kinderen en jongeren.',
                highlights: [
                    'Gemiddeld 8 gesprekken per dienst',
                    'Training in gesprekstechnieken en crisisinterventie afgerond',
                    'Gesprekken zorgvuldig geregistreerd volgens protocol en privacyafspraken',
                ],
            },
        ],
        education: [
            {
                degree: 'HBO Toegepaste Psychologie',
                school: 'HAN University of Applied Sciences',
                location: 'Nijmegen',
                start: 'september 2021',
                end: 'heden (verwacht juli 2025)',
                description: 'Richting Arbeids- en Organisatiepsychologie. Propedeuse cum laude behaald. Relevante vakken: onderzoeksmethoden, diagnostiek, gespreksvoering, statistiek en organisatiegedrag.',
            },
            {
                degree: 'HAVO Profiel Natuur & Gezondheid',
                school: 'Dominicus College',
                location: 'Nijmegen',
                start: 'september 2016',
                end: 'juni 2021',
                description: '',
            },
        ],
        skills: [
            { name: 'Gespreksvoering', level: 4 },
            { name: 'Onderzoeksmethoden', level: 4 },
            { name: 'SPSS', level: 3 },
            { name: 'Testafname', level: 3 },
            { name: 'Leerdoelen & reflectie', level: 4 },
        ],
        languages: [
            { name: 'Nederlands', level: 'Moedertaal' },
            { name: 'Engels', level: 'Vloeiend' },
        ],
        interests: ['Psychologie podcasts', 'Yoga', 'Lezen'],
        courses: [
            { name: 'Motiverende Gespreksvoering', institution: 'HAN', year: '2023' },
            { name: 'EHBO', institution: 'Rode Kruis', year: '2022' },
            { name: 'Privacy en ethiek in praktijkonderzoek', institution: 'HAN', year: '2024' },
        ],
        internships: [],
        awards: [],
    },
};
