import { CVExample } from '../../types';

export const studentCv: CVExample = {
    slug: 'student-cv',
    categorySlug: 'studenten-en-starters',
    name: 'Student / Afgestudeerde',
    description: 'CV voorbeeld voor studenten en recent afgestudeerden. Laat zien hoe je zonder veel werkervaring toch een overtuigend CV schrijft.',
    templateId: 'jobboss',
    colorThemeId: 'modern-teal',

    metaTitle: 'CV Voorbeeld Student & Afgestudeerde | WerkCV.nl',
    metaDesc: 'Professioneel CV voorbeeld voor studenten en afgestudeerden. Met voorbeeldteksten, tips en een gratis template. Maak direct je eigen CV.',
    keywords: ['cv voorbeeld student', 'cv afgestudeerde', 'student cv maken', 'cv zonder werkervaring'],
    heroTitle: 'CV Voorbeeld Student & Afgestudeerde',
    heroText: 'Als student of recent afgestudeerde heb je misschien weinig werkervaring, maar dat maakt niet uit. Dit CV voorbeeld laat zien hoe je met je opleiding, stages en extracurriculaire activiteiten een sterk CV maakt.',
    tips: [
        'Zet je opleiding bovenaan - dit is als student je sterkste troef',
        'Vermeld relevante vakken, projecten en je scriptieonderwerp',
        'Benadruk extracurriculaire activiteiten: studentenvereniging, commissies, vrijwilligerswerk',
        'Voeg relevante cursussen en certificaten toe (online courses tellen ook)',
        'Toon vaardigheden die je tijdens je studie hebt ontwikkeld',
    ],
    relatedSlugs: ['studenten-en-starters/stage-cv', 'studenten-en-starters/eerste-baan-starter'],

    sampleCV: {
        personal: {
            name: 'Sophie van den Berg',
            title: 'Recent Afgestudeerd - Communicatiewetenschappen',
            email: 'sophie.vdberg@email.nl',
            phone: '06-12345678',
            location: 'Utrecht',
            address: 'Studentenlaan 42',
            postalCode: '3512 JK',
            summary: 'Ambitieuze en creatieve communicatieprofessional, recent afgestudeerd aan de Universiteit Utrecht. Ervaring met contentcreatie, social media management en evenementorganisatie door stages en bestuurswerk. Op zoek naar een uitdagende startersfunctie in communicatie of marketing.',
            birthDate: '15 juni 2001',
            birthPlace: 'Amersfoort',
            nationality: 'Nederlands',
            driversLicense: 'B',
            gender: '',
            maritalStatus: '',
            linkedIn: 'linkedin.com/in/sophievdberg',
            github: '',
            website: '',
            photo: '',
        },
        experience: [
            {
                role: 'Stagiaire Communicatie',
                company: 'Gemeente Utrecht',
                location: 'Utrecht',
                start: 'februari 2024',
                end: 'juli 2024',
                description: 'Afstudeerstage bij de afdeling Communicatie.',
                highlights: [
                    'Social media strategie ontwikkeld voor 3 gemeentelijke campagnes',
                    'Persberichten en nieuwsbrieven geschreven (bereik 50.000+ inwoners)',
                    'Interne communicatie verbeterd door opzetten van nieuw intranet',
                ],
            },
            {
                role: 'Bestuurslid Marketing',
                company: 'Studentenvereniging USVN',
                location: 'Utrecht',
                start: 'september 2022',
                end: 'september 2023',
                description: 'Verantwoordelijk voor marketing en communicatie van de vereniging.',
                highlights: [
                    'Instagram volgersaantal verhoogd van 800 naar 2.500',
                    'Sponsoringdeals gesloten ter waarde van €15.000',
                ],
            },
        ],
        education: [
            {
                degree: 'Bachelor Communicatiewetenschappen',
                school: 'Universiteit Utrecht',
                location: 'Utrecht',
                start: 'september 2020',
                end: 'juli 2024',
                description: 'Minor: Digital Marketing. Scriptie over social media gebruik door gemeenten (beoordeling: 8.0).',
            },
            {
                degree: 'VWO Profiel Cultuur & Maatschappij',
                school: 'Amersfoort College',
                location: 'Amersfoort',
                start: 'september 2014',
                end: 'juni 2020',
                description: 'Eindexamenvakken: Nederlands, Engels, Wiskunde A, Geschiedenis, Economie',
            },
        ],
        skills: [
            { name: 'Contentcreatie', level: 4 },
            { name: 'Social Media Management', level: 4 },
            { name: 'Adobe Creative Suite', level: 3 },
            { name: 'Canva', level: 5 },
            { name: 'WordPress', level: 3 },
            { name: 'Google Analytics', level: 3 },
        ],
        languages: [
            { name: 'Nederlands', level: 'Moedertaal' },
            { name: 'Engels', level: 'Vloeiend' },
            { name: 'Spaans', level: 'Basis' },
        ],
        interests: ['Fotografie', 'Reizen', 'Podcasts', 'Hardlopen'],
        courses: [
            { name: 'Google Digital Marketing Certificate', institution: 'Google', year: '2024' },
            { name: 'Social Media Marketing', institution: 'HubSpot Academy', year: '2023' },
        ],
        internships: [],
        awards: [],
    },
};
