import { CVExample } from '../../types';

export const studentCv: CVExample = {
    slug: 'student-cv',
    categorySlug: 'studenten-en-starters',
    name: 'Student',
    description: 'CV voorbeeld voor studenten die solliciteren op bijbaan, stage, traineeship of eerste baan. Laat opleiding, projecten, bijbaan en skills overtuigend zien.',
    templateId: 'jobboss',
    colorThemeId: 'modern-teal',

    metaTitle: 'CV Voorbeeld Student | Bijbaan, Stage & Eerste Baan | WerkCV.nl',
    metaDesc: 'Sterk cv voorbeeld voor studenten. Met profieltekst, opleiding, projecten, bijbaan, stage, vaardigheden en direct te gebruiken CV-template.',
    keywords: ['cv voorbeeld student', 'student cv voorbeeld', 'student cv maken', 'cv student bijbaan', 'stage cv student', 'cv zonder werkervaring', 'cv voorbeeld student zonder ervaring', 'afgestudeerde cv voorbeeld'],
    heroTitle: 'CV Voorbeeld Student',
    heroText: 'Een student-CV moet snel laten zien wat je al kunt, ook als je nog weinig fulltime ervaring hebt. Dit voorbeeld toont hoe je opleiding, relevante vakken, projecten, bijbaan, stage, vrijwilligerswerk, software en talen slim inzet voor bijbaan, stage of eerste baan.',
    tips: [
        'Zet bovenaan je doel: bijbaan, stage, traineeship, werkstudentschap of eerste baan',
        'Gebruik opleiding als bewijs: relevante vakken, projecten, scriptie, minor en studie-resultaten',
        'Vertaal bijbaan, commissie, sport of vrijwilligerswerk naar werkvaardigheden zoals verantwoordelijkheid en klantcontact',
        'Noem software en tools concreet: Excel, Canva, WordPress, Python, SPSS, Figma, GA4 of CRM',
        'Houd het CV op 1 pagina als je nog weinig ervaring hebt en kies alleen wat past bij de vacature',
        'Schrijf bullets met resultaat: bereik, cijfer, aantal deelnemers, klanten, deadlines of teamgrootte',
        'Maak je beschikbaarheid duidelijk als je op een bijbaan of werkstudentschap solliciteert',
    ],
    relatedSlugs: ['studenten-en-starters/bijbaan-deeltijd-cv', 'studenten-en-starters/stage-cv', 'studenten-en-starters/eerste-baan-starter'],

    sampleCV: {
        personal: {
            name: 'Sophie van den Berg',
            title: 'Student Communicatiewetenschappen',
            email: 'sophie.vdberg@email.nl',
            phone: '06-12345678',
            location: 'Utrecht',
            address: 'Studentenlaan 42',
            postalCode: '3512 JK',
            summary: 'Gemotiveerde student Communicatiewetenschappen met ervaring in contentcreatie, social media, evenementenorganisatie en klantcontact via bijbaan en bestuurswerk. Sterk in schrijven, plannen, Canva, WordPress en samenwerken binnen commissies. Op zoek naar een stage, werkstudentschap of startersrol in communicatie of marketing.',
            birthDate: '15 juni 2001',
            birthPlace: 'Amersfoort',
            nationality: 'Nederlands',
            driversLicense: 'B',
            gender: '',
            maritalStatus: '',
            linkedIn: 'linkedin.com/in/sophievdberg',
            github: '',
            website: '',
            photo: '',
        },
        experience: [
            {
                role: 'Stagiaire Communicatie',
                company: 'Gemeente Utrecht',
                location: 'Utrecht',
                start: 'februari 2024',
                end: 'juli 2024',
                description: 'Afstudeerstage bij de afdeling Communicatie.',
                highlights: [
                    'Social media contentplanning gemaakt voor 3 gemeentelijke campagnes rond jongerenparticipatie',
                    'Persberichten en nieuwsbrieven geschreven voor een bereik van 50.000+ inwoners',
                    'Intranetpagina\'s herschreven in duidelijke taal, waardoor collega\'s informatie sneller konden vinden',
                    'Campagneresultaten verzameld in Excel en kort gepresenteerd aan communicatieadviseurs',
                ],
            },
            {
                role: 'Bestuurslid Marketing',
                company: 'Studentenvereniging USVN',
                location: 'Utrecht',
                start: 'september 2022',
                end: 'september 2023',
                description: 'Verantwoordelijk voor marketing en communicatie van de vereniging.',
                highlights: [
                    'Instagram volgersaantal verhoogd van 800 naar 2.500 door vaste contentkalender en eventreels',
                    'Sponsoringdeals ondersteund ter waarde van EUR 15.000 met lokale ondernemers',
                    'Promotie verzorgd voor 12 evenementen met gemiddeld 150+ deelnemers',
                ],
            },
            {
                role: 'Bijbaan Kassamedewerker',
                company: 'Jumbo',
                location: 'Utrecht',
                start: 'mei 2021',
                end: 'augustus 2022',
                description: 'Bijbaan naast studie met kassa, klantcontact en winkelondersteuning.',
                highlights: [
                    'Klanten geholpen aan de kassa en servicebalie tijdens avonden en weekenden',
                    'Nieuwe collega\'s kort ingewerkt op klantvriendelijkheid en kassaproces',
                ],
            },
        ],
        education: [
            {
                degree: 'Bachelor Communicatiewetenschappen',
                school: 'Universiteit Utrecht',
                location: 'Utrecht',
                start: 'september 2020',
                end: 'juli 2024',
                description: 'Minor Digital Marketing. Relevante vakken: onderzoeksmethoden, contentstrategie, publiekscommunicatie en data-analyse. Scriptie over social media gebruik door gemeenten, beoordeeld met een 8.0.',
            },
            {
                degree: 'VWO Profiel Cultuur & Maatschappij',
                school: 'Amersfoort College',
                location: 'Amersfoort',
                start: 'september 2014',
                end: 'juni 2020',
                description: 'Eindexamenvakken: Nederlands, Engels, Wiskunde A, Geschiedenis, Economie',
            },
        ],
        skills: [
            { name: 'Contentcreatie', level: 4 },
            { name: 'Social Media Management', level: 4 },
            { name: 'Onderzoek & analyse', level: 4 },
            { name: 'Canva', level: 5 },
            { name: 'WordPress', level: 3 },
            { name: 'Excel & GA4 basis', level: 3 },
        ],
        languages: [
            { name: 'Nederlands', level: 'Moedertaal' },
            { name: 'Engels', level: 'Vloeiend' },
            { name: 'Spaans', level: 'Basis' },
        ],
        interests: ['Fotografie', 'Reizen', 'Podcasts', 'Hardlopen'],
        courses: [
            { name: 'Google Digital Marketing Certificate', institution: 'Google', year: '2024' },
            { name: 'Social Media Marketing', institution: 'HubSpot Academy', year: '2023' },
        ],
        internships: [],
        awards: [],
    },
};
