import { CVExample } from '../../types';

export const zonderWerkervaring: CVExample = {
    slug: 'zonder-werkervaring',
    categorySlug: 'studenten-en-starters',
    name: 'Zonder Werkervaring',
    description: 'CV voorbeeld zonder werkervaring. Laat zien hoe je school, projecten, vrijwilligerswerk, sport, oppassen en vaardigheden omzet naar een serieus eerste CV.',
    templateId: 'simple',
    colorThemeId: 'classic-blue',

    metaTitle: 'CV Voorbeeld Zonder Werkervaring | Eerste CV Maken | WerkCV.nl',
    metaDesc: 'Sterk cv voorbeeld zonder werkervaring. Met profieltekst, opleiding, schoolprojecten, vrijwilligerswerk, vaardigheden en voorbeeldteksten voor je eerste CV.',
    keywords: [
        'cv voorbeeld zonder werkervaring',
        'cv zonder werkervaring',
        'eerste cv maken',
        'cv maken zonder ervaring',
        'cv scholier zonder werkervaring',
        'cv student zonder werkervaring',
        'voorbeeld cv zonder ervaring',
    ],
    heroTitle: 'CV Voorbeeld Zonder Werkervaring',
    heroText: 'Ook zonder officiële baan kun je een overtuigend CV maken. Dit voorbeeld laat zien hoe je school, projecten, vrijwilligerswerk, sport, oppassen, thuisverantwoordelijkheden en vaardigheden gebruikt als bewijs van inzet, betrouwbaarheid en leervermogen.',
    tips: [
        'Gebruik niet alleen het kopje werkervaring; kies eventueel voor ervaring, projecten of activiteiten',
        'Zet opleiding hoog op je CV en benoem relevante vakken, cijfers, projecten of presentaties',
        'Gebruik vrijwilligerswerk, sportteam, oppassen, mantelzorg, schoolcommissie of helpen in een familiezaak als bewijs',
        'Maak algemene eigenschappen concreet: op tijd komen, afspraken nakomen, samenwerken, uitleg geven of verantwoordelijkheid nemen',
        'Houd het CV op 1 pagina en schrijf een profieltekst die duidelijk maakt welk type baan of stage je zoekt',
    ],
    relatedSlugs: [
        'studenten-en-starters/student-cv',
        'studenten-en-starters/bijbaan-deeltijd-cv',
        'studenten-en-starters/eerste-baan-starter',
    ],

    sampleCV: {
        personal: {
            name: 'Lina Meijer',
            title: 'Scholier | Eerste bijbaan gezocht',
            email: 'lina.meijer@email.nl',
            phone: '06-11223344',
            location: 'Zwolle',
            address: 'Assendorperstraat 82',
            postalCode: '8012 CA',
            summary: 'Gemotiveerde en betrouwbare scholier van 16 jaar, op zoek naar een eerste bijbaan in winkel, horeca of supermarkt. Nog geen officiële werkervaring, maar wel gewend om verantwoordelijkheid te nemen via schoolprojecten, oppassen en vrijwilligerswerk bij de sportclub. Vriendelijk, leergierig, punctueel en beschikbaar op woensdagmiddag, vrijdagavond, zaterdag en in vakanties.',
            birthDate: '18 februari 2010',
            birthPlace: 'Zwolle',
            nationality: 'Nederlands',
            driversLicense: '',
            gender: '',
            maritalStatus: '',
            linkedIn: '',
            github: '',
            website: '',
            photo: '',
        },
        experience: [
            {
                role: 'Vrijwilliger Jeugdtoernooi',
                company: 'Sportclub Zwolle',
                location: 'Zwolle',
                start: 'mei 2024',
                end: 'heden',
                description: 'Ondersteuning bij jeugdwedstrijden, kantine en ontvangst van teams.',
                highlights: [
                    'Teams ontvangen, vragen beantwoord en ouders doorverwezen naar kleedkamers en velden',
                    'Kantine geholpen met bestellingen, opruimen en schoonhouden tijdens drukke wedstrijddagen',
                    'Afspraken nagekomen en op tijd aanwezig geweest bij meerdere toernooidagen',
                ],
            },
            {
                role: 'Oppas',
                company: 'Particulier gezin',
                location: 'Zwolle',
                start: 'september 2023',
                end: 'heden',
                description: 'Oppassen op twee kinderen in de buurt na schooltijd en in weekenden.',
                highlights: [
                    'Verantwoordelijkheid genomen voor vaste afspraken, veiligheid en duidelijke communicatie met ouders',
                    'Kinderen geholpen met huiswerk, eten klaargemaakt en activiteiten voorbereid',
                ],
            },
        ],
        education: [
            {
                degree: 'VMBO-TL',
                school: 'Thorbecke Scholengemeenschap',
                location: 'Zwolle',
                start: 'september 2022',
                end: 'heden',
                description: 'Profiel Economie. Relevante vakken: Nederlands, Engels, economie, wiskunde en maatschappijleer. Project: mini-onderneming opgezet voor schoolmarkt.',
            },
        ],
        skills: [
            { name: 'Betrouwbaarheid', level: 5 },
            { name: 'Klantvriendelijkheid', level: 4 },
            { name: 'Samenwerken', level: 4 },
            { name: 'Snel leren', level: 5 },
            { name: 'Beschikbaar weekend/vakantie', level: 5 },
        ],
        languages: [
            { name: 'Nederlands', level: 'Moedertaal' },
            { name: 'Engels', level: 'Goed' },
        ],
        interests: ['Volleybal', 'Bakken', 'Lezen', 'Dieren verzorgen'],
        courses: [
            { name: 'EHBO introductieles school', institution: 'Thorbecke Scholengemeenschap', year: '2025' },
        ],
        internships: [],
        awards: [
            'Mentorcompliment voor inzet en betrouwbaarheid bij schoolproject, 2025',
        ],
    },
};
