import { CVExample } from '../../types';

export const hotelReceptionist: CVExample = {
    slug: 'hotel-receptionist',
    categorySlug: 'horeca-en-detailhandel',
    name: 'Hotel Receptionist',
    description: 'CV voorbeeld voor hotel receptionisten. Laat zien hoe je je gastvrijheid, meertaligheid en ervaring met hotelmanagement-systemen presenteert.',
    templateId: 'elegant',
    colorThemeId: 'elegant-navy',

    metaTitle: 'CV Voorbeeld Hotel Receptionist | WerkCV.nl',
    metaDesc: 'Professioneel CV voorbeeld voor hotel receptionisten. Met voorbeeldteksten voor gastvrijheid, meertaligheid en PMS-systemen. Maak direct je eigen CV.',
    keywords: ['cv voorbeeld hotel receptionist', 'cv receptie hotel', 'cv front office', 'cv gastvrijheid'],
    heroTitle: 'CV Voorbeeld Hotel Receptionist',
    heroText: 'Als hotel receptionist ben je het eerste aanspreekpunt voor gasten. Dit CV voorbeeld laat zien hoe je je gastvrijheid, talenkennis en ervaring met property management-systemen professioneel presenteert aan hotels en hospitality-bedrijven.',
    tips: [
        'Benadruk je meertaligheid - dit is essentieel in de hotellerie',
        'Vermeld je ervaring met PMS-systemen (Opera, Mews, RoomRaccoon)',
        'Noem je ervaring met check-in/check-out procedures en reserveringsbeheer',
        'Toon je probleemoplossend vermogen met voorbeelden van gastklachten',
        'Geef aan dat je beschikbaar bent voor wisselende diensten inclusief nachtdienst',
    ],
    relatedSlugs: ['horeca-en-detailhandel/ober-serveerster', 'horeca-en-detailhandel/filiaalmanager'],

    sampleCV: {
        personal: {
            name: 'Priya Sharma',
            title: 'Hotel Receptionist / Front Office Medewerker',
            email: 'priya.sharma@email.nl',
            phone: '06-67543210',
            location: 'Den Haag',
            address: 'Laan van Meerdervoort 92',
            postalCode: '2517 AR',
            summary: 'Gastvrije en professionele hotel receptionist met 6 jaar ervaring in de internationale hotellerie. Vloeiend in vier talen en ervaren met Opera PMS en diverse reserveringssystemen. Sterk in het creëren van een uitstekende eerste indruk en het oplossen van gastverzoeken. Flexibel en stressbestendig, ook tijdens piekmomenten.',
            birthDate: '18 augustus 1995',
            birthPlace: 'Den Haag',
            nationality: 'Nederlands',
            driversLicense: '',
            gender: '',
            maritalStatus: '',
            linkedIn: 'linkedin.com/in/priyasharma',
            github: '',
            website: '',
            photo: '',
        },
        experience: [
            {
                role: 'Front Office Medewerker',
                company: 'Hilton The Hague',
                location: 'Den Haag',
                start: 'september 2021',
                end: 'heden',
                description: 'Receptiewerkzaamheden in een 4-sterren hotel met 200 kamers, gericht op internationale zakengasten.',
                highlights: [
                    'Dagelijks 50+ check-ins en check-outs verwerkt met Opera Cloud PMS',
                    'Guest satisfaction score verhoogd van 8,4 naar 9,1 door persoonlijke service',
                    'Upselling van kamers en arrangementen met een gemiddelde conversie van 25%',
                ],
            },
            {
                role: 'Receptionist',
                company: 'Boutique Hotel Corona',
                location: 'Den Haag',
                start: 'juni 2018',
                end: 'augustus 2021',
                description: 'All-round receptiewerkzaamheden in een intiem boutique hotel met 36 kamers.',
                highlights: [
                    'Reserveringsbeheer via Booking.com, Expedia en directe boekingen',
                    'Nachtdiensten gedraaid met verantwoordelijkheid voor veiligheid en nachtaudit',
                ],
            },
        ],
        education: [
            {
                degree: 'MBO 4 Hotelmanagement',
                school: 'STC Group (Hotelschool)',
                location: 'Rotterdam',
                start: 'september 2014',
                end: 'juli 2018',
                description: 'Opleiding hotelmanagement met stages in binnen- en buitenland.',
            },
        ],
        skills: [
            { name: 'Gastvrijheid & Service', level: 5 },
            { name: 'Opera PMS', level: 5 },
            { name: 'Reserveringsbeheer', level: 4 },
            { name: 'Upselling', level: 4 },
            { name: 'Klachtenafhandeling', level: 4 },
        ],
        languages: [
            { name: 'Nederlands', level: 'Moedertaal' },
            { name: 'Engels', level: 'Vloeiend' },
            { name: 'Duits', level: 'Goed' },
            { name: 'Hindi', level: 'Goed' },
        ],
        interests: ['Reizen', 'Gastvrijheidstrends', 'Yoga', 'Fotografie'],
        courses: [
            { name: 'Opera Cloud PMS Certificaat', institution: 'Oracle Hospitality', year: '2022' },
            { name: 'Upselling & Revenue Management', institution: 'HotelSchool The Hague', year: '2021' },
        ],
        internships: [],
        awards: [],
    },
};
