import { CVExample } from '../../types';

export const kassamedewerker: CVExample = {
    slug: 'kassamedewerker',
    categorySlug: 'horeca-en-detailhandel',
    name: 'Kassamedewerker',
    description: 'CV voorbeeld voor kassamedewerkers in supermarkt en retail. Laat kassasysteem, klantcontact, retouren, nauwkeurigheid en piekdrukte concreet zien.',
    templateId: 'remarkable',
    colorThemeId: 'modern-teal',

    metaTitle: 'CV Voorbeeld Kassamedewerker | Kassa & Retail | WerkCV.nl',
    metaDesc: 'Professioneel cv voorbeeld voor kassamedewerkers. Met profieltekst, POS/kassa, klantcontact, retouren, dagafsluiting, nauwkeurigheid en beschikbaarheid.',
    keywords: [
        'cv voorbeeld kassamedewerker',
        'kassamedewerker cv',
        'cv kassa medewerker',
        'cv supermarkt kassamedewerker',
        'cv retail kassa',
        'cv voorbeeld caissiere',
        'cv caissiere supermarkt',
    ],
    heroTitle: 'CV Voorbeeld Kassamedewerker',
    heroText: 'Voor een kassamedewerker telt vooral vertrouwen: nauwkeurig afrekenen, vriendelijk blijven bij drukte en klantvragen netjes oplossen. Dit voorbeeld laat zien hoe je kassasystemen, pin- en contante betalingen, retouren, servicebalie, wachtrijen en beschikbaarheid sterk presenteert.',
    tips: [
        'Benoem kassasystemen, zelfscan, pin, contant geld, retouren, kortingsacties en dagafsluiting als je die ervaring hebt',
        'Laat nauwkeurigheid zien met foutloze kassacontroles, kasverschillen voorkomen of zorgvuldig omgaan met geld',
        'Beschrijf klantcontact concreet: begroeten, vragen beantwoorden, klachten rustig oplossen en wachtrijen begeleiden',
        'Noem je inzetbaarheid voor koopavonden, weekenden, feestdagen en vakantieperiodes',
        'Maak bij weinig ervaring duidelijk dat je betrouwbaar bent met school, bijbaan, vrijwilligerswerk of verantwoordelijkheden thuis',
    ],
    expertContent: {
        recruiterFocus: [
            'Een recruiter kijkt eerst of je met geld, klanten en drukte betrouwbaar omgaat. Nauwkeurigheid en rust zijn belangrijker dan lange verkooppraat.',
            'Laat zien welke kassasituaties je kent: reguliere kassa, zelfscan, retouren, servicebalie, kortingsacties of dagafsluiting.',
            'Beschikbaarheid is bij kassawerk een echte selectievoorwaarde. Zet avonden, weekenden, koopavonden en vakanties zichtbaar in je CV.',
            'Bij weinig ervaring telt bewijs van verantwoordelijkheid: vaste shifts, schoolplanning, vrijwilligerswerk, klantcontact of hulp bij administratie.',
        ],
        copyReadyBullets: [
            'Klanten vriendelijk geholpen bij kassa, zelfscan en servicebalie, ook tijdens drukke piekmomenten.',
            'Pinbetalingen, contant geld, retouren en kortingsacties zorgvuldig verwerkt volgens winkelprocedure.',
            'Kasverschillen voorkomen door bedragen, correcties en retourbonnen direct te controleren.',
            'Wachtrijen verkort door klanten actief naar vrije kassa, zelfscan of servicebalie te begeleiden.',
            'Nieuwe hulpkrachten geholpen met basisuitleg over klantbegroeting, kassawerk en retourprocedure.',
        ],
        noExperienceAdvice: [
            'Gebruik school, vrijwilligerswerk of bijbaan zonder kassa als bewijs voor klantvriendelijkheid en betrouwbaarheid.',
            'Noem dat je zorgvuldig met geld, cijfers of administratie kunt omgaan als je nog geen POS-ervaring hebt.',
            'Zet je beschikbaarheid hoger dan normaal; dat kan bij starters belangrijker zijn dan ervaring.',
        ],
        rewriteExamples: [
            {
                bad: 'Ik heb achter de kassa gewerkt.',
                good: 'Klanten snel en vriendelijk geholpen bij reguliere kassa en zelfscan, inclusief pinbetalingen, retouren en kortingsacties.',
                reason: 'De sterke versie laat zien welke kassataken je beheerst en welke situaties je aankunt.',
            },
            {
                bad: 'Ik ben klantvriendelijk en nauwkeurig.',
                good: 'Kasverschillen voorkomen door contante betalingen, retourbonnen en correcties direct te controleren tijdens piekdrukte.',
                reason: 'Nauwkeurigheid wordt sterker als je het koppelt aan geld, procedure en drukte.',
            },
        ],
        trustSignals: [
            'Ervaring met geld, retouren of servicebalie staat concreet genoemd.',
            'Piekdrukte, wachtrijen en klantvragen worden niet vaag maar praktisch beschreven.',
            'Beschikbaarheid voor avonden, weekenden en vakanties is zichtbaar.',
            'De profieltekst noemt zowel klantcontact als nauwkeurigheid.',
        ],
    },
    relatedSlugs: [
        'horeca-en-detailhandel/winkelmedewerker',
        'horeca-en-detailhandel/klantenservice-medewerker',
        'horeca-en-detailhandel/vakkenvuller',
    ],

    sampleCV: {
        personal: {
            name: 'Sanne de Wit',
            title: 'Kassamedewerker / Caissiere',
            email: 'sanne.dewit@email.nl',
            phone: '06-34567890',
            location: 'Utrecht',
            address: 'Amsterdamsestraatweg 312',
            postalCode: '3551 CT',
            summary: 'Nauwkeurige kassamedewerker met 3 jaar ervaring in supermarkt en drogisterij. Sterk in klantvriendelijk afrekenen, retouren verwerken, zelfscancontrole, servicebaliewerk en werken tijdens drukke piekmomenten. Ervaren met pin, contant geld, kortingsacties en dagafsluiting. Beschikbaar voor avonden, weekenden en vakanties.',
            birthDate: '8 juli 2004',
            birthPlace: 'Utrecht',
            nationality: 'Nederlands',
            driversLicense: '',
            gender: '',
            maritalStatus: '',
            linkedIn: '',
            github: '',
            website: '',
            photo: '',
        },
        experience: [
            {
                role: 'Kassamedewerker',
                company: 'Albert Heijn',
                location: 'Utrecht',
                start: 'maart 2024',
                end: 'heden',
                description: 'Kassawerk, zelfscancontrole en servicebalie tijdens doordeweekse avonden en weekenden.',
                highlights: [
                    'Klanten snel en vriendelijk geholpen bij reguliere kassa, zelfscan en servicebalie',
                    'Retouren, statiegeldbonnen en kortingsacties zorgvuldig verwerkt volgens winkelprocedure',
                    'Wachtrijen actief verkort door klanten naar vrije kassa’s en zelfscanpunten te begeleiden',
                    'Kasverschillen voorkomen door nauwkeurig om te gaan met contant geld en correcties direct te melden',
                ],
            },
            {
                role: 'Caissiere',
                company: 'Kruidvat',
                location: 'Utrecht',
                start: 'juni 2022',
                end: 'februari 2024',
                description: 'Afrekenen, klanten helpen en winkelvoorraad ondersteunen in een drukke drogisterijomgeving.',
                highlights: [
                    'Promotieacties en klantenkaartvragen duidelijk uitgelegd aan klanten',
                    'Kassa gecombineerd met bijvullen van actiedisplays en controleren van prijskaartjes',
                    'Nieuwe hulpkrachten geholpen met basisuitleg over kassa, retouren en klantbegroeting',
                ],
            },
        ],
        education: [
            {
                degree: 'MBO 4 Retail Manager',
                school: 'ROC Midden Nederland',
                location: 'Utrecht',
                start: 'september 2021',
                end: 'juli 2025',
                description: 'Opleiding met aandacht voor retailprocessen, klantcontact, verkoop, voorraad en winkelorganisatie.',
            },
        ],
        skills: [
            { name: 'Kassasysteem / POS', level: 5 },
            { name: 'Pin en contante betalingen', level: 5 },
            { name: 'Retouren verwerken', level: 4 },
            { name: 'Zelfscancontrole', level: 4 },
            { name: 'Klantvriendelijkheid', level: 5 },
            { name: 'Nauwkeurigheid', level: 5 },
            { name: 'Werken onder druk', level: 4 },
            { name: 'Avond- en weekenddiensten', level: 5 },
        ],
        languages: [
            { name: 'Nederlands', level: 'Moedertaal' },
            { name: 'Engels', level: 'Goed' },
        ],
        interests: ['Mode', 'Lezen', 'Hardlopen', 'Retailtrends'],
        courses: [
            { name: 'Omgaan met klantvragen aan de kassa', institution: 'Albert Heijn', year: '2024' },
            { name: 'Basis retail en winkelveiligheid', institution: 'ROC Midden Nederland', year: '2023' },
        ],
        internships: [],
        awards: [
            'Meest klantvriendelijke hulpkracht van de maand, oktober 2025',
        ],
    },
};
