import { CVExample } from '../../types';

export const klantenserviceMedewerker: CVExample = {
    slug: 'klantenservice-medewerker',
    categorySlug: 'horeca-en-detailhandel',
    name: 'Klantenservice Medewerker',
    description: 'CV voorbeeld voor klantenservice medewerkers. Laat zien hoe je klantcontact, CRM, klachtoplossing en servicekwaliteit concreet presenteert.',
    templateId: 'simple',
    colorThemeId: 'modern-teal',

    metaTitle: 'CV Voorbeeld Klantenservice Medewerker | WerkCV.nl',
    metaDesc: 'Professioneel cv voorbeeld voor klantenservice medewerkers. Met profieltekst, CRM-ervaring, ticketafhandeling, klachtoplossing en servicevaardigheden.',
    keywords: [
        'cv voorbeeld klantenservice medewerker',
        'klantenservice medewerker cv',
        'cv medewerker klantenservice',
        'customer service cv',
        'cv callcenter medewerker',
        'cv klantcontact',
        'cv support medewerker',
    ],
    heroTitle: 'CV Voorbeeld Klantenservice Medewerker',
    heroText: 'Een sterk klantenservice CV laat zien dat je vriendelijk blijft onder druk, klantvragen zorgvuldig registreert en problemen echt oplost. Dit voorbeeld toont hoe je telefoon, e-mail, chat, CRM, klachtbehandeling en servicekwaliteit vertaalt naar concrete werkervaring.',
    tips: [
        'Benoem je kanalen: telefoon, e-mail, chat, social, balie of WhatsApp',
        'Gebruik meetbare service-resultaten zoals klanttevredenheid, first-contact resolution, SLA of ticketvolume',
        'Vermeld CRM- en ticketsystemen zoals Salesforce, Zendesk, Freshdesk, HubSpot of Microsoft Dynamics',
        'Laat zien hoe je klachten de-escaleert en afspraken duidelijk vastlegt',
        'Koppel soft skills zoals geduld en empathie aan concrete situaties uit je werkervaring',
    ],
    relatedSlugs: [
        'horeca-en-detailhandel/winkelmedewerker',
        'horeca-en-detailhandel/hotel-receptionist',
        'zakelijk-en-financieel/administratief-medewerker',
    ],

    sampleCV: {
        personal: {
            name: 'Nora van Leeuwen',
            title: 'Klantenservice Medewerker',
            email: 'nora.vanleeuwen@email.nl',
            phone: '06-45678901',
            location: 'Rotterdam',
            address: 'Nieuwe Binnenweg 214',
            postalCode: '3021 GL',
            summary: 'Servicegerichte klantenservice medewerker met 4 jaar ervaring in telefonische support, e-mailafhandeling en live chat. Sterk in het snel analyseren van klantvragen, duidelijk registreren in CRM-systemen en professioneel oplossen van klachten. Ervaren met Zendesk, Salesforce en Microsoft 365. Rustig onder druk, nauwkeurig in opvolging en gewend aan werken met SLA-afspraken.',
            birthDate: '2 februari 1997',
            birthPlace: 'Rotterdam',
            nationality: 'Nederlands',
            driversLicense: 'B',
            gender: '',
            maritalStatus: '',
            linkedIn: 'linkedin.com/in/noravanleeuwen',
            github: '',
            website: '',
            photo: '',
        },
        experience: [
            {
                role: 'Klantenservice Medewerker',
                company: 'Coolblue',
                location: 'Rotterdam',
                start: 'mei 2022',
                end: 'heden',
                description: 'Eerste aanspreekpunt voor klanten via telefoon, chat en e-mail binnen een drukke e-commerce omgeving.',
                highlights: [
                    'Gemiddeld 65 klantvragen per dag afgehandeld via telefoon, chat en e-mail met een klanttevredenheidsscore van 8,7',
                    'First-contact resolution verhoogd door retour- en garantievragen direct correct te registreren in Zendesk',
                    'Nieuwe collega’s ingewerkt op gespreksstructuur, tone of voice en het vastleggen van klantafspraken',
                    'Klachtendossiers voorbereid voor senior support en escalaties teruggebracht door heldere opvolgnotities',
                ],
            },
            {
                role: 'Customer Support Agent',
                company: 'Eneco',
                location: 'Rotterdam',
                start: 'januari 2020',
                end: 'april 2022',
                description: 'Ondersteuning van particuliere klanten bij facturen, contractvragen en meterstanden.',
                highlights: [
                    'Klantgegevens en contractwijzigingen verwerkt in Salesforce en interne energiesystemen',
                    'Complexe factuurvragen uitgezocht en begrijpelijk teruggekoppeld aan klanten',
                    'Dagelijks samengewerkt met billing, planning en technische support om openstaande cases af te ronden',
                ],
            },
        ],
        education: [
            {
                degree: 'MBO 4 Medewerker Marketing & Communicatie',
                school: 'Albeda College',
                location: 'Rotterdam',
                start: 'september 2015',
                end: 'juli 2019',
                description: 'Opleiding met focus op klantcommunicatie, commerciële vaardigheden, tekstschrijven en digitale kanalen.',
            },
        ],
        skills: [
            { name: 'Telefonische klantenservice', level: 5 },
            { name: 'Klachtbehandeling', level: 5 },
            { name: 'Zendesk', level: 4 },
            { name: 'Salesforce CRM', level: 4 },
            { name: 'Live chat en e-mail support', level: 5 },
            { name: 'SLA en ticketregistratie', level: 4 },
            { name: 'De-escalatie', level: 4 },
            { name: 'Microsoft 365', level: 4 },
        ],
        languages: [
            { name: 'Nederlands', level: 'Moedertaal' },
            { name: 'Engels', level: 'Vloeiend' },
            { name: 'Duits', level: 'Basis' },
        ],
        interests: ['Podcasts', 'Taal', 'Fitness', 'Vrijwilligerswerk bij evenementen'],
        courses: [
            { name: 'Omgaan met lastige klantgesprekken', institution: 'NCOI', year: '2023' },
            { name: 'Zendesk Support Administrator Basics', institution: 'Zendesk Training', year: '2022' },
            { name: 'Schrijven voor klantcontact', institution: 'Schouten & Nelissen', year: '2021' },
        ],
        internships: [],
        awards: [
            'Top 10 klanttevredenheid team Rotterdam, Q4 2023',
        ],
    },
};
