import { CVExample } from '../../types';

export const oberServeerster: CVExample = {
    slug: 'ober-serveerster',
    categorySlug: 'horeca-en-detailhandel',
    name: 'Ober / Serveerster',
    description: 'CV voorbeeld voor obers, serveersters en bedieningsmedewerkers. Laat gastvrijheid, tempo, upselling, kassasysteem en beschikbaarheid concreet zien.',
    templateId: 'jobboss',
    colorThemeId: 'modern-teal',

    metaTitle: 'CV Serveerster Voorbeeld 2026 | Profieltekst + Skills | WerkCV.nl',
    metaDesc: 'Bekijk een sterk cv serveerster voorbeeld met profieltekst, bediening, gastvrijheid, kassasysteem en flexibele beschikbaarheid.',
    keywords: ['cv serveerster', 'cv serveerster voorbeeld', 'cv voorbeeld ober', 'cv bedieningsmedewerker', 'cv ober serveerster', 'cv bediening', 'cv horeca service', 'horeca cv'],
    heroTitle: 'CV voorbeeld serveerster',
    heroText: 'Als ober of serveerster ben je het visitekaartje van het restaurant. Dit CV voorbeeld laat zien hoe je gastvrijheid, tempo, kassasysteem, terrasbediening, upselling, wijnkennis en flexibele beschikbaarheid overtuigend presenteert aan horecawerkgevers.',
    tips: [
        'Benoem het type horeca: à la carte, terras, hotel, banqueting, events, lunchroom, café of fine dining',
        'Vermeld je ervaring met kassasystemen, handhelds, reserveringen, tafelindeling en allergenencommunicatie',
        'Noem eventuele wijn- of barista-cursussen die je hebt gevolgd',
        'Geef aan dat je flexibel beschikbaar bent voor avonden, weekenden, feestdagen en het terrasseizoen',
        'Toon service-impact met gastbeoordelingen, gemiddelde couverts, upselling of het inwerken van collega’s',
    ],
    relatedSlugs: ['horeca-en-detailhandel/kok-chef', 'horeca-en-detailhandel/hotel-receptionist', 'horeca-en-detailhandel/cateringmedewerker'],
    expertContent: {
        recruiterFocus: [
            'Maak direct duidelijk in welk type horeca je hebt gewerkt en hoeveel gasten of tafels je tijdens piekuren bediende.',
            'Noem kassasysteem, handhelds, reserveringen en allergenencommunicatie als je daar zelfstandig mee werkte.',
            'Zet beschikbaarheid voor avonden, weekenden en feestdagen zichtbaar neer als dat bij de vacature past.',
        ],
        copyReadyBullets: [
            'Bediening verzorgd voor gemiddeld 80 gasten per dienst, inclusief bestellingen, uitserveren en afrekenen via handheld.',
            'Nieuwe collega’s ingewerkt op kassasysteem, tafelindeling en serviceafspraken tijdens drukke weekenddiensten.',
            'Allergenenwensen en tafelwissels afgestemd met keuken en bar zodat de service tijdens piekdrukte soepel bleef.',
        ],
        rewriteExamples: [
            {
                bad: 'Verantwoordelijk voor bediening.',
                good: 'Gemiddeld 80 gasten per dienst bediend op terras en in restaurant, inclusief handheld bestellingen en afrekenen.',
                reason: 'De sterke versie maakt werktempo, context en systeemervaring concreet.',
            },
        ],
        trustSignals: [
            'Noem sociale hygiene, wijnkennis of barista-certificaten als je die hebt.',
            'Beschrijf hoe je rustig blijft bij piekdrukte, klachten of speciale dieetwensen.',
            'Laat zien dat collega’s op je kunnen rekenen tijdens avonden, weekenden en het terrasseizoen.',
        ],
    },

    sampleCV: {
        personal: {
            name: 'Eva Jansen',
            title: 'Serveerster / Horeca Medewerker',
            email: 'eva.jansen@email.nl',
            phone: '06-56432109',
            location: 'Maastricht',
            address: 'Wycker Brugstraat 38',
            postalCode: '6221 ED',
            summary: 'Gastvrije serveerster met 5 jaar ervaring in à la carte bediening, terras, banqueting en drukke avonddiensten. Ervaren met Lightspeed, handheld bestellingen, tafelindeling, wijnadvies en allergenencommunicatie. Bekend om rustig werken onder druk, persoonlijke aandacht en betrouwbare inzet in weekenden en feestdagen.',
            birthDate: '9 juni 1998',
            birthPlace: 'Sittard',
            nationality: 'Nederlands',
            driversLicense: 'B',
            gender: '',
            maritalStatus: '',
            linkedIn: '',
            github: '',
            website: '',
            photo: '',
        },
        experience: [
            {
                role: 'Serveerster / Zaalverantwoordelijke',
                company: 'Brasserie Beluga',
                location: 'Maastricht',
                start: 'mei 2022',
                end: 'heden',
                description: 'Bediening in een drukbezochte brasserie met 120 couverts, inclusief avonddiensten en weekenden.',
                highlights: [
                    'Zaalverantwoordelijke op drukke avonden met een team van 4 bedieners',
                    'Wijnadvies gegeven aan gasten op basis van behaalde SDEN-certificering',
                    'Klanttevredenheidsscore verhoogd van 8,2 naar 8,7 door persoonlijke aandacht',
                    'Reserveringen, tafelwissels en allergenenwensen afgestemd met keuken en bar tijdens piekdrukte',
                ],
            },
            {
                role: 'Serveerster',
                company: 'Grand Café D\'n Heilansen',
                location: 'Sittard',
                start: 'maart 2019',
                end: 'april 2022',
                description: 'All-round bediening in een druk grand café met terras.',
                highlights: [
                    'Dagelijks gemiddeld 80 gasten bediend in een hoog tempo',
                    'Nieuwe medewerkers ingewerkt op kassasysteem en serviceprotocollen',
                    'Terrasbediening en afrekenen via handheld verzorgd tijdens drukke zomerdiensten',
                ],
            },
        ],
        education: [
            {
                degree: 'MBO 3 Gastheer/-vrouw',
                school: 'Arcus College',
                location: 'Heerlen',
                start: 'september 2015',
                end: 'juli 2018',
                description: 'Opleiding tot gastheer/-vrouw met stages in restaurants en hotels in Limburg.',
            },
        ],
        skills: [
            { name: 'Gastvrijheid & Service', level: 5 },
            { name: 'Kassasystemen (Lightspeed)', level: 4 },
            { name: 'Wijnkennis', level: 4 },
            { name: 'Terras & piekdrukte', level: 5 },
            { name: 'Teamwork', level: 4 },
        ],
        languages: [
            { name: 'Nederlands', level: 'Moedertaal' },
            { name: 'Engels', level: 'Goed' },
            { name: 'Duits', level: 'Goed' },
            { name: 'Frans', level: 'Basis' },
        ],
        interests: ['Wijnproeven', 'Koken', 'Reizen', 'Dansen'],
        courses: [
            { name: 'SDEN Wijnkennis Basis', institution: 'SDEN', year: '2023' },
            { name: 'Sociale Hygiëne', institution: 'SVH', year: '2022' },
        ],
        internships: [],
        awards: [],
    },
};
