import { CVExample } from '../../types';

export const oberServeerster: CVExample = {
    slug: 'ober-serveerster',
    categorySlug: 'horeca-en-detailhandel',
    name: 'Ober / Serveerster',
    description: 'CV voorbeeld voor obers en serveersters. Laat zien hoe je je service-ervaring, gastvrijheid en kennis van eten en drinken professioneel presenteert.',
    templateId: 'jobboss',
    colorThemeId: 'modern-teal',

    metaTitle: 'CV Voorbeeld Ober / Serveerster | WerkCV.nl',
    metaDesc: 'Professioneel CV voorbeeld voor obers en serveersters. Met voorbeeldteksten voor horecaservice, gastvrijheid en bediening. Maak direct je eigen CV.',
    keywords: ['cv voorbeeld ober', 'cv serveerster', 'cv bediening', 'cv horeca service'],
    heroTitle: 'CV Voorbeeld Ober / Serveerster',
    heroText: 'Als ober of serveerster ben je het visitekaartje van het restaurant. Dit CV voorbeeld laat zien hoe je je gastvrijheid, service-ervaring en kennis van wijn en gerechten overtuigend presenteert aan horecawerkgevers.',
    tips: [
        'Benadruk je gastvrijheid en klantgerichtheid met concrete voorbeelden',
        'Vermeld je ervaring met kassasystemen en bestellingssoftware',
        'Noem eventuele wijn- of barista-cursussen die je hebt gevolgd',
        'Geef aan dat je flexibel beschikbaar bent (avonden, weekenden, feestdagen)',
        'Toon je talenkennis - meertaligheid is een grote plus in de horeca',
    ],
    relatedSlugs: ['horeca-en-detailhandel/kok-chef', 'horeca-en-detailhandel/hotel-receptionist'],

    sampleCV: {
        personal: {
            name: 'Eva Jansen',
            title: 'Serveerster / Horeca Medewerker',
            email: 'eva.jansen@email.nl',
            phone: '06-56432109',
            location: 'Maastricht',
            address: 'Wycker Brugstraat 38',
            postalCode: '6221 ED',
            summary: 'Enthousiaste en gastvrije serveerster met 5 jaar ervaring in de horeca. Ervaren in à la carte bediening, banqueting en terrasservice. Bekend om een uitstekend geheugen voor gasten en hun voorkeuren. Flexibel inzetbaar en altijd gericht op een perfecte gastbeleving.',
            birthDate: '9 juni 1998',
            birthPlace: 'Sittard',
            nationality: 'Nederlands',
            driversLicense: 'B',
            gender: '',
            maritalStatus: '',
            linkedIn: '',
            github: '',
            website: '',
            photo: '',
        },
        experience: [
            {
                role: 'Serveerster / Zaalverantwoordelijke',
                company: 'Brasserie Beluga',
                location: 'Maastricht',
                start: 'mei 2022',
                end: 'heden',
                description: 'Bediening in een drukbezochte brasserie met 120 couverts, inclusief avonddiensten en weekenden.',
                highlights: [
                    'Zaalverantwoordelijke op drukke avonden met een team van 4 bedieners',
                    'Wijnadvies gegeven aan gasten op basis van behaalde SDEN-certificering',
                    'Klanttevredenheidsscore verhoogd van 8,2 naar 8,7 door persoonlijke aandacht',
                ],
            },
            {
                role: 'Serveerster',
                company: 'Grand Café D\'n Heilansen',
                location: 'Sittard',
                start: 'maart 2019',
                end: 'april 2022',
                description: 'All-round bediening in een druk grand café met terras.',
                highlights: [
                    'Dagelijks gemiddeld 80 gasten bediend in een hoog tempo',
                    'Nieuwe medewerkers ingewerkt op kassasysteem en serviceprotocollen',
                ],
            },
        ],
        education: [
            {
                degree: 'MBO 3 Gastheer/-vrouw',
                school: 'Arcus College',
                location: 'Heerlen',
                start: 'september 2015',
                end: 'juli 2018',
                description: 'Opleiding tot gastheer/-vrouw met stages in restaurants en hotels in Limburg.',
            },
        ],
        skills: [
            { name: 'Gastvrijheid & Service', level: 5 },
            { name: 'Kassasystemen (Lightspeed)', level: 4 },
            { name: 'Wijnkennis', level: 4 },
            { name: 'Stressbestendigheid', level: 5 },
            { name: 'Teamwork', level: 4 },
        ],
        languages: [
            { name: 'Nederlands', level: 'Moedertaal' },
            { name: 'Engels', level: 'Goed' },
            { name: 'Duits', level: 'Goed' },
            { name: 'Frans', level: 'Basis' },
        ],
        interests: ['Wijnproeven', 'Koken', 'Reizen', 'Dansen'],
        courses: [
            { name: 'SDEN Wijnkennis Basis', institution: 'SDEN', year: '2023' },
            { name: 'Sociale Hygiëne', institution: 'SVH', year: '2022' },
        ],
        internships: [],
        awards: [],
    },
};
