import { CVExample } from '../../types';

export const vakkenvuller: CVExample = {
    slug: 'vakkenvuller',
    categorySlug: 'horeca-en-detailhandel',
    name: 'Vakkenvuller',
    description: 'CV voorbeeld voor vakkenvullers in supermarkt en retail. Laat beschikbaarheid, tempo, FIFO, winkelpresentatie en klantvragen concreet zien.',
    templateId: 'simple',
    colorThemeId: 'modern-teal',

    metaTitle: 'CV Voorbeeld Vakkenvuller | Supermarkt & Bijbaan | WerkCV.nl',
    metaDesc: 'Professioneel cv voorbeeld voor vakkenvullers. Met profieltekst, FIFO, schappen spiegelen, voorraad, klantvragen, fysieke inzet en beschikbaarheid.',
    keywords: [
        'cv voorbeeld vakkenvuller',
        'vakkenvuller cv',
        'cv vakken vullen',
        'cv voorbeeld supermarkt',
        'cv supermarkt bijbaan',
        'cv voorbeeld bijbaan supermarkt',
        'cv vakkenvuller zonder ervaring',
    ],
    heroTitle: 'CV Voorbeeld Vakkenvuller',
    heroText: 'Een goed CV voor vakkenvuller hoeft niet lang te zijn, maar moet direct bewijzen dat je betrouwbaar, netjes en inzetbaar bent. Dit voorbeeld laat zien hoe je schappen vullen, FIFO, spiegelen, voorraad, klantvragen, fysieke belasting en avond- of weekendbeschikbaarheid professioneel opschrijft.',
    tips: [
        'Zet je beschikbaarheid hoog in je CV: avonden, weekenden, vakanties, koopavonden en extra diensten',
        'Gebruik supermarkttermen zoals FIFO, spiegelen, actiekoppen, restanten, derving en voorraadcontrole als je die kent',
        'Maak betrouwbaarheid concreet met op tijd komen, vaste shifts, extra diensten of zelfstandig sluiten van een pad',
        'Noem ook klantcontact: producten aanwijzen, vragen beantwoorden en rustig blijven tijdens drukte',
        'Heb je weinig ervaring, gebruik schoolprojecten, sport, vrijwilligerswerk of thuisverantwoordelijkheid als bewijs voor discipline',
    ],
    relatedSlugs: [
        'horeca-en-detailhandel/winkelmedewerker',
        'studenten-en-starters/bijbaan-deeltijd-cv',
        'studenten-en-starters/cv-16-jarige',
    ],

    sampleCV: {
        personal: {
            name: 'Daan Vermeer',
            title: 'Vakkenvuller / Supermarktmedewerker',
            email: 'daan.vermeer@email.nl',
            phone: '06-23456789',
            location: 'Amersfoort',
            address: 'Leusderweg 88',
            postalCode: '3817 KD',
            summary: 'Betrouwbare vakkenvuller met 2 jaar ervaring in supermarktwerk naast school. Ervaren met schappen vullen, FIFO, spiegelen, actiepaden, voorraad bijhouden en klanten helpen op de winkelvloer. Fysiek sterk, snel inzetbaar en beschikbaar op avonden, zaterdag en in schoolvakanties.',
            birthDate: '14 maart 2008',
            birthPlace: 'Amersfoort',
            nationality: 'Nederlands',
            driversLicense: '',
            gender: '',
            maritalStatus: '',
            linkedIn: '',
            github: '',
            website: '',
            photo: '',
        },
        experience: [
            {
                role: 'Vakkenvuller',
                company: 'Jumbo',
                location: 'Amersfoort',
                start: 'september 2024',
                end: 'heden',
                description: 'Vakken vullen en winkelpresentatie verzorgen op houdbaar, frisdrank en actieproducten.',
                highlights: [
                    'Schappen gevuld volgens FIFO en producten netjes gespiegeld voor opening en tijdens piekdrukte',
                    'Actiekoppen opgebouwd en restanten gecontroleerd met aandacht voor prijskaartjes en presentatie',
                    'Klanten geholpen met productlocaties en vragen doorverwezen naar teamleider wanneer nodig',
                    'Regelmatig extra diensten overgenomen in weekenden en schoolvakanties',
                ],
            },
            {
                role: 'Hulpkracht Winkelvloer',
                company: 'PLUS',
                location: 'Amersfoort',
                start: 'juni 2023',
                end: 'augustus 2024',
                description: 'Bijbaan op de winkelvloer met focus op vullen, spiegelen en opruimen.',
                highlights: [
                    'Binnengekomen rolcontainers verwerkt en lege verpakkingen direct afgevoerd',
                    'Derving beperkt door houdbaarheidsdata te controleren bij zuivel en versproducten',
                    'Winkelpaden vrij en veilig gehouden voor klanten en collega’s',
                ],
            },
        ],
        education: [
            {
                degree: 'Havo',
                school: 'Het Nieuwe Eemland',
                location: 'Amersfoort',
                start: 'september 2021',
                end: 'heden',
                description: 'Profiel Economie & Maatschappij. Combineert school met vaste bijbaan in de supermarkt.',
            },
        ],
        skills: [
            { name: 'Schappen vullen', level: 5 },
            { name: 'FIFO en datumcontrole', level: 4 },
            { name: 'Spiegelen en winkelpresentatie', level: 5 },
            { name: 'Voorraad aanvullen', level: 4 },
            { name: 'Klantvragen beantwoorden', level: 4 },
            { name: 'Fysiek werktempo', level: 5 },
            { name: 'Avond- en weekenddiensten', level: 5 },
            { name: 'Samenwerken met teamleider', level: 4 },
        ],
        languages: [
            { name: 'Nederlands', level: 'Moedertaal' },
            { name: 'Engels', level: 'Goed' },
        ],
        interests: ['Voetbal', 'Fitness', 'Gaming', 'Economie'],
        courses: [
            { name: 'Introductietraining supermarktveiligheid', institution: 'Jumbo', year: '2024' },
            { name: 'Klantvriendelijk werken op de winkelvloer', institution: 'PLUS', year: '2023' },
        ],
        internships: [],
        awards: [
            'Teamleidercompliment voor inzet tijdens kerstdrukte 2025',
        ],
    },
};
