import { CVExample } from '../../types';

export const winkelmedewerker: CVExample = {
    slug: 'winkelmedewerker',
    categorySlug: 'horeca-en-detailhandel',
    name: 'Winkelmedewerker / Verkoper',
    description: 'CV voorbeeld voor winkelmedewerkers en verkoopmedewerkers in retail. Laat verkoop, kassa, voorraad, klantadvies en beschikbaarheid concreet zien.',
    templateId: 'remarkable',
    colorThemeId: 'modern-teal',

    metaTitle: 'CV Voorbeeld Winkelmedewerker | Verkoop & Retail | WerkCV.nl',
    metaDesc: 'Professioneel cv voorbeeld voor winkelmedewerker en verkoopmedewerker. Met verkoopresultaten, kassasysteem, voorraadbeheer, klantadvies en beschikbaarheid.',
    keywords: ['cv voorbeeld winkelmedewerker', 'cv verkoopmedewerker', 'winkelmedewerker cv', 'cv verkoper', 'cv detailhandel', 'cv retail', 'cv kassamedewerker'],
    heroTitle: 'CV Voorbeeld Winkelmedewerker',
    heroText: 'Als winkelmedewerker moet je CV snel laten zien dat je klanten helpt, verkoopt, de winkel netjes houdt en betrouwbaar inzetbaar bent. Dit voorbeeld toont hoe je verkoopresultaten, kassasysteem, voorraadbeheer, visual merchandising en avond- of weekendbeschikbaarheid professioneel presenteert.',
    tips: [
        'Gebruik de functietitel uit de vacature: winkelmedewerker, verkoopmedewerker, kassamedewerker of retail medewerker',
        'Benadruk klantadvies, bijverkoop, retouren, klachtenafhandeling en winkelpresentatie met concrete voorbeelden',
        'Vermeld kassasystemen, pinbetalingen, dagafsluiting, voorraadbeheer, click & collect of omnichannel taken',
        'Geef beschikbaarheid duidelijk aan: koopavond, weekend, vakanties, feestdagen of flexibele shifts',
        'Maak verkoopresultaat meetbaar met targets, conversie, gemiddelde bonwaarde, klanttevredenheid of foutloze kassacontrole',
    ],
    relatedSlugs: ['horeca-en-detailhandel/filiaalmanager', 'horeca-en-detailhandel/klantenservice-medewerker', 'horeca-en-detailhandel/hotel-receptionist'],

    sampleCV: {
        personal: {
            name: 'Amber Kok',
            title: 'Winkelmedewerker / Verkoopmedewerker',
            email: 'amber.kok@email.nl',
            phone: '06-78654321',
            location: 'Leiden',
            address: 'Breestraat 55',
            postalCode: '2311 CK',
            summary: 'Klantgerichte verkoopmedewerker met 4 jaar ervaring in mode- en warenhuisretail. Sterk in persoonlijk advies, bijverkoop, kassawerk, voorraadbeheer en visual merchandising. Ervaren met retouren, click & collect, piekdrukte en koopavonden. Beschikbaar voor avonden, weekenden en vakantieperiodes.',
            birthDate: '25 september 1999',
            birthPlace: 'Leiden',
            nationality: 'Nederlands',
            driversLicense: '',
            gender: '',
            maritalStatus: '',
            linkedIn: '',
            github: '',
            website: '',
            photo: '',
        },
        experience: [
            {
                role: 'Verkoopmedewerker',
                company: 'Zara (Inditex)',
                location: 'Leiden',
                start: 'september 2022',
                end: 'heden',
                description: 'Verkoop en klantadvies in een drukbezochte modezaak in het stadscentrum.',
                highlights: [
                    'Persoonlijke verkooptargets gemiddeld 15% overtroffen door actief klantadvies en stylingcombinaties',
                    'Kassa, retouren, click & collect en voorraadchecks verzorgd tijdens drukke weekenddiensten',
                    'Visual merchandising en etalage-inrichting uitgevoerd volgens campagne- en seizoensrichtlijnen',
                    'Nieuwe collega\'s ingewerkt op verkoopproces, kassasysteem en klantbenadering op de winkelvloer',
                ],
            },
            {
                role: 'Winkelmedewerker',
                company: 'HEMA',
                location: 'Leiden',
                start: 'juni 2020',
                end: 'augustus 2022',
                description: 'All-round werkzaamheden waaronder kassa, vullen en klantadvies.',
                highlights: [
                    'Dagelijkse kassacontrole uitgevoerd met 100% nauwkeurigheid',
                    'Seizoenspresentaties mede-opgezet voor schoolseizoen en feestdagen',
                    'Voorraad aangevuld en derving gesignaleerd bij food, cadeauartikelen en huishoudelijke producten',
                ],
            },
        ],
        education: [
            {
                degree: 'MBO 3 Verkoopspecialist',
                school: 'ROC Leiden',
                location: 'Leiden',
                start: 'september 2017',
                end: 'juli 2020',
                description: 'Opleiding tot verkoopspecialist met stages in mode- en warenhuis retail.',
            },
        ],
        skills: [
            { name: 'Klantadvies & Verkoop', level: 5 },
            { name: 'Kassabeheer', level: 5 },
            { name: 'Visual Merchandising', level: 4 },
            { name: 'Voorraadbeheer', level: 4 },
            { name: 'Retouren & klachten', level: 4 },
        ],
        languages: [
            { name: 'Nederlands', level: 'Moedertaal' },
            { name: 'Engels', level: 'Goed' },
        ],
        interests: ['Mode', 'Shoppen', 'Instagram', 'Fitness'],
        courses: [
            { name: 'Verkooptechnieken Masterclass', institution: 'Retail Academy', year: '2023' },
            { name: 'Omgaan met klachten in de winkel', institution: 'HEMA Academy', year: '2021' },
        ],
        internships: [],
        awards: [],
    },
};
